-- Revert: schemas/constructive_infra_public/tables/platform_secret_values/constraints/platform_secret_values_secret_name_database_id_key/constraint


ALTER TABLE "constructive_infra_public".platform_secret_values
  DROP CONSTRAINT platform_secret_values_secret_name_database_id_key;
