-- Verify: schemas/constructive_compute_fbp_private/trigger_fns/tg_platform_function_graph_object_generate_id_hash


SELECT verify_function('constructive_compute_fbp_private.tg_platform_function_graph_object_generate_id_hash');


