apiVersion: v1
kind: ConfigMap
metadata:
  name: constructive
data:
  PORT: "3000"
  SERVER_HOST: "0.0.0.0"
  SERVER_TRUST_PROXY: "true"
  SERVER_ORIGIN: "*"
  SERVER_STRICT_AUTH: "false"

  PGHOST: "postgres.default.svc.cluster.local"
  PGPORT: "5432"
  PGDATABASE: "constructive"

  API_ENABLE_META: "true"
  API_EXPOSED_SCHEMAS: "collections_public,meta_public"
  API_ANON_ROLE: "administrator"
  API_ROLE_NAME: "administrator"
  API_ENABLE_SERVICES: "true"
  API_DEFAULT_DATABASE_ID: "constructive"

  LOG_TIMESTAMP: "true"
