apiVersion: v1
kind: Secret
metadata:
  name: mailgun-credentials
stringData:
  MAILGUN_API_KEY: "REPLACE_WITH_MAILGUN_API_KEY"
  MAILGUN_KEY: "REPLACE_WITH_MAILGUN_KEY"
  MAILGUN_DOMAIN: "REPLACE_WITH_MAILGUN_DOMAIN"
