apiVersion: v1
kind: Secret
metadata:
  name: pg-credentials
stringData:
  PGHOST: postgres.constructive-functions.svc.cluster.local
  PGPORT: "5432"
  PGDATABASE: constructive
  PGUSER: postgres
  PGPASSWORD: postgres123!
