-- Revert: schemas/constructive_platform_function_graph_public/tables/platform_function_graph_object/constraints/platform_function_graph_objects_pkey/constraint


ALTER TABLE "constructive_platform_function_graph_public".platform_function_graph_object 
  DROP CONSTRAINT platform_function_graph_objects_pkey;


