-- Revert: schemas/constructive_compute_private/tables/platform_function_graph_execution_node_states/columns/node_name/alterations/alt0000002706


COMMENT ON COLUMN "constructive_compute_private".platform_function_graph_execution_node_states.node_name IS NULL;
