-- Revert: schemas/constructive_infra_public/tables/platform_function_invocations/indexes/platform_function_invocations_task_identifier_created_at_idx


DROP INDEX "constructive_infra_public".platform_function_invocations_task_identifier_created_at_idx;


