-- Revert: schemas/constructive_compute_fbp_private/tables/function_graph_execution_outputs/constraints/function_graph_execution_outputs_pkey/constraint


ALTER TABLE "constructive_compute_fbp_private".function_graph_execution_outputs 
  DROP CONSTRAINT function_graph_execution_outputs_pkey;


