-- Verify: schemas/constructive_memberships_public/tables/app_permission_default_grants/indexes/app_permission_default_grants_grantor_id_idx


SELECT verify_index('constructive_memberships_public.app_permission_default_grants', 'app_permission_default_grants_grantor_id_idx');


