-- Revert: schemas/constructive_storage_public/tables/platform_buckets/triggers/platform_buckets_force_current_user_actor_id_tg


DROP TRIGGER platform_buckets_force_current_user_actor_id_tg ON "constructive_storage_public".platform_buckets;


