/**
 * Commit history — each commit snapshots a tree root for a store
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import type { QueryClient,UseQueryOptions, UseQueryResult } from '@tanstack/react-query';
import { useQuery } from '@tanstack/react-query';

import type {
  CommitFilter,
  CommitOrderBy,
  CommitSelect,
  CommitWithRelations,
} from '../../orm/input-types';
import type {
  ConnectionResult,
  HookStrictSelect,
  InferSelectResult,
} from '../../orm/select-types';
import { getClient } from '../client';
import { commitKeys } from '../query-keys';
import type { ListSelectionConfig } from '../selection';
import { buildListSelectionArgs } from '../selection';
export type {
  CommitFilter,
  CommitOrderBy,
  CommitSelect,
  CommitWithRelations,
} from '../../orm/input-types';
/** Query key factory - re-exported from query-keys.ts */
export const commitsQueryKey = commitKeys.list;
/**
 * Commit history — each commit snapshots a tree root for a store
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useCommitsQuery({
 *   selection: {
 *     fields: { id: true, name: true },
 *     where: { name: { equalTo: "example" } },
 *     orderBy: ['CREATED_AT_DESC'],
 *     first: 10,
 *   },
 * });
 * ```
 */
export function useCommitsQuery<
  S extends CommitSelect,
  TData = {
    commits: ConnectionResult<InferSelectResult<CommitWithRelations, S>>;
  },
>(
  params: {
    selection: {
      fields: S;
    } & Omit<ListSelectionConfig<S, CommitFilter, CommitOrderBy>, 'fields'> &
      HookStrictSelect<NoInfer<S>, CommitSelect>;
  } & Omit<
    UseQueryOptions<
      {
        commits: ConnectionResult<InferSelectResult<CommitWithRelations, S>>;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function useCommitsQuery(
  params: {
    selection: ListSelectionConfig<CommitSelect, CommitFilter, CommitOrderBy>;
  } & Omit<UseQueryOptions<any, Error, any, any>, 'queryKey' | 'queryFn'>
) {
  const args = buildListSelectionArgs<CommitSelect, CommitFilter, CommitOrderBy>(params.selection);
  const { selection: _selection, ...queryOptions } = params ?? {};
  void _selection;
  return useQuery({
    queryKey: commitKeys.list(args),
    queryFn: () => getClient().commit.findMany(args).unwrap(),
    ...queryOptions,
  });
}
/**
 * Commit history — each commit snapshots a tree root for a store
 *
 * @example
 * ```ts
 * const data = await fetchCommitsQuery({
 *   selection: {
 *     fields: { id: true },
 *     first: 10,
 *   },
 * });
 * ```
 */
export async function fetchCommitsQuery<S extends CommitSelect>(params: {
  selection: {
    fields: S;
  } & Omit<ListSelectionConfig<S, CommitFilter, CommitOrderBy>, 'fields'> &
    HookStrictSelect<NoInfer<S>, CommitSelect>;
}): Promise<{
  commits: ConnectionResult<InferSelectResult<CommitWithRelations, S>>;
}>;
export async function fetchCommitsQuery(params: {
  selection: ListSelectionConfig<CommitSelect, CommitFilter, CommitOrderBy>;
}) {
  const args = buildListSelectionArgs<CommitSelect, CommitFilter, CommitOrderBy>(params.selection);
  return getClient().commit.findMany(args).unwrap();
}
/**
 * Commit history — each commit snapshots a tree root for a store
 *
 * @example
 * ```ts
 * await prefetchCommitsQuery(queryClient, { selection: { fields: { id: true }, first: 10 } });
 * ```
 */
export async function prefetchCommitsQuery<S extends CommitSelect>(
  queryClient: QueryClient,
  params: {
    selection: {
      fields: S;
    } & Omit<ListSelectionConfig<S, CommitFilter, CommitOrderBy>, 'fields'> &
      HookStrictSelect<NoInfer<S>, CommitSelect>;
  }
): Promise<void>;
export async function prefetchCommitsQuery(
  queryClient: QueryClient,
  params: {
    selection: ListSelectionConfig<CommitSelect, CommitFilter, CommitOrderBy>;
  }
): Promise<void> {
  const args = buildListSelectionArgs<CommitSelect, CommitFilter, CommitOrderBy>(params.selection);
  await queryClient.prefetchQuery({
    queryKey: commitKeys.list(args),
    queryFn: () => getClient().commit.findMany(args).unwrap(),
  });
}
