/**
 * Content-addressed Merkle tree objects keyed by UUID v5 hash of data + children
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import { useQuery } from '@tanstack/react-query';
import type { UseQueryOptions, UseQueryResult, QueryClient } from '@tanstack/react-query';
import { getClient } from '../client';
import { buildSelectionArgs } from '../selection';
import type { SelectionConfig } from '../selection';
import { objectKeys } from '../query-keys';
import type { ObjectSelect, ObjectWithRelations } from '../../orm/input-types';
import type { InferSelectResult, HookStrictSelect } from '../../orm/select-types';
export type { ObjectSelect, ObjectWithRelations } from '../../orm/input-types';
/** Query key factory - re-exported from query-keys.ts */
export const getNodeAtPathQueryKey = objectKeys.detail;
/**
 * Content-addressed Merkle tree objects keyed by UUID v5 hash of data + children
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useObjectQuery({
 *   id: 'some-id',
 *   selection: { fields: { id: true, name: true } },
 * });
 * ```
 */
export function useObjectQuery<
  S extends ObjectSelect,
  TData = {
    getNodeAtPath: InferSelectResult<ObjectWithRelations, S> | null;
  },
>(
  params: {
    id: string;
    selection: {
      fields: S;
    } & HookStrictSelect<NoInfer<S>, ObjectSelect>;
  } & Omit<
    UseQueryOptions<
      {
        getNodeAtPath: InferSelectResult<ObjectWithRelations, S> | null;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function useObjectQuery(
  params: {
    id: string;
    selection: SelectionConfig<ObjectSelect>;
  } & Omit<UseQueryOptions<any, Error, any, any>, 'queryKey' | 'queryFn'>
) {
  const args = buildSelectionArgs<ObjectSelect>(params.selection);
  const { selection: _selection, ...queryOptions } = params ?? {};
  void _selection;
  return useQuery({
    queryKey: objectKeys.detail(params.id),
    queryFn: () =>
      getClient()
        .object.findOne({
          id: params.id,
          select: args.select,
        })
        .unwrap(),
    ...queryOptions,
  });
}
/**
 * Content-addressed Merkle tree objects keyed by UUID v5 hash of data + children
 *
 * @example
 * ```ts
 * const data = await fetchObjectQuery({
 *   id: 'some-id',
 *   selection: { fields: { id: true } },
 * });
 * ```
 */
export async function fetchObjectQuery<S extends ObjectSelect>(params: {
  id: string;
  selection: {
    fields: S;
  } & HookStrictSelect<NoInfer<S>, ObjectSelect>;
}): Promise<{
  getNodeAtPath: InferSelectResult<ObjectWithRelations, S> | null;
}>;
export async function fetchObjectQuery(params: {
  id: string;
  selection: SelectionConfig<ObjectSelect>;
}): Promise<any> {
  const args = buildSelectionArgs<ObjectSelect>(params.selection);
  return getClient()
    .object.findOne({
      id: params.id,
      select: args.select,
    })
    .unwrap();
}
/**
 * Content-addressed Merkle tree objects keyed by UUID v5 hash of data + children
 *
 * @example
 * ```ts
 * await prefetchObjectQuery(queryClient, { id: 'some-id', selection: { fields: { id: true } } });
 * ```
 */
export async function prefetchObjectQuery<S extends ObjectSelect>(
  queryClient: QueryClient,
  params: {
    id: string;
    selection: {
      fields: S;
    } & HookStrictSelect<NoInfer<S>, ObjectSelect>;
  }
): Promise<void>;
export async function prefetchObjectQuery(
  queryClient: QueryClient,
  params: {
    id: string;
    selection: SelectionConfig<ObjectSelect>;
  }
): Promise<void> {
  const args = buildSelectionArgs<ObjectSelect>(params.selection);
  await queryClient.prefetchQuery({
    queryKey: objectKeys.detail(params.id),
    queryFn: () =>
      getClient()
        .object.findOne({
          id: params.id,
          select: args.select,
        })
        .unwrap(),
  });
}
