/**
 * Branch heads — mutable pointers into the commit chain
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import type { QueryClient,UseQueryOptions, UseQueryResult } from '@tanstack/react-query';
import { useQuery } from '@tanstack/react-query';

import type { RefFilter, RefOrderBy,RefSelect, RefWithRelations } from '../../orm/input-types';
import type {
  ConnectionResult,
  HookStrictSelect,
  InferSelectResult,
} from '../../orm/select-types';
import { getClient } from '../client';
import { refKeys } from '../query-keys';
import type { ListSelectionConfig } from '../selection';
import { buildListSelectionArgs } from '../selection';
export type { RefFilter, RefOrderBy,RefSelect, RefWithRelations } from '../../orm/input-types';
/** Query key factory - re-exported from query-keys.ts */
export const refsQueryKey = refKeys.list;
/**
 * Branch heads — mutable pointers into the commit chain
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useRefsQuery({
 *   selection: {
 *     fields: { id: true, name: true },
 *     where: { name: { equalTo: "example" } },
 *     orderBy: ['CREATED_AT_DESC'],
 *     first: 10,
 *   },
 * });
 * ```
 */
export function useRefsQuery<
  S extends RefSelect,
  TData = {
    refs: ConnectionResult<InferSelectResult<RefWithRelations, S>>;
  },
>(
  params: {
    selection: {
      fields: S;
    } & Omit<ListSelectionConfig<S, RefFilter, RefOrderBy>, 'fields'> &
      HookStrictSelect<NoInfer<S>, RefSelect>;
  } & Omit<
    UseQueryOptions<
      {
        refs: ConnectionResult<InferSelectResult<RefWithRelations, S>>;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function useRefsQuery(
  params: {
    selection: ListSelectionConfig<RefSelect, RefFilter, RefOrderBy>;
  } & Omit<UseQueryOptions<any, Error, any, any>, 'queryKey' | 'queryFn'>
) {
  const args = buildListSelectionArgs<RefSelect, RefFilter, RefOrderBy>(params.selection);
  const { selection: _selection, ...queryOptions } = params ?? {};
  void _selection;
  return useQuery({
    queryKey: refKeys.list(args),
    queryFn: () => getClient().ref.findMany(args).unwrap(),
    ...queryOptions,
  });
}
/**
 * Branch heads — mutable pointers into the commit chain
 *
 * @example
 * ```ts
 * const data = await fetchRefsQuery({
 *   selection: {
 *     fields: { id: true },
 *     first: 10,
 *   },
 * });
 * ```
 */
export async function fetchRefsQuery<S extends RefSelect>(params: {
  selection: {
    fields: S;
  } & Omit<ListSelectionConfig<S, RefFilter, RefOrderBy>, 'fields'> &
    HookStrictSelect<NoInfer<S>, RefSelect>;
}): Promise<{
  refs: ConnectionResult<InferSelectResult<RefWithRelations, S>>;
}>;
export async function fetchRefsQuery(params: {
  selection: ListSelectionConfig<RefSelect, RefFilter, RefOrderBy>;
}) {
  const args = buildListSelectionArgs<RefSelect, RefFilter, RefOrderBy>(params.selection);
  return getClient().ref.findMany(args).unwrap();
}
/**
 * Branch heads — mutable pointers into the commit chain
 *
 * @example
 * ```ts
 * await prefetchRefsQuery(queryClient, { selection: { fields: { id: true }, first: 10 } });
 * ```
 */
export async function prefetchRefsQuery<S extends RefSelect>(
  queryClient: QueryClient,
  params: {
    selection: {
      fields: S;
    } & Omit<ListSelectionConfig<S, RefFilter, RefOrderBy>, 'fields'> &
      HookStrictSelect<NoInfer<S>, RefSelect>;
  }
): Promise<void>;
export async function prefetchRefsQuery(
  queryClient: QueryClient,
  params: {
    selection: ListSelectionConfig<RefSelect, RefFilter, RefOrderBy>;
  }
): Promise<void> {
  const args = buildListSelectionArgs<RefSelect, RefFilter, RefOrderBy>(params.selection);
  await queryClient.prefetchQuery({
    queryKey: refKeys.list(args),
    queryFn: () => getClient().ref.findMany(args).unwrap(),
  });
}
