-- Revert: schemas/constructive_compute_public/tables/platform_function_definitions/constraints/platform_function_definitions_namespace_id_fkey/constraint


ALTER TABLE "constructive_compute_public".platform_function_definitions 
  DROP CONSTRAINT platform_function_definitions_namespace_id_fkey;


