/**
 * GetAllRecord model for ORM client
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { OrmClient } from '../client';
import {
  QueryBuilder,
  buildFindManyDocument,
  buildFindFirstDocument,
  buildFindOneDocument,
  buildCreateDocument,
  buildUpdateByPkDocument,
  buildDeleteByPkDocument,
} from '../query-builder';
import type {
  ConnectionResult,
  FindManyArgs,
  FindFirstArgs,
  CreateArgs,
  UpdateArgs,
  DeleteArgs,
  InferSelectResult,
  StrictSelect,
} from '../select-types';
import type {
  GetAllRecord,
  GetAllRecordWithRelations,
  GetAllRecordSelect,
  GetAllRecordFilter,
  GetAllRecordsOrderBy,
  CreateGetAllRecordInput,
  UpdateGetAllRecordInput,
  GetAllRecordPatch,
} from '../input-types';
import { connectionFieldsMap } from '../input-types';
export class GetAllRecordModel {
  constructor(private client: OrmClient) {}
  findMany<S extends GetAllRecordSelect>(
    args: FindManyArgs<S, GetAllRecordFilter, GetAllRecordsOrderBy> & {
      select: S;
    } & StrictSelect<S, GetAllRecordSelect>
  ): QueryBuilder<{
    getAll: ConnectionResult<InferSelectResult<GetAllRecordWithRelations, S>>;
  }> {
    const { document, variables } = buildFindManyDocument(
      'GetAllRecord',
      'getAll',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
        first: args?.first,
        last: args?.last,
        after: args?.after,
        before: args?.before,
        offset: args?.offset,
      },
      'GetAllRecordFilter',
      'GetAllRecordsOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'GetAllRecord',
      fieldName: 'getAll',
      document,
      variables,
    });
  }
  findFirst<S extends GetAllRecordSelect>(
    args: FindFirstArgs<S, GetAllRecordFilter, GetAllRecordsOrderBy> & {
      select: S;
    } & StrictSelect<S, GetAllRecordSelect>
  ): QueryBuilder<{
    getAllRecord: InferSelectResult<GetAllRecordWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindFirstDocument(
      'GetAllRecord',
      'getAll',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
      },
      'GetAllRecordFilter',
      'GetAllRecordsOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'GetAllRecord',
      fieldName: 'getAllRecord',
      document,
      variables,
      transform: (data: {
        getAll?: {
          nodes?: InferSelectResult<GetAllRecordWithRelations, S>[];
        };
      }) => ({
        getAllRecord: data.getAll?.nodes?.[0] ?? null,
      }),
    });
  }
  create<S extends GetAllRecordSelect>(
    args: CreateArgs<S, CreateGetAllRecordInput['getAllRecord']> & {
      select: S;
    } & StrictSelect<S, GetAllRecordSelect>
  ): QueryBuilder<{
    createGetAllRecord: {
      getAllRecord: InferSelectResult<GetAllRecordWithRelations, S>;
    };
  }> {
    const { document, variables } = buildCreateDocument(
      'GetAllRecord',
      'createGetAllRecord',
      'getAllRecord',
      args.select,
      args.data,
      'CreateGetAllRecordInput',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'GetAllRecord',
      fieldName: 'createGetAllRecord',
      document,
      variables,
    });
  }
}
