/**
 * PlatformComputeLog model for ORM client
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { OrmClient } from '../client';
import type {
  CreatePlatformComputeLogInput,
  PlatformComputeLogFilter,
  PlatformComputeLogOrderBy,
  PlatformComputeLogPatch,
  PlatformComputeLogSelect,
  PlatformComputeLogWithRelations,
} from '../input-types';
import { connectionFieldsMap } from '../input-types';
import {
  buildCreateDocument,
  buildDeleteByPkDocument,
  buildFindFirstDocument,
  buildFindManyDocument,
  buildUpdateByPkDocument,
  QueryBuilder,
} from '../query-builder';
import type {
  ConnectionResult,
  CreateArgs,
  DeleteArgs,
  FindFirstArgs,
  FindManyArgs,
  InferSelectResult,
  StrictSelect,
  UpdateArgs,
} from '../select-types';
export class PlatformComputeLogModel {
  constructor(private client: OrmClient) {}
  findMany<S extends PlatformComputeLogSelect>(
    args: FindManyArgs<S, PlatformComputeLogFilter, PlatformComputeLogOrderBy> & {
      select: S;
    } & StrictSelect<S, PlatformComputeLogSelect>
  ): QueryBuilder<{
    platformComputeLogs: ConnectionResult<InferSelectResult<PlatformComputeLogWithRelations, S>>;
  }> {
    const { document, variables } = buildFindManyDocument(
      'PlatformComputeLog',
      'platformComputeLogs',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
        first: args?.first,
        last: args?.last,
        after: args?.after,
        before: args?.before,
        offset: args?.offset,
      },
      'PlatformComputeLogFilter',
      'PlatformComputeLogOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'PlatformComputeLog',
      fieldName: 'platformComputeLogs',
      document,
      variables,
    });
  }
  findFirst<S extends PlatformComputeLogSelect>(
    args: FindFirstArgs<S, PlatformComputeLogFilter, PlatformComputeLogOrderBy> & {
      select: S;
    } & StrictSelect<S, PlatformComputeLogSelect>
  ): QueryBuilder<{
    platformComputeLog: InferSelectResult<PlatformComputeLogWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindFirstDocument(
      'PlatformComputeLog',
      'platformComputeLogs',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
      },
      'PlatformComputeLogFilter',
      'PlatformComputeLogOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'PlatformComputeLog',
      fieldName: 'platformComputeLog',
      document,
      variables,
      transform: (data: {
        platformComputeLogs?: {
          nodes?: InferSelectResult<PlatformComputeLogWithRelations, S>[];
        };
      }) => ({
        platformComputeLog: data.platformComputeLogs?.nodes?.[0] ?? null,
      }),
    });
  }
  findOne<S extends PlatformComputeLogSelect>(
    args: {
      id: string;
      select: S;
    } & StrictSelect<S, PlatformComputeLogSelect>
  ): QueryBuilder<{
    platformComputeLog: InferSelectResult<PlatformComputeLogWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindManyDocument(
      'PlatformComputeLog',
      'platformComputeLogs',
      args.select,
      {
        where: {
          id: {
            equalTo: args.id,
          },
        },
        first: 1,
      },
      'PlatformComputeLogFilter',
      'PlatformComputeLogOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'PlatformComputeLog',
      fieldName: 'platformComputeLog',
      document,
      variables,
      transform: (data: {
        platformComputeLogs?: {
          nodes?: InferSelectResult<PlatformComputeLogWithRelations, S>[];
        };
      }) => ({
        platformComputeLog: data.platformComputeLogs?.nodes?.[0] ?? null,
      }),
    });
  }
  create<S extends PlatformComputeLogSelect>(
    args: CreateArgs<S, CreatePlatformComputeLogInput['platformComputeLog']> & {
      select: S;
    } & StrictSelect<S, PlatformComputeLogSelect>
  ): QueryBuilder<{
    createPlatformComputeLog: {
      platformComputeLog: InferSelectResult<PlatformComputeLogWithRelations, S>;
    };
  }> {
    const { document, variables } = buildCreateDocument(
      'PlatformComputeLog',
      'createPlatformComputeLog',
      'platformComputeLog',
      args.select,
      args.data,
      'CreatePlatformComputeLogInput',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'PlatformComputeLog',
      fieldName: 'createPlatformComputeLog',
      document,
      variables,
    });
  }
  update<S extends PlatformComputeLogSelect>(
    args: UpdateArgs<
      S,
      {
        id: string;
        completedAt: string;
      },
      PlatformComputeLogPatch
    > & {
      select: S;
    } & StrictSelect<S, PlatformComputeLogSelect>
  ): QueryBuilder<{
    updatePlatformComputeLog: {
      platformComputeLog: InferSelectResult<PlatformComputeLogWithRelations, S>;
    };
  }> {
    const { document, variables } = buildUpdateByPkDocument(
      'PlatformComputeLog',
      'updatePlatformComputeLog',
      'platformComputeLog',
      args.select,
      args.where.id,
      args.data,
      'UpdatePlatformComputeLogInput',
      'id',
      'platformComputeLogPatch',
      connectionFieldsMap,
      {
        completedAt: args.where.completedAt,
      }
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'PlatformComputeLog',
      fieldName: 'updatePlatformComputeLog',
      document,
      variables,
    });
  }
  delete<S extends PlatformComputeLogSelect>(
    args: DeleteArgs<
      {
        id: string;
        completedAt: string;
      },
      S
    > & {
      select: S;
    } & StrictSelect<S, PlatformComputeLogSelect>
  ): QueryBuilder<{
    deletePlatformComputeLog: {
      platformComputeLog: InferSelectResult<PlatformComputeLogWithRelations, S>;
    };
  }> {
    const { document, variables } = buildDeleteByPkDocument(
      'PlatformComputeLog',
      'deletePlatformComputeLog',
      'platformComputeLog',
      {
        id: args.where.id,
        completedAt: args.where.completedAt,
      },
      'DeletePlatformComputeLogInput',
      args.select,
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'PlatformComputeLog',
      fieldName: 'deletePlatformComputeLog',
      document,
      variables,
    });
  }
}
