-- Revert: schemas/constructive_memberships_public/tables/app_permission_default_permissions/indexes/app_permission_default_permissions_created_at_idx


DROP INDEX "constructive_memberships_public".app_permission_default_permissions_created_at_idx;


