/**
 * PlatformSecretDefinition model for ORM client
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { OrmClient } from '../client';
import {
  QueryBuilder,
  buildFindManyDocument,
  buildFindFirstDocument,
  buildFindOneDocument,
  buildCreateDocument,
  buildUpdateByPkDocument,
  buildDeleteByPkDocument,
} from '../query-builder';
import type {
  ConnectionResult,
  FindManyArgs,
  FindFirstArgs,
  CreateArgs,
  UpdateArgs,
  DeleteArgs,
  InferSelectResult,
  StrictSelect,
} from '../select-types';
import type {
  PlatformSecretDefinition,
  PlatformSecretDefinitionWithRelations,
  PlatformSecretDefinitionSelect,
  PlatformSecretDefinitionFilter,
  PlatformSecretDefinitionOrderBy,
  CreatePlatformSecretDefinitionInput,
  UpdatePlatformSecretDefinitionInput,
  PlatformSecretDefinitionPatch,
} from '../input-types';
import { connectionFieldsMap } from '../input-types';
export class PlatformSecretDefinitionModel {
  constructor(private client: OrmClient) {}
  findMany<S extends PlatformSecretDefinitionSelect>(
    args: FindManyArgs<S, PlatformSecretDefinitionFilter, PlatformSecretDefinitionOrderBy> & {
      select: S;
    } & StrictSelect<S, PlatformSecretDefinitionSelect>
  ): QueryBuilder<{
    platformSecretDefinitions: ConnectionResult<
      InferSelectResult<PlatformSecretDefinitionWithRelations, S>
    >;
  }> {
    const { document, variables } = buildFindManyDocument(
      'PlatformSecretDefinition',
      'platformSecretDefinitions',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
        first: args?.first,
        last: args?.last,
        after: args?.after,
        before: args?.before,
        offset: args?.offset,
      },
      'PlatformSecretDefinitionFilter',
      'PlatformSecretDefinitionOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'PlatformSecretDefinition',
      fieldName: 'platformSecretDefinitions',
      document,
      variables,
    });
  }
  findFirst<S extends PlatformSecretDefinitionSelect>(
    args: FindFirstArgs<S, PlatformSecretDefinitionFilter, PlatformSecretDefinitionOrderBy> & {
      select: S;
    } & StrictSelect<S, PlatformSecretDefinitionSelect>
  ): QueryBuilder<{
    platformSecretDefinition: InferSelectResult<PlatformSecretDefinitionWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindFirstDocument(
      'PlatformSecretDefinition',
      'platformSecretDefinitions',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
      },
      'PlatformSecretDefinitionFilter',
      'PlatformSecretDefinitionOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'PlatformSecretDefinition',
      fieldName: 'platformSecretDefinition',
      document,
      variables,
      transform: (data: {
        platformSecretDefinitions?: {
          nodes?: InferSelectResult<PlatformSecretDefinitionWithRelations, S>[];
        };
      }) => ({
        platformSecretDefinition: data.platformSecretDefinitions?.nodes?.[0] ?? null,
      }),
    });
  }
  findOne<S extends PlatformSecretDefinitionSelect>(
    args: {
      id: string;
      select: S;
    } & StrictSelect<S, PlatformSecretDefinitionSelect>
  ): QueryBuilder<{
    platformSecretDefinition: InferSelectResult<PlatformSecretDefinitionWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindManyDocument(
      'PlatformSecretDefinition',
      'platformSecretDefinitions',
      args.select,
      {
        where: {
          id: {
            equalTo: args.id,
          },
        },
        first: 1,
      },
      'PlatformSecretDefinitionFilter',
      'PlatformSecretDefinitionOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'PlatformSecretDefinition',
      fieldName: 'platformSecretDefinition',
      document,
      variables,
      transform: (data: {
        platformSecretDefinitions?: {
          nodes?: InferSelectResult<PlatformSecretDefinitionWithRelations, S>[];
        };
      }) => ({
        platformSecretDefinition: data.platformSecretDefinitions?.nodes?.[0] ?? null,
      }),
    });
  }
  create<S extends PlatformSecretDefinitionSelect>(
    args: CreateArgs<S, CreatePlatformSecretDefinitionInput['platformSecretDefinition']> & {
      select: S;
    } & StrictSelect<S, PlatformSecretDefinitionSelect>
  ): QueryBuilder<{
    createPlatformSecretDefinition: {
      platformSecretDefinition: InferSelectResult<PlatformSecretDefinitionWithRelations, S>;
    };
  }> {
    const { document, variables } = buildCreateDocument(
      'PlatformSecretDefinition',
      'createPlatformSecretDefinition',
      'platformSecretDefinition',
      args.select,
      args.data,
      'CreatePlatformSecretDefinitionInput',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'PlatformSecretDefinition',
      fieldName: 'createPlatformSecretDefinition',
      document,
      variables,
    });
  }
  update<S extends PlatformSecretDefinitionSelect>(
    args: UpdateArgs<
      S,
      {
        id: string;
      },
      PlatformSecretDefinitionPatch
    > & {
      select: S;
    } & StrictSelect<S, PlatformSecretDefinitionSelect>
  ): QueryBuilder<{
    updatePlatformSecretDefinition: {
      platformSecretDefinition: InferSelectResult<PlatformSecretDefinitionWithRelations, S>;
    };
  }> {
    const { document, variables } = buildUpdateByPkDocument(
      'PlatformSecretDefinition',
      'updatePlatformSecretDefinition',
      'platformSecretDefinition',
      args.select,
      args.where.id,
      args.data,
      'UpdatePlatformSecretDefinitionInput',
      'id',
      'platformSecretDefinitionPatch',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'PlatformSecretDefinition',
      fieldName: 'updatePlatformSecretDefinition',
      document,
      variables,
    });
  }
  delete<S extends PlatformSecretDefinitionSelect>(
    args: DeleteArgs<
      {
        id: string;
      },
      S
    > & {
      select: S;
    } & StrictSelect<S, PlatformSecretDefinitionSelect>
  ): QueryBuilder<{
    deletePlatformSecretDefinition: {
      platformSecretDefinition: InferSelectResult<PlatformSecretDefinitionWithRelations, S>;
    };
  }> {
    const { document, variables } = buildDeleteByPkDocument(
      'PlatformSecretDefinition',
      'deletePlatformSecretDefinition',
      'platformSecretDefinition',
      {
        id: args.where.id,
      },
      'DeletePlatformSecretDefinitionInput',
      args.select,
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'PlatformSecretDefinition',
      fieldName: 'deletePlatformSecretDefinition',
      document,
      variables,
    });
  }
}
