/**
 * PlatformFunctionGraphCommit model for ORM client
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { OrmClient } from '../client';
import {
  QueryBuilder,
  buildFindManyDocument,
  buildFindFirstDocument,
  buildFindOneDocument,
  buildCreateDocument,
  buildUpdateByPkDocument,
  buildDeleteByPkDocument,
} from '../query-builder';
import type {
  ConnectionResult,
  FindManyArgs,
  FindFirstArgs,
  CreateArgs,
  UpdateArgs,
  DeleteArgs,
  InferSelectResult,
  StrictSelect,
} from '../select-types';
import type {
  PlatformFunctionGraphCommit,
  PlatformFunctionGraphCommitWithRelations,
  PlatformFunctionGraphCommitSelect,
  PlatformFunctionGraphCommitFilter,
  PlatformFunctionGraphCommitOrderBy,
  CreatePlatformFunctionGraphCommitInput,
  UpdatePlatformFunctionGraphCommitInput,
  PlatformFunctionGraphCommitPatch,
} from '../input-types';
import { connectionFieldsMap } from '../input-types';
export class PlatformFunctionGraphCommitModel {
  constructor(private client: OrmClient) {}
  findMany<S extends PlatformFunctionGraphCommitSelect>(
    args: FindManyArgs<S, PlatformFunctionGraphCommitFilter, PlatformFunctionGraphCommitOrderBy> & {
      select: S;
    } & StrictSelect<S, PlatformFunctionGraphCommitSelect>
  ): QueryBuilder<{
    platformFunctionGraphCommits: ConnectionResult<
      InferSelectResult<PlatformFunctionGraphCommitWithRelations, S>
    >;
  }> {
    const { document, variables } = buildFindManyDocument(
      'PlatformFunctionGraphCommit',
      'platformFunctionGraphCommits',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
        first: args?.first,
        last: args?.last,
        after: args?.after,
        before: args?.before,
        offset: args?.offset,
      },
      'PlatformFunctionGraphCommitFilter',
      'PlatformFunctionGraphCommitOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'PlatformFunctionGraphCommit',
      fieldName: 'platformFunctionGraphCommits',
      document,
      variables,
    });
  }
  findFirst<S extends PlatformFunctionGraphCommitSelect>(
    args: FindFirstArgs<
      S,
      PlatformFunctionGraphCommitFilter,
      PlatformFunctionGraphCommitOrderBy
    > & {
      select: S;
    } & StrictSelect<S, PlatformFunctionGraphCommitSelect>
  ): QueryBuilder<{
    platformFunctionGraphCommit: InferSelectResult<
      PlatformFunctionGraphCommitWithRelations,
      S
    > | null;
  }> {
    const { document, variables } = buildFindFirstDocument(
      'PlatformFunctionGraphCommit',
      'platformFunctionGraphCommits',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
      },
      'PlatformFunctionGraphCommitFilter',
      'PlatformFunctionGraphCommitOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'PlatformFunctionGraphCommit',
      fieldName: 'platformFunctionGraphCommit',
      document,
      variables,
      transform: (data: {
        platformFunctionGraphCommits?: {
          nodes?: InferSelectResult<PlatformFunctionGraphCommitWithRelations, S>[];
        };
      }) => ({
        platformFunctionGraphCommit: data.platformFunctionGraphCommits?.nodes?.[0] ?? null,
      }),
    });
  }
  findOne<S extends PlatformFunctionGraphCommitSelect>(
    args: {
      id: string;
      select: S;
    } & StrictSelect<S, PlatformFunctionGraphCommitSelect>
  ): QueryBuilder<{
    platformFunctionGraphCommit: InferSelectResult<
      PlatformFunctionGraphCommitWithRelations,
      S
    > | null;
  }> {
    const { document, variables } = buildFindManyDocument(
      'PlatformFunctionGraphCommit',
      'platformFunctionGraphCommits',
      args.select,
      {
        where: {
          id: {
            equalTo: args.id,
          },
        },
        first: 1,
      },
      'PlatformFunctionGraphCommitFilter',
      'PlatformFunctionGraphCommitOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'PlatformFunctionGraphCommit',
      fieldName: 'platformFunctionGraphCommit',
      document,
      variables,
      transform: (data: {
        platformFunctionGraphCommits?: {
          nodes?: InferSelectResult<PlatformFunctionGraphCommitWithRelations, S>[];
        };
      }) => ({
        platformFunctionGraphCommit: data.platformFunctionGraphCommits?.nodes?.[0] ?? null,
      }),
    });
  }
  create<S extends PlatformFunctionGraphCommitSelect>(
    args: CreateArgs<S, CreatePlatformFunctionGraphCommitInput['platformFunctionGraphCommit']> & {
      select: S;
    } & StrictSelect<S, PlatformFunctionGraphCommitSelect>
  ): QueryBuilder<{
    createPlatformFunctionGraphCommit: {
      platformFunctionGraphCommit: InferSelectResult<PlatformFunctionGraphCommitWithRelations, S>;
    };
  }> {
    const { document, variables } = buildCreateDocument(
      'PlatformFunctionGraphCommit',
      'createPlatformFunctionGraphCommit',
      'platformFunctionGraphCommit',
      args.select,
      args.data,
      'CreatePlatformFunctionGraphCommitInput',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'PlatformFunctionGraphCommit',
      fieldName: 'createPlatformFunctionGraphCommit',
      document,
      variables,
    });
  }
  update<S extends PlatformFunctionGraphCommitSelect>(
    args: UpdateArgs<
      S,
      {
        id: string;
      },
      PlatformFunctionGraphCommitPatch
    > & {
      select: S;
    } & StrictSelect<S, PlatformFunctionGraphCommitSelect>
  ): QueryBuilder<{
    updatePlatformFunctionGraphCommit: {
      platformFunctionGraphCommit: InferSelectResult<PlatformFunctionGraphCommitWithRelations, S>;
    };
  }> {
    const { document, variables } = buildUpdateByPkDocument(
      'PlatformFunctionGraphCommit',
      'updatePlatformFunctionGraphCommit',
      'platformFunctionGraphCommit',
      args.select,
      args.where.id,
      args.data,
      'UpdatePlatformFunctionGraphCommitInput',
      'id',
      'platformFunctionGraphCommitPatch',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'PlatformFunctionGraphCommit',
      fieldName: 'updatePlatformFunctionGraphCommit',
      document,
      variables,
    });
  }
  delete<S extends PlatformFunctionGraphCommitSelect>(
    args: DeleteArgs<
      {
        id: string;
      },
      S
    > & {
      select: S;
    } & StrictSelect<S, PlatformFunctionGraphCommitSelect>
  ): QueryBuilder<{
    deletePlatformFunctionGraphCommit: {
      platformFunctionGraphCommit: InferSelectResult<PlatformFunctionGraphCommitWithRelations, S>;
    };
  }> {
    const { document, variables } = buildDeleteByPkDocument(
      'PlatformFunctionGraphCommit',
      'deletePlatformFunctionGraphCommit',
      'platformFunctionGraphCommit',
      {
        id: args.where.id,
      },
      'DeletePlatformFunctionGraphCommitInput',
      args.select,
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'PlatformFunctionGraphCommit',
      fieldName: 'deletePlatformFunctionGraphCommit',
      document,
      variables,
    });
  }
}
