/**
 * OrgFunctionExecutionLog model for ORM client
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { OrmClient } from '../client';
import {
  QueryBuilder,
  buildFindManyDocument,
  buildFindFirstDocument,
  buildFindOneDocument,
  buildCreateDocument,
  buildUpdateByPkDocument,
  buildDeleteByPkDocument,
} from '../query-builder';
import type {
  ConnectionResult,
  FindManyArgs,
  FindFirstArgs,
  CreateArgs,
  UpdateArgs,
  DeleteArgs,
  InferSelectResult,
  StrictSelect,
} from '../select-types';
import type {
  OrgFunctionExecutionLog,
  OrgFunctionExecutionLogWithRelations,
  OrgFunctionExecutionLogSelect,
  OrgFunctionExecutionLogFilter,
  OrgFunctionExecutionLogOrderBy,
  CreateOrgFunctionExecutionLogInput,
  UpdateOrgFunctionExecutionLogInput,
  OrgFunctionExecutionLogPatch,
} from '../input-types';
import { connectionFieldsMap } from '../input-types';
export class OrgFunctionExecutionLogModel {
  constructor(private client: OrmClient) {}
  findMany<S extends OrgFunctionExecutionLogSelect>(
    args: FindManyArgs<S, OrgFunctionExecutionLogFilter, OrgFunctionExecutionLogOrderBy> & {
      select: S;
    } & StrictSelect<S, OrgFunctionExecutionLogSelect>
  ): QueryBuilder<{
    orgFunctionExecutionLogs: ConnectionResult<
      InferSelectResult<OrgFunctionExecutionLogWithRelations, S>
    >;
  }> {
    const { document, variables } = buildFindManyDocument(
      'OrgFunctionExecutionLog',
      'orgFunctionExecutionLogs',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
        first: args?.first,
        last: args?.last,
        after: args?.after,
        before: args?.before,
        offset: args?.offset,
      },
      'OrgFunctionExecutionLogFilter',
      'OrgFunctionExecutionLogOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'OrgFunctionExecutionLog',
      fieldName: 'orgFunctionExecutionLogs',
      document,
      variables,
    });
  }
  findFirst<S extends OrgFunctionExecutionLogSelect>(
    args: FindFirstArgs<S, OrgFunctionExecutionLogFilter, OrgFunctionExecutionLogOrderBy> & {
      select: S;
    } & StrictSelect<S, OrgFunctionExecutionLogSelect>
  ): QueryBuilder<{
    orgFunctionExecutionLog: InferSelectResult<OrgFunctionExecutionLogWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindFirstDocument(
      'OrgFunctionExecutionLog',
      'orgFunctionExecutionLogs',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
      },
      'OrgFunctionExecutionLogFilter',
      'OrgFunctionExecutionLogOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'OrgFunctionExecutionLog',
      fieldName: 'orgFunctionExecutionLog',
      document,
      variables,
      transform: (data: {
        orgFunctionExecutionLogs?: {
          nodes?: InferSelectResult<OrgFunctionExecutionLogWithRelations, S>[];
        };
      }) => ({
        orgFunctionExecutionLog: data.orgFunctionExecutionLogs?.nodes?.[0] ?? null,
      }),
    });
  }
  findOne<S extends OrgFunctionExecutionLogSelect>(
    args: {
      id: string;
      select: S;
    } & StrictSelect<S, OrgFunctionExecutionLogSelect>
  ): QueryBuilder<{
    orgFunctionExecutionLog: InferSelectResult<OrgFunctionExecutionLogWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindManyDocument(
      'OrgFunctionExecutionLog',
      'orgFunctionExecutionLogs',
      args.select,
      {
        where: {
          id: {
            equalTo: args.id,
          },
        },
        first: 1,
      },
      'OrgFunctionExecutionLogFilter',
      'OrgFunctionExecutionLogOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'OrgFunctionExecutionLog',
      fieldName: 'orgFunctionExecutionLog',
      document,
      variables,
      transform: (data: {
        orgFunctionExecutionLogs?: {
          nodes?: InferSelectResult<OrgFunctionExecutionLogWithRelations, S>[];
        };
      }) => ({
        orgFunctionExecutionLog: data.orgFunctionExecutionLogs?.nodes?.[0] ?? null,
      }),
    });
  }
  create<S extends OrgFunctionExecutionLogSelect>(
    args: CreateArgs<S, CreateOrgFunctionExecutionLogInput['orgFunctionExecutionLog']> & {
      select: S;
    } & StrictSelect<S, OrgFunctionExecutionLogSelect>
  ): QueryBuilder<{
    createOrgFunctionExecutionLog: {
      orgFunctionExecutionLog: InferSelectResult<OrgFunctionExecutionLogWithRelations, S>;
    };
  }> {
    const { document, variables } = buildCreateDocument(
      'OrgFunctionExecutionLog',
      'createOrgFunctionExecutionLog',
      'orgFunctionExecutionLog',
      args.select,
      args.data,
      'CreateOrgFunctionExecutionLogInput',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'OrgFunctionExecutionLog',
      fieldName: 'createOrgFunctionExecutionLog',
      document,
      variables,
    });
  }
  update<S extends OrgFunctionExecutionLogSelect>(
    args: UpdateArgs<
      S,
      {
        id: string;
        createdAt: string;
      },
      OrgFunctionExecutionLogPatch
    > & {
      select: S;
    } & StrictSelect<S, OrgFunctionExecutionLogSelect>
  ): QueryBuilder<{
    updateOrgFunctionExecutionLog: {
      orgFunctionExecutionLog: InferSelectResult<OrgFunctionExecutionLogWithRelations, S>;
    };
  }> {
    const { document, variables } = buildUpdateByPkDocument(
      'OrgFunctionExecutionLog',
      'updateOrgFunctionExecutionLog',
      'orgFunctionExecutionLog',
      args.select,
      args.where.id,
      args.data,
      'UpdateOrgFunctionExecutionLogInput',
      'id',
      'orgFunctionExecutionLogPatch',
      connectionFieldsMap,
      {
        createdAt: args.where.createdAt,
      }
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'OrgFunctionExecutionLog',
      fieldName: 'updateOrgFunctionExecutionLog',
      document,
      variables,
    });
  }
  delete<S extends OrgFunctionExecutionLogSelect>(
    args: DeleteArgs<
      {
        id: string;
        createdAt: string;
      },
      S
    > & {
      select: S;
    } & StrictSelect<S, OrgFunctionExecutionLogSelect>
  ): QueryBuilder<{
    deleteOrgFunctionExecutionLog: {
      orgFunctionExecutionLog: InferSelectResult<OrgFunctionExecutionLogWithRelations, S>;
    };
  }> {
    const { document, variables } = buildDeleteByPkDocument(
      'OrgFunctionExecutionLog',
      'deleteOrgFunctionExecutionLog',
      'orgFunctionExecutionLog',
      {
        id: args.where.id,
        createdAt: args.where.createdAt,
      },
      'DeleteOrgFunctionExecutionLogInput',
      args.select,
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'OrgFunctionExecutionLog',
      fieldName: 'deleteOrgFunctionExecutionLog',
      document,
      variables,
    });
  }
}
