/**
 * PlatformFunctionGraphExecution model for ORM client
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { OrmClient } from '../client';
import {
  QueryBuilder,
  buildFindManyDocument,
  buildFindFirstDocument,
  buildFindOneDocument,
  buildCreateDocument,
  buildUpdateByPkDocument,
  buildDeleteByPkDocument,
} from '../query-builder';
import type {
  ConnectionResult,
  FindManyArgs,
  FindFirstArgs,
  CreateArgs,
  UpdateArgs,
  DeleteArgs,
  InferSelectResult,
  StrictSelect,
} from '../select-types';
import type {
  PlatformFunctionGraphExecution,
  PlatformFunctionGraphExecutionWithRelations,
  PlatformFunctionGraphExecutionSelect,
  PlatformFunctionGraphExecutionFilter,
  PlatformFunctionGraphExecutionOrderBy,
  CreatePlatformFunctionGraphExecutionInput,
  UpdatePlatformFunctionGraphExecutionInput,
  PlatformFunctionGraphExecutionPatch,
} from '../input-types';
import { connectionFieldsMap } from '../input-types';
export class PlatformFunctionGraphExecutionModel {
  constructor(private client: OrmClient) {}
  findMany<S extends PlatformFunctionGraphExecutionSelect>(
    args: FindManyArgs<
      S,
      PlatformFunctionGraphExecutionFilter,
      PlatformFunctionGraphExecutionOrderBy
    > & {
      select: S;
    } & StrictSelect<S, PlatformFunctionGraphExecutionSelect>
  ): QueryBuilder<{
    platformFunctionGraphExecutions: ConnectionResult<
      InferSelectResult<PlatformFunctionGraphExecutionWithRelations, S>
    >;
  }> {
    const { document, variables } = buildFindManyDocument(
      'PlatformFunctionGraphExecution',
      'platformFunctionGraphExecutions',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
        first: args?.first,
        last: args?.last,
        after: args?.after,
        before: args?.before,
        offset: args?.offset,
      },
      'PlatformFunctionGraphExecutionFilter',
      'PlatformFunctionGraphExecutionOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'PlatformFunctionGraphExecution',
      fieldName: 'platformFunctionGraphExecutions',
      document,
      variables,
    });
  }
  findFirst<S extends PlatformFunctionGraphExecutionSelect>(
    args: FindFirstArgs<
      S,
      PlatformFunctionGraphExecutionFilter,
      PlatformFunctionGraphExecutionOrderBy
    > & {
      select: S;
    } & StrictSelect<S, PlatformFunctionGraphExecutionSelect>
  ): QueryBuilder<{
    platformFunctionGraphExecution: InferSelectResult<
      PlatformFunctionGraphExecutionWithRelations,
      S
    > | null;
  }> {
    const { document, variables } = buildFindFirstDocument(
      'PlatformFunctionGraphExecution',
      'platformFunctionGraphExecutions',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
      },
      'PlatformFunctionGraphExecutionFilter',
      'PlatformFunctionGraphExecutionOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'PlatformFunctionGraphExecution',
      fieldName: 'platformFunctionGraphExecution',
      document,
      variables,
      transform: (data: {
        platformFunctionGraphExecutions?: {
          nodes?: InferSelectResult<PlatformFunctionGraphExecutionWithRelations, S>[];
        };
      }) => ({
        platformFunctionGraphExecution: data.platformFunctionGraphExecutions?.nodes?.[0] ?? null,
      }),
    });
  }
  findOne<S extends PlatformFunctionGraphExecutionSelect>(
    args: {
      id: string;
      select: S;
    } & StrictSelect<S, PlatformFunctionGraphExecutionSelect>
  ): QueryBuilder<{
    platformFunctionGraphExecution: InferSelectResult<
      PlatformFunctionGraphExecutionWithRelations,
      S
    > | null;
  }> {
    const { document, variables } = buildFindManyDocument(
      'PlatformFunctionGraphExecution',
      'platformFunctionGraphExecutions',
      args.select,
      {
        where: {
          id: {
            equalTo: args.id,
          },
        },
        first: 1,
      },
      'PlatformFunctionGraphExecutionFilter',
      'PlatformFunctionGraphExecutionOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'PlatformFunctionGraphExecution',
      fieldName: 'platformFunctionGraphExecution',
      document,
      variables,
      transform: (data: {
        platformFunctionGraphExecutions?: {
          nodes?: InferSelectResult<PlatformFunctionGraphExecutionWithRelations, S>[];
        };
      }) => ({
        platformFunctionGraphExecution: data.platformFunctionGraphExecutions?.nodes?.[0] ?? null,
      }),
    });
  }
  create<S extends PlatformFunctionGraphExecutionSelect>(
    args: CreateArgs<
      S,
      CreatePlatformFunctionGraphExecutionInput['platformFunctionGraphExecution']
    > & {
      select: S;
    } & StrictSelect<S, PlatformFunctionGraphExecutionSelect>
  ): QueryBuilder<{
    createPlatformFunctionGraphExecution: {
      platformFunctionGraphExecution: InferSelectResult<
        PlatformFunctionGraphExecutionWithRelations,
        S
      >;
    };
  }> {
    const { document, variables } = buildCreateDocument(
      'PlatformFunctionGraphExecution',
      'createPlatformFunctionGraphExecution',
      'platformFunctionGraphExecution',
      args.select,
      args.data,
      'CreatePlatformFunctionGraphExecutionInput',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'PlatformFunctionGraphExecution',
      fieldName: 'createPlatformFunctionGraphExecution',
      document,
      variables,
    });
  }
  update<S extends PlatformFunctionGraphExecutionSelect>(
    args: UpdateArgs<
      S,
      {
        id: string;
      },
      PlatformFunctionGraphExecutionPatch
    > & {
      select: S;
    } & StrictSelect<S, PlatformFunctionGraphExecutionSelect>
  ): QueryBuilder<{
    updatePlatformFunctionGraphExecution: {
      platformFunctionGraphExecution: InferSelectResult<
        PlatformFunctionGraphExecutionWithRelations,
        S
      >;
    };
  }> {
    const { document, variables } = buildUpdateByPkDocument(
      'PlatformFunctionGraphExecution',
      'updatePlatformFunctionGraphExecution',
      'platformFunctionGraphExecution',
      args.select,
      args.where.id,
      args.data,
      'UpdatePlatformFunctionGraphExecutionInput',
      'id',
      'platformFunctionGraphExecutionPatch',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'PlatformFunctionGraphExecution',
      fieldName: 'updatePlatformFunctionGraphExecution',
      document,
      variables,
    });
  }
  delete<S extends PlatformFunctionGraphExecutionSelect>(
    args: DeleteArgs<
      {
        id: string;
      },
      S
    > & {
      select: S;
    } & StrictSelect<S, PlatformFunctionGraphExecutionSelect>
  ): QueryBuilder<{
    deletePlatformFunctionGraphExecution: {
      platformFunctionGraphExecution: InferSelectResult<
        PlatformFunctionGraphExecutionWithRelations,
        S
      >;
    };
  }> {
    const { document, variables } = buildDeleteByPkDocument(
      'PlatformFunctionGraphExecution',
      'deletePlatformFunctionGraphExecution',
      'platformFunctionGraphExecution',
      {
        id: args.where.id,
      },
      'DeletePlatformFunctionGraphExecutionInput',
      args.select,
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'PlatformFunctionGraphExecution',
      fieldName: 'deletePlatformFunctionGraphExecution',
      document,
      variables,
    });
  }
}
