/**
 * PlatformUsageDaily model for ORM client
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { OrmClient } from '../client';
import {
  QueryBuilder,
  buildFindManyDocument,
  buildFindFirstDocument,
  buildFindOneDocument,
  buildCreateDocument,
  buildUpdateByPkDocument,
  buildDeleteByPkDocument,
} from '../query-builder';
import type {
  ConnectionResult,
  FindManyArgs,
  FindFirstArgs,
  CreateArgs,
  UpdateArgs,
  DeleteArgs,
  InferSelectResult,
  StrictSelect,
} from '../select-types';
import type {
  PlatformUsageDaily,
  PlatformUsageDailyWithRelations,
  PlatformUsageDailySelect,
  PlatformUsageDailyFilter,
  PlatformUsageDailyOrderBy,
  CreatePlatformUsageDailyInput,
  UpdatePlatformUsageDailyInput,
  PlatformUsageDailyPatch,
} from '../input-types';
import { connectionFieldsMap } from '../input-types';
export class PlatformUsageDailyModel {
  constructor(private client: OrmClient) {}
  findMany<S extends PlatformUsageDailySelect>(
    args: FindManyArgs<S, PlatformUsageDailyFilter, PlatformUsageDailyOrderBy> & {
      select: S;
    } & StrictSelect<S, PlatformUsageDailySelect>
  ): QueryBuilder<{
    platformUsageDailies: ConnectionResult<InferSelectResult<PlatformUsageDailyWithRelations, S>>;
  }> {
    const { document, variables } = buildFindManyDocument(
      'PlatformUsageDaily',
      'platformUsageDailies',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
        first: args?.first,
        last: args?.last,
        after: args?.after,
        before: args?.before,
        offset: args?.offset,
      },
      'PlatformUsageDailyFilter',
      'PlatformUsageDailyOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'PlatformUsageDaily',
      fieldName: 'platformUsageDailies',
      document,
      variables,
    });
  }
  findFirst<S extends PlatformUsageDailySelect>(
    args: FindFirstArgs<S, PlatformUsageDailyFilter, PlatformUsageDailyOrderBy> & {
      select: S;
    } & StrictSelect<S, PlatformUsageDailySelect>
  ): QueryBuilder<{
    platformUsageDaily: InferSelectResult<PlatformUsageDailyWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindFirstDocument(
      'PlatformUsageDaily',
      'platformUsageDailies',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
      },
      'PlatformUsageDailyFilter',
      'PlatformUsageDailyOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'PlatformUsageDaily',
      fieldName: 'platformUsageDaily',
      document,
      variables,
      transform: (data: {
        platformUsageDailies?: {
          nodes?: InferSelectResult<PlatformUsageDailyWithRelations, S>[];
        };
      }) => ({
        platformUsageDaily: data.platformUsageDailies?.nodes?.[0] ?? null,
      }),
    });
  }
  findOne<S extends PlatformUsageDailySelect>(
    args: {
      id: string;
      select: S;
    } & StrictSelect<S, PlatformUsageDailySelect>
  ): QueryBuilder<{
    platformUsageDaily: InferSelectResult<PlatformUsageDailyWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindManyDocument(
      'PlatformUsageDaily',
      'platformUsageDailies',
      args.select,
      {
        where: {
          id: {
            equalTo: args.id,
          },
        },
        first: 1,
      },
      'PlatformUsageDailyFilter',
      'PlatformUsageDailyOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'PlatformUsageDaily',
      fieldName: 'platformUsageDaily',
      document,
      variables,
      transform: (data: {
        platformUsageDailies?: {
          nodes?: InferSelectResult<PlatformUsageDailyWithRelations, S>[];
        };
      }) => ({
        platformUsageDaily: data.platformUsageDailies?.nodes?.[0] ?? null,
      }),
    });
  }
  create<S extends PlatformUsageDailySelect>(
    args: CreateArgs<S, CreatePlatformUsageDailyInput['platformUsageDaily']> & {
      select: S;
    } & StrictSelect<S, PlatformUsageDailySelect>
  ): QueryBuilder<{
    createPlatformUsageDaily: {
      platformUsageDaily: InferSelectResult<PlatformUsageDailyWithRelations, S>;
    };
  }> {
    const { document, variables } = buildCreateDocument(
      'PlatformUsageDaily',
      'createPlatformUsageDaily',
      'platformUsageDaily',
      args.select,
      args.data,
      'CreatePlatformUsageDailyInput',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'PlatformUsageDaily',
      fieldName: 'createPlatformUsageDaily',
      document,
      variables,
    });
  }
  update<S extends PlatformUsageDailySelect>(
    args: UpdateArgs<
      S,
      {
        id: string;
      },
      PlatformUsageDailyPatch
    > & {
      select: S;
    } & StrictSelect<S, PlatformUsageDailySelect>
  ): QueryBuilder<{
    updatePlatformUsageDaily: {
      platformUsageDaily: InferSelectResult<PlatformUsageDailyWithRelations, S>;
    };
  }> {
    const { document, variables } = buildUpdateByPkDocument(
      'PlatformUsageDaily',
      'updatePlatformUsageDaily',
      'platformUsageDaily',
      args.select,
      args.where.id,
      args.data,
      'UpdatePlatformUsageDailyInput',
      'id',
      'platformUsageDailyPatch',
      connectionFieldsMap,
      undefined
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'PlatformUsageDaily',
      fieldName: 'updatePlatformUsageDaily',
      document,
      variables,
    });
  }
  delete<S extends PlatformUsageDailySelect>(
    args: DeleteArgs<
      {
        id: string;
      },
      S
    > & {
      select: S;
    } & StrictSelect<S, PlatformUsageDailySelect>
  ): QueryBuilder<{
    deletePlatformUsageDaily: {
      platformUsageDaily: InferSelectResult<PlatformUsageDailyWithRelations, S>;
    };
  }> {
    const { document, variables } = buildDeleteByPkDocument(
      'PlatformUsageDaily',
      'deletePlatformUsageDaily',
      'platformUsageDaily',
      {
        id: args.where.id,
      },
      'DeletePlatformUsageDailyInput',
      args.select,
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'PlatformUsageDaily',
      fieldName: 'deletePlatformUsageDaily',
      document,
      variables,
    });
  }
}
