-- Revert: schemas/constructive_platform_function_graph_public/tables/platform_function_graph_ref/constraints/platform_function_graph_refs_pkey/constraint


ALTER TABLE "constructive_platform_function_graph_public".platform_function_graph_ref 
  DROP CONSTRAINT platform_function_graph_refs_pkey;


