/**
 * CLI commands for PlatformNamespaceEvent
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { CLIOptions, Inquirerer, extractFirst } from 'inquirerer';
import { getClient } from '../../executor';
import { coerceAnswers, parseFindFirstArgs, parseFindManyArgs, stripUndefined } from '../../utils';
import type { FieldSchema } from '../../utils';
import type {
  CreatePlatformNamespaceEventInput,
  PlatformNamespaceEventPatch,
  PlatformNamespaceEventSelect,
  PlatformNamespaceEventFilter,
  PlatformNamespaceEventOrderBy,
} from '../../../orm/input-types';
import type { FindManyArgs, FindFirstArgs } from '../../../orm/select-types';
const fieldSchema: FieldSchema = {
  createdAt: 'string',
  actorId: 'uuid',
  cpuMillicores: 'int',
  databaseId: 'uuid',
  eventType: 'string',
  id: 'uuid',
  memoryBytes: 'int',
  message: 'string',
  metadata: 'json',
  metrics: 'json',
  namespaceId: 'uuid',
  networkEgressBytes: 'int',
  networkIngressBytes: 'int',
  podCount: 'int',
  storageBytes: 'int',
};
const usage =
  '\nplatform-namespace-event <command>\n\nCommands:\n  list                  List platformNamespaceEvent records\n  find-first            Find first matching platformNamespaceEvent record\n  get                   Get a platformNamespaceEvent by ID\n  create                Create a new platformNamespaceEvent\n  update                Update an existing platformNamespaceEvent\n  delete                Delete a platformNamespaceEvent\n\nList Options:\n  --limit <n>           Max number of records to return (forward pagination)\n  --last <n>            Number of records from the end (backward pagination)\n  --after <cursor>      Cursor for forward pagination\n  --before <cursor>     Cursor for backward pagination\n  --offset <n>          Number of records to skip\n  --select <fields>     Comma-separated list of fields to return\n  --where.<field>.<op>  Filter (dot-notation, e.g. --where.name.equalTo foo)\n  --condition.<f>.<op>  Condition filter (dot-notation)\n  --orderBy <values>    Comma-separated ordering values (e.g. NAME_ASC,CREATED_AT_DESC)\n\nFind-First Options:\n  --select <fields>     Comma-separated list of fields to return\n  --where.<field>.<op>  Filter (dot-notation, e.g. --where.status.equalTo active)\n  --condition.<f>.<op>  Condition filter (dot-notation)\n  --orderBy <values>    Comma-separated ordering values (e.g. NAME_ASC,CREATED_AT_DESC)\n\n  --help, -h            Show this help message\n';
export default async (
  argv: Partial<Record<string, unknown>>,
  prompter: Inquirerer,
  _options: CLIOptions
) => {
  if (argv.help || argv.h) {
    console.log(usage);
    process.exit(0);
  }
  const { first: subcommand, newArgv } = extractFirst(argv);
  if (!subcommand) {
    const answer = await prompter.prompt(argv, [
      {
        type: 'autocomplete',
        name: 'subcommand',
        message: 'What do you want to do?',
        options: ['list', 'find-first', 'get', 'create', 'update', 'delete'],
      },
    ]);
    return handleTableSubcommand(answer.subcommand as string, newArgv, prompter);
  }
  return handleTableSubcommand(subcommand, newArgv, prompter);
};
async function handleTableSubcommand(
  subcommand: string,
  argv: Partial<Record<string, unknown>>,
  prompter: Inquirerer
) {
  switch (subcommand) {
    case 'list':
      return handleList(argv, prompter);
    case 'find-first':
      return handleFindFirst(argv, prompter);
    case 'get':
      return handleGet(argv, prompter);
    case 'create':
      return handleCreate(argv, prompter);
    case 'update':
      return handleUpdate(argv, prompter);
    case 'delete':
      return handleDelete(argv, prompter);
    default:
      console.log(usage);
      process.exit(1);
  }
}
async function handleList(argv: Partial<Record<string, unknown>>, _prompter: Inquirerer) {
  try {
    const defaultSelect = {
      createdAt: true,
      actorId: true,
      cpuMillicores: true,
      databaseId: true,
      eventType: true,
      id: true,
      memoryBytes: true,
      message: true,
      metadata: true,
      metrics: true,
      namespaceId: true,
      networkEgressBytes: true,
      networkIngressBytes: true,
      podCount: true,
      storageBytes: true,
    };
    const findManyArgs = parseFindManyArgs<
      FindManyArgs<
        PlatformNamespaceEventSelect,
        PlatformNamespaceEventFilter,
        PlatformNamespaceEventOrderBy
      > & {
        select: PlatformNamespaceEventSelect;
      }
    >(argv, defaultSelect);
    const client = getClient('api');
    const result = await client.platformNamespaceEvent.findMany(findManyArgs).execute();
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error('Failed to list records.');
    if (error instanceof Error) {
      console.error(error.message);
    }
    process.exit(1);
  }
}
async function handleFindFirst(argv: Partial<Record<string, unknown>>, _prompter: Inquirerer) {
  try {
    const defaultSelect = {
      createdAt: true,
      actorId: true,
      cpuMillicores: true,
      databaseId: true,
      eventType: true,
      id: true,
      memoryBytes: true,
      message: true,
      metadata: true,
      metrics: true,
      namespaceId: true,
      networkEgressBytes: true,
      networkIngressBytes: true,
      podCount: true,
      storageBytes: true,
    };
    const findFirstArgs = parseFindFirstArgs<
      FindFirstArgs<
        PlatformNamespaceEventSelect,
        PlatformNamespaceEventFilter,
        PlatformNamespaceEventOrderBy
      > & {
        select: PlatformNamespaceEventSelect;
      }
    >(argv, defaultSelect);
    const client = getClient('api');
    const result = await client.platformNamespaceEvent.findFirst(findFirstArgs).execute();
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error('Failed to find record.');
    if (error instanceof Error) {
      console.error(error.message);
    }
    process.exit(1);
  }
}
async function handleGet(argv: Partial<Record<string, unknown>>, prompter: Inquirerer) {
  try {
    const answers = await prompter.prompt(argv, [
      {
        type: 'text',
        name: 'id',
        message: 'id',
        required: true,
      },
    ]);
    const client = getClient('api');
    const result = await client.platformNamespaceEvent
      .findOne({
        id: answers.id as string,
        select: {
          createdAt: true,
          actorId: true,
          cpuMillicores: true,
          databaseId: true,
          eventType: true,
          id: true,
          memoryBytes: true,
          message: true,
          metadata: true,
          metrics: true,
          namespaceId: true,
          networkEgressBytes: true,
          networkIngressBytes: true,
          podCount: true,
          storageBytes: true,
        },
      })
      .execute();
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error('Record not found.');
    if (error instanceof Error) {
      console.error(error.message);
    }
    process.exit(1);
  }
}
async function handleCreate(argv: Partial<Record<string, unknown>>, prompter: Inquirerer) {
  try {
    const rawAnswers = await prompter.prompt(argv, [
      {
        type: 'text',
        name: 'actorId',
        message: 'actorId',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'cpuMillicores',
        message: 'cpuMillicores',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'databaseId',
        message: 'databaseId',
        required: true,
      },
      {
        type: 'text',
        name: 'eventType',
        message: 'eventType',
        required: true,
      },
      {
        type: 'text',
        name: 'memoryBytes',
        message: 'memoryBytes',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'message',
        message: 'message',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'json',
        name: 'metadata',
        message: 'metadata',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'json',
        name: 'metrics',
        message: 'metrics',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'namespaceId',
        message: 'namespaceId',
        required: true,
      },
      {
        type: 'text',
        name: 'networkEgressBytes',
        message: 'networkEgressBytes',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'networkIngressBytes',
        message: 'networkIngressBytes',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'podCount',
        message: 'podCount',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'storageBytes',
        message: 'storageBytes',
        required: false,
        skipPrompt: true,
      },
    ]);
    const answers = coerceAnswers(rawAnswers, fieldSchema);
    const cleanedData = stripUndefined(
      answers,
      fieldSchema
    ) as CreatePlatformNamespaceEventInput['platformNamespaceEvent'];
    const client = getClient('api');
    const result = await client.platformNamespaceEvent
      .create({
        data: {
          actorId: cleanedData.actorId,
          cpuMillicores: cleanedData.cpuMillicores,
          databaseId: cleanedData.databaseId,
          eventType: cleanedData.eventType,
          memoryBytes: cleanedData.memoryBytes,
          message: cleanedData.message,
          metadata: cleanedData.metadata,
          metrics: cleanedData.metrics,
          namespaceId: cleanedData.namespaceId,
          networkEgressBytes: cleanedData.networkEgressBytes,
          networkIngressBytes: cleanedData.networkIngressBytes,
          podCount: cleanedData.podCount,
          storageBytes: cleanedData.storageBytes,
        },
        select: {
          createdAt: true,
          actorId: true,
          cpuMillicores: true,
          databaseId: true,
          eventType: true,
          id: true,
          memoryBytes: true,
          message: true,
          metadata: true,
          metrics: true,
          namespaceId: true,
          networkEgressBytes: true,
          networkIngressBytes: true,
          podCount: true,
          storageBytes: true,
        },
      })
      .execute();
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error('Failed to create record.');
    if (error instanceof Error) {
      console.error(error.message);
    }
    process.exit(1);
  }
}
async function handleUpdate(argv: Partial<Record<string, unknown>>, prompter: Inquirerer) {
  try {
    const rawAnswers = await prompter.prompt(argv, [
      {
        type: 'text',
        name: 'id',
        message: 'id',
        required: true,
      },
      {
        type: 'text',
        name: 'actorId',
        message: 'actorId',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'cpuMillicores',
        message: 'cpuMillicores',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'databaseId',
        message: 'databaseId',
        required: false,
      },
      {
        type: 'text',
        name: 'eventType',
        message: 'eventType',
        required: false,
      },
      {
        type: 'text',
        name: 'memoryBytes',
        message: 'memoryBytes',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'message',
        message: 'message',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'json',
        name: 'metadata',
        message: 'metadata',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'json',
        name: 'metrics',
        message: 'metrics',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'namespaceId',
        message: 'namespaceId',
        required: false,
      },
      {
        type: 'text',
        name: 'networkEgressBytes',
        message: 'networkEgressBytes',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'networkIngressBytes',
        message: 'networkIngressBytes',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'podCount',
        message: 'podCount',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'storageBytes',
        message: 'storageBytes',
        required: false,
        skipPrompt: true,
      },
    ]);
    const answers = coerceAnswers(rawAnswers, fieldSchema);
    const cleanedData = stripUndefined(answers, fieldSchema) as PlatformNamespaceEventPatch;
    const client = getClient('api');
    const result = await client.platformNamespaceEvent
      .update({
        where: {
          id: answers.id as string,
        },
        data: {
          actorId: cleanedData.actorId,
          cpuMillicores: cleanedData.cpuMillicores,
          databaseId: cleanedData.databaseId,
          eventType: cleanedData.eventType,
          memoryBytes: cleanedData.memoryBytes,
          message: cleanedData.message,
          metadata: cleanedData.metadata,
          metrics: cleanedData.metrics,
          namespaceId: cleanedData.namespaceId,
          networkEgressBytes: cleanedData.networkEgressBytes,
          networkIngressBytes: cleanedData.networkIngressBytes,
          podCount: cleanedData.podCount,
          storageBytes: cleanedData.storageBytes,
        },
        select: {
          createdAt: true,
          actorId: true,
          cpuMillicores: true,
          databaseId: true,
          eventType: true,
          id: true,
          memoryBytes: true,
          message: true,
          metadata: true,
          metrics: true,
          namespaceId: true,
          networkEgressBytes: true,
          networkIngressBytes: true,
          podCount: true,
          storageBytes: true,
        },
      })
      .execute();
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error('Failed to update record.');
    if (error instanceof Error) {
      console.error(error.message);
    }
    process.exit(1);
  }
}
async function handleDelete(argv: Partial<Record<string, unknown>>, prompter: Inquirerer) {
  try {
    const rawAnswers = await prompter.prompt(argv, [
      {
        type: 'text',
        name: 'id',
        message: 'id',
        required: true,
      },
    ]);
    const answers = coerceAnswers(rawAnswers, fieldSchema);
    const client = getClient('api');
    const result = await client.platformNamespaceEvent
      .delete({
        where: {
          id: answers.id as string,
        },
        select: {
          id: true,
        },
      })
      .execute();
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error('Failed to delete record.');
    if (error instanceof Error) {
      console.error(error.message);
    }
    process.exit(1);
  }
}
