/**
 * CLI commands for PlatformConfig
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { CLIOptions, extractFirst,Inquirerer } from 'inquirerer';

import type {
  CreatePlatformConfigInput,
  PlatformConfigFilter,
  PlatformConfigOrderBy,
  PlatformConfigPatch,
  PlatformConfigSelect,
} from '../../../orm/input-types';
import type { FindFirstArgs,FindManyArgs } from '../../../orm/select-types';
import { getClient } from '../../executor';
import type { FieldSchema } from '../../utils';
import { coerceAnswers, parseFindFirstArgs, parseFindManyArgs, stripUndefined } from '../../utils';
const fieldSchema: FieldSchema = {
  annotations: 'json',
  createdAt: 'string',
  description: 'string',
  expiresAt: 'string',
  id: 'uuid',
  labels: 'json',
  name: 'string',
  namespaceId: 'uuid',
  updatedAt: 'string',
  value: 'string',
};
const usage =
  '\nplatform-config <command>\n\nCommands:\n  list                  List platformConfig records\n  find-first            Find first matching platformConfig record\n  get                   Get a platformConfig by ID\n  create                Create a new platformConfig\n  update                Update an existing platformConfig\n  delete                Delete a platformConfig\n\nList Options:\n  --limit <n>           Max number of records to return (forward pagination)\n  --last <n>            Number of records from the end (backward pagination)\n  --after <cursor>      Cursor for forward pagination\n  --before <cursor>     Cursor for backward pagination\n  --offset <n>          Number of records to skip\n  --select <fields>     Comma-separated list of fields to return\n  --where.<field>.<op>  Filter (dot-notation, e.g. --where.name.equalTo foo)\n  --condition.<f>.<op>  Condition filter (dot-notation)\n  --orderBy <values>    Comma-separated ordering values (e.g. NAME_ASC,CREATED_AT_DESC)\n\nFind-First Options:\n  --select <fields>     Comma-separated list of fields to return\n  --where.<field>.<op>  Filter (dot-notation, e.g. --where.status.equalTo active)\n  --condition.<f>.<op>  Condition filter (dot-notation)\n  --orderBy <values>    Comma-separated ordering values (e.g. NAME_ASC,CREATED_AT_DESC)\n\n  --help, -h            Show this help message\n';
export default async (
  argv: Partial<Record<string, unknown>>,
  prompter: Inquirerer,
  _options: CLIOptions
) => {
  if (argv.help || argv.h) {
    console.log(usage);
    process.exit(0);
  }
  const { first: subcommand, newArgv } = extractFirst(argv);
  if (!subcommand) {
    const answer = await prompter.prompt(argv, [
      {
        type: 'autocomplete',
        name: 'subcommand',
        message: 'What do you want to do?',
        options: ['list', 'find-first', 'get', 'create', 'update', 'delete'],
      },
    ]);
    return handleTableSubcommand(answer.subcommand as string, newArgv, prompter);
  }
  return handleTableSubcommand(subcommand, newArgv, prompter);
};
async function handleTableSubcommand(
  subcommand: string,
  argv: Partial<Record<string, unknown>>,
  prompter: Inquirerer
) {
  switch (subcommand) {
    case 'list':
      return handleList(argv, prompter);
    case 'find-first':
      return handleFindFirst(argv, prompter);
    case 'get':
      return handleGet(argv, prompter);
    case 'create':
      return handleCreate(argv, prompter);
    case 'update':
      return handleUpdate(argv, prompter);
    case 'delete':
      return handleDelete(argv, prompter);
    default:
      console.log(usage);
      process.exit(1);
  }
}
async function handleList(argv: Partial<Record<string, unknown>>, _prompter: Inquirerer) {
  try {
    const defaultSelect = {
      annotations: true,
      createdAt: true,
      description: true,
      expiresAt: true,
      id: true,
      labels: true,
      name: true,
      namespaceId: true,
      updatedAt: true,
      value: true,
    };
    const findManyArgs = parseFindManyArgs<
      FindManyArgs<PlatformConfigSelect, PlatformConfigFilter, PlatformConfigOrderBy> & {
        select: PlatformConfigSelect;
      }
    >(argv, defaultSelect);
    const client = getClient('api');
    const result = await client.platformConfig.findMany(findManyArgs).execute();
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error('Failed to list records.');
    if (error instanceof Error) {
      console.error(error.message);
    }
    process.exit(1);
  }
}
async function handleFindFirst(argv: Partial<Record<string, unknown>>, _prompter: Inquirerer) {
  try {
    const defaultSelect = {
      annotations: true,
      createdAt: true,
      description: true,
      expiresAt: true,
      id: true,
      labels: true,
      name: true,
      namespaceId: true,
      updatedAt: true,
      value: true,
    };
    const findFirstArgs = parseFindFirstArgs<
      FindFirstArgs<PlatformConfigSelect, PlatformConfigFilter, PlatformConfigOrderBy> & {
        select: PlatformConfigSelect;
      }
    >(argv, defaultSelect);
    const client = getClient('api');
    const result = await client.platformConfig.findFirst(findFirstArgs).execute();
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error('Failed to find record.');
    if (error instanceof Error) {
      console.error(error.message);
    }
    process.exit(1);
  }
}
async function handleGet(argv: Partial<Record<string, unknown>>, prompter: Inquirerer) {
  try {
    const answers = await prompter.prompt(argv, [
      {
        type: 'text',
        name: 'id',
        message: 'id',
        required: true,
      },
    ]);
    const client = getClient('api');
    const result = await client.platformConfig
      .findOne({
        id: answers.id as string,
        select: {
          annotations: true,
          createdAt: true,
          description: true,
          expiresAt: true,
          id: true,
          labels: true,
          name: true,
          namespaceId: true,
          updatedAt: true,
          value: true,
        },
      })
      .execute();
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error('Record not found.');
    if (error instanceof Error) {
      console.error(error.message);
    }
    process.exit(1);
  }
}
async function handleCreate(argv: Partial<Record<string, unknown>>, prompter: Inquirerer) {
  try {
    const rawAnswers = await prompter.prompt(argv, [
      {
        type: 'json',
        name: 'annotations',
        message: 'annotations',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'description',
        message: 'description',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'expiresAt',
        message: 'expiresAt',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'json',
        name: 'labels',
        message: 'labels',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'name',
        message: 'name',
        required: true,
      },
      {
        type: 'text',
        name: 'namespaceId',
        message: 'namespaceId',
        required: true,
      },
      {
        type: 'text',
        name: 'value',
        message: 'value',
        required: false,
        skipPrompt: true,
      },
    ]);
    const answers = coerceAnswers(rawAnswers, fieldSchema);
    const cleanedData = stripUndefined(
      answers,
      fieldSchema
    ) as CreatePlatformConfigInput['platformConfig'];
    const client = getClient('api');
    const result = await client.platformConfig
      .create({
        data: {
          annotations: cleanedData.annotations,
          description: cleanedData.description,
          expiresAt: cleanedData.expiresAt,
          labels: cleanedData.labels,
          name: cleanedData.name,
          namespaceId: cleanedData.namespaceId,
          value: cleanedData.value,
        },
        select: {
          annotations: true,
          createdAt: true,
          description: true,
          expiresAt: true,
          id: true,
          labels: true,
          name: true,
          namespaceId: true,
          updatedAt: true,
          value: true,
        },
      })
      .execute();
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error('Failed to create record.');
    if (error instanceof Error) {
      console.error(error.message);
    }
    process.exit(1);
  }
}
async function handleUpdate(argv: Partial<Record<string, unknown>>, prompter: Inquirerer) {
  try {
    const rawAnswers = await prompter.prompt(argv, [
      {
        type: 'text',
        name: 'id',
        message: 'id',
        required: true,
      },
      {
        type: 'json',
        name: 'annotations',
        message: 'annotations',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'description',
        message: 'description',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'expiresAt',
        message: 'expiresAt',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'json',
        name: 'labels',
        message: 'labels',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'name',
        message: 'name',
        required: false,
      },
      {
        type: 'text',
        name: 'namespaceId',
        message: 'namespaceId',
        required: false,
      },
      {
        type: 'text',
        name: 'value',
        message: 'value',
        required: false,
        skipPrompt: true,
      },
    ]);
    const answers = coerceAnswers(rawAnswers, fieldSchema);
    const cleanedData = stripUndefined(answers, fieldSchema) as PlatformConfigPatch;
    const client = getClient('api');
    const result = await client.platformConfig
      .update({
        where: {
          id: answers.id as string,
        },
        data: {
          annotations: cleanedData.annotations,
          description: cleanedData.description,
          expiresAt: cleanedData.expiresAt,
          labels: cleanedData.labels,
          name: cleanedData.name,
          namespaceId: cleanedData.namespaceId,
          value: cleanedData.value,
        },
        select: {
          annotations: true,
          createdAt: true,
          description: true,
          expiresAt: true,
          id: true,
          labels: true,
          name: true,
          namespaceId: true,
          updatedAt: true,
          value: true,
        },
      })
      .execute();
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error('Failed to update record.');
    if (error instanceof Error) {
      console.error(error.message);
    }
    process.exit(1);
  }
}
async function handleDelete(argv: Partial<Record<string, unknown>>, prompter: Inquirerer) {
  try {
    const rawAnswers = await prompter.prompt(argv, [
      {
        type: 'text',
        name: 'id',
        message: 'id',
        required: true,
      },
    ]);
    const answers = coerceAnswers(rawAnswers, fieldSchema);
    const client = getClient('api');
    const result = await client.platformConfig
      .delete({
        where: {
          id: answers.id as string,
        },
        select: {
          id: true,
        },
      })
      .execute();
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error('Failed to delete record.');
    if (error instanceof Error) {
      console.error(error.message);
    }
    process.exit(1);
  }
}
