/**
 * CLI command for mutation uploadPlatformFile
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { CLIOptions, Inquirerer } from 'inquirerer';
import { getClient } from '../../executor';
import { unflattenDotNotation, buildSelectFromPaths } from '../../utils';
import type { UploadPlatformFileVariables } from '../../../orm/mutation';
import type { UploadPlatformFilePayloadSelect } from '../../../orm/input-types';
export default async (
  argv: Partial<Record<string, unknown>>,
  prompter: Inquirerer,
  _options: CLIOptions
) => {
  try {
    if (argv.help || argv.h) {
      console.log(
        'upload-platform-file - Upload a file: resolves the bucket by key, creates the file row, and returns a presigned PUT URL.\n\nUsage: upload-platform-file [OPTIONS]\n'
      );
      process.exit(0);
    }
    const answers = await prompter.prompt(argv, [
      {
        type: 'text',
        name: 'input',
        message:
          'The exclusive input argument for this mutation. An object type, make sure to see documentation for this object\u2019s fields.',
        required: true,
      },
    ]);
    const client = getClient('api');
    const parsedAnswers = unflattenDotNotation(answers);
    const selectFields = buildSelectFromPaths((argv.select as string) ?? 'clientMutationId');
    const result = await client.mutation
      .uploadPlatformFile(
        parsedAnswers as unknown as UploadPlatformFileVariables,
        {
          select: selectFields,
        } as unknown as {
          select: UploadPlatformFilePayloadSelect;
        }
      )
      .execute();
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error('Failed: uploadPlatformFile');
    if (error instanceof Error) {
      console.error(error.message);
    }
    process.exit(1);
  }
};
