/**
 * Centralized mutation key factory
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

// ============================================================================
// Mutation keys for tracking in-flight mutations
//
// Benefits:
// - Track mutation state with useIsMutating
// - Implement optimistic updates with proper rollback
// - Deduplicate identical mutations
// - Coordinate related mutations
// ============================================================================

// ============================================================================
// Entity Mutation Keys
// ============================================================================

export const getAllRecordMutationKeys = {
  /** All getAllRecord mutation keys */ all: ['mutation', 'getallrecord'] as const,
  /** Create getAllRecord mutation key */ create: () =>
    ['mutation', 'getallrecord', 'create'] as const,
  /** Update getAllRecord mutation key */ update: (id: string | number) =>
    ['mutation', 'getallrecord', 'update', id] as const,
  /** Delete getAllRecord mutation key */ delete: (id: string | number) =>
    ['mutation', 'getallrecord', 'delete', id] as const,
} as const;
export const platformFunctionGraphRefMutationKeys = {
  /** All platformFunctionGraphRef mutation keys */ all: [
    'mutation',
    'platformfunctiongraphref',
  ] as const,
  /** Create platformFunctionGraphRef mutation key */ create: () =>
    ['mutation', 'platformfunctiongraphref', 'create'] as const,
  /** Update platformFunctionGraphRef mutation key */ update: (id: string | number) =>
    ['mutation', 'platformfunctiongraphref', 'update', id] as const,
  /** Delete platformFunctionGraphRef mutation key */ delete: (id: string | number) =>
    ['mutation', 'platformfunctiongraphref', 'delete', id] as const,
} as const;
export const platformFunctionGraphStoreMutationKeys = {
  /** All platformFunctionGraphStore mutation keys */ all: [
    'mutation',
    'platformfunctiongraphstore',
  ] as const,
  /** Create platformFunctionGraphStore mutation key */ create: () =>
    ['mutation', 'platformfunctiongraphstore', 'create'] as const,
  /** Update platformFunctionGraphStore mutation key */ update: (id: string | number) =>
    ['mutation', 'platformfunctiongraphstore', 'update', id] as const,
  /** Delete platformFunctionGraphStore mutation key */ delete: (id: string | number) =>
    ['mutation', 'platformfunctiongraphstore', 'delete', id] as const,
} as const;
export const platformFunctionGraphObjectMutationKeys = {
  /** All platformFunctionGraphObject mutation keys */ all: [
    'mutation',
    'platformfunctiongraphobject',
  ] as const,
  /** Create platformFunctionGraphObject mutation key */ create: () =>
    ['mutation', 'platformfunctiongraphobject', 'create'] as const,
  /** Update platformFunctionGraphObject mutation key */ update: (id: string | number) =>
    ['mutation', 'platformfunctiongraphobject', 'update', id] as const,
  /** Delete platformFunctionGraphObject mutation key */ delete: (id: string | number) =>
    ['mutation', 'platformfunctiongraphobject', 'delete', id] as const,
} as const;
export const orgFunctionExecutionLogMutationKeys = {
  /** All orgFunctionExecutionLog mutation keys */ all: [
    'mutation',
    'orgfunctionexecutionlog',
  ] as const,
  /** Create orgFunctionExecutionLog mutation key */ create: () =>
    ['mutation', 'orgfunctionexecutionlog', 'create'] as const,
  /** Update orgFunctionExecutionLog mutation key */ update: (id: string | number) =>
    ['mutation', 'orgfunctionexecutionlog', 'update', id] as const,
  /** Delete orgFunctionExecutionLog mutation key */ delete: (id: string | number) =>
    ['mutation', 'orgfunctionexecutionlog', 'delete', id] as const,
} as const;
export const platformFunctionGraphExecutionOutputMutationKeys = {
  /** All platformFunctionGraphExecutionOutput mutation keys */ all: [
    'mutation',
    'platformfunctiongraphexecutionoutput',
  ] as const,
  /** Create platformFunctionGraphExecutionOutput mutation key */ create: () =>
    ['mutation', 'platformfunctiongraphexecutionoutput', 'create'] as const,
  /** Update platformFunctionGraphExecutionOutput mutation key */ update: (id: string | number) =>
    ['mutation', 'platformfunctiongraphexecutionoutput', 'update', id] as const,
  /** Delete platformFunctionGraphExecutionOutput mutation key */ delete: (id: string | number) =>
    ['mutation', 'platformfunctiongraphexecutionoutput', 'delete', id] as const,
} as const;
export const platformFunctionGraphCommitMutationKeys = {
  /** All platformFunctionGraphCommit mutation keys */ all: [
    'mutation',
    'platformfunctiongraphcommit',
  ] as const,
  /** Create platformFunctionGraphCommit mutation key */ create: () =>
    ['mutation', 'platformfunctiongraphcommit', 'create'] as const,
  /** Update platformFunctionGraphCommit mutation key */ update: (id: string | number) =>
    ['mutation', 'platformfunctiongraphcommit', 'update', id] as const,
  /** Delete platformFunctionGraphCommit mutation key */ delete: (id: string | number) =>
    ['mutation', 'platformfunctiongraphcommit', 'delete', id] as const,
} as const;
export const platformSecretDefinitionMutationKeys = {
  /** All platformSecretDefinition mutation keys */ all: [
    'mutation',
    'platformsecretdefinition',
  ] as const,
  /** Create platformSecretDefinition mutation key */ create: () =>
    ['mutation', 'platformsecretdefinition', 'create'] as const,
  /** Update platformSecretDefinition mutation key */ update: (id: string | number) =>
    ['mutation', 'platformsecretdefinition', 'update', id] as const,
  /** Delete platformSecretDefinition mutation key */ delete: (id: string | number) =>
    ['mutation', 'platformsecretdefinition', 'delete', id] as const,
} as const;
export const platformFunctionExecutionLogMutationKeys = {
  /** All platformFunctionExecutionLog mutation keys */ all: [
    'mutation',
    'platformfunctionexecutionlog',
  ] as const,
  /** Create platformFunctionExecutionLog mutation key */ create: () =>
    ['mutation', 'platformfunctionexecutionlog', 'create'] as const,
  /** Update platformFunctionExecutionLog mutation key */ update: (id: string | number) =>
    ['mutation', 'platformfunctionexecutionlog', 'update', id] as const,
  /** Delete platformFunctionExecutionLog mutation key */ delete: (id: string | number) =>
    ['mutation', 'platformfunctionexecutionlog', 'delete', id] as const,
} as const;
export const platformFunctionGraphExecutionNodeStateMutationKeys = {
  /** All platformFunctionGraphExecutionNodeState mutation keys */ all: [
    'mutation',
    'platformfunctiongraphexecutionnodestate',
  ] as const,
  /** Create platformFunctionGraphExecutionNodeState mutation key */ create: () =>
    ['mutation', 'platformfunctiongraphexecutionnodestate', 'create'] as const,
  /** Update platformFunctionGraphExecutionNodeState mutation key */ update: (
    id: string | number
  ) => ['mutation', 'platformfunctiongraphexecutionnodestate', 'update', id] as const,
  /** Delete platformFunctionGraphExecutionNodeState mutation key */ delete: (
    id: string | number
  ) => ['mutation', 'platformfunctiongraphexecutionnodestate', 'delete', id] as const,
} as const;
export const platformFunctionGraphMutationKeys = {
  /** All platformFunctionGraph mutation keys */ all: [
    'mutation',
    'platformfunctiongraph',
  ] as const,
  /** Create platformFunctionGraph mutation key */ create: () =>
    ['mutation', 'platformfunctiongraph', 'create'] as const,
  /** Update platformFunctionGraph mutation key */ update: (id: string | number) =>
    ['mutation', 'platformfunctiongraph', 'update', id] as const,
  /** Delete platformFunctionGraph mutation key */ delete: (id: string | number) =>
    ['mutation', 'platformfunctiongraph', 'delete', id] as const,
} as const;
export const platformComputeLogMutationKeys = {
  /** All platformComputeLog mutation keys */ all: ['mutation', 'platformcomputelog'] as const,
  /** Create platformComputeLog mutation key */ create: () =>
    ['mutation', 'platformcomputelog', 'create'] as const,
  /** Update platformComputeLog mutation key */ update: (id: string | number) =>
    ['mutation', 'platformcomputelog', 'update', id] as const,
  /** Delete platformComputeLog mutation key */ delete: (id: string | number) =>
    ['mutation', 'platformcomputelog', 'delete', id] as const,
} as const;
export const platformUsageDailyMutationKeys = {
  /** All platformUsageDaily mutation keys */ all: ['mutation', 'platformusagedaily'] as const,
  /** Create platformUsageDaily mutation key */ create: () =>
    ['mutation', 'platformusagedaily', 'create'] as const,
  /** Update platformUsageDaily mutation key */ update: (id: string | number) =>
    ['mutation', 'platformusagedaily', 'update', id] as const,
  /** Delete platformUsageDaily mutation key */ delete: (id: string | number) =>
    ['mutation', 'platformusagedaily', 'delete', id] as const,
} as const;
export const orgFunctionInvocationMutationKeys = {
  /** All orgFunctionInvocation mutation keys */ all: [
    'mutation',
    'orgfunctioninvocation',
  ] as const,
  /** Create orgFunctionInvocation mutation key */ create: () =>
    ['mutation', 'orgfunctioninvocation', 'create'] as const,
  /** Update orgFunctionInvocation mutation key */ update: (id: string | number) =>
    ['mutation', 'orgfunctioninvocation', 'update', id] as const,
  /** Delete orgFunctionInvocation mutation key */ delete: (id: string | number) =>
    ['mutation', 'orgfunctioninvocation', 'delete', id] as const,
} as const;
export const platformFunctionInvocationMutationKeys = {
  /** All platformFunctionInvocation mutation keys */ all: [
    'mutation',
    'platformfunctioninvocation',
  ] as const,
  /** Create platformFunctionInvocation mutation key */ create: () =>
    ['mutation', 'platformfunctioninvocation', 'create'] as const,
  /** Update platformFunctionInvocation mutation key */ update: (id: string | number) =>
    ['mutation', 'platformfunctioninvocation', 'update', id] as const,
  /** Delete platformFunctionInvocation mutation key */ delete: (id: string | number) =>
    ['mutation', 'platformfunctioninvocation', 'delete', id] as const,
} as const;
export const platformFunctionGraphExecutionMutationKeys = {
  /** All platformFunctionGraphExecution mutation keys */ all: [
    'mutation',
    'platformfunctiongraphexecution',
  ] as const,
  /** Create platformFunctionGraphExecution mutation key */ create: () =>
    ['mutation', 'platformfunctiongraphexecution', 'create'] as const,
  /** Update platformFunctionGraphExecution mutation key */ update: (id: string | number) =>
    ['mutation', 'platformfunctiongraphexecution', 'update', id] as const,
  /** Delete platformFunctionGraphExecution mutation key */ delete: (id: string | number) =>
    ['mutation', 'platformfunctiongraphexecution', 'delete', id] as const,
} as const;
export const platformFunctionDefinitionMutationKeys = {
  /** All platformFunctionDefinition mutation keys */ all: [
    'mutation',
    'platformfunctiondefinition',
  ] as const,
  /** Create platformFunctionDefinition mutation key */ create: () =>
    ['mutation', 'platformfunctiondefinition', 'create'] as const,
  /** Update platformFunctionDefinition mutation key */ update: (id: string | number) =>
    ['mutation', 'platformfunctiondefinition', 'update', id] as const,
  /** Delete platformFunctionDefinition mutation key */ delete: (id: string | number) =>
    ['mutation', 'platformfunctiondefinition', 'delete', id] as const,
} as const;

// ============================================================================
// Custom Mutation Keys
// ============================================================================

export const customMutationKeys = {
  /** Mutation key for platformValidateFunctionGraph */ platformValidateFunctionGraph: (
    identifier?: string
  ) =>
    identifier
      ? (['mutation', 'platformValidateFunctionGraph', identifier] as const)
      : (['mutation', 'platformValidateFunctionGraph'] as const),
  /** Mutation key for initEmptyRepo */ initEmptyRepo: (identifier?: string) =>
    identifier
      ? (['mutation', 'initEmptyRepo', identifier] as const)
      : (['mutation', 'initEmptyRepo'] as const),
  /** Mutation key for platformImportDefinitions */ platformImportDefinitions: (
    identifier?: string
  ) =>
    identifier
      ? (['mutation', 'platformImportDefinitions', identifier] as const)
      : (['mutation', 'platformImportDefinitions'] as const),
  /** Mutation key for setDataAtPath */ setDataAtPath: (identifier?: string) =>
    identifier
      ? (['mutation', 'setDataAtPath', identifier] as const)
      : (['mutation', 'setDataAtPath'] as const),
  /** Mutation key for platformCopyGraph */ platformCopyGraph: (identifier?: string) =>
    identifier
      ? (['mutation', 'platformCopyGraph', identifier] as const)
      : (['mutation', 'platformCopyGraph'] as const),
  /** Mutation key for platformSaveGraph */ platformSaveGraph: (identifier?: string) =>
    identifier
      ? (['mutation', 'platformSaveGraph', identifier] as const)
      : (['mutation', 'platformSaveGraph'] as const),
  /** Mutation key for platformAddEdgeAndSave */ platformAddEdgeAndSave: (identifier?: string) =>
    identifier
      ? (['mutation', 'platformAddEdgeAndSave', identifier] as const)
      : (['mutation', 'platformAddEdgeAndSave'] as const),
  /** Mutation key for platformAddNodeAndSave */ platformAddNodeAndSave: (identifier?: string) =>
    identifier
      ? (['mutation', 'platformAddNodeAndSave', identifier] as const)
      : (['mutation', 'platformAddNodeAndSave'] as const),
  /** Mutation key for platformCreateFunctionGraph */ platformCreateFunctionGraph: (
    identifier?: string
  ) =>
    identifier
      ? (['mutation', 'platformCreateFunctionGraph', identifier] as const)
      : (['mutation', 'platformCreateFunctionGraph'] as const),
  /** Mutation key for platformAddEdge */ platformAddEdge: (identifier?: string) =>
    identifier
      ? (['mutation', 'platformAddEdge', identifier] as const)
      : (['mutation', 'platformAddEdge'] as const),
  /** Mutation key for platformAddNode */ platformAddNode: (identifier?: string) =>
    identifier
      ? (['mutation', 'platformAddNode', identifier] as const)
      : (['mutation', 'platformAddNode'] as const),
  /** Mutation key for platformImportGraphJson */ platformImportGraphJson: (identifier?: string) =>
    identifier
      ? (['mutation', 'platformImportGraphJson', identifier] as const)
      : (['mutation', 'platformImportGraphJson'] as const),
  /** Mutation key for insertNodeAtPath */ insertNodeAtPath: (identifier?: string) =>
    identifier
      ? (['mutation', 'insertNodeAtPath', identifier] as const)
      : (['mutation', 'insertNodeAtPath'] as const),
  /** Mutation key for platformStartExecution */ platformStartExecution: (identifier?: string) =>
    identifier
      ? (['mutation', 'platformStartExecution', identifier] as const)
      : (['mutation', 'platformStartExecution'] as const),
  /** Mutation key for provisionBucket */ provisionBucket: (identifier?: string) =>
    identifier
      ? (['mutation', 'provisionBucket', identifier] as const)
      : (['mutation', 'provisionBucket'] as const),
} as const;
/**

// ============================================================================
// Unified Mutation Key Store
// ============================================================================

 * Unified mutation key store
 * 
 * Use this for tracking in-flight mutations with useIsMutating.
 * 
 * @example
 * ```ts
 * import { useIsMutating } from '@tanstack/react-query';
 * import { mutationKeys } from './generated';
 * 
 * // Check if any user mutations are in progress
 * const isMutatingUser = useIsMutating({ mutationKey: mutationKeys.user.all });
 * 
 * // Check if a specific user is being updated
 * const isUpdating = useIsMutating({ mutationKey: mutationKeys.user.update(userId) });
 * ```
 */
export const mutationKeys = {
  getAllRecord: getAllRecordMutationKeys,
  platformFunctionGraphRef: platformFunctionGraphRefMutationKeys,
  platformFunctionGraphStore: platformFunctionGraphStoreMutationKeys,
  platformFunctionGraphObject: platformFunctionGraphObjectMutationKeys,
  orgFunctionExecutionLog: orgFunctionExecutionLogMutationKeys,
  platformFunctionGraphExecutionOutput: platformFunctionGraphExecutionOutputMutationKeys,
  platformFunctionGraphCommit: platformFunctionGraphCommitMutationKeys,
  platformSecretDefinition: platformSecretDefinitionMutationKeys,
  platformFunctionExecutionLog: platformFunctionExecutionLogMutationKeys,
  platformFunctionGraphExecutionNodeState: platformFunctionGraphExecutionNodeStateMutationKeys,
  platformFunctionGraph: platformFunctionGraphMutationKeys,
  platformComputeLog: platformComputeLogMutationKeys,
  platformUsageDaily: platformUsageDailyMutationKeys,
  orgFunctionInvocation: orgFunctionInvocationMutationKeys,
  platformFunctionInvocation: platformFunctionInvocationMutationKeys,
  platformFunctionGraphExecution: platformFunctionGraphExecutionMutationKeys,
  platformFunctionDefinition: platformFunctionDefinitionMutationKeys,
  custom: customMutationKeys,
} as const;
