import express from 'express';
import { createServer } from 'http';
import { WebSocketServer, WebSocket } from 'ws';
import { Pool } from 'pg';
import { spawn } from 'child_process';
import { readFileSync, writeFileSync, existsSync } from 'fs';
import { resolve } from 'path';

const PORT = parseInt(process.env.PLATFORM_UI_PORT || '3456', 10);
const app = express();
const server = createServer(app);

app.use(express.json());

// ─── Postgres pool ──────────────────────────────────────────────────────────
// Still used for /api/status (aggregate counts), /api/secret-values (DB
// storage), and .env↔DB sync. Data-read routes (functions, secrets, jobs,
// invocations, namespaces) are served by the GraphQL server on port 3002.

const pool = new Pool({
  host: process.env.PGHOST || 'localhost',
  port: parseInt(process.env.PGPORT || '5432', 10),
  user: process.env.PGUSER || 'postgres',
  password: process.env.PGPASSWORD || 'password',
  database: process.env.PGDATABASE || 'constructive',
});

// ─── Helpers ────────────────────────────────────────────────────────────────

function parseRequirements(raw: string): Array<{ name: string; required: boolean }> {
  if (!raw || raw === '{}') return [];
  const inner = raw.slice(1, -1);
  const items: Array<{ name: string; required: boolean }> = [];
  for (const match of inner.matchAll(/"?\(([^,]+),(t|f)\)"?/g)) {
    items.push({ name: match[1], required: match[2] === 't' });
  }
  return items;
}

// ─── REST API — FBP Node Definitions ────────────────────────────────────────

app.get('/api/definitions', async (_req, res) => {
  try {
    const result = await pool.query(`
      SELECT name, task_identifier, service_url, is_invocable,
             scope, description, required_secrets, required_configs,
             payload_schema
      FROM constructive_infra_public.platform_function_definitions
      ORDER BY name
    `);

    const definitions = result.rows.map((r: any) => {
      const secrets = parseRequirements(r.required_secrets);
      const configs = parseRequirements(r.required_configs);
      const schema = r.payload_schema;

      const props = [
        ...secrets.map((s: { name: string; required: boolean }) => ({
          name: s.name,
          type: 'secret',
          required: s.required,
          description: `Secret: ${s.name}`,
        })),
        ...configs.map((c: { name: string; required: boolean }) => ({
          name: c.name,
          type: 'config',
          required: c.required,
          description: `Config: ${c.name}`,
        })),
      ];

      const inputs = [{
        name: 'payload',
        type: 'json',
        description: 'Job payload object',
        ...(schema ? { schema } : {}),
      }];

      return {
        context: r.task_identifier,
        name: r.name,
        category: r.scope || 'default',
        description: r.description,
        inputs,
        outputs: [{ name: 'result', type: 'json', description: 'Handler return value' }],
        props: props.length > 0 ? props : undefined,
      };
    });

    res.json(definitions);
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

// ─── .env helpers (must be declared before Secret Values endpoints) ────────

const PROJECT_ROOT = process.env.PROJECT_ROOT || resolve(process.cwd(), '..');
const ENV_PATH = resolve(PROJECT_ROOT, '.env');

function parseDotEnv(filePath: string): Record<string, string> {
  if (!existsSync(filePath)) return {};
  const vars: Record<string, string> = {};
  for (const line of readFileSync(filePath, 'utf-8').split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eqIdx = trimmed.indexOf('=');
    if (eqIdx === -1) continue;
    const key = trimmed.slice(0, eqIdx).trim();
    let val = trimmed.slice(eqIdx + 1).trim();
    if ((val.startsWith('"') && val.endsWith('"')) ||
        (val.startsWith("'") && val.endsWith("'"))) {
      val = val.slice(1, -1);
    }
    vars[key] = val;
  }
  return vars;
}

function writeDotEnv(filePath: string, vars: Record<string, string>): void {
  const lines: string[] = [
    '# Auto-generated by Platform UI — edits here are safe.',
    '# Values can also be edited from http://localhost:5173 → Secrets tab.',
    '',
  ];
  const groups: Record<string, string[]> = {
    postgres: ['POSTGRES_PASSWORD', 'PGADMIN_DEFAULT_PASSWORD', 'PGHOST', 'PGPORT', 'PGUSER', 'PGPASSWORD', 'PGDATABASE'],
    email_mailgun: ['MAILGUN_API_KEY', 'MAILGUN_KEY', 'MAILGUN_DOMAIN', 'MAILGUN_FROM', 'MAILGUN_REPLY'],
    email_smtp: ['EMAIL_SEND_USE_SMTP', 'SMTP_HOST', 'SMTP_PORT', 'SMTP_FROM'],
    dryrun: ['SEND_EMAIL_DRY_RUN', 'SEND_VERIFICATION_LINK_DRY_RUN'],
    minio: ['MINIO_ROOT_USER', 'MINIO_ROOT_PASSWORD'],
    aws: ['ROUTE53_ACCESS_KEY_ID', 'ROUTE53_HOSTED_ZONE_ID'],
  };
  const groupLabels: Record<string, string> = {
    postgres: '# --- PostgreSQL ---',
    email_mailgun: '# --- Email: Mailgun ---',
    email_smtp: '# --- Email: SMTP / Mailpit ---',
    dryrun: '# --- Function dry-run toggles ---',
    minio: '# --- MinIO ---',
    aws: '# --- AWS ---',
  };

  const written = new Set<string>();
  for (const [group, keys] of Object.entries(groups)) {
    const groupVars = keys.filter((k) => k in vars);
    if (groupVars.length === 0) continue;
    lines.push(groupLabels[group] || `# --- ${group} ---`);
    for (const key of groupVars) {
      lines.push(`${key}=${vars[key]}`);
      written.add(key);
    }
    lines.push('');
  }
  const remaining = Object.entries(vars).filter(([k]) => !written.has(k));
  if (remaining.length > 0) {
    lines.push('# --- Other ---');
    for (const [key, val] of remaining) {
      lines.push(`${key}=${val}`);
    }
    lines.push('');
  }

  writeFileSync(filePath, lines.join('\n'), 'utf-8');
}

// ─── REST API — Secret Values (DB storage) ─────────────────────────────────

async function getDefaultDatabaseId(): Promise<string> {
  const result = await pool.query(
    `SELECT database_id FROM constructive_infra_public.platform_secret_definitions LIMIT 1`
  );
  if (result.rows.length > 0) return result.rows[0].database_id ?? 'default';
  return 'default';
}

app.get('/api/secret-values', async (_req, res) => {
  try {
    const result = await pool.query(`
      SELECT secret_name, configured_value, database_id,
             created_at, updated_at
      FROM constructive_infra_public.platform_secret_values
      ORDER BY secret_name
    `);
    const vars: Record<string, string> = {};
    for (const row of result.rows) {
      if (row.configured_value != null) {
        vars[row.secret_name] = row.configured_value;
      }
    }
    res.json({ vars, rows: result.rows });
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

app.post('/api/secret-values', async (req, res) => {
  try {
    const { vars } = req.body as { vars: Record<string, string> };
    if (!vars || typeof vars !== 'object') {
      res.status(400).json({ error: 'Body must contain { vars: { KEY: "value", ... } }' });
      return;
    }
    const dbId = await getDefaultDatabaseId();
    let upserted = 0;
    for (const [name, value] of Object.entries(vars)) {
      if (value === '') continue;
      await pool.query(
        `INSERT INTO constructive_infra_public.platform_secret_values
           (secret_name, configured_value, database_id)
         VALUES ($1, $2, $3)
         ON CONFLICT (secret_name, database_id)
         DO UPDATE SET configured_value = EXCLUDED.configured_value`,
        [name, value, dbId]
      );
      upserted++;
    }
    res.json({ ok: true, upserted });
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

app.post('/api/secrets/sync-from-db', async (_req, res) => {
  try {
    const result = await pool.query(`
      SELECT secret_name, configured_value
      FROM constructive_infra_public.platform_secret_values
      WHERE configured_value IS NOT NULL AND configured_value != ''
    `);
    const dbVars: Record<string, string> = {};
    for (const row of result.rows) {
      dbVars[row.secret_name] = row.configured_value;
    }
    const existing = parseDotEnv(ENV_PATH);
    const merged = { ...existing, ...dbVars };
    writeDotEnv(ENV_PATH, merged);
    res.json({ ok: true, synced: Object.keys(dbVars).length, total: Object.keys(merged).length });
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

app.post('/api/secrets/sync-to-db', async (_req, res) => {
  try {
    const envVars = parseDotEnv(ENV_PATH);
    const dbId = await getDefaultDatabaseId();
    let upserted = 0;
    for (const [name, value] of Object.entries(envVars)) {
      if (value === '') continue;
      await pool.query(
        `INSERT INTO constructive_infra_public.platform_secret_values
           (secret_name, configured_value, database_id)
         VALUES ($1, $2, $3)
         ON CONFLICT (secret_name, database_id)
         DO UPDATE SET configured_value = EXCLUDED.configured_value`,
        [name, value, dbId]
      );
      upserted++;
    }
    res.json({ ok: true, synced: upserted });
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

// ─── REST API — .env file (read / write) ─────────────────────────────────────

app.get('/api/env', (_req, res) => {
  try {
    const vars = parseDotEnv(ENV_PATH);
    res.json({ path: ENV_PATH, exists: existsSync(ENV_PATH), vars });
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

app.post('/api/env', async (req, res) => {
  try {
    const { vars } = req.body as { vars: Record<string, string> };
    if (!vars || typeof vars !== 'object') {
      res.status(400).json({ error: 'Body must contain { vars: { KEY: "value", ... } }' });
      return;
    }
    const existing = parseDotEnv(ENV_PATH);
    const merged = { ...existing, ...vars };
    for (const [k, v] of Object.entries(merged)) {
      if (v === '' && !(k in existing)) delete merged[k];
    }
    writeDotEnv(ENV_PATH, merged);

    // Also sync non-empty values to DB
    try {
      const dbId = await getDefaultDatabaseId();
      for (const [name, value] of Object.entries(merged)) {
        if (value === '') continue;
        await pool.query(
          `INSERT INTO constructive_infra_public.platform_secret_values
             (secret_name, configured_value, database_id)
           VALUES ($1, $2, $3)
           ON CONFLICT (secret_name, database_id)
           DO UPDATE SET configured_value = EXCLUDED.configured_value`,
          [name, value, dbId]
        );
      }
    } catch {
      // DB sync is best-effort; .env write already succeeded
    }

    res.json({ ok: true, path: ENV_PATH, count: Object.keys(merged).length });
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

// ─── REST API — Status ──────────────────────────────────────────────────────

app.get('/api/status', async (_req, res) => {
  try {
    const pgVersion = await pool.query('SELECT version()');
    const dbName = await pool.query('SELECT current_database()');
    const fnCount = await pool.query(
      `SELECT count(*) as count FROM constructive_infra_public.platform_function_definitions WHERE is_invocable = true`
    );
    const jobCount = await pool.query(
      `SELECT count(*) as count FROM app_jobs.jobs`
    );
    const invocationCount = await pool.query(
      `SELECT count(*) as count FROM constructive_infra_public.platform_function_invocations`
    );

    res.json({
      database: dbName.rows[0].current_database,
      postgres: pgVersion.rows[0].version.split(' ').slice(0, 2).join(' '),
      functions: parseInt(fnCount.rows[0].count, 10),
      jobs: parseInt(jobCount.rows[0].count, 10),
      invocations: parseInt(invocationCount.rows[0].count, 10),
    });
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

// ─── REST API — Run make commands ───────────────────────────────────────────

app.post('/api/run', (req, res) => {
  const { command } = req.body;
  const allowedCommands = [
    'make status',
    'make verify-platform',
    'make up',
    'make down',
    'make up:email-job',
    'make down:email-job',
    'make check-env',
  ];

  if (!allowedCommands.some(c => command.startsWith(c))) {
    res.status(400).json({ error: `Command not allowed. Allowed: ${allowedCommands.join(', ')}` });
    return;
  }

  const proc = spawn('bash', ['-c', command], {
    cwd: process.env.PROJECT_ROOT || process.cwd(),
    env: process.env as Record<string, string>,
  });

  let output = '';
  proc.stdout.on('data', (data: Buffer) => { output += data.toString(); });
  proc.stderr.on('data', (data: Buffer) => { output += data.toString(); });
  proc.on('close', (exitCode: number | null) => {
    res.json({ output, exitCode: exitCode ?? 1 });
  });
});

// ─── REST API — K8s proxy ────────────────────────────────────────────────────

const K8S_API = process.env.KUBERNETES_API_URL || 'http://127.0.0.1:8001';

app.all('/api/k8s/*', async (req, res) => {
  const k8sPath = '/' + (req.params as any)[0];
  const url = `${K8S_API}${k8sPath}${req.url.includes('?') ? req.url.slice(req.url.indexOf('?')) : ''}`;

  try {
    const headers: Record<string, string> = { 'Accept': 'application/json' };
    if (req.headers['content-type']) {
      headers['Content-Type'] = req.headers['content-type'] as string;
    }

    const init: RequestInit = {
      method: req.method,
      headers,
    };
    if (req.method !== 'GET' && req.method !== 'HEAD' && req.body) {
      init.body = JSON.stringify(req.body);
    }

    const k8sRes = await fetch(url, init);
    const body = await k8sRes.text();

    res.status(k8sRes.status);
    for (const [key, value] of k8sRes.headers.entries()) {
      if (key.toLowerCase() !== 'transfer-encoding') {
        res.setHeader(key, value);
      }
    }
    res.send(body);
  } catch (err: any) {
    res.status(502).json({ error: `K8s proxy error: ${err.message}`, target: url });
  }
});

// ─── WebSocket — Shell Terminal ─────────────────────────────────────────────

const wss = new WebSocketServer({ server, path: '/ws/terminal' });

wss.on('connection', (ws: WebSocket) => {
  const shell = spawn('bash', ['-i'], {
    cwd: process.env.PROJECT_ROOT || process.cwd(),
    env: { ...process.env, TERM: 'xterm-256color' } as Record<string, string>,
    stdio: ['pipe', 'pipe', 'pipe'],
  });

  shell.stdout.on('data', (data: Buffer) => {
    if (ws.readyState === WebSocket.OPEN) {
      ws.send(data.toString());
    }
  });

  shell.stderr.on('data', (data: Buffer) => {
    if (ws.readyState === WebSocket.OPEN) {
      ws.send(data.toString());
    }
  });

  ws.on('message', (msg: Buffer | string) => {
    const str = msg.toString();
    if (shell.stdin.writable) {
      shell.stdin.write(str);
    }
  });

  ws.on('close', () => {
    shell.kill();
  });

  shell.on('exit', () => {
    if (ws.readyState === WebSocket.OPEN) {
      ws.close();
    }
  });
});

// ─── Start ──────────────────────────────────────────────────────────────────

server.listen(PORT, () => {
  console.log(`\n  Platform UI server: http://localhost:${PORT}`);
  console.log(`  Terminal WebSocket: ws://localhost:${PORT}/ws/terminal`);
  console.log(`  REST API:          http://localhost:${PORT}/api/{status,env,secret-values,run}`);
  console.log(`  K8s proxy:         http://localhost:${PORT}/api/k8s/* → ${K8S_API}`);
  console.log(`  GraphQL:           http://localhost:3002/graphql (proxied via Vite at /graphql)`);
  console.log(`  Database:          ${process.env.PGDATABASE || 'constructive'}\n`);
});
