/**
 * Multi-target executor and config store for CLI
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { createConfigStore } from 'appstash';

import { createClient as createApiClient } from '../src/api/orm';
import { createClient as createComputeClient } from '../src/compute/orm';
import { createClient as createObjectsClient } from '../src/objects/orm';
const store = createConfigStore('constructive-functions');
export const getStore = () => store;
const targetClients = {
  api: createApiClient,
  compute: createComputeClient,
  objects: createObjectsClient,
};
const defaultEndpoints = {
  api: '',
  compute: '',
  objects: '',
};
export const getTargetNames = () => Object.keys(targetClients);
export const getDefaultEndpoint = (targetName: string) => defaultEndpoints[targetName] || '';
export function getClient(targetName: string, contextName?: string) {
  const createFn = targetClients[targetName];
  if (!createFn) {
    throw new Error(`Unknown target: ${targetName}`);
  }
  const headers: Record<string, string> = {};
  let endpoint = '';
  const ctx = contextName ? store.loadContext(contextName) : store.getCurrentContext();
  if (ctx) {
    const resolved = store.getTargetEndpoint(targetName, ctx.name);
    endpoint = resolved || defaultEndpoints[targetName] || '';
    if (store.hasValidCredentials(ctx.name)) {
      const creds = store.getCredentials(ctx.name);
      if (creds?.token) {
        headers.Authorization = `Bearer ${creds.token}`;
      }
    }
  } else {
    endpoint = defaultEndpoints[targetName] || '';
  }
  return createFn({
    endpoint: endpoint,
    headers: headers,
  });
}
