-- Revert: schemas/constructive_compute_public/tables/platform_function_definitions/constraints/platform_function_definitions_scope_name_key/constraint


ALTER TABLE "constructive_compute_public".platform_function_definitions 
  DROP CONSTRAINT platform_function_definitions_scope_name_key;


