-- Verify: schemas/constructive_compute_fbp_public/procedures/platform_function_graph_insert_node_at_path/procedure


SELECT verify_function('constructive_compute_fbp_public.platform_function_graph_insert_node_at_path');


