/**
 * Query hooks barrel export
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
export * from './usePlatformBucketQuery';
export * from './usePlatformBucketsQuery';
export * from './usePlatformConfigDefinitionQuery';
export * from './usePlatformConfigDefinitionsQuery';
export * from './usePlatformConfigQuery';
export * from './usePlatformConfigsQuery';
export * from './usePlatformFileQuery';
export * from './usePlatformFilesQuery';
export * from './usePlatformNamespaceEventQuery';
export * from './usePlatformNamespaceEventsQuery';
export * from './usePlatformNamespaceQuery';
export * from './usePlatformNamespacesQuery';
export * from './useRoleTypeQuery';
export * from './useRoleTypesQuery';
export * from './useUserQuery';
export * from './useUsersQuery';
