/**
 * Registry of valid config keys — declares which config entries the platform recognizes
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import type { QueryClient,UseQueryOptions, UseQueryResult } from '@tanstack/react-query';
import { useQuery } from '@tanstack/react-query';

import type {
  PlatformConfigDefinitionSelect,
  PlatformConfigDefinitionWithRelations,
} from '../../orm/input-types';
import type { HookStrictSelect,InferSelectResult } from '../../orm/select-types';
import { getClient } from '../client';
import { platformConfigDefinitionKeys } from '../query-keys';
import type { SelectionConfig } from '../selection';
import { buildSelectionArgs } from '../selection';
export type {
  PlatformConfigDefinitionSelect,
  PlatformConfigDefinitionWithRelations,
} from '../../orm/input-types';
/** Query key factory - re-exported from query-keys.ts */
export const platformConfigDefinitionQueryKey = platformConfigDefinitionKeys.detail;
/**
 * Registry of valid config keys — declares which config entries the platform recognizes
 *
 * @example
 * ```tsx
 * const { data, isLoading } = usePlatformConfigDefinitionQuery({
 *   id: 'some-id',
 *   selection: { fields: { id: true, name: true } },
 * });
 * ```
 */
export function usePlatformConfigDefinitionQuery<
  S extends PlatformConfigDefinitionSelect,
  TData = {
    platformConfigDefinition: InferSelectResult<PlatformConfigDefinitionWithRelations, S> | null;
  },
>(
  params: {
    id: string;
    selection: {
      fields: S;
    } & HookStrictSelect<NoInfer<S>, PlatformConfigDefinitionSelect>;
  } & Omit<
    UseQueryOptions<
      {
        platformConfigDefinition: InferSelectResult<
          PlatformConfigDefinitionWithRelations,
          S
        > | null;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function usePlatformConfigDefinitionQuery(
  params: {
    id: string;
    selection: SelectionConfig<PlatformConfigDefinitionSelect>;
  } & Omit<UseQueryOptions<any, Error, any, any>, 'queryKey' | 'queryFn'>
) {
  const args = buildSelectionArgs<PlatformConfigDefinitionSelect>(params.selection);
  const { selection: _selection, ...queryOptions } = params ?? {};
  void _selection;
  return useQuery({
    queryKey: platformConfigDefinitionKeys.detail(params.id),
    queryFn: () =>
      getClient()
        .platformConfigDefinition.findOne({
          id: params.id,
          select: args.select,
        })
        .unwrap(),
    ...queryOptions,
  });
}
/**
 * Registry of valid config keys — declares which config entries the platform recognizes
 *
 * @example
 * ```ts
 * const data = await fetchPlatformConfigDefinitionQuery({
 *   id: 'some-id',
 *   selection: { fields: { id: true } },
 * });
 * ```
 */
export async function fetchPlatformConfigDefinitionQuery<
  S extends PlatformConfigDefinitionSelect,
>(params: {
  id: string;
  selection: {
    fields: S;
  } & HookStrictSelect<NoInfer<S>, PlatformConfigDefinitionSelect>;
}): Promise<{
  platformConfigDefinition: InferSelectResult<PlatformConfigDefinitionWithRelations, S> | null;
}>;
export async function fetchPlatformConfigDefinitionQuery(params: {
  id: string;
  selection: SelectionConfig<PlatformConfigDefinitionSelect>;
}): Promise<any> {
  const args = buildSelectionArgs<PlatformConfigDefinitionSelect>(params.selection);
  return getClient()
    .platformConfigDefinition.findOne({
      id: params.id,
      select: args.select,
    })
    .unwrap();
}
/**
 * Registry of valid config keys — declares which config entries the platform recognizes
 *
 * @example
 * ```ts
 * await prefetchPlatformConfigDefinitionQuery(queryClient, { id: 'some-id', selection: { fields: { id: true } } });
 * ```
 */
export async function prefetchPlatformConfigDefinitionQuery<
  S extends PlatformConfigDefinitionSelect,
>(
  queryClient: QueryClient,
  params: {
    id: string;
    selection: {
      fields: S;
    } & HookStrictSelect<NoInfer<S>, PlatformConfigDefinitionSelect>;
  }
): Promise<void>;
export async function prefetchPlatformConfigDefinitionQuery(
  queryClient: QueryClient,
  params: {
    id: string;
    selection: SelectionConfig<PlatformConfigDefinitionSelect>;
  }
): Promise<void> {
  const args = buildSelectionArgs<PlatformConfigDefinitionSelect>(params.selection);
  await queryClient.prefetchQuery({
    queryKey: platformConfigDefinitionKeys.detail(params.id),
    queryFn: () =>
      getClient()
        .platformConfigDefinition.findOne({
          id: params.id,
          select: args.select,
        })
        .unwrap(),
  });
}
