/**
 * Individual file records within buckets, with immutable identity fields and mutable metadata
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import { useQuery } from '@tanstack/react-query';
import type { UseQueryOptions, UseQueryResult, QueryClient } from '@tanstack/react-query';
import { getClient } from '../client';
import { buildSelectionArgs } from '../selection';
import type { SelectionConfig } from '../selection';
import { platformFileKeys } from '../query-keys';
import type { PlatformFileSelect, PlatformFileWithRelations } from '../../orm/input-types';
import type { InferSelectResult, HookStrictSelect } from '../../orm/select-types';
export type { PlatformFileSelect, PlatformFileWithRelations } from '../../orm/input-types';
/** Query key factory - re-exported from query-keys.ts */
export const platformFileQueryKey = platformFileKeys.detail;
/**
 * Individual file records within buckets, with immutable identity fields and mutable metadata
 *
 * @example
 * ```tsx
 * const { data, isLoading } = usePlatformFileQuery({
 *   id: 'some-id',
 *   selection: { fields: { id: true, name: true } },
 * });
 * ```
 */
export function usePlatformFileQuery<
  S extends PlatformFileSelect,
  TData = {
    platformFile: InferSelectResult<PlatformFileWithRelations, S> | null;
  },
>(
  params: {
    id: string;
    selection: {
      fields: S;
    } & HookStrictSelect<NoInfer<S>, PlatformFileSelect>;
  } & Omit<
    UseQueryOptions<
      {
        platformFile: InferSelectResult<PlatformFileWithRelations, S> | null;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function usePlatformFileQuery(
  params: {
    id: string;
    selection: SelectionConfig<PlatformFileSelect>;
  } & Omit<UseQueryOptions<any, Error, any, any>, 'queryKey' | 'queryFn'>
) {
  const args = buildSelectionArgs<PlatformFileSelect>(params.selection);
  const { selection: _selection, ...queryOptions } = params ?? {};
  void _selection;
  return useQuery({
    queryKey: platformFileKeys.detail(params.id),
    queryFn: () =>
      getClient()
        .platformFile.findOne({
          id: params.id,
          select: args.select,
        })
        .unwrap(),
    ...queryOptions,
  });
}
/**
 * Individual file records within buckets, with immutable identity fields and mutable metadata
 *
 * @example
 * ```ts
 * const data = await fetchPlatformFileQuery({
 *   id: 'some-id',
 *   selection: { fields: { id: true } },
 * });
 * ```
 */
export async function fetchPlatformFileQuery<S extends PlatformFileSelect>(params: {
  id: string;
  selection: {
    fields: S;
  } & HookStrictSelect<NoInfer<S>, PlatformFileSelect>;
}): Promise<{
  platformFile: InferSelectResult<PlatformFileWithRelations, S> | null;
}>;
export async function fetchPlatformFileQuery(params: {
  id: string;
  selection: SelectionConfig<PlatformFileSelect>;
}): Promise<any> {
  const args = buildSelectionArgs<PlatformFileSelect>(params.selection);
  return getClient()
    .platformFile.findOne({
      id: params.id,
      select: args.select,
    })
    .unwrap();
}
/**
 * Individual file records within buckets, with immutable identity fields and mutable metadata
 *
 * @example
 * ```ts
 * await prefetchPlatformFileQuery(queryClient, { id: 'some-id', selection: { fields: { id: true } } });
 * ```
 */
export async function prefetchPlatformFileQuery<S extends PlatformFileSelect>(
  queryClient: QueryClient,
  params: {
    id: string;
    selection: {
      fields: S;
    } & HookStrictSelect<NoInfer<S>, PlatformFileSelect>;
  }
): Promise<void>;
export async function prefetchPlatformFileQuery(
  queryClient: QueryClient,
  params: {
    id: string;
    selection: SelectionConfig<PlatformFileSelect>;
  }
): Promise<void> {
  const args = buildSelectionArgs<PlatformFileSelect>(params.selection);
  await queryClient.prefetchQuery({
    queryKey: platformFileKeys.detail(params.id),
    queryFn: () =>
      getClient()
        .platformFile.findOne({
          id: params.id,
          select: args.select,
        })
        .unwrap(),
  });
}
