/**
 * Logical storage containers that group files with shared access policies and CDN behavior
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import type { QueryClient,UseQueryOptions, UseQueryResult } from '@tanstack/react-query';
import { useQuery } from '@tanstack/react-query';

import type {
  PlatformBucketFilter,
  PlatformBucketOrderBy,
  PlatformBucketSelect,
  PlatformBucketWithRelations,
} from '../../orm/input-types';
import type {
  ConnectionResult,
  HookStrictSelect,
  InferSelectResult,
} from '../../orm/select-types';
import { getClient } from '../client';
import { platformBucketKeys } from '../query-keys';
import type { ListSelectionConfig } from '../selection';
import { buildListSelectionArgs } from '../selection';
export type {
  PlatformBucketFilter,
  PlatformBucketOrderBy,
  PlatformBucketSelect,
  PlatformBucketWithRelations,
} from '../../orm/input-types';
/** Query key factory - re-exported from query-keys.ts */
export const platformBucketsQueryKey = platformBucketKeys.list;
/**
 * Logical storage containers that group files with shared access policies and CDN behavior
 *
 * @example
 * ```tsx
 * const { data, isLoading } = usePlatformBucketsQuery({
 *   selection: {
 *     fields: { id: true, name: true },
 *     where: { name: { equalTo: "example" } },
 *     orderBy: ['CREATED_AT_DESC'],
 *     first: 10,
 *   },
 * });
 * ```
 */
export function usePlatformBucketsQuery<
  S extends PlatformBucketSelect,
  TData = {
    platformBuckets: ConnectionResult<InferSelectResult<PlatformBucketWithRelations, S>>;
  },
>(
  params: {
    selection: {
      fields: S;
    } & Omit<ListSelectionConfig<S, PlatformBucketFilter, PlatformBucketOrderBy>, 'fields'> &
      HookStrictSelect<NoInfer<S>, PlatformBucketSelect>;
  } & Omit<
    UseQueryOptions<
      {
        platformBuckets: ConnectionResult<InferSelectResult<PlatformBucketWithRelations, S>>;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function usePlatformBucketsQuery(
  params: {
    selection: ListSelectionConfig<
      PlatformBucketSelect,
      PlatformBucketFilter,
      PlatformBucketOrderBy
    >;
  } & Omit<UseQueryOptions<any, Error, any, any>, 'queryKey' | 'queryFn'>
) {
  const args = buildListSelectionArgs<
    PlatformBucketSelect,
    PlatformBucketFilter,
    PlatformBucketOrderBy
  >(params.selection);
  const { selection: _selection, ...queryOptions } = params ?? {};
  void _selection;
  return useQuery({
    queryKey: platformBucketKeys.list(args),
    queryFn: () => getClient().platformBucket.findMany(args).unwrap(),
    ...queryOptions,
  });
}
/**
 * Logical storage containers that group files with shared access policies and CDN behavior
 *
 * @example
 * ```ts
 * const data = await fetchPlatformBucketsQuery({
 *   selection: {
 *     fields: { id: true },
 *     first: 10,
 *   },
 * });
 * ```
 */
export async function fetchPlatformBucketsQuery<S extends PlatformBucketSelect>(params: {
  selection: {
    fields: S;
  } & Omit<ListSelectionConfig<S, PlatformBucketFilter, PlatformBucketOrderBy>, 'fields'> &
    HookStrictSelect<NoInfer<S>, PlatformBucketSelect>;
}): Promise<{
  platformBuckets: ConnectionResult<InferSelectResult<PlatformBucketWithRelations, S>>;
}>;
export async function fetchPlatformBucketsQuery(params: {
  selection: ListSelectionConfig<PlatformBucketSelect, PlatformBucketFilter, PlatformBucketOrderBy>;
}) {
  const args = buildListSelectionArgs<
    PlatformBucketSelect,
    PlatformBucketFilter,
    PlatformBucketOrderBy
  >(params.selection);
  return getClient().platformBucket.findMany(args).unwrap();
}
/**
 * Logical storage containers that group files with shared access policies and CDN behavior
 *
 * @example
 * ```ts
 * await prefetchPlatformBucketsQuery(queryClient, { selection: { fields: { id: true }, first: 10 } });
 * ```
 */
export async function prefetchPlatformBucketsQuery<S extends PlatformBucketSelect>(
  queryClient: QueryClient,
  params: {
    selection: {
      fields: S;
    } & Omit<ListSelectionConfig<S, PlatformBucketFilter, PlatformBucketOrderBy>, 'fields'> &
      HookStrictSelect<NoInfer<S>, PlatformBucketSelect>;
  }
): Promise<void>;
export async function prefetchPlatformBucketsQuery(
  queryClient: QueryClient,
  params: {
    selection: ListSelectionConfig<
      PlatformBucketSelect,
      PlatformBucketFilter,
      PlatformBucketOrderBy
    >;
  }
): Promise<void> {
  const args = buildListSelectionArgs<
    PlatformBucketSelect,
    PlatformBucketFilter,
    PlatformBucketOrderBy
  >(params.selection);
  await queryClient.prefetchQuery({
    queryKey: platformBucketKeys.list(args),
    queryFn: () => getClient().platformBucket.findMany(args).unwrap(),
  });
}
