/**
 * Individual file records within buckets, with immutable identity fields and mutable metadata
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import type { QueryClient,UseQueryOptions, UseQueryResult } from '@tanstack/react-query';
import { useQuery } from '@tanstack/react-query';

import type {
  PlatformFileFilter,
  PlatformFileOrderBy,
  PlatformFileSelect,
  PlatformFileWithRelations,
} from '../../orm/input-types';
import type {
  ConnectionResult,
  HookStrictSelect,
  InferSelectResult,
} from '../../orm/select-types';
import { getClient } from '../client';
import { platformFileKeys } from '../query-keys';
import type { ListSelectionConfig } from '../selection';
import { buildListSelectionArgs } from '../selection';
export type {
  PlatformFileFilter,
  PlatformFileOrderBy,
  PlatformFileSelect,
  PlatformFileWithRelations,
} from '../../orm/input-types';
/** Query key factory - re-exported from query-keys.ts */
export const platformFilesQueryKey = platformFileKeys.list;
/**
 * Individual file records within buckets, with immutable identity fields and mutable metadata
 *
 * @example
 * ```tsx
 * const { data, isLoading } = usePlatformFilesQuery({
 *   selection: {
 *     fields: { id: true, name: true },
 *     where: { name: { equalTo: "example" } },
 *     orderBy: ['CREATED_AT_DESC'],
 *     first: 10,
 *   },
 * });
 * ```
 */
export function usePlatformFilesQuery<
  S extends PlatformFileSelect,
  TData = {
    platformFiles: ConnectionResult<InferSelectResult<PlatformFileWithRelations, S>>;
  },
>(
  params: {
    selection: {
      fields: S;
    } & Omit<ListSelectionConfig<S, PlatformFileFilter, PlatformFileOrderBy>, 'fields'> &
      HookStrictSelect<NoInfer<S>, PlatformFileSelect>;
  } & Omit<
    UseQueryOptions<
      {
        platformFiles: ConnectionResult<InferSelectResult<PlatformFileWithRelations, S>>;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function usePlatformFilesQuery(
  params: {
    selection: ListSelectionConfig<PlatformFileSelect, PlatformFileFilter, PlatformFileOrderBy>;
  } & Omit<UseQueryOptions<any, Error, any, any>, 'queryKey' | 'queryFn'>
) {
  const args = buildListSelectionArgs<PlatformFileSelect, PlatformFileFilter, PlatformFileOrderBy>(
    params.selection
  );
  const { selection: _selection, ...queryOptions } = params ?? {};
  void _selection;
  return useQuery({
    queryKey: platformFileKeys.list(args),
    queryFn: () => getClient().platformFile.findMany(args).unwrap(),
    ...queryOptions,
  });
}
/**
 * Individual file records within buckets, with immutable identity fields and mutable metadata
 *
 * @example
 * ```ts
 * const data = await fetchPlatformFilesQuery({
 *   selection: {
 *     fields: { id: true },
 *     first: 10,
 *   },
 * });
 * ```
 */
export async function fetchPlatformFilesQuery<S extends PlatformFileSelect>(params: {
  selection: {
    fields: S;
  } & Omit<ListSelectionConfig<S, PlatformFileFilter, PlatformFileOrderBy>, 'fields'> &
    HookStrictSelect<NoInfer<S>, PlatformFileSelect>;
}): Promise<{
  platformFiles: ConnectionResult<InferSelectResult<PlatformFileWithRelations, S>>;
}>;
export async function fetchPlatformFilesQuery(params: {
  selection: ListSelectionConfig<PlatformFileSelect, PlatformFileFilter, PlatformFileOrderBy>;
}) {
  const args = buildListSelectionArgs<PlatformFileSelect, PlatformFileFilter, PlatformFileOrderBy>(
    params.selection
  );
  return getClient().platformFile.findMany(args).unwrap();
}
/**
 * Individual file records within buckets, with immutable identity fields and mutable metadata
 *
 * @example
 * ```ts
 * await prefetchPlatformFilesQuery(queryClient, { selection: { fields: { id: true }, first: 10 } });
 * ```
 */
export async function prefetchPlatformFilesQuery<S extends PlatformFileSelect>(
  queryClient: QueryClient,
  params: {
    selection: {
      fields: S;
    } & Omit<ListSelectionConfig<S, PlatformFileFilter, PlatformFileOrderBy>, 'fields'> &
      HookStrictSelect<NoInfer<S>, PlatformFileSelect>;
  }
): Promise<void>;
export async function prefetchPlatformFilesQuery(
  queryClient: QueryClient,
  params: {
    selection: ListSelectionConfig<PlatformFileSelect, PlatformFileFilter, PlatformFileOrderBy>;
  }
): Promise<void> {
  const args = buildListSelectionArgs<PlatformFileSelect, PlatformFileFilter, PlatformFileOrderBy>(
    params.selection
  );
  await queryClient.prefetchQuery({
    queryKey: platformFileKeys.list(args),
    queryFn: () => getClient().platformFile.findMany(args).unwrap(),
  });
}
