-- Revert: schemas/constructive_compute_public/tables/org_function_invocations/indexes/org_function_invocations_graph_execution_id_created_at_idx


DROP INDEX "constructive_compute_public".org_function_invocations_graph_execution_id_created_at_idx;


