-- Revert: schemas/constructive_compute_public/tables/platform_function_graph_execution_node_states/columns/error_code/alterations/alt0000002712


COMMENT ON COLUMN "constructive_compute_public".platform_function_graph_execution_node_states.error_code IS NULL;
