-- Revert: schemas/constructive_compute_public/tables/platform_function_graph_execution_node_states/alterations/alt0000002697


COMMENT ON TABLE "constructive_compute_public".platform_function_graph_execution_node_states IS NULL;
