apiVersion: v1
kind: Service
metadata:
  name: functions-service
  namespace: constructive-functions
  labels:
    app: functions-runtime
spec:
  type: ClusterIP
  selector:
    app: functions-runtime
  ports:
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP
