/**
 * GraphQL schema types for custom operations
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import type {
  PlatformBucket,
  PlatformConfig,
  PlatformConfigDefinition,
  PlatformFile,
  PlatformNamespace,
  PlatformNamespaceEvent,
  RoleType,
  User,
  BigFloatFilter,
  BigIntFilter,
  BitStringFilter,
  BooleanFilter,
  DateFilter,
  DatetimeFilter,
  FloatFilter,
  FullTextFilter,
  IntFilter,
  IntListFilter,
  InternetAddressFilter,
  JSONFilter,
  StringFilter,
  StringListFilter,
  UUIDFilter,
  UUIDListFilter,
  VectorFilter,
} from './types';
export type ConstructiveInternalTypeImage = unknown;
export type ConstructiveInternalTypeUpload = unknown;
/** Methods to use when ordering `RoleType`. */
export type RoleTypeOrderBy =
  | 'NATURAL'
  | 'PRIMARY_KEY_ASC'
  | 'PRIMARY_KEY_DESC'
  | 'ID_ASC'
  | 'ID_DESC'
  | 'NAME_ASC'
  | 'NAME_DESC';
/** Methods to use when ordering `PlatformConfigDefinition`. */
export type PlatformConfigDefinitionOrderBy =
  | 'NATURAL'
  | 'PRIMARY_KEY_ASC'
  | 'PRIMARY_KEY_DESC'
  | 'ANNOTATIONS_ASC'
  | 'ANNOTATIONS_DESC'
  | 'CREATED_AT_ASC'
  | 'CREATED_AT_DESC'
  | 'DEFAULT_VALUE_ASC'
  | 'DEFAULT_VALUE_DESC'
  | 'DESCRIPTION_ASC'
  | 'DESCRIPTION_DESC'
  | 'ID_ASC'
  | 'ID_DESC'
  | 'IS_BUILT_IN_ASC'
  | 'IS_BUILT_IN_DESC'
  | 'LABELS_ASC'
  | 'LABELS_DESC'
  | 'NAME_ASC'
  | 'NAME_DESC'
  | 'UPDATED_AT_ASC'
  | 'UPDATED_AT_DESC';
/** Methods to use when ordering `PlatformConfig`. */
export type PlatformConfigOrderBy =
  | 'NATURAL'
  | 'PRIMARY_KEY_ASC'
  | 'PRIMARY_KEY_DESC'
  | 'ANNOTATIONS_ASC'
  | 'ANNOTATIONS_DESC'
  | 'CREATED_AT_ASC'
  | 'CREATED_AT_DESC'
  | 'DESCRIPTION_ASC'
  | 'DESCRIPTION_DESC'
  | 'EXPIRES_AT_ASC'
  | 'EXPIRES_AT_DESC'
  | 'ID_ASC'
  | 'ID_DESC'
  | 'LABELS_ASC'
  | 'LABELS_DESC'
  | 'NAME_ASC'
  | 'NAME_DESC'
  | 'NAMESPACE_ID_ASC'
  | 'NAMESPACE_ID_DESC'
  | 'UPDATED_AT_ASC'
  | 'UPDATED_AT_DESC'
  | 'VALUE_ASC'
  | 'VALUE_DESC';
/** Methods to use when ordering `PlatformNamespace`. */
export type PlatformNamespaceOrderBy =
  | 'NATURAL'
  | 'PRIMARY_KEY_ASC'
  | 'PRIMARY_KEY_DESC'
  | 'ANNOTATIONS_ASC'
  | 'ANNOTATIONS_DESC'
  | 'CREATED_AT_ASC'
  | 'CREATED_AT_DESC'
  | 'DATABASE_ID_ASC'
  | 'DATABASE_ID_DESC'
  | 'DESCRIPTION_ASC'
  | 'DESCRIPTION_DESC'
  | 'ID_ASC'
  | 'ID_DESC'
  | 'IS_ACTIVE_ASC'
  | 'IS_ACTIVE_DESC'
  | 'LABELS_ASC'
  | 'LABELS_DESC'
  | 'NAME_ASC'
  | 'NAME_DESC'
  | 'NAMESPACE_NAME_ASC'
  | 'NAMESPACE_NAME_DESC'
  | 'UPDATED_AT_ASC'
  | 'UPDATED_AT_DESC';
export type FileStatus = 'REQUESTED' | 'UPLOADED' | 'PROCESSED';
/** Methods to use when ordering `PlatformFile`. */
export type PlatformFileOrderBy =
  | 'NATURAL'
  | 'PRIMARY_KEY_ASC'
  | 'PRIMARY_KEY_DESC'
  | 'ACTOR_ID_ASC'
  | 'ACTOR_ID_DESC'
  | 'BUCKET_ID_ASC'
  | 'BUCKET_ID_DESC'
  | 'CONTENT_HASH_ASC'
  | 'CONTENT_HASH_DESC'
  | 'CREATED_AT_ASC'
  | 'CREATED_AT_DESC'
  | 'DATABASE_ID_ASC'
  | 'DATABASE_ID_DESC'
  | 'DESCRIPTION_ASC'
  | 'DESCRIPTION_DESC'
  | 'FILENAME_ASC'
  | 'FILENAME_DESC'
  | 'ID_ASC'
  | 'ID_DESC'
  | 'IS_PUBLIC_ASC'
  | 'IS_PUBLIC_DESC'
  | 'KEY_ASC'
  | 'KEY_DESC'
  | 'MIME_TYPE_ASC'
  | 'MIME_TYPE_DESC'
  | 'SIZE_ASC'
  | 'SIZE_DESC'
  | 'TAGS_ASC'
  | 'TAGS_DESC'
  | 'UPDATED_AT_ASC'
  | 'UPDATED_AT_DESC'
  | 'UPLOAD_ASC'
  | 'UPLOAD_DESC'
  | 'STATUS_ASC'
  | 'STATUS_DESC';
/** Methods to use when ordering `PlatformBucket`. */
export type PlatformBucketOrderBy =
  | 'NATURAL'
  | 'PRIMARY_KEY_ASC'
  | 'PRIMARY_KEY_DESC'
  | 'ACTOR_ID_ASC'
  | 'ACTOR_ID_DESC'
  | 'ALLOW_CUSTOM_KEYS_ASC'
  | 'ALLOW_CUSTOM_KEYS_DESC'
  | 'ALLOWED_MIME_TYPES_ASC'
  | 'ALLOWED_MIME_TYPES_DESC'
  | 'ALLOWED_ORIGINS_ASC'
  | 'ALLOWED_ORIGINS_DESC'
  | 'CREATED_AT_ASC'
  | 'CREATED_AT_DESC'
  | 'DATABASE_ID_ASC'
  | 'DATABASE_ID_DESC'
  | 'DESCRIPTION_ASC'
  | 'DESCRIPTION_DESC'
  | 'ID_ASC'
  | 'ID_DESC'
  | 'IS_PUBLIC_ASC'
  | 'IS_PUBLIC_DESC'
  | 'KEY_ASC'
  | 'KEY_DESC'
  | 'MAX_FILE_SIZE_ASC'
  | 'MAX_FILE_SIZE_DESC'
  | 'TYPE_ASC'
  | 'TYPE_DESC'
  | 'UPDATED_AT_ASC'
  | 'UPDATED_AT_DESC';
/** Methods to use when ordering `User`. */
export type UserOrderBy =
  | 'NATURAL'
  | 'PRIMARY_KEY_ASC'
  | 'PRIMARY_KEY_DESC'
  | 'CREATED_AT_ASC'
  | 'CREATED_AT_DESC'
  | 'DISPLAY_NAME_ASC'
  | 'DISPLAY_NAME_DESC'
  | 'ID_ASC'
  | 'ID_DESC'
  | 'PROFILE_PICTURE_ASC'
  | 'PROFILE_PICTURE_DESC'
  | 'SEARCH_TSV_ASC'
  | 'SEARCH_TSV_DESC'
  | 'TYPE_ASC'
  | 'TYPE_DESC'
  | 'UPDATED_AT_ASC'
  | 'UPDATED_AT_DESC'
  | 'USERNAME_ASC'
  | 'USERNAME_DESC'
  | 'SEARCH_TSV_RANK_ASC'
  | 'SEARCH_TSV_RANK_DESC'
  | 'DISPLAY_NAME_TRGM_SIMILARITY_ASC'
  | 'DISPLAY_NAME_TRGM_SIMILARITY_DESC'
  | 'SEARCH_SCORE_ASC'
  | 'SEARCH_SCORE_DESC';
/** Methods to use when ordering `PlatformNamespaceEvent`. */
export type PlatformNamespaceEventOrderBy =
  | 'NATURAL'
  | 'PRIMARY_KEY_ASC'
  | 'PRIMARY_KEY_DESC'
  | 'CREATED_AT_ASC'
  | 'CREATED_AT_DESC'
  | 'ACTOR_ID_ASC'
  | 'ACTOR_ID_DESC'
  | 'CPU_MILLICORES_ASC'
  | 'CPU_MILLICORES_DESC'
  | 'DATABASE_ID_ASC'
  | 'DATABASE_ID_DESC'
  | 'EVENT_TYPE_ASC'
  | 'EVENT_TYPE_DESC'
  | 'ID_ASC'
  | 'ID_DESC'
  | 'MEMORY_BYTES_ASC'
  | 'MEMORY_BYTES_DESC'
  | 'MESSAGE_ASC'
  | 'MESSAGE_DESC'
  | 'METADATA_ASC'
  | 'METADATA_DESC'
  | 'METRICS_ASC'
  | 'METRICS_DESC'
  | 'NAMESPACE_ID_ASC'
  | 'NAMESPACE_ID_DESC'
  | 'NETWORK_EGRESS_BYTES_ASC'
  | 'NETWORK_EGRESS_BYTES_DESC'
  | 'NETWORK_INGRESS_BYTES_ASC'
  | 'NETWORK_INGRESS_BYTES_DESC'
  | 'POD_COUNT_ASC'
  | 'POD_COUNT_DESC'
  | 'STORAGE_BYTES_ASC'
  | 'STORAGE_BYTES_DESC';
/** A filter to be used against `RoleType` object types. All fields are combined with a logical ‘and.’ */
export interface RoleTypeFilter {
  /** Filter by the object’s `id` field. */
  id?: IntFilter;
  /** Filter by the object’s `name` field. */
  name?: StringFilter;
  /** Checks for all expressions in this list. */
  and?: RoleTypeFilter[];
  /** Checks for any expressions in this list. */
  or?: RoleTypeFilter[];
  /** Negates the expression. */
  not?: RoleTypeFilter;
}
/** A filter to be used against `PlatformConfigDefinition` object types. All fields are combined with a logical ‘and.’ */
export interface PlatformConfigDefinitionFilter {
  /** Filter by the object’s `annotations` field. */
  annotations?: JSONFilter;
  /** Filter by the object’s `createdAt` field. */
  createdAt?: DatetimeFilter;
  /** Filter by the object’s `defaultValue` field. */
  defaultValue?: StringFilter;
  /** Filter by the object’s `description` field. */
  description?: StringFilter;
  /** Filter by the object’s `id` field. */
  id?: UUIDFilter;
  /** Filter by the object’s `isBuiltIn` field. */
  isBuiltIn?: BooleanFilter;
  /** Filter by the object’s `labels` field. */
  labels?: JSONFilter;
  /** Filter by the object’s `name` field. */
  name?: StringFilter;
  /** Filter by the object’s `updatedAt` field. */
  updatedAt?: DatetimeFilter;
  /** Checks for all expressions in this list. */
  and?: PlatformConfigDefinitionFilter[];
  /** Checks for any expressions in this list. */
  or?: PlatformConfigDefinitionFilter[];
  /** Negates the expression. */
  not?: PlatformConfigDefinitionFilter;
}
/** A filter to be used against `PlatformConfig` object types. All fields are combined with a logical ‘and.’ */
export interface PlatformConfigFilter {
  /** Filter by the object’s `annotations` field. */
  annotations?: JSONFilter;
  /** Filter by the object’s `createdAt` field. */
  createdAt?: DatetimeFilter;
  /** Filter by the object’s `description` field. */
  description?: StringFilter;
  /** Filter by the object’s `expiresAt` field. */
  expiresAt?: DatetimeFilter;
  /** Filter by the object’s `id` field. */
  id?: UUIDFilter;
  /** Filter by the object’s `labels` field. */
  labels?: JSONFilter;
  /** Filter by the object’s `name` field. */
  name?: StringFilter;
  /** Filter by the object’s `namespaceId` field. */
  namespaceId?: UUIDFilter;
  /** Filter by the object’s `updatedAt` field. */
  updatedAt?: DatetimeFilter;
  /** Filter by the object’s `value` field. */
  value?: StringFilter;
  /** Checks for all expressions in this list. */
  and?: PlatformConfigFilter[];
  /** Checks for any expressions in this list. */
  or?: PlatformConfigFilter[];
  /** Negates the expression. */
  not?: PlatformConfigFilter;
  /** Filter by the object’s `namespace` relation. */
  namespace?: PlatformNamespaceFilter;
}
/** A filter to be used against `PlatformNamespace` object types. All fields are combined with a logical ‘and.’ */
export interface PlatformNamespaceFilter {
  /** Filter by the object’s `annotations` field. */
  annotations?: JSONFilter;
  /** Filter by the object’s `createdAt` field. */
  createdAt?: DatetimeFilter;
  /** Filter by the object’s `databaseId` field. */
  databaseId?: UUIDFilter;
  /** Filter by the object’s `description` field. */
  description?: StringFilter;
  /** Filter by the object’s `id` field. */
  id?: UUIDFilter;
  /** Filter by the object’s `isActive` field. */
  isActive?: BooleanFilter;
  /** Filter by the object’s `labels` field. */
  labels?: JSONFilter;
  /** Filter by the object’s `name` field. */
  name?: StringFilter;
  /** Filter by the object’s `namespaceName` field. */
  namespaceName?: StringFilter;
  /** Filter by the object’s `updatedAt` field. */
  updatedAt?: DatetimeFilter;
  /** Checks for all expressions in this list. */
  and?: PlatformNamespaceFilter[];
  /** Checks for any expressions in this list. */
  or?: PlatformNamespaceFilter[];
  /** Negates the expression. */
  not?: PlatformNamespaceFilter;
  /** Filter by the object’s `platformConfigsByNamespaceId` relation. */
  platformConfigsByNamespaceId?: PlatformNamespaceToManyPlatformConfigFilter;
  /** `platformConfigsByNamespaceId` exist. */
  platformConfigsByNamespaceIdExist?: boolean;
}
/** A filter to be used against many `PlatformConfig` object types. All fields are combined with a logical ‘and.’ */
export interface PlatformNamespaceToManyPlatformConfigFilter {
  /** Filters to entities where at least one related entity matches. */
  some?: PlatformConfigFilter;
  /** Filters to entities where every related entity matches. */
  every?: PlatformConfigFilter;
  /** Filters to entities where no related entity matches. */
  none?: PlatformConfigFilter;
}
/** A filter to be used against `PlatformFile` object types. All fields are combined with a logical ‘and.’ */
export interface PlatformFileFilter {
  /** Filter by the object’s `actorId` field. */
  actorId?: UUIDFilter;
  /** Filter by the object’s `bucketId` field. */
  bucketId?: UUIDFilter;
  /** Filter by the object’s `contentHash` field. */
  contentHash?: StringFilter;
  /** Filter by the object’s `createdAt` field. */
  createdAt?: DatetimeFilter;
  /** Filter by the object’s `databaseId` field. */
  databaseId?: UUIDFilter;
  /** Filter by the object’s `description` field. */
  description?: StringFilter;
  /** Filter by the object’s `filename` field. */
  filename?: StringFilter;
  /** Filter by the object’s `id` field. */
  id?: UUIDFilter;
  /** Filter by the object’s `isPublic` field. */
  isPublic?: BooleanFilter;
  /** Filter by the object’s `key` field. */
  key?: StringFilter;
  /** Filter by the object’s `mimeType` field. */
  mimeType?: StringFilter;
  /** Filter by the object’s `size` field. */
  size?: BigIntFilter;
  /** Filter by the object’s `tags` field. */
  tags?: StringListFilter;
  /** Filter by the object’s `updatedAt` field. */
  updatedAt?: DatetimeFilter;
  /** Filter by the object’s `upload` field. */
  upload?: ConstructiveInternalTypeUploadFilter;
  /** Filter by the object’s `status` field. */
  status?: FileStatusFilter;
  /** Checks for all expressions in this list. */
  and?: PlatformFileFilter[];
  /** Checks for any expressions in this list. */
  or?: PlatformFileFilter[];
  /** Negates the expression. */
  not?: PlatformFileFilter;
  /** Filter by the object’s `bucket` relation. */
  bucket?: PlatformBucketFilter;
}
/** A filter to be used against ConstructiveInternalTypeUpload fields. All fields are combined with a logical ‘and.’ */
export interface ConstructiveInternalTypeUploadFilter {
  /** Is null (if `true` is specified) or is not null (if `false` is specified). */
  isNull?: boolean;
  /** Equal to the specified value. */
  equalTo?: ConstructiveInternalTypeUpload;
  /** Not equal to the specified value. */
  notEqualTo?: ConstructiveInternalTypeUpload;
  /** Not equal to the specified value, treating null like an ordinary value. */
  distinctFrom?: ConstructiveInternalTypeUpload;
  /** Equal to the specified value, treating null like an ordinary value. */
  notDistinctFrom?: ConstructiveInternalTypeUpload;
  /** Included in the specified list. */
  in?: ConstructiveInternalTypeUpload[];
  /** Not included in the specified list. */
  notIn?: ConstructiveInternalTypeUpload[];
  /** Less than the specified value. */
  lessThan?: ConstructiveInternalTypeUpload;
  /** Less than or equal to the specified value. */
  lessThanOrEqualTo?: ConstructiveInternalTypeUpload;
  /** Greater than the specified value. */
  greaterThan?: ConstructiveInternalTypeUpload;
  /** Greater than or equal to the specified value. */
  greaterThanOrEqualTo?: ConstructiveInternalTypeUpload;
  /** Contains the specified JSON. */
  contains?: ConstructiveInternalTypeUpload;
  /** Contains the specified key. */
  containsKey?: string;
  /** Contains all of the specified keys. */
  containsAllKeys?: string[];
  /** Contains any of the specified keys. */
  containsAnyKeys?: string[];
  /** Contained by the specified JSON. */
  containedBy?: ConstructiveInternalTypeUpload;
}
/** A filter to be used against FileStatus fields. All fields are combined with a logical ‘and.’ */
export interface FileStatusFilter {
  /** Is null (if `true` is specified) or is not null (if `false` is specified). */
  isNull?: boolean;
  /** Equal to the specified value. */
  equalTo?: FileStatus;
  /** Not equal to the specified value. */
  notEqualTo?: FileStatus;
  /** Not equal to the specified value, treating null like an ordinary value. */
  distinctFrom?: FileStatus;
  /** Equal to the specified value, treating null like an ordinary value. */
  notDistinctFrom?: FileStatus;
  /** Included in the specified list. */
  in?: FileStatus[];
  /** Not included in the specified list. */
  notIn?: FileStatus[];
  /** Less than the specified value. */
  lessThan?: FileStatus;
  /** Less than or equal to the specified value. */
  lessThanOrEqualTo?: FileStatus;
  /** Greater than the specified value. */
  greaterThan?: FileStatus;
  /** Greater than or equal to the specified value. */
  greaterThanOrEqualTo?: FileStatus;
}
/** A filter to be used against `PlatformBucket` object types. All fields are combined with a logical ‘and.’ */
export interface PlatformBucketFilter {
  /** Filter by the object’s `actorId` field. */
  actorId?: UUIDFilter;
  /** Filter by the object’s `allowCustomKeys` field. */
  allowCustomKeys?: BooleanFilter;
  /** Filter by the object’s `allowedMimeTypes` field. */
  allowedMimeTypes?: StringListFilter;
  /** Filter by the object’s `allowedOrigins` field. */
  allowedOrigins?: StringListFilter;
  /** Filter by the object’s `createdAt` field. */
  createdAt?: DatetimeFilter;
  /** Filter by the object’s `databaseId` field. */
  databaseId?: UUIDFilter;
  /** Filter by the object’s `description` field. */
  description?: StringFilter;
  /** Filter by the object’s `id` field. */
  id?: UUIDFilter;
  /** Filter by the object’s `isPublic` field. */
  isPublic?: BooleanFilter;
  /** Filter by the object’s `key` field. */
  key?: StringFilter;
  /** Filter by the object’s `maxFileSize` field. */
  maxFileSize?: BigIntFilter;
  /** Filter by the object’s `type` field. */
  type?: StringFilter;
  /** Filter by the object’s `updatedAt` field. */
  updatedAt?: DatetimeFilter;
  /** Checks for all expressions in this list. */
  and?: PlatformBucketFilter[];
  /** Checks for any expressions in this list. */
  or?: PlatformBucketFilter[];
  /** Negates the expression. */
  not?: PlatformBucketFilter;
  /** Filter by the object’s `platformFilesByBucketId` relation. */
  platformFilesByBucketId?: PlatformBucketToManyPlatformFileFilter;
  /** `platformFilesByBucketId` exist. */
  platformFilesByBucketIdExist?: boolean;
}
/** A filter to be used against many `PlatformFile` object types. All fields are combined with a logical ‘and.’ */
export interface PlatformBucketToManyPlatformFileFilter {
  /** Filters to entities where at least one related entity matches. */
  some?: PlatformFileFilter;
  /** Filters to entities where every related entity matches. */
  every?: PlatformFileFilter;
  /** Filters to entities where no related entity matches. */
  none?: PlatformFileFilter;
}
/** A filter to be used against `User` object types. All fields are combined with a logical ‘and.’ */
export interface UserFilter {
  /** Filter by the object’s `createdAt` field. */
  createdAt?: DatetimeFilter;
  /** Filter by the object’s `displayName` field. */
  displayName?: StringTrgmFilter;
  /** Filter by the object’s `id` field. */
  id?: UUIDFilter;
  /** Filter by the object’s `profilePicture` field. */
  profilePicture?: ConstructiveInternalTypeImageFilter;
  /** Filter by the object’s `searchTsv` field. */
  searchTsv?: FullTextFilter;
  /** Filter by the object’s `type` field. */
  type?: IntFilter;
  /** Filter by the object’s `updatedAt` field. */
  updatedAt?: DatetimeFilter;
  /** Filter by the object’s `username` field. */
  username?: StringTrgmFilter;
  /** Checks for all expressions in this list. */
  and?: UserFilter[];
  /** Checks for any expressions in this list. */
  or?: UserFilter[];
  /** Negates the expression. */
  not?: UserFilter;
  /** Filter by the object’s `roleType` relation. */
  roleType?: RoleTypeFilter;
  /** TSV search on the `search_tsv` column. */
  tsvSearchTsv?: string;
  /** TRGM search on the `display_name` column. */
  trgmDisplayName?: TrgmSearchInput;
  /**
   * Composite unified search. Provide a search string and it will be dispatched to
   * all text-compatible search algorithms (tsvector, BM25, pg_trgm)
   * simultaneously. Rows matching ANY algorithm are returned. All matching score
   * fields are populated.
   */
  unifiedSearch?: string;
}
/** A filter to be used against String fields with pg_trgm support. All fields are combined with a logical ‘and.’ */
export interface StringTrgmFilter {
  /** Is null (if `true` is specified) or is not null (if `false` is specified). */
  isNull?: boolean;
  /** Equal to the specified value. */
  equalTo?: string;
  /** Not equal to the specified value. */
  notEqualTo?: string;
  /** Not equal to the specified value, treating null like an ordinary value. */
  distinctFrom?: string;
  /** Equal to the specified value, treating null like an ordinary value. */
  notDistinctFrom?: string;
  /** Included in the specified list. */
  in?: string[];
  /** Not included in the specified list. */
  notIn?: string[];
  /** Less than the specified value. */
  lessThan?: string;
  /** Less than or equal to the specified value. */
  lessThanOrEqualTo?: string;
  /** Greater than the specified value. */
  greaterThan?: string;
  /** Greater than or equal to the specified value. */
  greaterThanOrEqualTo?: string;
  /** Contains the specified string (case-sensitive). */
  includes?: string;
  /** Does not contain the specified string (case-sensitive). */
  notIncludes?: string;
  /** Contains the specified string (case-insensitive). */
  includesInsensitive?: string;
  /** Does not contain the specified string (case-insensitive). */
  notIncludesInsensitive?: string;
  /** Starts with the specified string (case-sensitive). */
  startsWith?: string;
  /** Does not start with the specified string (case-sensitive). */
  notStartsWith?: string;
  /** Starts with the specified string (case-insensitive). */
  startsWithInsensitive?: string;
  /** Does not start with the specified string (case-insensitive). */
  notStartsWithInsensitive?: string;
  /** Ends with the specified string (case-sensitive). */
  endsWith?: string;
  /** Does not end with the specified string (case-sensitive). */
  notEndsWith?: string;
  /** Ends with the specified string (case-insensitive). */
  endsWithInsensitive?: string;
  /** Does not end with the specified string (case-insensitive). */
  notEndsWithInsensitive?: string;
  /** Matches the specified pattern (case-sensitive). An underscore (_) matches any single character; a percent sign (%) matches any sequence of zero or more characters. */
  like?: string;
  /** Does not match the specified pattern (case-sensitive). An underscore (_) matches any single character; a percent sign (%) matches any sequence of zero or more characters. */
  notLike?: string;
  /** Matches the specified pattern (case-insensitive). An underscore (_) matches any single character; a percent sign (%) matches any sequence of zero or more characters. */
  likeInsensitive?: string;
  /** Does not match the specified pattern (case-insensitive). An underscore (_) matches any single character; a percent sign (%) matches any sequence of zero or more characters. */
  notLikeInsensitive?: string;
  /** Equal to the specified value (case-insensitive). */
  equalToInsensitive?: string;
  /** Not equal to the specified value (case-insensitive). */
  notEqualToInsensitive?: string;
  /** Not equal to the specified value, treating null like an ordinary value (case-insensitive). */
  distinctFromInsensitive?: string;
  /** Equal to the specified value, treating null like an ordinary value (case-insensitive). */
  notDistinctFromInsensitive?: string;
  /** Included in the specified list (case-insensitive). */
  inInsensitive?: string[];
  /** Not included in the specified list (case-insensitive). */
  notInInsensitive?: string[];
  /** Less than the specified value (case-insensitive). */
  lessThanInsensitive?: string;
  /** Less than or equal to the specified value (case-insensitive). */
  lessThanOrEqualToInsensitive?: string;
  /** Greater than the specified value (case-insensitive). */
  greaterThanInsensitive?: string;
  /** Greater than or equal to the specified value (case-insensitive). */
  greaterThanOrEqualToInsensitive?: string;
  /** Fuzzy matches using pg_trgm trigram similarity. Tolerates typos and misspellings. */
  similarTo?: TrgmSearchInput;
  /** Fuzzy matches using pg_trgm word_similarity. Finds the best matching substring within the column value. */
  wordSimilarTo?: TrgmSearchInput;
}
/** Input for pg_trgm fuzzy text matching. Provide a search value and optional similarity threshold. */
export interface TrgmSearchInput {
  /** The text to fuzzy-match against. Typos and misspellings are tolerated. */
  value: string;
  /** Minimum similarity threshold (0.0 to 1.0). Higher = stricter matching. Default is 0.3. */
  threshold?: number;
}
/** A filter to be used against ConstructiveInternalTypeImage fields. All fields are combined with a logical ‘and.’ */
export interface ConstructiveInternalTypeImageFilter {
  /** Is null (if `true` is specified) or is not null (if `false` is specified). */
  isNull?: boolean;
  /** Equal to the specified value. */
  equalTo?: ConstructiveInternalTypeImage;
  /** Not equal to the specified value. */
  notEqualTo?: ConstructiveInternalTypeImage;
  /** Not equal to the specified value, treating null like an ordinary value. */
  distinctFrom?: ConstructiveInternalTypeImage;
  /** Equal to the specified value, treating null like an ordinary value. */
  notDistinctFrom?: ConstructiveInternalTypeImage;
  /** Included in the specified list. */
  in?: ConstructiveInternalTypeImage[];
  /** Not included in the specified list. */
  notIn?: ConstructiveInternalTypeImage[];
  /** Less than the specified value. */
  lessThan?: ConstructiveInternalTypeImage;
  /** Less than or equal to the specified value. */
  lessThanOrEqualTo?: ConstructiveInternalTypeImage;
  /** Greater than the specified value. */
  greaterThan?: ConstructiveInternalTypeImage;
  /** Greater than or equal to the specified value. */
  greaterThanOrEqualTo?: ConstructiveInternalTypeImage;
  /** Contains the specified JSON. */
  contains?: ConstructiveInternalTypeImage;
  /** Contains the specified key. */
  containsKey?: string;
  /** Contains all of the specified keys. */
  containsAllKeys?: string[];
  /** Contains any of the specified keys. */
  containsAnyKeys?: string[];
  /** Contained by the specified JSON. */
  containedBy?: ConstructiveInternalTypeImage;
}
/** A filter to be used against `PlatformNamespaceEvent` object types. All fields are combined with a logical ‘and.’ */
export interface PlatformNamespaceEventFilter {
  /** Filter by the object’s `createdAt` field. */
  createdAt?: DatetimeFilter;
  /** Filter by the object’s `actorId` field. */
  actorId?: UUIDFilter;
  /** Filter by the object’s `cpuMillicores` field. */
  cpuMillicores?: IntFilter;
  /** Filter by the object’s `databaseId` field. */
  databaseId?: UUIDFilter;
  /** Filter by the object’s `eventType` field. */
  eventType?: StringFilter;
  /** Filter by the object’s `id` field. */
  id?: UUIDFilter;
  /** Filter by the object’s `memoryBytes` field. */
  memoryBytes?: BigIntFilter;
  /** Filter by the object’s `message` field. */
  message?: StringFilter;
  /** Filter by the object’s `metadata` field. */
  metadata?: JSONFilter;
  /** Filter by the object’s `metrics` field. */
  metrics?: JSONFilter;
  /** Filter by the object’s `namespaceId` field. */
  namespaceId?: UUIDFilter;
  /** Filter by the object’s `networkEgressBytes` field. */
  networkEgressBytes?: BigIntFilter;
  /** Filter by the object’s `networkIngressBytes` field. */
  networkIngressBytes?: BigIntFilter;
  /** Filter by the object’s `podCount` field. */
  podCount?: IntFilter;
  /** Filter by the object’s `storageBytes` field. */
  storageBytes?: BigIntFilter;
  /** Checks for all expressions in this list. */
  and?: PlatformNamespaceEventFilter[];
  /** Checks for any expressions in this list. */
  or?: PlatformNamespaceEventFilter[];
  /** Negates the expression. */
  not?: PlatformNamespaceEventFilter;
}
export interface PlatformSecretsDelInput {
  clientMutationId?: string;
  secretName?: string;
  secretNamespace?: string;
}
export interface PlatformSecretsSetInput {
  clientMutationId?: string;
  secretName?: string;
  secretValue?: string;
  algo?: string;
  secretNamespace?: string;
}
export interface OrgSecretsDelInput {
  clientMutationId?: string;
  ownerId?: string;
  secretName?: string;
  secretNamespace?: string;
}
export interface OrgSecretsSetInput {
  clientMutationId?: string;
  ownerId?: string;
  secretName?: string;
  secretValue?: string;
  algo?: string;
  secretNamespace?: string;
}
export interface OrgSecretsRemoveArrayInput {
  clientMutationId?: string;
  ownerId?: string;
  secretNames?: string[];
  secretNamespace?: string;
}
export interface PlatformFilesRenameInput {
  clientMutationId?: string;
  pFileId?: string;
  pNewFilename?: string;
}
export interface CreateRoleTypeInput {
  clientMutationId?: string;
  /** The `RoleType` to be created by this mutation. */
  roleType: RoleTypeInput;
}
/** An input for mutations affecting `RoleType` */
export interface RoleTypeInput {
  id: number;
  name: string;
}
export interface CreatePlatformConfigDefinitionInput {
  clientMutationId?: string;
  /** The `PlatformConfigDefinition` to be created by this mutation. */
  platformConfigDefinition: PlatformConfigDefinitionInput;
}
/** An input for mutations affecting `PlatformConfigDefinition` */
export interface PlatformConfigDefinitionInput {
  /** Freeform metadata annotations for config definitions */
  annotations?: unknown;
  createdAt?: string;
  /** Default value used when no config entry exists for a namespace */
  defaultValue?: string;
  /** Human-readable description of what this config key controls */
  description?: string;
  /** Unique identifier for this config definition */
  id?: string;
  /** Whether this row was seeded as a built-in config definition */
  isBuiltIn?: boolean;
  /** Key-value metadata for filtering and grouping config definitions */
  labels?: unknown;
  /** Config key name (must match config table name for resolution) */
  name: string;
  updatedAt?: string;
}
export interface CreatePlatformNamespaceInput {
  clientMutationId?: string;
  /** The `PlatformNamespace` to be created by this mutation. */
  platformNamespace: PlatformNamespaceInput;
}
/** An input for mutations affecting `PlatformNamespace` */
export interface PlatformNamespaceInput {
  /** Freeform metadata for tooling and operational notes */
  annotations?: unknown;
  createdAt?: string;
  /** Database that owns this resource (database-scoped isolation) */
  databaseId: string;
  /** Optional human-readable description of this namespace */
  description?: string;
  id?: string;
  /** Whether this namespace is active (soft-disable for filtering) */
  isActive?: boolean;
  /** Key/value pairs for selecting and filtering namespaces */
  labels?: unknown;
  /** Human-readable namespace name (e.g. default, production, oauth) */
  name: string;
  /** Globally unique computed namespace identifier via inflection.underscore */
  namespaceName: string;
  updatedAt?: string;
}
export interface CreatePlatformConfigInput {
  clientMutationId?: string;
  /** The `PlatformConfig` to be created by this mutation. */
  platformConfig: PlatformConfigInput;
}
/** An input for mutations affecting `PlatformConfig` */
export interface PlatformConfigInput {
  /** Freeform metadata for tooling and operational notes */
  annotations?: unknown;
  createdAt?: string;
  /** Human-readable note about this config entry */
  description?: string;
  /** Optional expiration timestamp for time-limited config entries */
  expiresAt?: string;
  /** Unique identifier for this config entry */
  id?: string;
  /** Key/value pairs for selecting/filtering config entries */
  labels?: unknown;
  /** Key name identifying the config entry */
  name: string;
  /** FK to namespaces — logical grouping for config entries */
  namespaceId: string;
  updatedAt?: string;
  /** Plaintext config value */
  value?: string;
}
export interface CreatePlatformBucketInput {
  clientMutationId?: string;
  /** The `PlatformBucket` to be created by this mutation. */
  platformBucket: PlatformBucketInput;
}
/** An input for mutations affecting `PlatformBucket` */
export interface PlatformBucketInput {
  /** User who created this bucket. Forced to current_user_id() on INSERT. */
  actorId: string;
  /** When true, clients can provide custom S3 keys (e.g. reports/2024/Q1.pdf). When false (default), S3 key = content hash (automatic dedup). contentHash always required for integrity. */
  allowCustomKeys?: boolean;
  /** Whitelist of allowed MIME types for files in this bucket (NULL = all allowed, enforcement deferred) */
  allowedMimeTypes?: string[];
  /** Per-bucket CORS allowed origins override (NULL = inherit from storage_module/plugin defaults). Use ARRAY['*'] for open/CDN mode. */
  allowedOrigins?: string[];
  createdAt?: string;
  /** Database that owns this resource (database-scoped isolation) */
  databaseId: string;
  /** Human-readable description of the bucket purpose */
  description?: string;
  id?: string;
  /** Whether bucket contents are publicly readable. Set to true when type is public. */
  isPublic?: boolean;
  /** Unique bucket identifier used in S3 key paths (e.g. avatars, documents, temp) */
  key: string;
  /** Maximum file size in bytes allowed in this bucket (NULL = no limit, enforcement deferred) */
  maxFileSize?: string;
  /** Bucket CDN access type: public (CDN-served), private (presigned GET), temp (staging uploads) */
  type?: string;
  updatedAt?: string;
}
export interface CreateUserInput {
  clientMutationId?: string;
  /** The `User` to be created by this mutation. */
  user: UserInput;
}
/** An input for mutations affecting `User` */
export interface UserInput {
  createdAt?: string;
  displayName?: string;
  id?: string;
  profilePicture?: ConstructiveInternalTypeImage;
  type?: number;
  updatedAt?: string;
  username?: string;
}
export interface CreatePlatformNamespaceEventInput {
  clientMutationId?: string;
  /** The `PlatformNamespaceEvent` to be created by this mutation. */
  platformNamespaceEvent: PlatformNamespaceEventInput;
}
/** An input for mutations affecting `PlatformNamespaceEvent` */
export interface PlatformNamespaceEventInput {
  /** Event timestamp (partition key) */
  createdAt?: string;
  /** User who triggered this event (NULL for system/automated) */
  actorId?: string;
  /** CPU usage in millicores at time of event */
  cpuMillicores?: number;
  /** Database that owns this resource (database-scoped isolation) */
  databaseId: string;
  /** Event type: created, activated, deactivated, labels_updated, annotations_updated, renamed */
  eventType: string;
  /** Unique event identifier */
  id?: string;
  /** Memory usage in bytes at time of event */
  memoryBytes?: string;
  /** Human-readable description of the event */
  message?: string;
  /** Structured context (old/new values, labels diff, etc.) */
  metadata?: unknown;
  /** Additional resource metrics (gpu, replicas, quotas, etc.) */
  metrics?: unknown;
  /** Namespace this event belongs to */
  namespaceId: string;
  /** Network egress in bytes during event window */
  networkEgressBytes?: string;
  /** Network ingress in bytes during event window */
  networkIngressBytes?: string;
  /** Number of active pods in the namespace at time of event */
  podCount?: number;
  /** Storage usage in bytes at time of event */
  storageBytes?: string;
}
export interface CreatePlatformFileInput {
  clientMutationId?: string;
  /** The `PlatformFile` to be created by this mutation. */
  platformFile: PlatformFileInput;
}
/** An input for mutations affecting `PlatformFile` */
export interface PlatformFileInput {
  /** User who uploaded this file. Forced to current_user_id() on INSERT. Used for UPDATE/DELETE authorization. */
  actorId: string;
  /** Bucket this file belongs to. Determines owner_id and is_public via inheritance trigger. */
  bucketId: string;
  /** SHA-256 content hash for integrity verification and dedup. In default mode, equals the S3 key. In custom key mode, stored separately. */
  contentHash?: string;
  createdAt?: string;
  /** Database that owns this resource (database-scoped isolation) */
  databaseId: string;
  /** Human-readable description or alt text for the file (mutable) */
  description?: string;
  /** Original filename provided by the uploader. Used for display and Content-Disposition header on download. */
  filename?: string;
  id?: string;
  /** Whether this file is publicly readable. Inherited from bucket on INSERT. */
  isPublic?: boolean;
  /** S3 object key for this file, unique within its bucket */
  key: string;
  /** MIME type of the file (e.g. image/png, application/pdf). Immutable after INSERT. */
  mimeType: string;
  /** File size in bytes. Immutable after INSERT. */
  size: string;
  /** User-defined tags for categorization and search (mutable) */
  tags?: string[];
  updatedAt?: string;
  /** Processed file reference (upload domain). Populated by processing jobs after file is uploaded. Copy this value to other tables to reference the file. */
  upload?: ConstructiveInternalTypeUpload;
  /** File lifecycle status: requested (presigned URL generated, not yet in S3), uploaded (file in S3, ready for basic use), processed (MIME verified, image resized, embedding computed). */
  status?: FileStatus;
}
export interface UpdateRoleTypeInput {
  clientMutationId?: string;
  id: number;
  /** An object where the defined keys will be set on the `RoleType` being updated. */
  roleTypePatch: RoleTypePatch;
}
/** Represents an update to a `RoleType`. Fields that are set will be updated. */
export interface RoleTypePatch {
  id?: number;
  name?: string;
}
export interface UpdatePlatformConfigDefinitionInput {
  clientMutationId?: string;
  /** Unique identifier for this config definition */
  id: string;
  /** An object where the defined keys will be set on the `PlatformConfigDefinition` being updated. */
  platformConfigDefinitionPatch: PlatformConfigDefinitionPatch;
}
/** Represents an update to a `PlatformConfigDefinition`. Fields that are set will be updated. */
export interface PlatformConfigDefinitionPatch {
  /** Freeform metadata annotations for config definitions */
  annotations?: unknown;
  createdAt?: string;
  /** Default value used when no config entry exists for a namespace */
  defaultValue?: string;
  /** Human-readable description of what this config key controls */
  description?: string;
  /** Unique identifier for this config definition */
  id?: string;
  /** Whether this row was seeded as a built-in config definition */
  isBuiltIn?: boolean;
  /** Key-value metadata for filtering and grouping config definitions */
  labels?: unknown;
  /** Config key name (must match config table name for resolution) */
  name?: string;
  updatedAt?: string;
}
export interface UpdatePlatformNamespaceInput {
  clientMutationId?: string;
  id: string;
  /** An object where the defined keys will be set on the `PlatformNamespace` being updated. */
  platformNamespacePatch: PlatformNamespacePatch;
}
/** Represents an update to a `PlatformNamespace`. Fields that are set will be updated. */
export interface PlatformNamespacePatch {
  /** Freeform metadata for tooling and operational notes */
  annotations?: unknown;
  createdAt?: string;
  /** Database that owns this resource (database-scoped isolation) */
  databaseId?: string;
  /** Optional human-readable description of this namespace */
  description?: string;
  id?: string;
  /** Whether this namespace is active (soft-disable for filtering) */
  isActive?: boolean;
  /** Key/value pairs for selecting and filtering namespaces */
  labels?: unknown;
  /** Human-readable namespace name (e.g. default, production, oauth) */
  name?: string;
  /** Globally unique computed namespace identifier via inflection.underscore */
  namespaceName?: string;
  updatedAt?: string;
}
export interface UpdatePlatformConfigInput {
  clientMutationId?: string;
  /** Unique identifier for this config entry */
  id: string;
  /** An object where the defined keys will be set on the `PlatformConfig` being updated. */
  platformConfigPatch: PlatformConfigPatch;
}
/** Represents an update to a `PlatformConfig`. Fields that are set will be updated. */
export interface PlatformConfigPatch {
  /** Freeform metadata for tooling and operational notes */
  annotations?: unknown;
  createdAt?: string;
  /** Human-readable note about this config entry */
  description?: string;
  /** Optional expiration timestamp for time-limited config entries */
  expiresAt?: string;
  /** Unique identifier for this config entry */
  id?: string;
  /** Key/value pairs for selecting/filtering config entries */
  labels?: unknown;
  /** Key name identifying the config entry */
  name?: string;
  /** FK to namespaces — logical grouping for config entries */
  namespaceId?: string;
  updatedAt?: string;
  /** Plaintext config value */
  value?: string;
}
export interface UpdatePlatformBucketInput {
  clientMutationId?: string;
  id: string;
  /** An object where the defined keys will be set on the `PlatformBucket` being updated. */
  platformBucketPatch: PlatformBucketPatch;
}
/** Represents an update to a `PlatformBucket`. Fields that are set will be updated. */
export interface PlatformBucketPatch {
  /** User who created this bucket. Forced to current_user_id() on INSERT. */
  actorId?: string;
  /** When true, clients can provide custom S3 keys (e.g. reports/2024/Q1.pdf). When false (default), S3 key = content hash (automatic dedup). contentHash always required for integrity. */
  allowCustomKeys?: boolean;
  /** Whitelist of allowed MIME types for files in this bucket (NULL = all allowed, enforcement deferred) */
  allowedMimeTypes?: string[];
  /** Per-bucket CORS allowed origins override (NULL = inherit from storage_module/plugin defaults). Use ARRAY['*'] for open/CDN mode. */
  allowedOrigins?: string[];
  createdAt?: string;
  /** Database that owns this resource (database-scoped isolation) */
  databaseId?: string;
  /** Human-readable description of the bucket purpose */
  description?: string;
  id?: string;
  /** Whether bucket contents are publicly readable. Set to true when type is public. */
  isPublic?: boolean;
  /** Unique bucket identifier used in S3 key paths (e.g. avatars, documents, temp) */
  key?: string;
  /** Maximum file size in bytes allowed in this bucket (NULL = no limit, enforcement deferred) */
  maxFileSize?: string;
  /** Bucket CDN access type: public (CDN-served), private (presigned GET), temp (staging uploads) */
  type?: string;
  updatedAt?: string;
}
export interface UpdateUserInput {
  clientMutationId?: string;
  id: string;
  /** An object where the defined keys will be set on the `User` being updated. */
  userPatch: UserPatch;
}
/** Represents an update to a `User`. Fields that are set will be updated. */
export interface UserPatch {
  createdAt?: string;
  displayName?: string;
  id?: string;
  profilePicture?: ConstructiveInternalTypeImage;
  type?: number;
  updatedAt?: string;
  username?: string;
  /** File upload for the `profilePicture` field. */
  profilePictureUpload?: File;
}
export interface UpdatePlatformNamespaceEventInput {
  clientMutationId?: string;
  /** Event timestamp (partition key) */
  createdAt: string;
  /** Unique event identifier */
  id: string;
  /** An object where the defined keys will be set on the `PlatformNamespaceEvent` being updated. */
  platformNamespaceEventPatch: PlatformNamespaceEventPatch;
}
/** Represents an update to a `PlatformNamespaceEvent`. Fields that are set will be updated. */
export interface PlatformNamespaceEventPatch {
  /** Event timestamp (partition key) */
  createdAt?: string;
  /** User who triggered this event (NULL for system/automated) */
  actorId?: string;
  /** CPU usage in millicores at time of event */
  cpuMillicores?: number;
  /** Database that owns this resource (database-scoped isolation) */
  databaseId?: string;
  /** Event type: created, activated, deactivated, labels_updated, annotations_updated, renamed */
  eventType?: string;
  /** Unique event identifier */
  id?: string;
  /** Memory usage in bytes at time of event */
  memoryBytes?: string;
  /** Human-readable description of the event */
  message?: string;
  /** Structured context (old/new values, labels diff, etc.) */
  metadata?: unknown;
  /** Additional resource metrics (gpu, replicas, quotas, etc.) */
  metrics?: unknown;
  /** Namespace this event belongs to */
  namespaceId?: string;
  /** Network egress in bytes during event window */
  networkEgressBytes?: string;
  /** Network ingress in bytes during event window */
  networkIngressBytes?: string;
  /** Number of active pods in the namespace at time of event */
  podCount?: number;
  /** Storage usage in bytes at time of event */
  storageBytes?: string;
}
export interface UpdatePlatformFileInput {
  clientMutationId?: string;
  id: string;
  /** An object where the defined keys will be set on the `PlatformFile` being updated. */
  platformFilePatch: PlatformFilePatch;
}
/** Represents an update to a `PlatformFile`. Fields that are set will be updated. */
export interface PlatformFilePatch {
  /** User who uploaded this file. Forced to current_user_id() on INSERT. Used for UPDATE/DELETE authorization. */
  actorId?: string;
  /** Bucket this file belongs to. Determines owner_id and is_public via inheritance trigger. */
  bucketId?: string;
  /** SHA-256 content hash for integrity verification and dedup. In default mode, equals the S3 key. In custom key mode, stored separately. */
  contentHash?: string;
  createdAt?: string;
  /** Database that owns this resource (database-scoped isolation) */
  databaseId?: string;
  /** Human-readable description or alt text for the file (mutable) */
  description?: string;
  /** Original filename provided by the uploader. Used for display and Content-Disposition header on download. */
  filename?: string;
  id?: string;
  /** Whether this file is publicly readable. Inherited from bucket on INSERT. */
  isPublic?: boolean;
  /** S3 object key for this file, unique within its bucket */
  key?: string;
  /** MIME type of the file (e.g. image/png, application/pdf). Immutable after INSERT. */
  mimeType?: string;
  /** File size in bytes. Immutable after INSERT. */
  size?: string;
  /** User-defined tags for categorization and search (mutable) */
  tags?: string[];
  updatedAt?: string;
  /** Processed file reference (upload domain). Populated by processing jobs after file is uploaded. Copy this value to other tables to reference the file. */
  upload?: ConstructiveInternalTypeUpload;
  /** File lifecycle status: requested (presigned URL generated, not yet in S3), uploaded (file in S3, ready for basic use), processed (MIME verified, image resized, embedding computed). */
  status?: FileStatus;
  /** Upload for Processed file reference (upload domain). Populated by processing jobs after file is uploaded. Copy this value to other tables to reference the file. */
  uploadUpload?: File;
}
export interface DeleteRoleTypeInput {
  clientMutationId?: string;
  id: number;
}
export interface DeletePlatformConfigDefinitionInput {
  clientMutationId?: string;
  /** Unique identifier for this config definition */
  id: string;
}
export interface DeletePlatformNamespaceInput {
  clientMutationId?: string;
  id: string;
}
export interface DeletePlatformConfigInput {
  clientMutationId?: string;
  /** Unique identifier for this config entry */
  id: string;
}
export interface DeletePlatformBucketInput {
  clientMutationId?: string;
  id: string;
}
export interface DeleteUserInput {
  clientMutationId?: string;
  id: string;
}
export interface DeletePlatformNamespaceEventInput {
  clientMutationId?: string;
  /** Event timestamp (partition key) */
  createdAt: string;
  /** Unique event identifier */
  id: string;
}
export interface DeletePlatformFileInput {
  clientMutationId?: string;
  id: string;
}
export interface UploadPlatformFileInput {
  /** Bucket key (e.g., "public", "private") */
  bucketKey: string;
  /** SHA-256 content hash (hex-encoded, 64 chars) */
  contentHash: string;
  /** MIME type of the file */
  contentType: string;
  /** File size in bytes */
  size: number;
  /** Original filename (optional) */
  filename?: string;
  /** Custom S3 key (only when bucket has allow_custom_keys=true) */
  key?: string;
}
export interface UploadPlatformFileBulkInput {
  /** Bucket key (e.g., "public", "private") */
  bucketKey: string;
  /** Array of files to upload */
  files: UploadPlatformFileBulkFileInput[];
}
export interface UploadPlatformFileBulkFileInput {
  /** SHA-256 content hash (hex-encoded, 64 chars) */
  contentHash: string;
  /** MIME type of the file */
  contentType: string;
  /** File size in bytes */
  size: number;
  /** Original filename (optional) */
  filename?: string;
  /** Custom S3 key (only when bucket has allow_custom_keys=true) */
  key?: string;
}
export interface ProvisionBucketInput {
  /** The logical bucket key (e.g., "public", "private") */
  bucketKey: string;
  /**
   * Owner entity ID for entity-scoped bucket provisioning.
   * Omit for app-level (database-wide) storage.
   */
  ownerId?: string;
}
/** A connection to a list of `RoleType` values. */
export interface RoleTypeConnection {
  nodes: RoleType[];
  edges: RoleTypeEdge[];
  pageInfo: PageInfo;
  totalCount: number;
}
/** A connection to a list of `PlatformConfigDefinition` values. */
export interface PlatformConfigDefinitionConnection {
  nodes: PlatformConfigDefinition[];
  edges: PlatformConfigDefinitionEdge[];
  pageInfo: PageInfo;
  totalCount: number;
}
/** A connection to a list of `PlatformNamespace` values. */
export interface PlatformNamespaceConnection {
  nodes: PlatformNamespace[];
  edges: PlatformNamespaceEdge[];
  pageInfo: PageInfo;
  totalCount: number;
}
/** A connection to a list of `PlatformConfig` values. */
export interface PlatformConfigConnection {
  nodes: PlatformConfig[];
  edges: PlatformConfigEdge[];
  pageInfo: PageInfo;
  totalCount: number;
}
/** A connection to a list of `PlatformBucket` values. */
export interface PlatformBucketConnection {
  nodes: PlatformBucket[];
  edges: PlatformBucketEdge[];
  pageInfo: PageInfo;
  totalCount: number;
}
/** A connection to a list of `User` values. */
export interface UserConnection {
  nodes: User[];
  edges: UserEdge[];
  pageInfo: PageInfo;
  totalCount: number;
}
/** A connection to a list of `PlatformNamespaceEvent` values. */
export interface PlatformNamespaceEventConnection {
  nodes: PlatformNamespaceEvent[];
  edges: PlatformNamespaceEventEdge[];
  pageInfo: PageInfo;
  totalCount: number;
}
/** A connection to a list of `PlatformFile` values. */
export interface PlatformFileConnection {
  nodes: PlatformFile[];
  edges: PlatformFileEdge[];
  pageInfo: PageInfo;
  totalCount: number;
}
/** Root meta schema type */
export interface MetaSchema {
  tables: MetaTable[];
}
export interface PlatformSecretsDelPayload {
  clientMutationId?: string | null;
}
export interface PlatformSecretsSetPayload {
  clientMutationId?: string | null;
  result?: boolean | null;
}
export interface OrgSecretsDelPayload {
  clientMutationId?: string | null;
}
export interface OrgSecretsSetPayload {
  clientMutationId?: string | null;
  result?: boolean | null;
}
export interface OrgSecretsRemoveArrayPayload {
  clientMutationId?: string | null;
}
export interface PlatformFilesRenamePayload {
  clientMutationId?: string | null;
  result?: PlatformFile | null;
  platformFileEdge?: PlatformFileEdge | null;
}
export interface CreateRoleTypePayload {
  clientMutationId?: string | null;
  /** The `RoleType` that was created by this mutation. */
  roleType?: RoleType | null;
  roleTypeEdge?: RoleTypeEdge | null;
}
export interface CreatePlatformConfigDefinitionPayload {
  clientMutationId?: string | null;
  /** The `PlatformConfigDefinition` that was created by this mutation. */
  platformConfigDefinition?: PlatformConfigDefinition | null;
  platformConfigDefinitionEdge?: PlatformConfigDefinitionEdge | null;
}
export interface CreatePlatformNamespacePayload {
  clientMutationId?: string | null;
  /** The `PlatformNamespace` that was created by this mutation. */
  platformNamespace?: PlatformNamespace | null;
  platformNamespaceEdge?: PlatformNamespaceEdge | null;
}
export interface CreatePlatformConfigPayload {
  clientMutationId?: string | null;
  /** The `PlatformConfig` that was created by this mutation. */
  platformConfig?: PlatformConfig | null;
  platformConfigEdge?: PlatformConfigEdge | null;
}
export interface CreatePlatformBucketPayload {
  clientMutationId?: string | null;
  /** The `PlatformBucket` that was created by this mutation. */
  platformBucket?: PlatformBucket | null;
  platformBucketEdge?: PlatformBucketEdge | null;
}
export interface CreateUserPayload {
  clientMutationId?: string | null;
  /** The `User` that was created by this mutation. */
  user?: User | null;
  userEdge?: UserEdge | null;
}
export interface CreatePlatformNamespaceEventPayload {
  clientMutationId?: string | null;
  /** The `PlatformNamespaceEvent` that was created by this mutation. */
  platformNamespaceEvent?: PlatformNamespaceEvent | null;
  platformNamespaceEventEdge?: PlatformNamespaceEventEdge | null;
}
export interface CreatePlatformFilePayload {
  clientMutationId?: string | null;
  /** The `PlatformFile` that was created by this mutation. */
  platformFile?: PlatformFile | null;
  platformFileEdge?: PlatformFileEdge | null;
}
export interface UpdateRoleTypePayload {
  clientMutationId?: string | null;
  /** The `RoleType` that was updated by this mutation. */
  roleType?: RoleType | null;
  roleTypeEdge?: RoleTypeEdge | null;
}
export interface UpdatePlatformConfigDefinitionPayload {
  clientMutationId?: string | null;
  /** The `PlatformConfigDefinition` that was updated by this mutation. */
  platformConfigDefinition?: PlatformConfigDefinition | null;
  platformConfigDefinitionEdge?: PlatformConfigDefinitionEdge | null;
}
export interface UpdatePlatformNamespacePayload {
  clientMutationId?: string | null;
  /** The `PlatformNamespace` that was updated by this mutation. */
  platformNamespace?: PlatformNamespace | null;
  platformNamespaceEdge?: PlatformNamespaceEdge | null;
}
export interface UpdatePlatformConfigPayload {
  clientMutationId?: string | null;
  /** The `PlatformConfig` that was updated by this mutation. */
  platformConfig?: PlatformConfig | null;
  platformConfigEdge?: PlatformConfigEdge | null;
}
export interface UpdatePlatformBucketPayload {
  clientMutationId?: string | null;
  /** The `PlatformBucket` that was updated by this mutation. */
  platformBucket?: PlatformBucket | null;
  platformBucketEdge?: PlatformBucketEdge | null;
}
export interface UpdateUserPayload {
  clientMutationId?: string | null;
  /** The `User` that was updated by this mutation. */
  user?: User | null;
  userEdge?: UserEdge | null;
}
export interface UpdatePlatformNamespaceEventPayload {
  clientMutationId?: string | null;
  /** The `PlatformNamespaceEvent` that was updated by this mutation. */
  platformNamespaceEvent?: PlatformNamespaceEvent | null;
  platformNamespaceEventEdge?: PlatformNamespaceEventEdge | null;
}
export interface UpdatePlatformFilePayload {
  clientMutationId?: string | null;
  /** The `PlatformFile` that was updated by this mutation. */
  platformFile?: PlatformFile | null;
  platformFileEdge?: PlatformFileEdge | null;
}
export interface DeleteRoleTypePayload {
  clientMutationId?: string | null;
  /** The `RoleType` that was deleted by this mutation. */
  roleType?: RoleType | null;
  roleTypeEdge?: RoleTypeEdge | null;
}
export interface DeletePlatformConfigDefinitionPayload {
  clientMutationId?: string | null;
  /** The `PlatformConfigDefinition` that was deleted by this mutation. */
  platformConfigDefinition?: PlatformConfigDefinition | null;
  platformConfigDefinitionEdge?: PlatformConfigDefinitionEdge | null;
}
export interface DeletePlatformNamespacePayload {
  clientMutationId?: string | null;
  /** The `PlatformNamespace` that was deleted by this mutation. */
  platformNamespace?: PlatformNamespace | null;
  platformNamespaceEdge?: PlatformNamespaceEdge | null;
}
export interface DeletePlatformConfigPayload {
  clientMutationId?: string | null;
  /** The `PlatformConfig` that was deleted by this mutation. */
  platformConfig?: PlatformConfig | null;
  platformConfigEdge?: PlatformConfigEdge | null;
}
export interface DeletePlatformBucketPayload {
  clientMutationId?: string | null;
  /** The `PlatformBucket` that was deleted by this mutation. */
  platformBucket?: PlatformBucket | null;
  platformBucketEdge?: PlatformBucketEdge | null;
}
export interface DeleteUserPayload {
  clientMutationId?: string | null;
  /** The `User` that was deleted by this mutation. */
  user?: User | null;
  userEdge?: UserEdge | null;
}
export interface DeletePlatformNamespaceEventPayload {
  clientMutationId?: string | null;
  /** The `PlatformNamespaceEvent` that was deleted by this mutation. */
  platformNamespaceEvent?: PlatformNamespaceEvent | null;
  platformNamespaceEventEdge?: PlatformNamespaceEventEdge | null;
}
export interface DeletePlatformFilePayload {
  clientMutationId?: string | null;
  /** The `PlatformFile` that was deleted by this mutation. */
  platformFile?: PlatformFile | null;
  platformFileEdge?: PlatformFileEdge | null;
}
export interface UploadPlatformFilePayload {
  /** Presigned PUT URL (null if deduplicated) */
  uploadUrl?: string | null;
  /** The file ID (UUID) */
  fileId: string;
  /** The S3 object key */
  key: string;
  /** Whether this file was deduplicated (content already exists) */
  deduplicated: boolean;
  /** Presigned URL expiry time (null if deduplicated) */
  expiresAt?: string | null;
  /** ID of the previous version (when using custom keys) */
  previousVersionId?: string | null;
}
export interface UploadPlatformFileBulkPayload {
  files: UploadPlatformFileBulkFilePayload[];
}
export interface ProvisionBucketPayload {
  /** Whether provisioning succeeded */
  success: boolean;
  /** The S3 bucket name that was provisioned */
  bucketName: string;
  /** The access type applied */
  accessType: string;
  /** The storage provider used */
  provider: string;
  /** The S3 endpoint (null for AWS S3 default) */
  endpoint?: string | null;
  /** Error message if provisioning failed */
  error?: string | null;
}
/** A `RoleType` edge in the connection. */
export interface RoleTypeEdge {
  cursor?: string | null;
  /** The `RoleType` at the end of the edge. */
  node?: RoleType | null;
}
/** Information about pagination in a connection. */
export interface PageInfo {
  /** When paginating forwards, are there more items? */
  hasNextPage: boolean;
  /** When paginating backwards, are there more items? */
  hasPreviousPage: boolean;
  /** When paginating backwards, the cursor to continue. */
  startCursor?: string | null;
  /** When paginating forwards, the cursor to continue. */
  endCursor?: string | null;
}
/** A `PlatformConfigDefinition` edge in the connection. */
export interface PlatformConfigDefinitionEdge {
  cursor?: string | null;
  /** The `PlatformConfigDefinition` at the end of the edge. */
  node?: PlatformConfigDefinition | null;
}
/** A `PlatformNamespace` edge in the connection. */
export interface PlatformNamespaceEdge {
  cursor?: string | null;
  /** The `PlatformNamespace` at the end of the edge. */
  node?: PlatformNamespace | null;
}
/** A `PlatformConfig` edge in the connection. */
export interface PlatformConfigEdge {
  cursor?: string | null;
  /** The `PlatformConfig` at the end of the edge. */
  node?: PlatformConfig | null;
}
/** A `PlatformBucket` edge in the connection. */
export interface PlatformBucketEdge {
  cursor?: string | null;
  /** The `PlatformBucket` at the end of the edge. */
  node?: PlatformBucket | null;
}
/** A `User` edge in the connection. */
export interface UserEdge {
  cursor?: string | null;
  /** The `User` at the end of the edge. */
  node?: User | null;
}
/** A `PlatformNamespaceEvent` edge in the connection. */
export interface PlatformNamespaceEventEdge {
  cursor?: string | null;
  /** The `PlatformNamespaceEvent` at the end of the edge. */
  node?: PlatformNamespaceEvent | null;
}
/** A `PlatformFile` edge in the connection. */
export interface PlatformFileEdge {
  cursor?: string | null;
  /** The `PlatformFile` at the end of the edge. */
  node?: PlatformFile | null;
}
/** Information about a database table */
export interface MetaTable {
  name: string;
  schemaName: string;
  fields: MetaField[];
  indexes: MetaIndex[];
  constraints: MetaConstraints;
  foreignKeyConstraints: MetaForeignKeyConstraint[];
  primaryKeyConstraints: MetaPrimaryKeyConstraint[];
  uniqueConstraints: MetaUniqueConstraint[];
  relations: MetaRelations;
  inflection: MetaInflection;
  query: MetaQuery;
}
export interface UploadPlatformFileBulkFilePayload {
  uploadUrl?: string | null;
  fileId: string;
  key: string;
  deduplicated: boolean;
  expiresAt?: string | null;
  previousVersionId?: string | null;
}
/** Information about a table field/column */
export interface MetaField {
  name: string;
  type: MetaType;
  isNotNull: boolean;
  hasDefault: boolean;
  isPrimaryKey: boolean;
  isForeignKey: boolean;
  description?: string | null;
}
/** Information about a database index */
export interface MetaIndex {
  name: string;
  isUnique: boolean;
  isPrimary: boolean;
  columns: string[];
  fields?: MetaField[] | null;
}
/** Table constraints */
export interface MetaConstraints {
  primaryKey?: MetaPrimaryKeyConstraint | null;
  unique: MetaUniqueConstraint[];
  foreignKey: MetaForeignKeyConstraint[];
}
/** Information about a foreign key constraint */
export interface MetaForeignKeyConstraint {
  name: string;
  fields: MetaField[];
  referencedTable: string;
  referencedFields: string[];
  refFields?: MetaField[] | null;
  refTable?: MetaRefTable | null;
}
/** Information about a primary key constraint */
export interface MetaPrimaryKeyConstraint {
  name: string;
  fields: MetaField[];
}
/** Information about a unique constraint */
export interface MetaUniqueConstraint {
  name: string;
  fields: MetaField[];
}
/** Table relations */
export interface MetaRelations {
  belongsTo: MetaBelongsToRelation[];
  has: MetaHasRelation[];
  hasOne: MetaHasRelation[];
  hasMany: MetaHasRelation[];
  manyToMany: MetaManyToManyRelation[];
}
/** Table inflection names */
export interface MetaInflection {
  tableType: string;
  allRows: string;
  connection: string;
  edge: string;
  filterType?: string | null;
  orderByType: string;
  conditionType: string;
  patchType?: string | null;
  createInputType: string;
  createPayloadType: string;
  updatePayloadType?: string | null;
  deletePayloadType: string;
}
/** Table query/mutation names */
export interface MetaQuery {
  all: string;
  one?: string | null;
  create?: string | null;
  update?: string | null;
  delete?: string | null;
}
/** Information about a PostgreSQL type */
export interface MetaType {
  pgType: string;
  gqlType: string;
  isArray: boolean;
  isNotNull?: boolean | null;
  hasDefault?: boolean | null;
  subtype?: string | null;
}
/** Reference to a related table */
export interface MetaRefTable {
  name: string;
}
/** A belongs-to (forward FK) relation */
export interface MetaBelongsToRelation {
  fieldName?: string | null;
  isUnique: boolean;
  type?: string | null;
  keys: MetaField[];
  references: MetaRefTable;
}
/** A has-one or has-many (reverse FK) relation */
export interface MetaHasRelation {
  fieldName?: string | null;
  isUnique: boolean;
  type?: string | null;
  keys: MetaField[];
  referencedBy: MetaRefTable;
}
/** A many-to-many relation via junction table */
export interface MetaManyToManyRelation {
  fieldName?: string | null;
  type?: string | null;
  junctionTable: MetaRefTable;
  junctionLeftConstraint: MetaForeignKeyConstraint;
  junctionLeftKeyAttributes: MetaField[];
  junctionRightConstraint: MetaForeignKeyConstraint;
  junctionRightKeyAttributes: MetaField[];
  leftKeyAttributes: MetaField[];
  rightKeyAttributes: MetaField[];
  rightTable: MetaRefTable;
}
