apiVersion: batch/v1
kind: Job
metadata:
  name: simple-bash
  namespace: default
spec:
  template:
    spec:
      imagePullSecrets:
        - name: ghcr-pull
      containers:
      - name: function
        image: ghcr.io/constructive-io/simple-bash:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: JOB_PAYLOAD
          value: "{}"
      restartPolicy: Never
