-- Revert: schemas/constructive_platform_function_graph_public/tables/platform_function_graph_object/triggers/generate_id_hash


DROP TRIGGER generate_id_hash ON "constructive_platform_function_graph_public".platform_function_graph_object;


