-- Revert: schemas/constructive_compute_public/tables/platform_function_graph_execution_node_states/columns/completed_at/alterations/alt0000002711


COMMENT ON COLUMN "constructive_compute_public".platform_function_graph_execution_node_states.completed_at IS NULL;
