/**
 * Function invocation log — INSERT to call a function (business-layer, metered). Linked to definitions by task_identifier string.
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import { useQuery } from '@tanstack/react-query';
import type { UseQueryOptions, UseQueryResult, QueryClient } from '@tanstack/react-query';
import { getClient } from '../client';
import { buildSelectionArgs } from '../selection';
import type { SelectionConfig } from '../selection';
import { orgFunctionInvocationKeys } from '../query-keys';
import type {
  OrgFunctionInvocationSelect,
  OrgFunctionInvocationWithRelations,
} from '../../orm/input-types';
import type { InferSelectResult, HookStrictSelect } from '../../orm/select-types';
export type {
  OrgFunctionInvocationSelect,
  OrgFunctionInvocationWithRelations,
} from '../../orm/input-types';
/** Query key factory - re-exported from query-keys.ts */
export const orgFunctionInvocationQueryKey = orgFunctionInvocationKeys.detail;
/**
 * Function invocation log — INSERT to call a function (business-layer, metered). Linked to definitions by task_identifier string.
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useOrgFunctionInvocationQuery({
 *   id: 'some-id',
 *   selection: { fields: { id: true, name: true } },
 * });
 * ```
 */
export function useOrgFunctionInvocationQuery<
  S extends OrgFunctionInvocationSelect,
  TData = {
    orgFunctionInvocation: InferSelectResult<OrgFunctionInvocationWithRelations, S> | null;
  },
>(
  params: {
    id: string;
    selection: {
      fields: S;
    } & HookStrictSelect<NoInfer<S>, OrgFunctionInvocationSelect>;
  } & Omit<
    UseQueryOptions<
      {
        orgFunctionInvocation: InferSelectResult<OrgFunctionInvocationWithRelations, S> | null;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function useOrgFunctionInvocationQuery(
  params: {
    id: string;
    selection: SelectionConfig<OrgFunctionInvocationSelect>;
  } & Omit<UseQueryOptions<any, Error, any, any>, 'queryKey' | 'queryFn'>
) {
  const args = buildSelectionArgs<OrgFunctionInvocationSelect>(params.selection);
  const { selection: _selection, ...queryOptions } = params ?? {};
  void _selection;
  return useQuery({
    queryKey: orgFunctionInvocationKeys.detail(params.id),
    queryFn: () =>
      getClient()
        .orgFunctionInvocation.findOne({
          id: params.id,
          select: args.select,
        })
        .unwrap(),
    ...queryOptions,
  });
}
/**
 * Function invocation log — INSERT to call a function (business-layer, metered). Linked to definitions by task_identifier string.
 *
 * @example
 * ```ts
 * const data = await fetchOrgFunctionInvocationQuery({
 *   id: 'some-id',
 *   selection: { fields: { id: true } },
 * });
 * ```
 */
export async function fetchOrgFunctionInvocationQuery<
  S extends OrgFunctionInvocationSelect,
>(params: {
  id: string;
  selection: {
    fields: S;
  } & HookStrictSelect<NoInfer<S>, OrgFunctionInvocationSelect>;
}): Promise<{
  orgFunctionInvocation: InferSelectResult<OrgFunctionInvocationWithRelations, S> | null;
}>;
export async function fetchOrgFunctionInvocationQuery(params: {
  id: string;
  selection: SelectionConfig<OrgFunctionInvocationSelect>;
}): Promise<any> {
  const args = buildSelectionArgs<OrgFunctionInvocationSelect>(params.selection);
  return getClient()
    .orgFunctionInvocation.findOne({
      id: params.id,
      select: args.select,
    })
    .unwrap();
}
/**
 * Function invocation log — INSERT to call a function (business-layer, metered). Linked to definitions by task_identifier string.
 *
 * @example
 * ```ts
 * await prefetchOrgFunctionInvocationQuery(queryClient, { id: 'some-id', selection: { fields: { id: true } } });
 * ```
 */
export async function prefetchOrgFunctionInvocationQuery<S extends OrgFunctionInvocationSelect>(
  queryClient: QueryClient,
  params: {
    id: string;
    selection: {
      fields: S;
    } & HookStrictSelect<NoInfer<S>, OrgFunctionInvocationSelect>;
  }
): Promise<void>;
export async function prefetchOrgFunctionInvocationQuery(
  queryClient: QueryClient,
  params: {
    id: string;
    selection: SelectionConfig<OrgFunctionInvocationSelect>;
  }
): Promise<void> {
  const args = buildSelectionArgs<OrgFunctionInvocationSelect>(params.selection);
  await queryClient.prefetchQuery({
    queryKey: orgFunctionInvocationKeys.detail(params.id),
    queryFn: () =>
      getClient()
        .orgFunctionInvocation.findOne({
          id: params.id,
          select: args.select,
        })
        .unwrap(),
  });
}
