/**
 * Function execution logs — structured console output per invocation
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import type { QueryClient,UseQueryOptions, UseQueryResult } from '@tanstack/react-query';
import { useQuery } from '@tanstack/react-query';

import type {
  OrgFunctionExecutionLogSelect,
  OrgFunctionExecutionLogWithRelations,
} from '../../orm/input-types';
import type { HookStrictSelect,InferSelectResult } from '../../orm/select-types';
import { getClient } from '../client';
import { orgFunctionExecutionLogKeys } from '../query-keys';
import type { SelectionConfig } from '../selection';
import { buildSelectionArgs } from '../selection';
export type {
  OrgFunctionExecutionLogSelect,
  OrgFunctionExecutionLogWithRelations,
} from '../../orm/input-types';
/** Query key factory - re-exported from query-keys.ts */
export const orgFunctionExecutionLogQueryKey = orgFunctionExecutionLogKeys.detail;
/**
 * Function execution logs — structured console output per invocation
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useOrgFunctionExecutionLogQuery({
 *   id: 'some-id',
 *   selection: { fields: { id: true, name: true } },
 * });
 * ```
 */
export function useOrgFunctionExecutionLogQuery<
  S extends OrgFunctionExecutionLogSelect,
  TData = {
    orgFunctionExecutionLog: InferSelectResult<OrgFunctionExecutionLogWithRelations, S> | null;
  },
>(
  params: {
    id: string;
    selection: {
      fields: S;
    } & HookStrictSelect<NoInfer<S>, OrgFunctionExecutionLogSelect>;
  } & Omit<
    UseQueryOptions<
      {
        orgFunctionExecutionLog: InferSelectResult<OrgFunctionExecutionLogWithRelations, S> | null;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function useOrgFunctionExecutionLogQuery(
  params: {
    id: string;
    selection: SelectionConfig<OrgFunctionExecutionLogSelect>;
  } & Omit<UseQueryOptions<any, Error, any, any>, 'queryKey' | 'queryFn'>
) {
  const args = buildSelectionArgs<OrgFunctionExecutionLogSelect>(params.selection);
  const { selection: _selection, ...queryOptions } = params ?? {};
  void _selection;
  return useQuery({
    queryKey: orgFunctionExecutionLogKeys.detail(params.id),
    queryFn: () =>
      getClient()
        .orgFunctionExecutionLog.findOne({
          id: params.id,
          select: args.select,
        })
        .unwrap(),
    ...queryOptions,
  });
}
/**
 * Function execution logs — structured console output per invocation
 *
 * @example
 * ```ts
 * const data = await fetchOrgFunctionExecutionLogQuery({
 *   id: 'some-id',
 *   selection: { fields: { id: true } },
 * });
 * ```
 */
export async function fetchOrgFunctionExecutionLogQuery<
  S extends OrgFunctionExecutionLogSelect,
>(params: {
  id: string;
  selection: {
    fields: S;
  } & HookStrictSelect<NoInfer<S>, OrgFunctionExecutionLogSelect>;
}): Promise<{
  orgFunctionExecutionLog: InferSelectResult<OrgFunctionExecutionLogWithRelations, S> | null;
}>;
export async function fetchOrgFunctionExecutionLogQuery(params: {
  id: string;
  selection: SelectionConfig<OrgFunctionExecutionLogSelect>;
}): Promise<any> {
  const args = buildSelectionArgs<OrgFunctionExecutionLogSelect>(params.selection);
  return getClient()
    .orgFunctionExecutionLog.findOne({
      id: params.id,
      select: args.select,
    })
    .unwrap();
}
/**
 * Function execution logs — structured console output per invocation
 *
 * @example
 * ```ts
 * await prefetchOrgFunctionExecutionLogQuery(queryClient, { id: 'some-id', selection: { fields: { id: true } } });
 * ```
 */
export async function prefetchOrgFunctionExecutionLogQuery<S extends OrgFunctionExecutionLogSelect>(
  queryClient: QueryClient,
  params: {
    id: string;
    selection: {
      fields: S;
    } & HookStrictSelect<NoInfer<S>, OrgFunctionExecutionLogSelect>;
  }
): Promise<void>;
export async function prefetchOrgFunctionExecutionLogQuery(
  queryClient: QueryClient,
  params: {
    id: string;
    selection: SelectionConfig<OrgFunctionExecutionLogSelect>;
  }
): Promise<void> {
  const args = buildSelectionArgs<OrgFunctionExecutionLogSelect>(params.selection);
  await queryClient.prefetchQuery({
    queryKey: orgFunctionExecutionLogKeys.detail(params.id),
    queryFn: () =>
      getClient()
        .orgFunctionExecutionLog.findOne({
          id: params.id,
          select: args.select,
        })
        .unwrap(),
  });
}
