/**
 * Global secret name registry — declares which secrets the platform recognizes. Actual values live in app_secrets.
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import type { QueryClient,UseQueryOptions, UseQueryResult } from '@tanstack/react-query';
import { useQuery } from '@tanstack/react-query';

import type {
  PlatformSecretDefinitionSelect,
  PlatformSecretDefinitionWithRelations,
} from '../../orm/input-types';
import type { HookStrictSelect,InferSelectResult } from '../../orm/select-types';
import { getClient } from '../client';
import { platformSecretDefinitionKeys } from '../query-keys';
import type { SelectionConfig } from '../selection';
import { buildSelectionArgs } from '../selection';
export type {
  PlatformSecretDefinitionSelect,
  PlatformSecretDefinitionWithRelations,
} from '../../orm/input-types';
/** Query key factory - re-exported from query-keys.ts */
export const platformSecretDefinitionQueryKey = platformSecretDefinitionKeys.detail;
/**
 * Global secret name registry — declares which secrets the platform recognizes. Actual values live in app_secrets.
 *
 * @example
 * ```tsx
 * const { data, isLoading } = usePlatformSecretDefinitionQuery({
 *   id: 'some-id',
 *   selection: { fields: { id: true, name: true } },
 * });
 * ```
 */
export function usePlatformSecretDefinitionQuery<
  S extends PlatformSecretDefinitionSelect,
  TData = {
    platformSecretDefinition: InferSelectResult<PlatformSecretDefinitionWithRelations, S> | null;
  },
>(
  params: {
    id: string;
    selection: {
      fields: S;
    } & HookStrictSelect<NoInfer<S>, PlatformSecretDefinitionSelect>;
  } & Omit<
    UseQueryOptions<
      {
        platformSecretDefinition: InferSelectResult<
          PlatformSecretDefinitionWithRelations,
          S
        > | null;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function usePlatformSecretDefinitionQuery(
  params: {
    id: string;
    selection: SelectionConfig<PlatformSecretDefinitionSelect>;
  } & Omit<UseQueryOptions<any, Error, any, any>, 'queryKey' | 'queryFn'>
) {
  const args = buildSelectionArgs<PlatformSecretDefinitionSelect>(params.selection);
  const { selection: _selection, ...queryOptions } = params ?? {};
  void _selection;
  return useQuery({
    queryKey: platformSecretDefinitionKeys.detail(params.id),
    queryFn: () =>
      getClient()
        .platformSecretDefinition.findOne({
          id: params.id,
          select: args.select,
        })
        .unwrap(),
    ...queryOptions,
  });
}
/**
 * Global secret name registry — declares which secrets the platform recognizes. Actual values live in app_secrets.
 *
 * @example
 * ```ts
 * const data = await fetchPlatformSecretDefinitionQuery({
 *   id: 'some-id',
 *   selection: { fields: { id: true } },
 * });
 * ```
 */
export async function fetchPlatformSecretDefinitionQuery<
  S extends PlatformSecretDefinitionSelect,
>(params: {
  id: string;
  selection: {
    fields: S;
  } & HookStrictSelect<NoInfer<S>, PlatformSecretDefinitionSelect>;
}): Promise<{
  platformSecretDefinition: InferSelectResult<PlatformSecretDefinitionWithRelations, S> | null;
}>;
export async function fetchPlatformSecretDefinitionQuery(params: {
  id: string;
  selection: SelectionConfig<PlatformSecretDefinitionSelect>;
}): Promise<any> {
  const args = buildSelectionArgs<PlatformSecretDefinitionSelect>(params.selection);
  return getClient()
    .platformSecretDefinition.findOne({
      id: params.id,
      select: args.select,
    })
    .unwrap();
}
/**
 * Global secret name registry — declares which secrets the platform recognizes. Actual values live in app_secrets.
 *
 * @example
 * ```ts
 * await prefetchPlatformSecretDefinitionQuery(queryClient, { id: 'some-id', selection: { fields: { id: true } } });
 * ```
 */
export async function prefetchPlatformSecretDefinitionQuery<
  S extends PlatformSecretDefinitionSelect,
>(
  queryClient: QueryClient,
  params: {
    id: string;
    selection: {
      fields: S;
    } & HookStrictSelect<NoInfer<S>, PlatformSecretDefinitionSelect>;
  }
): Promise<void>;
export async function prefetchPlatformSecretDefinitionQuery(
  queryClient: QueryClient,
  params: {
    id: string;
    selection: SelectionConfig<PlatformSecretDefinitionSelect>;
  }
): Promise<void> {
  const args = buildSelectionArgs<PlatformSecretDefinitionSelect>(params.selection);
  await queryClient.prefetchQuery({
    queryKey: platformSecretDefinitionKeys.detail(params.id),
    queryFn: () =>
      getClient()
        .platformSecretDefinition.findOne({
          id: params.id,
          select: args.select,
        })
        .unwrap(),
  });
}
