/**
 * Content-addressed Merkle tree objects keyed by UUID v5 hash of data + children
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import { useQuery } from '@tanstack/react-query';
import type { UseQueryOptions, UseQueryResult, QueryClient } from '@tanstack/react-query';
import { getClient } from '../client';
import { buildListSelectionArgs } from '../selection';
import type { ListSelectionConfig } from '../selection';
import { platformFunctionGraphObjectKeys } from '../query-keys';
import type {
  PlatformFunctionGraphObjectSelect,
  PlatformFunctionGraphObjectWithRelations,
  PlatformFunctionGraphObjectFilter,
  PlatformFunctionGraphObjectOrderBy,
} from '../../orm/input-types';
import type {
  FindManyArgs,
  InferSelectResult,
  ConnectionResult,
  HookStrictSelect,
} from '../../orm/select-types';
export type {
  PlatformFunctionGraphObjectSelect,
  PlatformFunctionGraphObjectWithRelations,
  PlatformFunctionGraphObjectFilter,
  PlatformFunctionGraphObjectOrderBy,
} from '../../orm/input-types';
/** Query key factory - re-exported from query-keys.ts */
export const platformFunctionGraphObjectsQueryKey = platformFunctionGraphObjectKeys.list;
/**
 * Content-addressed Merkle tree objects keyed by UUID v5 hash of data + children
 *
 * @example
 * ```tsx
 * const { data, isLoading } = usePlatformFunctionGraphObjectsQuery({
 *   selection: {
 *     fields: { id: true, name: true },
 *     where: { name: { equalTo: "example" } },
 *     orderBy: ['CREATED_AT_DESC'],
 *     first: 10,
 *   },
 * });
 * ```
 */
export function usePlatformFunctionGraphObjectsQuery<
  S extends PlatformFunctionGraphObjectSelect,
  TData = {
    platformFunctionGraphObjects: ConnectionResult<
      InferSelectResult<PlatformFunctionGraphObjectWithRelations, S>
    >;
  },
>(
  params: {
    selection: {
      fields: S;
    } & Omit<
      ListSelectionConfig<S, PlatformFunctionGraphObjectFilter, PlatformFunctionGraphObjectOrderBy>,
      'fields'
    > &
      HookStrictSelect<NoInfer<S>, PlatformFunctionGraphObjectSelect>;
  } & Omit<
    UseQueryOptions<
      {
        platformFunctionGraphObjects: ConnectionResult<
          InferSelectResult<PlatformFunctionGraphObjectWithRelations, S>
        >;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function usePlatformFunctionGraphObjectsQuery(
  params: {
    selection: ListSelectionConfig<
      PlatformFunctionGraphObjectSelect,
      PlatformFunctionGraphObjectFilter,
      PlatformFunctionGraphObjectOrderBy
    >;
  } & Omit<UseQueryOptions<any, Error, any, any>, 'queryKey' | 'queryFn'>
) {
  const args = buildListSelectionArgs<
    PlatformFunctionGraphObjectSelect,
    PlatformFunctionGraphObjectFilter,
    PlatformFunctionGraphObjectOrderBy
  >(params.selection);
  const { selection: _selection, ...queryOptions } = params ?? {};
  void _selection;
  return useQuery({
    queryKey: platformFunctionGraphObjectKeys.list(args),
    queryFn: () => getClient().platformFunctionGraphObject.findMany(args).unwrap(),
    ...queryOptions,
  });
}
/**
 * Content-addressed Merkle tree objects keyed by UUID v5 hash of data + children
 *
 * @example
 * ```ts
 * const data = await fetchPlatformFunctionGraphObjectsQuery({
 *   selection: {
 *     fields: { id: true },
 *     first: 10,
 *   },
 * });
 * ```
 */
export async function fetchPlatformFunctionGraphObjectsQuery<
  S extends PlatformFunctionGraphObjectSelect,
>(params: {
  selection: {
    fields: S;
  } & Omit<
    ListSelectionConfig<S, PlatformFunctionGraphObjectFilter, PlatformFunctionGraphObjectOrderBy>,
    'fields'
  > &
    HookStrictSelect<NoInfer<S>, PlatformFunctionGraphObjectSelect>;
}): Promise<{
  platformFunctionGraphObjects: ConnectionResult<
    InferSelectResult<PlatformFunctionGraphObjectWithRelations, S>
  >;
}>;
export async function fetchPlatformFunctionGraphObjectsQuery(params: {
  selection: ListSelectionConfig<
    PlatformFunctionGraphObjectSelect,
    PlatformFunctionGraphObjectFilter,
    PlatformFunctionGraphObjectOrderBy
  >;
}) {
  const args = buildListSelectionArgs<
    PlatformFunctionGraphObjectSelect,
    PlatformFunctionGraphObjectFilter,
    PlatformFunctionGraphObjectOrderBy
  >(params.selection);
  return getClient().platformFunctionGraphObject.findMany(args).unwrap();
}
/**
 * Content-addressed Merkle tree objects keyed by UUID v5 hash of data + children
 *
 * @example
 * ```ts
 * await prefetchPlatformFunctionGraphObjectsQuery(queryClient, { selection: { fields: { id: true }, first: 10 } });
 * ```
 */
export async function prefetchPlatformFunctionGraphObjectsQuery<
  S extends PlatformFunctionGraphObjectSelect,
>(
  queryClient: QueryClient,
  params: {
    selection: {
      fields: S;
    } & Omit<
      ListSelectionConfig<S, PlatformFunctionGraphObjectFilter, PlatformFunctionGraphObjectOrderBy>,
      'fields'
    > &
      HookStrictSelect<NoInfer<S>, PlatformFunctionGraphObjectSelect>;
  }
): Promise<void>;
export async function prefetchPlatformFunctionGraphObjectsQuery(
  queryClient: QueryClient,
  params: {
    selection: ListSelectionConfig<
      PlatformFunctionGraphObjectSelect,
      PlatformFunctionGraphObjectFilter,
      PlatformFunctionGraphObjectOrderBy
    >;
  }
): Promise<void> {
  const args = buildListSelectionArgs<
    PlatformFunctionGraphObjectSelect,
    PlatformFunctionGraphObjectFilter,
    PlatformFunctionGraphObjectOrderBy
  >(params.selection);
  await queryClient.prefetchQuery({
    queryKey: platformFunctionGraphObjectKeys.list(args),
    queryFn: () => getClient().platformFunctionGraphObject.findMany(args).unwrap(),
  });
}
