/**
 * List query hook for PlatformComputeLog
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import type { QueryClient,UseQueryOptions, UseQueryResult } from '@tanstack/react-query';
import { useQuery } from '@tanstack/react-query';

import type {
  PlatformComputeLogFilter,
  PlatformComputeLogOrderBy,
  PlatformComputeLogSelect,
  PlatformComputeLogWithRelations,
} from '../../orm/input-types';
import type {
  ConnectionResult,
  HookStrictSelect,
  InferSelectResult,
} from '../../orm/select-types';
import { getClient } from '../client';
import { platformComputeLogKeys } from '../query-keys';
import type { ListSelectionConfig } from '../selection';
import { buildListSelectionArgs } from '../selection';
export type {
  PlatformComputeLogFilter,
  PlatformComputeLogOrderBy,
  PlatformComputeLogSelect,
  PlatformComputeLogWithRelations,
} from '../../orm/input-types';
/** Query key factory - re-exported from query-keys.ts */
export const platformComputeLogsQueryKey = platformComputeLogKeys.list;
/**
 * Query hook for fetching PlatformComputeLog list
 *
 * @example
 * ```tsx
 * const { data, isLoading } = usePlatformComputeLogsQuery({
 *   selection: {
 *     fields: { id: true, name: true },
 *     where: { name: { equalTo: "example" } },
 *     orderBy: ['CREATED_AT_DESC'],
 *     first: 10,
 *   },
 * });
 * ```
 */
export function usePlatformComputeLogsQuery<
  S extends PlatformComputeLogSelect,
  TData = {
    platformComputeLogs: ConnectionResult<InferSelectResult<PlatformComputeLogWithRelations, S>>;
  },
>(
  params: {
    selection: {
      fields: S;
    } & Omit<
      ListSelectionConfig<S, PlatformComputeLogFilter, PlatformComputeLogOrderBy>,
      'fields'
    > &
      HookStrictSelect<NoInfer<S>, PlatformComputeLogSelect>;
  } & Omit<
    UseQueryOptions<
      {
        platformComputeLogs: ConnectionResult<
          InferSelectResult<PlatformComputeLogWithRelations, S>
        >;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function usePlatformComputeLogsQuery(
  params: {
    selection: ListSelectionConfig<
      PlatformComputeLogSelect,
      PlatformComputeLogFilter,
      PlatformComputeLogOrderBy
    >;
  } & Omit<UseQueryOptions<any, Error, any, any>, 'queryKey' | 'queryFn'>
) {
  const args = buildListSelectionArgs<
    PlatformComputeLogSelect,
    PlatformComputeLogFilter,
    PlatformComputeLogOrderBy
  >(params.selection);
  const { selection: _selection, ...queryOptions } = params ?? {};
  void _selection;
  return useQuery({
    queryKey: platformComputeLogKeys.list(args),
    queryFn: () => getClient().platformComputeLog.findMany(args).unwrap(),
    ...queryOptions,
  });
}
/**
 * Fetch PlatformComputeLog list without React hooks
 *
 * @example
 * ```ts
 * const data = await fetchPlatformComputeLogsQuery({
 *   selection: {
 *     fields: { id: true },
 *     first: 10,
 *   },
 * });
 * ```
 */
export async function fetchPlatformComputeLogsQuery<S extends PlatformComputeLogSelect>(params: {
  selection: {
    fields: S;
  } & Omit<ListSelectionConfig<S, PlatformComputeLogFilter, PlatformComputeLogOrderBy>, 'fields'> &
    HookStrictSelect<NoInfer<S>, PlatformComputeLogSelect>;
}): Promise<{
  platformComputeLogs: ConnectionResult<InferSelectResult<PlatformComputeLogWithRelations, S>>;
}>;
export async function fetchPlatformComputeLogsQuery(params: {
  selection: ListSelectionConfig<
    PlatformComputeLogSelect,
    PlatformComputeLogFilter,
    PlatformComputeLogOrderBy
  >;
}) {
  const args = buildListSelectionArgs<
    PlatformComputeLogSelect,
    PlatformComputeLogFilter,
    PlatformComputeLogOrderBy
  >(params.selection);
  return getClient().platformComputeLog.findMany(args).unwrap();
}
/**
 * Prefetch PlatformComputeLog list for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchPlatformComputeLogsQuery(queryClient, { selection: { fields: { id: true }, first: 10 } });
 * ```
 */
export async function prefetchPlatformComputeLogsQuery<S extends PlatformComputeLogSelect>(
  queryClient: QueryClient,
  params: {
    selection: {
      fields: S;
    } & Omit<
      ListSelectionConfig<S, PlatformComputeLogFilter, PlatformComputeLogOrderBy>,
      'fields'
    > &
      HookStrictSelect<NoInfer<S>, PlatformComputeLogSelect>;
  }
): Promise<void>;
export async function prefetchPlatformComputeLogsQuery(
  queryClient: QueryClient,
  params: {
    selection: ListSelectionConfig<
      PlatformComputeLogSelect,
      PlatformComputeLogFilter,
      PlatformComputeLogOrderBy
    >;
  }
): Promise<void> {
  const args = buildListSelectionArgs<
    PlatformComputeLogSelect,
    PlatformComputeLogFilter,
    PlatformComputeLogOrderBy
  >(params.selection);
  await queryClient.prefetchQuery({
    queryKey: platformComputeLogKeys.list(args),
    queryFn: () => getClient().platformComputeLog.findMany(args).unwrap(),
  });
}
