/**
 * Custom query hook for platformReadFunctionGraph
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import type { QueryClient,UseQueryOptions, UseQueryResult } from '@tanstack/react-query';
import { useQuery } from '@tanstack/react-query';

import type { PlatformReadFunctionGraphVariables } from '../../orm/query';
import { getClient } from '../client';
import { customQueryKeys } from '../query-keys';
export type { PlatformReadFunctionGraphVariables } from '../../orm/query';
/** Query key factory - re-exported from query-keys.ts */
export const platformReadFunctionGraphQueryKey = customQueryKeys.platformReadFunctionGraph;
/**
 * Query hook for platformReadFunctionGraph
 *
 * @example
 * ```tsx
 * const { data, isLoading } = usePlatformReadFunctionGraphQuery({ variables: { graphId } });
 *
 * if (data?.platformReadFunctionGraph) {
 *   console.log(data.platformReadFunctionGraph);
 * }
 * ```
 */
export function usePlatformReadFunctionGraphQuery<
  TData = {
    platformReadFunctionGraph: unknown | null;
  },
>(
  params?: {
    variables?: PlatformReadFunctionGraphVariables;
  } & Omit<
    UseQueryOptions<
      {
        platformReadFunctionGraph: unknown | null;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function usePlatformReadFunctionGraphQuery<
  TData = {
    platformReadFunctionGraph: unknown | null;
  },
>(
  params?: {
    variables?: PlatformReadFunctionGraphVariables;
  } & Omit<
    UseQueryOptions<
      {
        platformReadFunctionGraph: unknown | null;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData> {
  const variables = params?.variables ?? {};
  const { variables: _variables, ...queryOptions } = params ?? {};
  void _variables;
  return useQuery({
    queryKey: platformReadFunctionGraphQueryKey(variables),
    queryFn: () => getClient().query.platformReadFunctionGraph(variables).unwrap(),
    ...queryOptions,
  });
}
/**
 * Fetch platformReadFunctionGraph without React hooks
 *
 * @example
 * ```ts
 * const data = await fetchPlatformReadFunctionGraphQuery({ variables: { graphId } });
 * ```
 */
export async function fetchPlatformReadFunctionGraphQuery(params?: {
  variables?: PlatformReadFunctionGraphVariables;
}) {
  const variables = params?.variables ?? {};
  return getClient().query.platformReadFunctionGraph(variables).unwrap();
}
/**
 * Prefetch platformReadFunctionGraph for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchPlatformReadFunctionGraphQuery(queryClient, { variables: { graphId } });
 * ```
 */
export async function prefetchPlatformReadFunctionGraphQuery(
  queryClient: QueryClient,
  params?: {
    variables?: PlatformReadFunctionGraphVariables;
  }
): Promise<void> {
  const variables = params?.variables ?? {};
  await queryClient.prefetchQuery({
    queryKey: platformReadFunctionGraphQueryKey(variables),
    queryFn: () => getClient().query.platformReadFunctionGraph(variables).unwrap(),
  });
}
