/**
 * Single item query hook for PlatformUsageDaily
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import type { QueryClient,UseQueryOptions, UseQueryResult } from '@tanstack/react-query';
import { useQuery } from '@tanstack/react-query';

import type {
  PlatformUsageDailySelect,
  PlatformUsageDailyWithRelations,
} from '../../orm/input-types';
import type { HookStrictSelect,InferSelectResult } from '../../orm/select-types';
import { getClient } from '../client';
import { platformUsageDailyKeys } from '../query-keys';
import type { SelectionConfig } from '../selection';
import { buildSelectionArgs } from '../selection';
export type {
  PlatformUsageDailySelect,
  PlatformUsageDailyWithRelations,
} from '../../orm/input-types';
/** Query key factory - re-exported from query-keys.ts */
export const platformUsageDailyQueryKey = platformUsageDailyKeys.detail;
/**
 * Query hook for fetching a single PlatformUsageDaily
 *
 * @example
 * ```tsx
 * const { data, isLoading } = usePlatformUsageDailyQuery({
 *   id: 'some-id',
 *   selection: { fields: { id: true, name: true } },
 * });
 * ```
 */
export function usePlatformUsageDailyQuery<
  S extends PlatformUsageDailySelect,
  TData = {
    platformUsageDaily: InferSelectResult<PlatformUsageDailyWithRelations, S> | null;
  },
>(
  params: {
    id: string;
    selection: {
      fields: S;
    } & HookStrictSelect<NoInfer<S>, PlatformUsageDailySelect>;
  } & Omit<
    UseQueryOptions<
      {
        platformUsageDaily: InferSelectResult<PlatformUsageDailyWithRelations, S> | null;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function usePlatformUsageDailyQuery(
  params: {
    id: string;
    selection: SelectionConfig<PlatformUsageDailySelect>;
  } & Omit<UseQueryOptions<any, Error, any, any>, 'queryKey' | 'queryFn'>
) {
  const args = buildSelectionArgs<PlatformUsageDailySelect>(params.selection);
  const { selection: _selection, ...queryOptions } = params ?? {};
  void _selection;
  return useQuery({
    queryKey: platformUsageDailyKeys.detail(params.id),
    queryFn: () =>
      getClient()
        .platformUsageDaily.findOne({
          id: params.id,
          select: args.select,
        })
        .unwrap(),
    ...queryOptions,
  });
}
/**
 * Fetch a single PlatformUsageDaily without React hooks
 *
 * @example
 * ```ts
 * const data = await fetchPlatformUsageDailyQuery({
 *   id: 'some-id',
 *   selection: { fields: { id: true } },
 * });
 * ```
 */
export async function fetchPlatformUsageDailyQuery<S extends PlatformUsageDailySelect>(params: {
  id: string;
  selection: {
    fields: S;
  } & HookStrictSelect<NoInfer<S>, PlatformUsageDailySelect>;
}): Promise<{
  platformUsageDaily: InferSelectResult<PlatformUsageDailyWithRelations, S> | null;
}>;
export async function fetchPlatformUsageDailyQuery(params: {
  id: string;
  selection: SelectionConfig<PlatformUsageDailySelect>;
}): Promise<any> {
  const args = buildSelectionArgs<PlatformUsageDailySelect>(params.selection);
  return getClient()
    .platformUsageDaily.findOne({
      id: params.id,
      select: args.select,
    })
    .unwrap();
}
/**
 * Prefetch a single PlatformUsageDaily for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchPlatformUsageDailyQuery(queryClient, { id: 'some-id', selection: { fields: { id: true } } });
 * ```
 */
export async function prefetchPlatformUsageDailyQuery<S extends PlatformUsageDailySelect>(
  queryClient: QueryClient,
  params: {
    id: string;
    selection: {
      fields: S;
    } & HookStrictSelect<NoInfer<S>, PlatformUsageDailySelect>;
  }
): Promise<void>;
export async function prefetchPlatformUsageDailyQuery(
  queryClient: QueryClient,
  params: {
    id: string;
    selection: SelectionConfig<PlatformUsageDailySelect>;
  }
): Promise<void> {
  const args = buildSelectionArgs<PlatformUsageDailySelect>(params.selection);
  await queryClient.prefetchQuery({
    queryKey: platformUsageDailyKeys.detail(params.id),
    queryFn: () =>
      getClient()
        .platformUsageDaily.findOne({
          id: params.id,
          select: args.select,
        })
        .unwrap(),
  });
}
