/**
 * Named stores — one per version-controlled tree (e.g. one graph, one definition set)
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import type { QueryClient,UseQueryOptions, UseQueryResult } from '@tanstack/react-query';
import { useQuery } from '@tanstack/react-query';

import type {
  PlatformFunctionGraphStoreSelect,
  PlatformFunctionGraphStoreWithRelations,
} from '../../orm/input-types';
import type { HookStrictSelect,InferSelectResult } from '../../orm/select-types';
import { getClient } from '../client';
import { platformFunctionGraphStoreKeys } from '../query-keys';
import type { SelectionConfig } from '../selection';
import { buildSelectionArgs } from '../selection';
export type {
  PlatformFunctionGraphStoreSelect,
  PlatformFunctionGraphStoreWithRelations,
} from '../../orm/input-types';
/** Query key factory - re-exported from query-keys.ts */
export const platformFunctionGraphStoreQueryKey = platformFunctionGraphStoreKeys.detail;
/**
 * Named stores — one per version-controlled tree (e.g. one graph, one definition set)
 *
 * @example
 * ```tsx
 * const { data, isLoading } = usePlatformFunctionGraphStoreQuery({
 *   id: 'some-id',
 *   selection: { fields: { id: true, name: true } },
 * });
 * ```
 */
export function usePlatformFunctionGraphStoreQuery<
  S extends PlatformFunctionGraphStoreSelect,
  TData = {
    platformFunctionGraphStore: InferSelectResult<
      PlatformFunctionGraphStoreWithRelations,
      S
    > | null;
  },
>(
  params: {
    id: string;
    selection: {
      fields: S;
    } & HookStrictSelect<NoInfer<S>, PlatformFunctionGraphStoreSelect>;
  } & Omit<
    UseQueryOptions<
      {
        platformFunctionGraphStore: InferSelectResult<
          PlatformFunctionGraphStoreWithRelations,
          S
        > | null;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function usePlatformFunctionGraphStoreQuery(
  params: {
    id: string;
    selection: SelectionConfig<PlatformFunctionGraphStoreSelect>;
  } & Omit<UseQueryOptions<any, Error, any, any>, 'queryKey' | 'queryFn'>
) {
  const args = buildSelectionArgs<PlatformFunctionGraphStoreSelect>(params.selection);
  const { selection: _selection, ...queryOptions } = params ?? {};
  void _selection;
  return useQuery({
    queryKey: platformFunctionGraphStoreKeys.detail(params.id),
    queryFn: () =>
      getClient()
        .platformFunctionGraphStore.findOne({
          id: params.id,
          select: args.select,
        })
        .unwrap(),
    ...queryOptions,
  });
}
/**
 * Named stores — one per version-controlled tree (e.g. one graph, one definition set)
 *
 * @example
 * ```ts
 * const data = await fetchPlatformFunctionGraphStoreQuery({
 *   id: 'some-id',
 *   selection: { fields: { id: true } },
 * });
 * ```
 */
export async function fetchPlatformFunctionGraphStoreQuery<
  S extends PlatformFunctionGraphStoreSelect,
>(params: {
  id: string;
  selection: {
    fields: S;
  } & HookStrictSelect<NoInfer<S>, PlatformFunctionGraphStoreSelect>;
}): Promise<{
  platformFunctionGraphStore: InferSelectResult<PlatformFunctionGraphStoreWithRelations, S> | null;
}>;
export async function fetchPlatformFunctionGraphStoreQuery(params: {
  id: string;
  selection: SelectionConfig<PlatformFunctionGraphStoreSelect>;
}): Promise<any> {
  const args = buildSelectionArgs<PlatformFunctionGraphStoreSelect>(params.selection);
  return getClient()
    .platformFunctionGraphStore.findOne({
      id: params.id,
      select: args.select,
    })
    .unwrap();
}
/**
 * Named stores — one per version-controlled tree (e.g. one graph, one definition set)
 *
 * @example
 * ```ts
 * await prefetchPlatformFunctionGraphStoreQuery(queryClient, { id: 'some-id', selection: { fields: { id: true } } });
 * ```
 */
export async function prefetchPlatformFunctionGraphStoreQuery<
  S extends PlatformFunctionGraphStoreSelect,
>(
  queryClient: QueryClient,
  params: {
    id: string;
    selection: {
      fields: S;
    } & HookStrictSelect<NoInfer<S>, PlatformFunctionGraphStoreSelect>;
  }
): Promise<void>;
export async function prefetchPlatformFunctionGraphStoreQuery(
  queryClient: QueryClient,
  params: {
    id: string;
    selection: SelectionConfig<PlatformFunctionGraphStoreSelect>;
  }
): Promise<void> {
  const args = buildSelectionArgs<PlatformFunctionGraphStoreSelect>(params.selection);
  await queryClient.prefetchQuery({
    queryKey: platformFunctionGraphStoreKeys.detail(params.id),
    queryFn: () =>
      getClient()
        .platformFunctionGraphStore.findOne({
          id: params.id,
          select: args.select,
        })
        .unwrap(),
  });
}
