/**
 * Ephemeral execution state for flow graph evaluation
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import type { QueryClient,UseQueryOptions, UseQueryResult } from '@tanstack/react-query';
import { useQuery } from '@tanstack/react-query';

import type {
  PlatformFunctionGraphExecutionSelect,
  PlatformFunctionGraphExecutionWithRelations,
} from '../../orm/input-types';
import type { HookStrictSelect,InferSelectResult } from '../../orm/select-types';
import { getClient } from '../client';
import { platformFunctionGraphExecutionKeys } from '../query-keys';
import type { SelectionConfig } from '../selection';
import { buildSelectionArgs } from '../selection';
export type {
  PlatformFunctionGraphExecutionSelect,
  PlatformFunctionGraphExecutionWithRelations,
} from '../../orm/input-types';
/** Query key factory - re-exported from query-keys.ts */
export const platformFunctionGraphExecutionQueryKey = platformFunctionGraphExecutionKeys.detail;
/**
 * Ephemeral execution state for flow graph evaluation
 *
 * @example
 * ```tsx
 * const { data, isLoading } = usePlatformFunctionGraphExecutionQuery({
 *   id: 'some-id',
 *   selection: { fields: { id: true, name: true } },
 * });
 * ```
 */
export function usePlatformFunctionGraphExecutionQuery<
  S extends PlatformFunctionGraphExecutionSelect,
  TData = {
    platformFunctionGraphExecution: InferSelectResult<
      PlatformFunctionGraphExecutionWithRelations,
      S
    > | null;
  },
>(
  params: {
    id: string;
    selection: {
      fields: S;
    } & HookStrictSelect<NoInfer<S>, PlatformFunctionGraphExecutionSelect>;
  } & Omit<
    UseQueryOptions<
      {
        platformFunctionGraphExecution: InferSelectResult<
          PlatformFunctionGraphExecutionWithRelations,
          S
        > | null;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function usePlatformFunctionGraphExecutionQuery(
  params: {
    id: string;
    selection: SelectionConfig<PlatformFunctionGraphExecutionSelect>;
  } & Omit<UseQueryOptions<any, Error, any, any>, 'queryKey' | 'queryFn'>
) {
  const args = buildSelectionArgs<PlatformFunctionGraphExecutionSelect>(params.selection);
  const { selection: _selection, ...queryOptions } = params ?? {};
  void _selection;
  return useQuery({
    queryKey: platformFunctionGraphExecutionKeys.detail(params.id),
    queryFn: () =>
      getClient()
        .platformFunctionGraphExecution.findOne({
          id: params.id,
          select: args.select,
        })
        .unwrap(),
    ...queryOptions,
  });
}
/**
 * Ephemeral execution state for flow graph evaluation
 *
 * @example
 * ```ts
 * const data = await fetchPlatformFunctionGraphExecutionQuery({
 *   id: 'some-id',
 *   selection: { fields: { id: true } },
 * });
 * ```
 */
export async function fetchPlatformFunctionGraphExecutionQuery<
  S extends PlatformFunctionGraphExecutionSelect,
>(params: {
  id: string;
  selection: {
    fields: S;
  } & HookStrictSelect<NoInfer<S>, PlatformFunctionGraphExecutionSelect>;
}): Promise<{
  platformFunctionGraphExecution: InferSelectResult<
    PlatformFunctionGraphExecutionWithRelations,
    S
  > | null;
}>;
export async function fetchPlatformFunctionGraphExecutionQuery(params: {
  id: string;
  selection: SelectionConfig<PlatformFunctionGraphExecutionSelect>;
}): Promise<any> {
  const args = buildSelectionArgs<PlatformFunctionGraphExecutionSelect>(params.selection);
  return getClient()
    .platformFunctionGraphExecution.findOne({
      id: params.id,
      select: args.select,
    })
    .unwrap();
}
/**
 * Ephemeral execution state for flow graph evaluation
 *
 * @example
 * ```ts
 * await prefetchPlatformFunctionGraphExecutionQuery(queryClient, { id: 'some-id', selection: { fields: { id: true } } });
 * ```
 */
export async function prefetchPlatformFunctionGraphExecutionQuery<
  S extends PlatformFunctionGraphExecutionSelect,
>(
  queryClient: QueryClient,
  params: {
    id: string;
    selection: {
      fields: S;
    } & HookStrictSelect<NoInfer<S>, PlatformFunctionGraphExecutionSelect>;
  }
): Promise<void>;
export async function prefetchPlatformFunctionGraphExecutionQuery(
  queryClient: QueryClient,
  params: {
    id: string;
    selection: SelectionConfig<PlatformFunctionGraphExecutionSelect>;
  }
): Promise<void> {
  const args = buildSelectionArgs<PlatformFunctionGraphExecutionSelect>(params.selection);
  await queryClient.prefetchQuery({
    queryKey: platformFunctionGraphExecutionKeys.detail(params.id),
    queryFn: () =>
      getClient()
        .platformFunctionGraphExecution.findOne({
          id: params.id,
          select: args.select,
        })
        .unwrap(),
  });
}
