/**
 * Flow graph definitions — FBP graphs stored in the dedicated graph Merkle store
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import type { QueryClient,UseQueryOptions, UseQueryResult } from '@tanstack/react-query';
import { useQuery } from '@tanstack/react-query';

import type {
  PlatformFunctionGraphFilter,
  PlatformFunctionGraphOrderBy,
  PlatformFunctionGraphSelect,
  PlatformFunctionGraphWithRelations,
} from '../../orm/input-types';
import type {
  ConnectionResult,
  HookStrictSelect,
  InferSelectResult,
} from '../../orm/select-types';
import { getClient } from '../client';
import { platformFunctionGraphKeys } from '../query-keys';
import type { ListSelectionConfig } from '../selection';
import { buildListSelectionArgs } from '../selection';
export type {
  PlatformFunctionGraphFilter,
  PlatformFunctionGraphOrderBy,
  PlatformFunctionGraphSelect,
  PlatformFunctionGraphWithRelations,
} from '../../orm/input-types';
/** Query key factory - re-exported from query-keys.ts */
export const platformFunctionGraphsQueryKey = platformFunctionGraphKeys.list;
/**
 * Flow graph definitions — FBP graphs stored in the dedicated graph Merkle store
 *
 * @example
 * ```tsx
 * const { data, isLoading } = usePlatformFunctionGraphsQuery({
 *   selection: {
 *     fields: { id: true, name: true },
 *     where: { name: { equalTo: "example" } },
 *     orderBy: ['CREATED_AT_DESC'],
 *     first: 10,
 *   },
 * });
 * ```
 */
export function usePlatformFunctionGraphsQuery<
  S extends PlatformFunctionGraphSelect,
  TData = {
    platformFunctionGraphs: ConnectionResult<
      InferSelectResult<PlatformFunctionGraphWithRelations, S>
    >;
  },
>(
  params: {
    selection: {
      fields: S;
    } & Omit<
      ListSelectionConfig<S, PlatformFunctionGraphFilter, PlatformFunctionGraphOrderBy>,
      'fields'
    > &
      HookStrictSelect<NoInfer<S>, PlatformFunctionGraphSelect>;
  } & Omit<
    UseQueryOptions<
      {
        platformFunctionGraphs: ConnectionResult<
          InferSelectResult<PlatformFunctionGraphWithRelations, S>
        >;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function usePlatformFunctionGraphsQuery(
  params: {
    selection: ListSelectionConfig<
      PlatformFunctionGraphSelect,
      PlatformFunctionGraphFilter,
      PlatformFunctionGraphOrderBy
    >;
  } & Omit<UseQueryOptions<any, Error, any, any>, 'queryKey' | 'queryFn'>
) {
  const args = buildListSelectionArgs<
    PlatformFunctionGraphSelect,
    PlatformFunctionGraphFilter,
    PlatformFunctionGraphOrderBy
  >(params.selection);
  const { selection: _selection, ...queryOptions } = params ?? {};
  void _selection;
  return useQuery({
    queryKey: platformFunctionGraphKeys.list(args),
    queryFn: () => getClient().platformFunctionGraph.findMany(args).unwrap(),
    ...queryOptions,
  });
}
/**
 * Flow graph definitions — FBP graphs stored in the dedicated graph Merkle store
 *
 * @example
 * ```ts
 * const data = await fetchPlatformFunctionGraphsQuery({
 *   selection: {
 *     fields: { id: true },
 *     first: 10,
 *   },
 * });
 * ```
 */
export async function fetchPlatformFunctionGraphsQuery<
  S extends PlatformFunctionGraphSelect,
>(params: {
  selection: {
    fields: S;
  } & Omit<
    ListSelectionConfig<S, PlatformFunctionGraphFilter, PlatformFunctionGraphOrderBy>,
    'fields'
  > &
    HookStrictSelect<NoInfer<S>, PlatformFunctionGraphSelect>;
}): Promise<{
  platformFunctionGraphs: ConnectionResult<
    InferSelectResult<PlatformFunctionGraphWithRelations, S>
  >;
}>;
export async function fetchPlatformFunctionGraphsQuery(params: {
  selection: ListSelectionConfig<
    PlatformFunctionGraphSelect,
    PlatformFunctionGraphFilter,
    PlatformFunctionGraphOrderBy
  >;
}) {
  const args = buildListSelectionArgs<
    PlatformFunctionGraphSelect,
    PlatformFunctionGraphFilter,
    PlatformFunctionGraphOrderBy
  >(params.selection);
  return getClient().platformFunctionGraph.findMany(args).unwrap();
}
/**
 * Flow graph definitions — FBP graphs stored in the dedicated graph Merkle store
 *
 * @example
 * ```ts
 * await prefetchPlatformFunctionGraphsQuery(queryClient, { selection: { fields: { id: true }, first: 10 } });
 * ```
 */
export async function prefetchPlatformFunctionGraphsQuery<S extends PlatformFunctionGraphSelect>(
  queryClient: QueryClient,
  params: {
    selection: {
      fields: S;
    } & Omit<
      ListSelectionConfig<S, PlatformFunctionGraphFilter, PlatformFunctionGraphOrderBy>,
      'fields'
    > &
      HookStrictSelect<NoInfer<S>, PlatformFunctionGraphSelect>;
  }
): Promise<void>;
export async function prefetchPlatformFunctionGraphsQuery(
  queryClient: QueryClient,
  params: {
    selection: ListSelectionConfig<
      PlatformFunctionGraphSelect,
      PlatformFunctionGraphFilter,
      PlatformFunctionGraphOrderBy
    >;
  }
): Promise<void> {
  const args = buildListSelectionArgs<
    PlatformFunctionGraphSelect,
    PlatformFunctionGraphFilter,
    PlatformFunctionGraphOrderBy
  >(params.selection);
  await queryClient.prefetchQuery({
    queryKey: platformFunctionGraphKeys.list(args),
    queryFn: () => getClient().platformFunctionGraph.findMany(args).unwrap(),
  });
}
