/**
 * CLI commands for Object
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { CLIOptions, Inquirerer, extractFirst } from 'inquirerer';
import { getClient } from '../../executor';
import { coerceAnswers, parseFindFirstArgs, parseFindManyArgs, stripUndefined } from '../../utils';
import type { FieldSchema } from '../../utils';
import type {
  CreateObjectInput,
  ObjectPatch,
  ObjectSelect,
  ObjectFilter,
  ObjectOrderBy,
} from '../../../orm/input-types';
import type { FindManyArgs, FindFirstArgs } from '../../../orm/select-types';
const fieldSchema: FieldSchema = {
  createdAt: 'string',
  data: 'json',
  databaseId: 'uuid',
  id: 'uuid',
  kids: 'uuid',
  ktree: 'string',
};
const usage =
  '\nobject <command>\n\nCommands:\n  list                  List object records\n  find-first            Find first matching object record\n  get                   Get a object by ID\n  create                Create a new object\n  update                Update an existing object\n  delete                Delete a object\n\nList Options:\n  --limit <n>           Max number of records to return (forward pagination)\n  --last <n>            Number of records from the end (backward pagination)\n  --after <cursor>      Cursor for forward pagination\n  --before <cursor>     Cursor for backward pagination\n  --offset <n>          Number of records to skip\n  --select <fields>     Comma-separated list of fields to return\n  --where.<field>.<op>  Filter (dot-notation, e.g. --where.name.equalTo foo)\n  --condition.<f>.<op>  Condition filter (dot-notation)\n  --orderBy <values>    Comma-separated ordering values (e.g. NAME_ASC,CREATED_AT_DESC)\n\nFind-First Options:\n  --select <fields>     Comma-separated list of fields to return\n  --where.<field>.<op>  Filter (dot-notation, e.g. --where.status.equalTo active)\n  --condition.<f>.<op>  Condition filter (dot-notation)\n  --orderBy <values>    Comma-separated ordering values (e.g. NAME_ASC,CREATED_AT_DESC)\n\n  --help, -h            Show this help message\n';
export default async (
  argv: Partial<Record<string, unknown>>,
  prompter: Inquirerer,
  _options: CLIOptions
) => {
  if (argv.help || argv.h) {
    console.log(usage);
    process.exit(0);
  }
  const { first: subcommand, newArgv } = extractFirst(argv);
  if (!subcommand) {
    const answer = await prompter.prompt(argv, [
      {
        type: 'autocomplete',
        name: 'subcommand',
        message: 'What do you want to do?',
        options: ['list', 'find-first', 'get', 'create', 'update', 'delete'],
      },
    ]);
    return handleTableSubcommand(answer.subcommand as string, newArgv, prompter);
  }
  return handleTableSubcommand(subcommand, newArgv, prompter);
};
async function handleTableSubcommand(
  subcommand: string,
  argv: Partial<Record<string, unknown>>,
  prompter: Inquirerer
) {
  switch (subcommand) {
    case 'list':
      return handleList(argv, prompter);
    case 'find-first':
      return handleFindFirst(argv, prompter);
    case 'get':
      return handleGet(argv, prompter);
    case 'create':
      return handleCreate(argv, prompter);
    case 'update':
      return handleUpdate(argv, prompter);
    case 'delete':
      return handleDelete(argv, prompter);
    default:
      console.log(usage);
      process.exit(1);
  }
}
async function handleList(argv: Partial<Record<string, unknown>>, _prompter: Inquirerer) {
  try {
    const defaultSelect = {
      createdAt: true,
      data: true,
      databaseId: true,
      id: true,
      kids: true,
      ktree: true,
    };
    const findManyArgs = parseFindManyArgs<
      FindManyArgs<ObjectSelect, ObjectFilter, ObjectOrderBy> & {
        select: ObjectSelect;
      }
    >(argv, defaultSelect);
    const client = getClient('objects');
    const result = await client.object.findMany(findManyArgs).execute();
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error('Failed to list records.');
    if (error instanceof Error) {
      console.error(error.message);
    }
    process.exit(1);
  }
}
async function handleFindFirst(argv: Partial<Record<string, unknown>>, _prompter: Inquirerer) {
  try {
    const defaultSelect = {
      createdAt: true,
      data: true,
      databaseId: true,
      id: true,
      kids: true,
      ktree: true,
    };
    const findFirstArgs = parseFindFirstArgs<
      FindFirstArgs<ObjectSelect, ObjectFilter, ObjectOrderBy> & {
        select: ObjectSelect;
      }
    >(argv, defaultSelect);
    const client = getClient('objects');
    const result = await client.object.findFirst(findFirstArgs).execute();
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error('Failed to find record.');
    if (error instanceof Error) {
      console.error(error.message);
    }
    process.exit(1);
  }
}
async function handleGet(argv: Partial<Record<string, unknown>>, prompter: Inquirerer) {
  try {
    const answers = await prompter.prompt(argv, [
      {
        type: 'text',
        name: 'id',
        message: 'id',
        required: true,
      },
    ]);
    const client = getClient('objects');
    const result = await client.object
      .findOne({
        id: answers.id as string,
        select: {
          createdAt: true,
          data: true,
          databaseId: true,
          id: true,
          kids: true,
          ktree: true,
        },
      })
      .execute();
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error('Record not found.');
    if (error instanceof Error) {
      console.error(error.message);
    }
    process.exit(1);
  }
}
async function handleCreate(argv: Partial<Record<string, unknown>>, prompter: Inquirerer) {
  try {
    const rawAnswers = await prompter.prompt(argv, [
      {
        type: 'json',
        name: 'data',
        message: 'data',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'databaseId',
        message: 'databaseId',
        required: true,
      },
      {
        type: 'text',
        name: 'kids',
        message: 'kids',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'ktree',
        message: 'ktree',
        required: false,
        skipPrompt: true,
      },
    ]);
    const answers = coerceAnswers(rawAnswers, fieldSchema);
    const cleanedData = stripUndefined(answers, fieldSchema) as CreateObjectInput['object'];
    const client = getClient('objects');
    const result = await client.object
      .create({
        data: {
          data: cleanedData.data,
          databaseId: cleanedData.databaseId,
          kids: cleanedData.kids,
          ktree: cleanedData.ktree,
        },
        select: {
          createdAt: true,
          data: true,
          databaseId: true,
          id: true,
          kids: true,
          ktree: true,
        },
      })
      .execute();
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error('Failed to create record.');
    if (error instanceof Error) {
      console.error(error.message);
    }
    process.exit(1);
  }
}
async function handleUpdate(argv: Partial<Record<string, unknown>>, prompter: Inquirerer) {
  try {
    const rawAnswers = await prompter.prompt(argv, [
      {
        type: 'text',
        name: 'id',
        message: 'id',
        required: true,
      },
      {
        type: 'json',
        name: 'data',
        message: 'data',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'databaseId',
        message: 'databaseId',
        required: false,
      },
      {
        type: 'text',
        name: 'kids',
        message: 'kids',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'ktree',
        message: 'ktree',
        required: false,
        skipPrompt: true,
      },
    ]);
    const answers = coerceAnswers(rawAnswers, fieldSchema);
    const cleanedData = stripUndefined(answers, fieldSchema) as ObjectPatch;
    const client = getClient('objects');
    const result = await client.object
      .update({
        where: {
          id: answers.id as string,
        },
        data: {
          data: cleanedData.data,
          databaseId: cleanedData.databaseId,
          kids: cleanedData.kids,
          ktree: cleanedData.ktree,
        },
        select: {
          createdAt: true,
          data: true,
          databaseId: true,
          id: true,
          kids: true,
          ktree: true,
        },
      })
      .execute();
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error('Failed to update record.');
    if (error instanceof Error) {
      console.error(error.message);
    }
    process.exit(1);
  }
}
async function handleDelete(argv: Partial<Record<string, unknown>>, prompter: Inquirerer) {
  try {
    const rawAnswers = await prompter.prompt(argv, [
      {
        type: 'text',
        name: 'id',
        message: 'id',
        required: true,
      },
    ]);
    const answers = coerceAnswers(rawAnswers, fieldSchema);
    const client = getClient('objects');
    const result = await client.object
      .delete({
        where: {
          id: answers.id as string,
        },
        select: {
          id: true,
        },
      })
      .execute();
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error('Failed to delete record.');
    if (error instanceof Error) {
      console.error(error.message);
    }
    process.exit(1);
  }
}
