/**
 * PlatformConfig model for ORM client
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { OrmClient } from '../client';
import type {
  CreatePlatformConfigInput,
  PlatformConfigFilter,
  PlatformConfigOrderBy,
  PlatformConfigPatch,
  PlatformConfigSelect,
  PlatformConfigWithRelations,
} from '../input-types';
import { connectionFieldsMap } from '../input-types';
import {
  buildCreateDocument,
  buildDeleteByPkDocument,
  buildFindFirstDocument,
  buildFindManyDocument,
  buildUpdateByPkDocument,
  QueryBuilder,
} from '../query-builder';
import type {
  ConnectionResult,
  CreateArgs,
  DeleteArgs,
  FindFirstArgs,
  FindManyArgs,
  InferSelectResult,
  StrictSelect,
  UpdateArgs,
} from '../select-types';
export class PlatformConfigModel {
  constructor(private client: OrmClient) {}
  findMany<S extends PlatformConfigSelect>(
    args: FindManyArgs<S, PlatformConfigFilter, PlatformConfigOrderBy> & {
      select: S;
    } & StrictSelect<S, PlatformConfigSelect>
  ): QueryBuilder<{
    platformConfigs: ConnectionResult<InferSelectResult<PlatformConfigWithRelations, S>>;
  }> {
    const { document, variables } = buildFindManyDocument(
      'PlatformConfig',
      'platformConfigs',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
        first: args?.first,
        last: args?.last,
        after: args?.after,
        before: args?.before,
        offset: args?.offset,
      },
      'PlatformConfigFilter',
      'PlatformConfigOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'PlatformConfig',
      fieldName: 'platformConfigs',
      document,
      variables,
    });
  }
  findFirst<S extends PlatformConfigSelect>(
    args: FindFirstArgs<S, PlatformConfigFilter, PlatformConfigOrderBy> & {
      select: S;
    } & StrictSelect<S, PlatformConfigSelect>
  ): QueryBuilder<{
    platformConfig: InferSelectResult<PlatformConfigWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindFirstDocument(
      'PlatformConfig',
      'platformConfigs',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
      },
      'PlatformConfigFilter',
      'PlatformConfigOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'PlatformConfig',
      fieldName: 'platformConfig',
      document,
      variables,
      transform: (data: {
        platformConfigs?: {
          nodes?: InferSelectResult<PlatformConfigWithRelations, S>[];
        };
      }) => ({
        platformConfig: data.platformConfigs?.nodes?.[0] ?? null,
      }),
    });
  }
  findOne<S extends PlatformConfigSelect>(
    args: {
      id: string;
      select: S;
    } & StrictSelect<S, PlatformConfigSelect>
  ): QueryBuilder<{
    platformConfig: InferSelectResult<PlatformConfigWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindManyDocument(
      'PlatformConfig',
      'platformConfigs',
      args.select,
      {
        where: {
          id: {
            equalTo: args.id,
          },
        },
        first: 1,
      },
      'PlatformConfigFilter',
      'PlatformConfigOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'PlatformConfig',
      fieldName: 'platformConfig',
      document,
      variables,
      transform: (data: {
        platformConfigs?: {
          nodes?: InferSelectResult<PlatformConfigWithRelations, S>[];
        };
      }) => ({
        platformConfig: data.platformConfigs?.nodes?.[0] ?? null,
      }),
    });
  }
  create<S extends PlatformConfigSelect>(
    args: CreateArgs<S, CreatePlatformConfigInput['platformConfig']> & {
      select: S;
    } & StrictSelect<S, PlatformConfigSelect>
  ): QueryBuilder<{
    createPlatformConfig: {
      platformConfig: InferSelectResult<PlatformConfigWithRelations, S>;
    };
  }> {
    const { document, variables } = buildCreateDocument(
      'PlatformConfig',
      'createPlatformConfig',
      'platformConfig',
      args.select,
      args.data,
      'CreatePlatformConfigInput',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'PlatformConfig',
      fieldName: 'createPlatformConfig',
      document,
      variables,
    });
  }
  update<S extends PlatformConfigSelect>(
    args: UpdateArgs<
      S,
      {
        id: string;
      },
      PlatformConfigPatch
    > & {
      select: S;
    } & StrictSelect<S, PlatformConfigSelect>
  ): QueryBuilder<{
    updatePlatformConfig: {
      platformConfig: InferSelectResult<PlatformConfigWithRelations, S>;
    };
  }> {
    const { document, variables } = buildUpdateByPkDocument(
      'PlatformConfig',
      'updatePlatformConfig',
      'platformConfig',
      args.select,
      args.where.id,
      args.data,
      'UpdatePlatformConfigInput',
      'id',
      'platformConfigPatch',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'PlatformConfig',
      fieldName: 'updatePlatformConfig',
      document,
      variables,
    });
  }
  delete<S extends PlatformConfigSelect>(
    args: DeleteArgs<
      {
        id: string;
      },
      S
    > & {
      select: S;
    } & StrictSelect<S, PlatformConfigSelect>
  ): QueryBuilder<{
    deletePlatformConfig: {
      platformConfig: InferSelectResult<PlatformConfigWithRelations, S>;
    };
  }> {
    const { document, variables } = buildDeleteByPkDocument(
      'PlatformConfig',
      'deletePlatformConfig',
      'platformConfig',
      {
        id: args.where.id,
      },
      'DeletePlatformConfigInput',
      args.select,
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'PlatformConfig',
      fieldName: 'deletePlatformConfig',
      document,
      variables,
    });
  }
}
