-- Revert: schemas/constructive_infra_public/tables/platform_function_definitions/indexes/platform_function_definitions_updated_at_idx


DROP INDEX "constructive_infra_public".platform_function_definitions_updated_at_idx;


