-- Revert: schemas/constructive_compute_fbp_private/tables/function_graph_execution_outputs/indexes/idx_function_graph_execution_outputs_unique_hash


DROP INDEX "constructive_compute_fbp_private".idx_function_graph_execution_outputs_unique_hash;


