-- Verify: schemas/constructive_compute_public/tables/app_function_execution_logs/indexes/app_function_execution_logs_invocation_id_created_at_idx


SELECT verify_index('constructive_compute_public.app_function_execution_logs', 'app_function_execution_logs_invocation_id_created_at_idx');


