-- Revert: schemas/constructive_infra_public/partitions/create_default_partitions

BEGIN;

DROP TABLE IF EXISTS constructive_infra_public.platform_function_invocations_default;
DROP TABLE IF EXISTS constructive_infra_public.platform_function_execution_logs_default;
DROP TABLE IF EXISTS constructive_infra_public.platform_namespace_events_default;
DROP TABLE IF EXISTS constructive_fbp_private.function_graph_executions_default;
DROP TABLE IF EXISTS constructive_fbp_private.function_graph_execution_outputs_default;

COMMIT;
