---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin
  labels:
    app: pgadmin
spec:
  type: ClusterIP
  selector:
    app: pgadmin        # must match Deployment .spec.template.metadata.labels.app
  ports:
    - name: http
      port: 80          # what Ingress will use
      targetPort: http
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-servers
data:
  servers.json: |
    {
      "Servers": {
        "1": {
          "Name": "CNPG RW",
          "Group": "Constructive",
          "Host": "postgres-cluster-rw.postgres-db.svc.cluster.local",
          "Port": 5432,
          "MaintenanceDB": "launchql",
          "Username": "postgres",
          "Password": "postgres123!",
          "SSLMode": "prefer"
        }
      }
    }

