-- Revert: schemas/constructive_compute_public/tables/platform_secret_definitions/indexes/platform_secret_definitions_updated_at_idx


DROP INDEX "constructive_compute_public".platform_secret_definitions_updated_at_idx;


