-- Revert: schemas/constructive_compute_private/tables/platform_function_graph_execution_node_states/columns/database_id/alterations/alt0000002704


COMMENT ON COLUMN "constructive_compute_private".platform_function_graph_execution_node_states.database_id IS NULL;
