-- Revert: schemas/constructive_compute_public/tables/platform_function_execution_logs/indexes/platform_function_execution_logs_invocation_id_created_at_idx


DROP INDEX "constructive_compute_public".platform_function_execution_logs_invocation_id_created_at_idx;


