-- Revert: schemas/constructive_compute_public/tables/platform_function_definitions/indexes/platform_function_definitions_created_at_idx


DROP INDEX "constructive_compute_public".platform_function_definitions_created_at_idx;


