-- Verify: schemas/constructive_compute_public/tables/platform_function_definitions/indexes/platform_function_definitions_updated_at_idx


SELECT verify_index('constructive_compute_public.platform_function_definitions', 'platform_function_definitions_updated_at_idx');


