-- Revert: schemas/constructive_memberships_public/tables/app_permission_default_grants/indexes/app_permission_default_grants_grantor_id_idx


DROP INDEX "constructive_memberships_public".app_permission_default_grants_grantor_id_idx;


