-- Revert: schemas/constructive_compute_private/tables/platform_function_graph_executions/constraints/platform_function_graph_executions_pkey/constraint


ALTER TABLE "constructive_compute_private".platform_function_graph_executions 
  DROP CONSTRAINT platform_function_graph_executions_pkey;


