/**
 * PlatformNamespace model for ORM client
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { OrmClient } from '../client';
import {
  QueryBuilder,
  buildFindManyDocument,
  buildFindFirstDocument,
  buildFindOneDocument,
  buildCreateDocument,
  buildUpdateByPkDocument,
  buildDeleteByPkDocument,
} from '../query-builder';
import type {
  ConnectionResult,
  FindManyArgs,
  FindFirstArgs,
  CreateArgs,
  UpdateArgs,
  DeleteArgs,
  InferSelectResult,
  StrictSelect,
} from '../select-types';
import type {
  PlatformNamespace,
  PlatformNamespaceWithRelations,
  PlatformNamespaceSelect,
  PlatformNamespaceFilter,
  PlatformNamespaceOrderBy,
  CreatePlatformNamespaceInput,
  UpdatePlatformNamespaceInput,
  PlatformNamespacePatch,
} from '../input-types';
import { connectionFieldsMap } from '../input-types';
export class PlatformNamespaceModel {
  constructor(private client: OrmClient) {}
  findMany<S extends PlatformNamespaceSelect>(
    args: FindManyArgs<S, PlatformNamespaceFilter, PlatformNamespaceOrderBy> & {
      select: S;
    } & StrictSelect<S, PlatformNamespaceSelect>
  ): QueryBuilder<{
    platformNamespaces: ConnectionResult<InferSelectResult<PlatformNamespaceWithRelations, S>>;
  }> {
    const { document, variables } = buildFindManyDocument(
      'PlatformNamespace',
      'platformNamespaces',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
        first: args?.first,
        last: args?.last,
        after: args?.after,
        before: args?.before,
        offset: args?.offset,
      },
      'PlatformNamespaceFilter',
      'PlatformNamespaceOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'PlatformNamespace',
      fieldName: 'platformNamespaces',
      document,
      variables,
    });
  }
  findFirst<S extends PlatformNamespaceSelect>(
    args: FindFirstArgs<S, PlatformNamespaceFilter, PlatformNamespaceOrderBy> & {
      select: S;
    } & StrictSelect<S, PlatformNamespaceSelect>
  ): QueryBuilder<{
    platformNamespace: InferSelectResult<PlatformNamespaceWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindFirstDocument(
      'PlatformNamespace',
      'platformNamespaces',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
      },
      'PlatformNamespaceFilter',
      'PlatformNamespaceOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'PlatformNamespace',
      fieldName: 'platformNamespace',
      document,
      variables,
      transform: (data: {
        platformNamespaces?: {
          nodes?: InferSelectResult<PlatformNamespaceWithRelations, S>[];
        };
      }) => ({
        platformNamespace: data.platformNamespaces?.nodes?.[0] ?? null,
      }),
    });
  }
  findOne<S extends PlatformNamespaceSelect>(
    args: {
      id: string;
      select: S;
    } & StrictSelect<S, PlatformNamespaceSelect>
  ): QueryBuilder<{
    platformNamespace: InferSelectResult<PlatformNamespaceWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindManyDocument(
      'PlatformNamespace',
      'platformNamespaces',
      args.select,
      {
        where: {
          id: {
            equalTo: args.id,
          },
        },
        first: 1,
      },
      'PlatformNamespaceFilter',
      'PlatformNamespaceOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'PlatformNamespace',
      fieldName: 'platformNamespace',
      document,
      variables,
      transform: (data: {
        platformNamespaces?: {
          nodes?: InferSelectResult<PlatformNamespaceWithRelations, S>[];
        };
      }) => ({
        platformNamespace: data.platformNamespaces?.nodes?.[0] ?? null,
      }),
    });
  }
  create<S extends PlatformNamespaceSelect>(
    args: CreateArgs<S, CreatePlatformNamespaceInput['platformNamespace']> & {
      select: S;
    } & StrictSelect<S, PlatformNamespaceSelect>
  ): QueryBuilder<{
    createPlatformNamespace: {
      platformNamespace: InferSelectResult<PlatformNamespaceWithRelations, S>;
    };
  }> {
    const { document, variables } = buildCreateDocument(
      'PlatformNamespace',
      'createPlatformNamespace',
      'platformNamespace',
      args.select,
      args.data,
      'CreatePlatformNamespaceInput',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'PlatformNamespace',
      fieldName: 'createPlatformNamespace',
      document,
      variables,
    });
  }
  update<S extends PlatformNamespaceSelect>(
    args: UpdateArgs<
      S,
      {
        id: string;
      },
      PlatformNamespacePatch
    > & {
      select: S;
    } & StrictSelect<S, PlatformNamespaceSelect>
  ): QueryBuilder<{
    updatePlatformNamespace: {
      platformNamespace: InferSelectResult<PlatformNamespaceWithRelations, S>;
    };
  }> {
    const { document, variables } = buildUpdateByPkDocument(
      'PlatformNamespace',
      'updatePlatformNamespace',
      'platformNamespace',
      args.select,
      args.where.id,
      args.data,
      'UpdatePlatformNamespaceInput',
      'id',
      'platformNamespacePatch',
      connectionFieldsMap,
      undefined
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'PlatformNamespace',
      fieldName: 'updatePlatformNamespace',
      document,
      variables,
    });
  }
  delete<S extends PlatformNamespaceSelect>(
    args: DeleteArgs<
      {
        id: string;
      },
      S
    > & {
      select: S;
    } & StrictSelect<S, PlatformNamespaceSelect>
  ): QueryBuilder<{
    deletePlatformNamespace: {
      platformNamespace: InferSelectResult<PlatformNamespaceWithRelations, S>;
    };
  }> {
    const { document, variables } = buildDeleteByPkDocument(
      'PlatformNamespace',
      'deletePlatformNamespace',
      'platformNamespace',
      {
        id: args.where.id,
      },
      'DeletePlatformNamespaceInput',
      args.select,
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'PlatformNamespace',
      fieldName: 'deletePlatformNamespace',
      document,
      variables,
    });
  }
}
