// register-functions: reads functions/<name>/handler.json manifests and generates
// the pgpm seed SQL that registers them in platform_function_definitions.
//
// Usage:
//   node --experimental-strip-types scripts/register-functions.ts
//   node --experimental-strip-types scripts/register-functions.ts --dry-run
//
// Reads each handler.json for:
//   - name, description, port, taskIdentifier  (existing fields)
//   - scope           (default: 'platform')
//   - requiredSecrets  [{name, required}]
//   - requiredConfigs  [{name, required}]
//   - payloadSchema   (JSON Schema — reserved for FBP typed ports)
//
// Outputs:
//   pgpm/constructive-infra-seed/deploy/.../seed_built_in_functions.sql
//   pgpm/constructive-infra-seed/deploy/.../seed_built_in_secrets.sql

const fs = require('fs') as typeof import('fs');
const path = require('path') as typeof import('path');

const ROOT: string = process.cwd();
const FUNCTIONS_DIR: string = path.resolve(ROOT, 'functions');

const SEED_PATH = path.resolve(
  ROOT,
  'pgpm/constructive-infra-seed/deploy/schemas/constructive_infra_public/tables/platform_function_definitions/fixtures/seed_built_in_functions.sql'
);

const SECRETS_SEED_PATH = path.resolve(
  ROOT,
  'pgpm/constructive-infra-seed/deploy/schemas/constructive_infra_public/tables/platform_secret_definitions/fixtures/seed_built_in_secrets.sql'
);

// ── Types ────────────────────────────────────────────────────────────────────

interface Requirement {
  name: string;
  required: boolean;
}

interface FunctionManifest {
  name: string;
  version: string;
  description?: string;
  type?: string;
  port?: number;
  taskIdentifier?: string;
  scope?: string;
  requiredSecrets?: Requirement[];
  requiredConfigs?: Requirement[];
  payloadSchema?: Record<string, unknown>;
  dependencies?: Record<string, string>;
}

// ── Discovery ────────────────────────────────────────────────────────────────

function findFunctions(): string[] {
  if (!fs.existsSync(FUNCTIONS_DIR)) {
    console.log('No functions/ directory found.');
    return [];
  }
  return fs
    .readdirSync(FUNCTIONS_DIR)
    .filter((name: string) => {
      const p = path.join(FUNCTIONS_DIR, name, 'handler.json');
      return fs.existsSync(p);
    })
    .sort();
}

function readManifest(fnName: string): FunctionManifest {
  const p = path.join(FUNCTIONS_DIR, fnName, 'handler.json');
  return JSON.parse(fs.readFileSync(p, 'utf-8'));
}

// ── SQL Generation ───────────────────────────────────────────────────────────

function sqlArray(items: Requirement[] | undefined, typeCast: string): string {
  if (!items || items.length === 0) return `ARRAY[]::${typeCast}[]`;
  const rows = items.map(
    (r) => `      ROW('${r.name}', ${r.required})`
  );
  return `ARRAY[\n${rows.join(',\n')}\n    ]::${typeCast}[]`;
}

function sqlJsonb(obj: Record<string, unknown> | undefined): string {
  if (!obj || Object.keys(obj).length === 0) return 'NULL';
  return `'${JSON.stringify(obj).replace(/'/g, "''")}'::jsonb`;
}

function generateValueBlock(m: FunctionManifest): string {
  const taskId = m.taskIdentifier || m.name;
  const scope = m.scope || 'platform';
  const desc = (m.description || '').replace(/'/g, "''");
  const port = m.port || 8080;
  const secrets = sqlArray(m.requiredSecrets, 'constructive_infra_public.function_requirement');
  const configs = sqlArray(m.requiredConfigs, 'constructive_infra_public.function_requirement');
  const schema = sqlJsonb(m.payloadSchema);

  return `  (
    '${m.name}',
    '${taskId}',
    'http://localhost:${port}',
    true, true, '${scope}',
    '${desc}',
    (SELECT id FROM constructive_infra_public.platform_namespaces WHERE name = 'default' AND database_id = '00000000-0000-0000-0000-000000000000'),
    ${secrets},
    ${configs},
    ${schema}
  )`;
}

function generateSeedSQL(manifests: FunctionManifest[]): string {
  const header = `-- Deploy: schemas/constructive_infra_public/tables/platform_function_definitions/fixtures/seed_built_in_functions
-- made with <3 @ constructive.io
--
-- AUTO-GENERATED by scripts/register-functions.ts
-- Do not edit manually — run: make register

-- requires: schemas/constructive_infra_public/partitions/create_default_partitions
-- requires: schemas/constructive_infra_public/tables/platform_namespaces/fixtures/seed_default_namespace`;

  const values = manifests.map(generateValueBlock).join(',\n');

  return `${header}

BEGIN;

INSERT INTO constructive_infra_public.platform_function_definitions
  (name, task_identifier, service_url, is_invocable, is_built_in, scope, description,
   namespace_id, required_secrets, required_configs, payload_schema)
VALUES
${values}
ON CONFLICT (scope, name) DO UPDATE SET
  task_identifier  = EXCLUDED.task_identifier,
  service_url      = EXCLUDED.service_url,
  namespace_id     = EXCLUDED.namespace_id,
  required_secrets = EXCLUDED.required_secrets,
  required_configs = EXCLUDED.required_configs,
  description      = EXCLUDED.description,
  payload_schema   = EXCLUDED.payload_schema;

COMMIT;
`;
}

function generateRevertSQL(manifests: FunctionManifest[]): string {
  const names = manifests.map((m) => `'${m.name}'`).join(', ');
  return `-- Revert: schemas/constructive_infra_public/tables/platform_function_definitions/fixtures/seed_built_in_functions
-- made with <3 @ constructive.io
-- AUTO-GENERATED by scripts/register-functions.ts

BEGIN;

DELETE FROM constructive_infra_public.platform_function_definitions
WHERE is_built_in = true
  AND scope = 'platform'
  AND name IN (${names});

COMMIT;
`;
}

function generateVerifySQL(manifests: FunctionManifest[]): string {
  const checks = manifests
    .map((m) => `SELECT 1 FROM constructive_infra_public.platform_function_definitions\nWHERE name = '${m.name}' AND is_built_in = true;`)
    .join('\n\n');
  return `-- Verify: schemas/constructive_infra_public/tables/platform_function_definitions/fixtures/seed_built_in_functions
-- made with <3 @ constructive.io
-- AUTO-GENERATED by scripts/register-functions.ts

BEGIN;

${checks}

ROLLBACK;
`;
}

// ── Secret/Config Seed SQL ───────────────────────────────────────────────────

interface SecretDef {
  name: string;
  description: string;
  kind: 'secret' | 'config';
}

function collectSecretDefs(manifests: FunctionManifest[]): SecretDef[] {
  const seen = new Map<string, SecretDef>();
  for (const m of manifests) {
    for (const s of m.requiredSecrets || []) {
      if (!seen.has(s.name)) {
        seen.set(s.name, { name: s.name, description: `Secret used by ${m.name}`, kind: 'secret' });
      }
    }
    for (const c of m.requiredConfigs || []) {
      if (!seen.has(c.name)) {
        seen.set(c.name, { name: c.name, description: `Config used by ${m.name}`, kind: 'config' });
      }
    }
  }
  return Array.from(seen.values()).sort((a, b) => a.name.localeCompare(b.name));
}

function generateSecretsSeedSQL(defs: SecretDef[]): string {
  if (defs.length === 0) return '';
  const values = defs.map(
    (d) => `  ('${d.name}', '${d.description.replace(/'/g, "''")}', true, '00000000-0000-0000-0000-000000000000')`
  ).join(',\n');

  return `-- Deploy: schemas/constructive_infra_public/tables/platform_secret_definitions/fixtures/seed_built_in_secrets
-- made with <3 @ constructive.io
--
-- AUTO-GENERATED by scripts/register-functions.ts
-- Do not edit manually — run: make register

-- requires: schemas/constructive_infra_public/partitions/create_default_partitions
-- requires: schemas/constructive_infra_public/tables/platform_namespaces/fixtures/seed_default_namespace

BEGIN;

INSERT INTO constructive_infra_public.platform_secret_definitions
  (name, description, is_built_in, database_id)
VALUES
${values}
ON CONFLICT (name) DO UPDATE SET
  description = EXCLUDED.description;

COMMIT;
`;
}

function generateSecretsRevertSQL(defs: SecretDef[]): string {
  const names = defs.map((d) => `'${d.name}'`).join(', ');
  return `-- Revert: schemas/constructive_infra_public/tables/platform_secret_definitions/fixtures/seed_built_in_secrets
-- made with <3 @ constructive.io
-- AUTO-GENERATED by scripts/register-functions.ts

BEGIN;

DELETE FROM constructive_infra_public.platform_secret_definitions
WHERE is_built_in = true
  AND name IN (${names});

COMMIT;
`;
}

function generateSecretsVerifySQL(defs: SecretDef[]): string {
  const checks = defs
    .map((d) => `SELECT 1 FROM constructive_infra_public.platform_secret_definitions\nWHERE name = '${d.name}' AND is_built_in = true;`)
    .join('\n\n');
  return `-- Verify: schemas/constructive_infra_public/tables/platform_secret_definitions/fixtures/seed_built_in_secrets
-- made with <3 @ constructive.io
-- AUTO-GENERATED by scripts/register-functions.ts

BEGIN;

${checks}

ROLLBACK;
`;
}

// ── Main ─────────────────────────────────────────────────────────────────────

const REVERT_PATH = SEED_PATH.replace('/deploy/', '/revert/');
const VERIFY_PATH = SEED_PATH.replace('/deploy/', '/verify/');
const SECRETS_REVERT = SECRETS_SEED_PATH.replace('/deploy/', '/revert/');
const SECRETS_VERIFY = SECRETS_SEED_PATH.replace('/deploy/', '/verify/');

function main(): void {
  const dryRun = process.argv.includes('--dry-run');
  const functions = findFunctions();

  if (functions.length === 0) {
    console.log('No functions found to register.');
    return;
  }

  const manifests = functions.map(readManifest);
  const deploySql = generateSeedSQL(manifests);
  const revertSql = generateRevertSQL(manifests);
  const verifySql = generateVerifySQL(manifests);

  const secretDefs = collectSecretDefs(manifests);
  const secretsDeploy = generateSecretsSeedSQL(secretDefs);
  const secretsRevert = generateSecretsRevertSQL(secretDefs);
  const secretsVerify = generateSecretsVerifySQL(secretDefs);

  console.log(`Found ${manifests.length} function(s):`);
  for (const m of manifests) {
    const port = m.port || 8080;
    const secrets = (m.requiredSecrets || []).length;
    const configs = (m.requiredConfigs || []).length;
    const hasSchema = m.payloadSchema && Object.keys(m.payloadSchema).length > 0;
    console.log(`  ${m.name} → :${port} (${secrets} secrets, ${configs} configs${hasSchema ? ', has schema' : ''})`);
  }
  console.log(`\nCollected ${secretDefs.length} unique secret/config definition(s):`);
  for (const d of secretDefs) {
    console.log(`  ${d.name} (${d.kind})`);
  }

  if (dryRun) {
    console.log('\n--- Generated Functions SQL (dry run) ---\n');
    console.log(deploySql);
    console.log('\n--- Generated Secrets SQL (dry run) ---\n');
    console.log(secretsDeploy);
    return;
  }

  const writeSql = (p: string, content: string) => {
    fs.mkdirSync(path.dirname(p), { recursive: true });
    fs.writeFileSync(p, content);
    console.log(`  ${path.relative(ROOT, p)}`);
  };

  console.log('\nWrote:');
  writeSql(SEED_PATH, deploySql);
  writeSql(REVERT_PATH, revertSql);
  writeSql(VERIFY_PATH, verifySql);
  writeSql(SECRETS_SEED_PATH, secretsDeploy);
  writeSql(SECRETS_REVERT, secretsRevert);
  writeSql(SECRETS_VERIFY, secretsVerify);
}

main();
