// register-functions: reads functions/<name>/handler.json manifests and generates
// the pgpm seed SQL that registers them in platform_function_definitions.
//
// Usage:
//   node --experimental-strip-types scripts/register-functions.ts
//   node --experimental-strip-types scripts/register-functions.ts --dry-run
//
// Reads each handler.json for:
//   - name, description, port, taskIdentifier  (existing fields)
//   - scope           (default: 'platform')
//   - requiredSecrets  [{name, required}]
//   - requiredConfigs  [{name, required}]
//   - payloadSchema   (JSON Schema — reserved for FBP typed ports)
//
// Outputs:
//   pgpm/constructive-infra-seed/deploy/.../seed_built_in_functions.sql

const fs = require('fs') as typeof import('fs');
const path = require('path') as typeof import('path');

const ROOT: string = process.cwd();
const FUNCTIONS_DIR: string = path.resolve(ROOT, 'functions');

const SEED_PATH = path.resolve(
  ROOT,
  'pgpm/constructive-infra-seed/deploy/schemas/constructive_compute_public/tables/platform_function_definitions/fixtures/seed_built_in_functions.sql'
);

// ── Types ────────────────────────────────────────────────────────────────────

interface Requirement {
  name: string;
  required: boolean;
}

interface PortDef {
  name: string;
  type: string;
  description?: string;
  optional?: boolean;
  multi?: boolean;
  schema?: Record<string, unknown>;
}

interface PropDef {
  name: string;
  type: string;
  default?: unknown;
  description?: string;
  required?: boolean;
  schema?: Record<string, unknown>;
}

interface FunctionManifest {
  name: string;
  version: string;
  description?: string;
  type?: string;
  port?: number;
  taskIdentifier?: string;
  scope?: string;
  requiredSecrets?: Requirement[];
  requiredConfigs?: Requirement[];
  payloadSchema?: Record<string, unknown>;
  inputs?: PortDef[];
  outputs?: PortDef[];
  props?: PropDef[];
  volatile?: boolean;
  icon?: string;
  category?: string;
  runtime?: 'http' | 'inline';
  dependencies?: Record<string, string>;
}

// ── Discovery ────────────────────────────────────────────────────────────────

function findFunctions(): string[] {
  if (!fs.existsSync(FUNCTIONS_DIR)) {
    console.log('No functions/ directory found.');
    return [];
  }
  return fs
    .readdirSync(FUNCTIONS_DIR)
    .filter((name: string) => {
      const p = path.join(FUNCTIONS_DIR, name, 'handler.json');
      return fs.existsSync(p);
    })
    .sort();
}

function readManifest(fnName: string): FunctionManifest {
  const p = path.join(FUNCTIONS_DIR, fnName, 'handler.json');
  return JSON.parse(fs.readFileSync(p, 'utf-8'));
}

// ── SQL Generation ───────────────────────────────────────────────────────────

function sqlArray(items: Requirement[] | undefined, typeCast: string): string {
  if (!items || items.length === 0) return `ARRAY[]::${typeCast}[]`;
  const rows = items.map(
    (r) => `      ROW('${r.name}', ${r.required})`
  );
  return `ARRAY[\n${rows.join(',\n')}\n    ]::${typeCast}[]`;
}

function sqlJsonb(obj: Record<string, unknown> | unknown[] | undefined): string {
  if (obj === undefined || obj === null) return 'NULL';
  if (Array.isArray(obj) && obj.length === 0) return "'[]'::jsonb";
  if (typeof obj === 'object' && !Array.isArray(obj) && Object.keys(obj).length === 0) return 'NULL';
  return `'${JSON.stringify(obj).replace(/'/g, "''")}'::jsonb`;
}

function generateValueBlock(m: FunctionManifest): string {
  const taskId = m.taskIdentifier || m.name;
  const scope = m.scope || 'platform';
  const desc = (m.description || '').replace(/'/g, "''");
  const port = m.port || 8080;
  const secrets = sqlArray(m.requiredSecrets, 'constructive_compute_public.function_requirement');
  const configs = sqlArray(m.requiredConfigs, 'constructive_compute_public.function_requirement');

  const inputs = sqlJsonb(m.inputs || []);
  const outputs = sqlJsonb(m.outputs || []);
  const props = sqlJsonb(m.props || []);
  const isVolatile = m.volatile === true ? 'true' : 'false';
  const icon = m.icon ? `'${m.icon.replace(/'/g, "''")}'` : 'NULL';
  const category = m.category ? `'${m.category.replace(/'/g, "''")}'` : 'NULL';

  const serviceUrl = m.runtime === 'inline' ? 'NULL' : `'http://localhost:${port}'`;
  const runtime = m.runtime ? `'${m.runtime}'` : "'http'";

  return `  (
    '${m.name}',
    '${taskId}',
    ${serviceUrl},
    true, true, '${scope}',
    '${desc}',
    (SELECT id FROM constructive_infra_public.platform_namespaces WHERE name = 'default' AND database_id = '00000000-0000-0000-0000-000000000000'),
    ${secrets},
    ${configs},
    ${inputs},
    ${outputs},
    ${props},
    ${isVolatile},
    ${icon},
    ${category},
    ${runtime}
  )`;
}

function generateSeedSQL(manifests: FunctionManifest[]): string {
  const header = `-- Deploy: schemas/constructive_compute_public/tables/platform_function_definitions/fixtures/seed_built_in_functions
-- made with <3 @ constructive.io
--
-- AUTO-GENERATED by scripts/register-functions.ts
-- Do not edit manually — run: make register

-- requires: partitions/create_default_partitions
-- requires: schemas/constructive_infra_public/tables/platform_namespaces/fixtures/seed_default_namespace`;

  const values = manifests.map(generateValueBlock).join(',\n');

  return `${header}

BEGIN;

INSERT INTO constructive_compute_public.platform_function_definitions
  (name, task_identifier, service_url, is_invocable, is_built_in, scope, description,
   namespace_id, required_secrets, required_configs,
   inputs, outputs, props, volatile, icon, category, runtime)
VALUES
${values}
ON CONFLICT (scope, name) DO UPDATE SET
  task_identifier  = EXCLUDED.task_identifier,
  service_url      = EXCLUDED.service_url,
  namespace_id     = EXCLUDED.namespace_id,
  required_secrets = EXCLUDED.required_secrets,
  required_configs = EXCLUDED.required_configs,
  description      = EXCLUDED.description,
  inputs           = EXCLUDED.inputs,
  outputs          = EXCLUDED.outputs,
  props            = EXCLUDED.props,
  volatile         = EXCLUDED.volatile,
  icon             = EXCLUDED.icon,
  category         = EXCLUDED.category,
  runtime          = EXCLUDED.runtime;

COMMIT;
`;
}

function generateRevertSQL(manifests: FunctionManifest[]): string {
  const names = manifests.map((m) => `'${m.name}'`).join(', ');
  return `-- Revert: schemas/constructive_compute_public/tables/platform_function_definitions/fixtures/seed_built_in_functions
-- made with <3 @ constructive.io
-- AUTO-GENERATED by scripts/register-functions.ts

BEGIN;

DELETE FROM constructive_compute_public.platform_function_definitions
WHERE is_built_in = true
  AND scope = 'platform'
  AND name IN (${names});

COMMIT;
`;
}

function generateVerifySQL(manifests: FunctionManifest[]): string {
  const checks = manifests
    .map((m) => `SELECT 1 FROM constructive_compute_public.platform_function_definitions\nWHERE name = '${m.name}' AND is_built_in = true;`)
    .join('\n\n');
  return `-- Verify: schemas/constructive_compute_public/tables/platform_function_definitions/fixtures/seed_built_in_functions
-- made with <3 @ constructive.io
-- AUTO-GENERATED by scripts/register-functions.ts

BEGIN;

${checks}

ROLLBACK;
`;
}

// ── Apply (direct DB execution) ──────────────────────────────────────────────

function applyToDatabase(sql: string, dbName: string): boolean {
  const { execSync } = require('child_process') as typeof import('child_process');
  try {
    execSync(`psql -d "${dbName}" -v ON_ERROR_STOP=1`, {
      input: sql,
      stdio: ['pipe', 'pipe', 'pipe'],
    });
    return true;
  } catch (err: any) {
    const stderr = err.stderr?.toString() || '';
    console.error(`  Failed to apply SQL: ${stderr.trim()}`);
    return false;
  }
}

// ── Inline Node Definitions ──────────────────────────────────────────────────
// These run in-process on the compute-worker (no HTTP service needed).

const INLINE_NODES: FunctionManifest[] = [
  {
    name: 'math/add', version: '1.0.0', taskIdentifier: 'math/add', scope: 'platform', runtime: 'inline',
    description: 'Adds two numbers', icon: 'plus', category: 'math',
    inputs: [{ name: 'a', type: 'number' }, { name: 'b', type: 'number' }],
    outputs: [{ name: 'sum', type: 'number' }],
  },
  {
    name: 'math/multiply', version: '1.0.0', taskIdentifier: 'math/multiply', scope: 'platform', runtime: 'inline',
    description: 'Multiplies two numbers', icon: 'x', category: 'math',
    inputs: [{ name: 'a', type: 'number' }, { name: 'b', type: 'number' }],
    outputs: [{ name: 'product', type: 'number' }],
  },
  {
    name: 'math/subtract', version: '1.0.0', taskIdentifier: 'math/subtract', scope: 'platform', runtime: 'inline',
    description: 'Subtracts b from a', icon: 'minus', category: 'math',
    inputs: [{ name: 'a', type: 'number' }, { name: 'b', type: 'number' }],
    outputs: [{ name: 'difference', type: 'number' }],
  },
  {
    name: 'const/number', version: '1.0.0', taskIdentifier: 'const/number', scope: 'platform', runtime: 'inline',
    description: 'Outputs a constant number', icon: 'hash', category: 'const',
    outputs: [{ name: 'value', type: 'number' }],
    props: [{ name: 'value', type: 'number', default: 0 }],
  },
  {
    name: 'const/string', version: '1.0.0', taskIdentifier: 'const/string', scope: 'platform', runtime: 'inline',
    description: 'Outputs a constant string', icon: 'type', category: 'const',
    outputs: [{ name: 'value', type: 'string' }],
    props: [{ name: 'value', type: 'string', default: '' }],
  },
  {
    name: 'const/boolean', version: '1.0.0', taskIdentifier: 'const/boolean', scope: 'platform', runtime: 'inline',
    description: 'Outputs a constant boolean', icon: 'toggle-left', category: 'const',
    outputs: [{ name: 'value', type: 'boolean' }],
    props: [{ name: 'value', type: 'boolean', default: false }],
  },
  {
    name: 'json/select', version: '1.0.0', taskIdentifier: 'json/select', scope: 'platform', runtime: 'inline',
    description: 'Extract a value from JSON by dot-path', icon: 'circle', category: 'json',
    inputs: [{ name: 'obj', type: 'json' }],
    outputs: [{ name: 'value', type: 'any' }],
    props: [{ name: 'path', type: 'string', default: '' }],
  },
  {
    name: 'json/object', version: '1.0.0', taskIdentifier: 'json/object', scope: 'platform', runtime: 'inline',
    description: 'Build a JSON object from named inputs', icon: 'braces', category: 'json',
    outputs: [{ name: 'value', type: 'json' }],
  },
  {
    name: 'json/merge', version: '1.0.0', taskIdentifier: 'json/merge', scope: 'platform', runtime: 'inline',
    description: 'Merge two JSON objects', icon: 'git-merge', category: 'json',
    inputs: [{ name: 'a', type: 'json' }, { name: 'b', type: 'json' }],
    outputs: [{ name: 'value', type: 'json' }],
  },
  {
    name: 'json/split', version: '1.0.0', taskIdentifier: 'json/split', scope: 'platform', runtime: 'inline',
    description: 'Split a JSON object by key list', icon: 'scissors', category: 'json',
    inputs: [{ name: 'obj', type: 'json' }],
    outputs: [{ name: 'selected', type: 'json' }, { name: 'rest', type: 'json' }],
    props: [{ name: 'keys', type: 'json', default: [] }],
  },
  {
    name: 'string/template', version: '1.0.0', taskIdentifier: 'string/template', scope: 'platform', runtime: 'inline',
    description: 'Build a string from a template with {{placeholder}} syntax', icon: 'quote', category: 'string',
    outputs: [{ name: 'value', type: 'string' }],
    props: [{ name: 'template', type: 'string', default: '' }],
  },
  {
    name: 'flow/guard', version: '1.0.0', taskIdentifier: 'flow/guard', scope: 'platform', runtime: 'inline',
    description: 'Stop the flow if a condition fails', icon: 'shield', category: 'flow',
    inputs: [{ name: 'ok', type: 'boolean' }, { name: 'error', type: 'json', optional: true }],
    outputs: [{ name: 'pass', type: 'signal' }, { name: 'fail', type: 'signal' }, { name: 'error', type: 'json' }],
  },
  {
    name: 'coerce', version: '1.0.0', taskIdentifier: 'coerce', scope: 'platform', runtime: 'inline',
    description: 'Convert a value to a different type', icon: 'repeat', category: 'flow',
    inputs: [{ name: 'value', type: 'any' }],
    outputs: [{ name: 'value', type: 'any' }],
    props: [{ name: 'type', type: 'string', default: 'string' }],
  },
];

// ── Main ─────────────────────────────────────────────────────────────────────

const REVERT_PATH = SEED_PATH.replace('/deploy/', '/revert/');
const VERIFY_PATH = SEED_PATH.replace('/deploy/', '/verify/');

function main(): void {
  const dryRun = process.argv.includes('--dry-run');
  const apply = process.argv.includes('--apply');
  const dbArg = process.argv.find((a) => a.startsWith('--database='));
  const dbName = dbArg ? dbArg.split('=')[1] : process.env.PGDATABASE || 'constructive-functions-db1';

  const functions = findFunctions();
  const httpManifests = functions.map(readManifest);
  const manifests = [...httpManifests, ...INLINE_NODES];

  if (manifests.length === 0) {
    console.log('No functions found to register.');
    return;
  }

  const deploySql = generateSeedSQL(manifests);
  const revertSql = generateRevertSQL(manifests);
  const verifySql = generateVerifySQL(manifests);

  console.log(`Found ${httpManifests.length} HTTP function(s) + ${INLINE_NODES.length} inline node(s):`);
  for (const m of httpManifests) {
    const port = m.port || 8080;
    const secrets = (m.requiredSecrets || []).length;
    const configs = (m.requiredConfigs || []).length;
    const hasSchema = m.payloadSchema && Object.keys(m.payloadSchema).length > 0;
    console.log(`  ${m.name} → :${port} (${secrets} secrets, ${configs} configs${hasSchema ? ', has schema' : ''})`);
  }
  for (const m of INLINE_NODES) {
    console.log(`  ${m.name} → inline (${m.category})`);
  }

  if (dryRun) {
    console.log('\n--- Generated Functions SQL (dry run) ---\n');
    console.log(deploySql);
    return;
  }

  if (apply) {
    console.log(`\nApplying to database: ${dbName}`);
    if (applyToDatabase(deploySql, dbName)) {
      console.log(`  ✓ ${manifests.length} function(s) registered`);
    }
    return;
  }

  const writeSql = (p: string, content: string) => {
    fs.mkdirSync(path.dirname(p), { recursive: true });
    fs.writeFileSync(p, content);
    console.log(`  ${path.relative(ROOT, p)}`);
  };

  console.log('\nWrote:');
  writeSql(SEED_PATH, deploySql);
  writeSql(REVERT_PATH, revertSql);
  writeSql(VERIFY_PATH, verifySql);
}

main();
