#!/usr/bin/env bash
#
# secrets-sync.sh — bidirectional sync between .env and platform_secret_values
#
# Reads .env → upserts into DB, then reads DB → merges into .env.
# Priority on conflict: .env wins (values already in .env are not overwritten by DB).
#
# Usage:
#   ./scripts/secrets-sync.sh                       # defaults
#   ./scripts/secrets-sync.sh .env.local db8        # custom env file + database
#   DB_NAME=db8 ./scripts/secrets-sync.sh           # via env var

set -euo pipefail

ENV_FILE="${1:-.env}"
DB_NAME="${2:-${DB_NAME:-constructive-functions-db1}}"

echo "════════════════════════════════════════════════════════════"
echo "  Secrets Bidirectional Sync"
echo "  .env: $ENV_FILE    database: $DB_NAME"
echo "════════════════════════════════════════════════════════════"
echo ""

# --- Step 1: .env → DB ---

declare -A ENV_VARS
SYNCED_TO_DB=0

if [ -f "$ENV_FILE" ]; then
  while IFS= read -r line; do
    [[ "$line" =~ ^[[:space:]]*# ]] && continue
    [[ -z "$line" ]] && continue
    if [[ "$line" =~ ^([A-Za-z_][A-Za-z0-9_]*)=(.*) ]]; then
      key="${BASH_REMATCH[1]}"
      val="${BASH_REMATCH[2]}"
      val="${val#\"}"
      val="${val%\"}"
      val="${val#\'}"
      val="${val%\'}"
      ENV_VARS["$key"]="$val"
    fi
  done < "$ENV_FILE"

  echo "Loaded ${#ENV_VARS[@]} variable(s) from $ENV_FILE"

  # Get a database_id for scoping
  DB_ID=$(psql -d "$DB_NAME" -t -A -c "
    SELECT COALESCE(
      (SELECT database_id FROM constructive_infra_public.platform_secret_definitions LIMIT 1),
      'default'
    )
  " 2>/dev/null || echo "default")

  for key in "${!ENV_VARS[@]}"; do
    val="${ENV_VARS[$key]}"
    [ -z "$val" ] && continue
    psql -d "$DB_NAME" -q -c "
      INSERT INTO constructive_infra_public.platform_secret_values
        (secret_name, configured_value, database_id)
      VALUES ('$key', '$(echo "$val" | sed "s/'/''/g")', '$DB_ID')
      ON CONFLICT (secret_name, database_id)
      DO UPDATE SET configured_value = EXCLUDED.configured_value
    " 2>/dev/null && ((SYNCED_TO_DB++)) || true
  done

  echo "→ Synced $SYNCED_TO_DB values from .env → DB"
else
  echo "No .env file found at $ENV_FILE (will be created from DB values)"
fi

# --- Step 2: DB → .env ---

echo ""
echo "Reading configured values from DB..."

DB_VALUES=$(psql -d "$DB_NAME" -t -A -F '|' -c "
  SELECT secret_name, configured_value
  FROM constructive_infra_public.platform_secret_values
  WHERE configured_value IS NOT NULL AND configured_value != ''
  ORDER BY secret_name
" 2>/dev/null || echo "")

SYNCED_FROM_DB=0

if [ -n "$DB_VALUES" ]; then
  while IFS='|' read -r name value; do
    [ -z "$name" ] && continue
    if [ -z "${ENV_VARS[$name]+x}" ]; then
      ENV_VARS["$name"]="$value"
      ((SYNCED_FROM_DB++)) || true
    fi
  done <<< "$DB_VALUES"
fi

echo "→ Synced $SYNCED_FROM_DB new values from DB → .env"

# --- Step 3: Write merged .env ---

if [ ${#ENV_VARS[@]} -gt 0 ]; then
  {
    echo "# Auto-generated by secrets-sync — edits here are safe."
    echo "# Values can also be edited from http://localhost:5173 → Secrets tab."
    echo ""
    for key in $(echo "${!ENV_VARS[@]}" | tr ' ' '\n' | sort); do
      echo "$key=${ENV_VARS[$key]}"
    done
  } > "$ENV_FILE"
  echo ""
  echo "Wrote ${#ENV_VARS[@]} variable(s) to $ENV_FILE"
fi

echo ""
echo "Done. Total: $SYNCED_TO_DB → DB, $SYNCED_FROM_DB ← DB"
