/**
 * CLI command for mutation platformCopyGraph
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { CLIOptions, Inquirerer } from 'inquirerer';

import type { PlatformCopyGraphPayloadSelect } from '../../../orm/input-types';
import type { PlatformCopyGraphVariables } from '../../../orm/mutation';
import { getClient } from '../../executor';
import { buildSelectFromPaths,unflattenDotNotation } from '../../utils';
export default async (
  argv: Partial<Record<string, unknown>>,
  prompter: Inquirerer,
  _options: CLIOptions
) => {
  try {
    if (argv.help || argv.h) {
      console.log(
        'platform-copy-graph - platformCopyGraph\n\nUsage: platform-copy-graph [OPTIONS]\n'
      );
      process.exit(0);
    }
    const answers = await prompter.prompt(argv, [
      {
        type: 'text',
        name: 'input',
        message:
          'The exclusive input argument for this mutation. An object type, make sure to see documentation for this object\u2019s fields.',
        required: true,
      },
    ]);
    const client = getClient('compute');
    const parsedAnswers = unflattenDotNotation(answers);
    const selectFields = buildSelectFromPaths((argv.select as string) ?? 'clientMutationId');
    const result = await client.mutation
      .platformCopyGraph(
        parsedAnswers as unknown as PlatformCopyGraphVariables,
        {
          select: selectFields,
        } as unknown as {
          select: PlatformCopyGraphPayloadSelect;
        }
      )
      .execute();
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error('Failed: platformCopyGraph');
    if (error instanceof Error) {
      console.error(error.message);
    }
    process.exit(1);
  }
};
