/**
 * CLI command for mutation platformAddNode
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { CLIOptions, Inquirerer } from 'inquirerer';
import { getClient } from '../../executor';
import { unflattenDotNotation, buildSelectFromPaths } from '../../utils';
import type { PlatformAddNodeVariables } from '../../../orm/mutation';
import type { PlatformAddNodePayloadSelect } from '../../../orm/input-types';
export default async (
  argv: Partial<Record<string, unknown>>,
  prompter: Inquirerer,
  _options: CLIOptions
) => {
  try {
    if (argv.help || argv.h) {
      console.log('platform-add-node - platformAddNode\n\nUsage: platform-add-node [OPTIONS]\n');
      process.exit(0);
    }
    const answers = await prompter.prompt(argv, [
      {
        type: 'text',
        name: 'input',
        message:
          'The exclusive input argument for this mutation. An object type, make sure to see documentation for this object\u2019s fields.',
        required: true,
      },
    ]);
    const client = getClient('compute');
    const parsedAnswers = unflattenDotNotation(answers);
    const selectFields = buildSelectFromPaths((argv.select as string) ?? 'clientMutationId');
    const result = await client.mutation
      .platformAddNode(
        parsedAnswers as unknown as PlatformAddNodeVariables,
        {
          select: selectFields,
        } as unknown as {
          select: PlatformAddNodePayloadSelect;
        }
      )
      .execute();
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error('Failed: platformAddNode');
    if (error instanceof Error) {
      console.error(error.message);
    }
    process.exit(1);
  }
};
