/**
 * CLI command for mutation platformStartExecution
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { CLIOptions, Inquirerer } from 'inquirerer';
import { getClient } from '../../executor';
import { unflattenDotNotation, buildSelectFromPaths } from '../../utils';
import type { PlatformStartExecutionVariables } from '../../../orm/mutation';
import type { PlatformStartExecutionPayloadSelect } from '../../../orm/input-types';
export default async (
  argv: Partial<Record<string, unknown>>,
  prompter: Inquirerer,
  _options: CLIOptions
) => {
  try {
    if (argv.help || argv.h) {
      console.log(
        'platform-start-execution - platformStartExecution\n\nUsage: platform-start-execution [OPTIONS]\n'
      );
      process.exit(0);
    }
    const answers = await prompter.prompt(argv, [
      {
        type: 'text',
        name: 'input',
        message:
          'The exclusive input argument for this mutation. An object type, make sure to see documentation for this object\u2019s fields.',
        required: true,
      },
    ]);
    const client = getClient('compute');
    const parsedAnswers = unflattenDotNotation(answers);
    const selectFields = buildSelectFromPaths((argv.select as string) ?? 'clientMutationId');
    const result = await client.mutation
      .platformStartExecution(
        parsedAnswers as unknown as PlatformStartExecutionVariables,
        {
          select: selectFields,
        } as unknown as {
          select: PlatformStartExecutionPayloadSelect;
        }
      )
      .execute();
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error('Failed: platformStartExecution');
    if (error instanceof Error) {
      console.error(error.message);
    }
    process.exit(1);
  }
};
