-- Revert: schemas/constructive_compute_public/tables/platform_function_graph_execution_node_states/columns/output_id/alterations/alt0000002714


COMMENT ON COLUMN "constructive_compute_public".platform_function_graph_execution_node_states.output_id IS NULL;
