-- Deploy: schemas/constructive_compute_public/tables/platform_function_definitions/fixtures/seed_built_in_functions
-- made with <3 @ constructive.io
--
-- AUTO-GENERATED by scripts/register-functions.ts
-- Do not edit manually — run: make register

-- requires: partitions/create_default_partitions
-- requires: schemas/constructive_infra_public/tables/platform_namespaces/fixtures/seed_default_namespace

BEGIN;

INSERT INTO constructive_compute_public.platform_function_definitions
  (name, task_identifier, service_url, is_invocable, is_built_in, scope, description,
   namespace_id, required_secrets, required_configs)
VALUES
  (
    'node-example',
    'node-example',
    'http://localhost:8083',
    true, true, 'platform',
    'Example Node.js function — copy this to create a new function',
    (SELECT id FROM constructive_infra_public.platform_namespaces WHERE name = 'default' AND database_id = '00000000-0000-0000-0000-000000000000'),
    ARRAY[]::constructive_compute_public.function_requirement[],
    ARRAY[]::constructive_compute_public.function_requirement[]
  ),
  (
    'python-example',
    'python-example',
    'http://localhost:8084',
    true, true, 'platform',
    'Example Python function — copy this to create a new Python function',
    (SELECT id FROM constructive_infra_public.platform_namespaces WHERE name = 'default' AND database_id = '00000000-0000-0000-0000-000000000000'),
    ARRAY[]::constructive_compute_public.function_requirement[],
    ARRAY[]::constructive_compute_public.function_requirement[]
  ),
  (
    'send-email',
    'send-email',
    'http://localhost:8081',
    true, true, 'platform',
    'Sends transactional emails via Mailgun or SMTP',
    (SELECT id FROM constructive_infra_public.platform_namespaces WHERE name = 'default' AND database_id = '00000000-0000-0000-0000-000000000000'),
    ARRAY[
      ROW('MAILGUN_API_KEY', false),
      ROW('MAILGUN_DOMAIN', false),
      ROW('MAILGUN_FROM', false)
    ]::constructive_compute_public.function_requirement[],
    ARRAY[
      ROW('EMAIL_SEND_USE_SMTP', false),
      ROW('SMTP_HOST', false),
      ROW('SMTP_PORT', false),
      ROW('SMTP_FROM', false),
      ROW('SEND_EMAIL_DRY_RUN', false)
    ]::constructive_compute_public.function_requirement[]
  ),
  (
    'send-verification-link',
    'send-verification-link',
    'http://localhost:8082',
    true, true, 'platform',
    'Sends invite, password reset, and verification emails',
    (SELECT id FROM constructive_infra_public.platform_namespaces WHERE name = 'default' AND database_id = '00000000-0000-0000-0000-000000000000'),
    ARRAY[
      ROW('MAILGUN_API_KEY', false),
      ROW('MAILGUN_DOMAIN', false),
      ROW('MAILGUN_FROM', false),
      ROW('MAILGUN_REPLY', false)
    ]::constructive_compute_public.function_requirement[],
    ARRAY[
      ROW('EMAIL_SEND_USE_SMTP', false),
      ROW('SMTP_HOST', false),
      ROW('SMTP_PORT', false),
      ROW('SMTP_FROM', false),
      ROW('LOCAL_APP_PORT', false),
      ROW('SEND_VERIFICATION_LINK_DRY_RUN', false)
    ]::constructive_compute_public.function_requirement[]
  )
ON CONFLICT (scope, name) DO UPDATE SET
  task_identifier  = EXCLUDED.task_identifier,
  service_url      = EXCLUDED.service_url,
  namespace_id     = EXCLUDED.namespace_id,
  required_secrets = EXCLUDED.required_secrets,
  required_configs = EXCLUDED.required_configs,
  description      = EXCLUDED.description;

COMMIT;
