-- Verify: schemas/constructive_infra_public/tables/platform_function_execution_logs/indexes/platform_function_execution_logs_invocation_id_created_at_idx


SELECT verify_index('constructive_infra_public.platform_function_execution_logs', 'platform_function_execution_logs_invocation_id_created_at_idx');


