/**
 * ORM Client - createClient factory
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { OrmClient } from './client';
import type { OrmClientConfig } from './client';
import { GetAllRecordModel } from './models/getAllRecord';
import { PlatformFunctionGraphRefModel } from './models/platformFunctionGraphRef';
import { PlatformFunctionGraphStoreModel } from './models/platformFunctionGraphStore';
import { PlatformFunctionGraphObjectModel } from './models/platformFunctionGraphObject';
import { OrgFunctionExecutionLogModel } from './models/orgFunctionExecutionLog';
import { PlatformFunctionGraphCommitModel } from './models/platformFunctionGraphCommit';
import { PlatformSecretDefinitionModel } from './models/platformSecretDefinition';
import { PlatformFunctionExecutionLogModel } from './models/platformFunctionExecutionLog';
import { PlatformFunctionGraphModel } from './models/platformFunctionGraph';
import { OrgFunctionInvocationModel } from './models/orgFunctionInvocation';
import { PlatformFunctionInvocationModel } from './models/platformFunctionInvocation';
import { PlatformFunctionDefinitionModel } from './models/platformFunctionDefinition';
import { createQueryOperations } from './query';
import { createMutationOperations } from './mutation';
export type { OrmClientConfig, QueryResult, GraphQLError, GraphQLAdapter } from './client';
export { GraphQLRequestError, FetchAdapter } from './client';
export { QueryBuilder } from './query-builder';
export * from './select-types';
export * from './models';
export { createQueryOperations } from './query';
export { createMutationOperations } from './mutation';
/**
 * Create an ORM client instance
 *
 * @example
 * ```typescript
 * const db = createClient({
 *   endpoint: 'https://api.example.com/graphql',
 *   headers: { Authorization: 'Bearer token' },
 * });
 *
 * // Query users
 * const users = await db.user.findMany({
 *   select: { id: true, name: true },
 *   first: 10,
 * }).execute();
 *
 * // Create a user
 * const newUser = await db.user.create({
 *   data: { name: 'John', email: 'john@example.com' },
 *   select: { id: true },
 * }).execute();
 * ```
 */
export function createClient(config: OrmClientConfig) {
  const client = new OrmClient(config);
  return {
    getAllRecord: new GetAllRecordModel(client),
    platformFunctionGraphRef: new PlatformFunctionGraphRefModel(client),
    platformFunctionGraphStore: new PlatformFunctionGraphStoreModel(client),
    platformFunctionGraphObject: new PlatformFunctionGraphObjectModel(client),
    orgFunctionExecutionLog: new OrgFunctionExecutionLogModel(client),
    platformFunctionGraphCommit: new PlatformFunctionGraphCommitModel(client),
    platformSecretDefinition: new PlatformSecretDefinitionModel(client),
    platformFunctionExecutionLog: new PlatformFunctionExecutionLogModel(client),
    platformFunctionGraph: new PlatformFunctionGraphModel(client),
    orgFunctionInvocation: new OrgFunctionInvocationModel(client),
    platformFunctionInvocation: new PlatformFunctionInvocationModel(client),
    platformFunctionDefinition: new PlatformFunctionDefinitionModel(client),
    query: createQueryOperations(client),
    mutation: createMutationOperations(client),
  };
}
