/**
 * GraphQL types for ORM client
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
// ============ Scalar Filter Types ============
export interface StringFilter {
  isNull?: boolean;
  equalTo?: string;
  notEqualTo?: string;
  distinctFrom?: string;
  notDistinctFrom?: string;
  in?: string[];
  notIn?: string[];
  lessThan?: string;
  lessThanOrEqualTo?: string;
  greaterThan?: string;
  greaterThanOrEqualTo?: string;
  includes?: string;
  notIncludes?: string;
  includesInsensitive?: string;
  notIncludesInsensitive?: string;
  startsWith?: string;
  notStartsWith?: string;
  startsWithInsensitive?: string;
  notStartsWithInsensitive?: string;
  endsWith?: string;
  notEndsWith?: string;
  endsWithInsensitive?: string;
  notEndsWithInsensitive?: string;
  like?: string;
  notLike?: string;
  likeInsensitive?: string;
  notLikeInsensitive?: string;
}
export interface IntFilter {
  isNull?: boolean;
  equalTo?: number;
  notEqualTo?: number;
  distinctFrom?: number;
  notDistinctFrom?: number;
  in?: number[];
  notIn?: number[];
  lessThan?: number;
  lessThanOrEqualTo?: number;
  greaterThan?: number;
  greaterThanOrEqualTo?: number;
}
export interface FloatFilter {
  isNull?: boolean;
  equalTo?: number;
  notEqualTo?: number;
  distinctFrom?: number;
  notDistinctFrom?: number;
  in?: number[];
  notIn?: number[];
  lessThan?: number;
  lessThanOrEqualTo?: number;
  greaterThan?: number;
  greaterThanOrEqualTo?: number;
}
export interface BooleanFilter {
  isNull?: boolean;
  equalTo?: boolean;
  notEqualTo?: boolean;
}
export interface UUIDFilter {
  isNull?: boolean;
  equalTo?: string;
  notEqualTo?: string;
  distinctFrom?: string;
  notDistinctFrom?: string;
  in?: string[];
  notIn?: string[];
}
export interface DatetimeFilter {
  isNull?: boolean;
  equalTo?: string;
  notEqualTo?: string;
  distinctFrom?: string;
  notDistinctFrom?: string;
  in?: string[];
  notIn?: string[];
  lessThan?: string;
  lessThanOrEqualTo?: string;
  greaterThan?: string;
  greaterThanOrEqualTo?: string;
}
export interface DateFilter {
  isNull?: boolean;
  equalTo?: string;
  notEqualTo?: string;
  distinctFrom?: string;
  notDistinctFrom?: string;
  in?: string[];
  notIn?: string[];
  lessThan?: string;
  lessThanOrEqualTo?: string;
  greaterThan?: string;
  greaterThanOrEqualTo?: string;
}
export interface JSONFilter {
  isNull?: boolean;
  equalTo?: Record<string, unknown>;
  notEqualTo?: Record<string, unknown>;
  distinctFrom?: Record<string, unknown>;
  notDistinctFrom?: Record<string, unknown>;
  contains?: Record<string, unknown>;
  containedBy?: Record<string, unknown>;
  containsKey?: string;
  containsAllKeys?: string[];
  containsAnyKeys?: string[];
}
export interface BigIntFilter {
  isNull?: boolean;
  equalTo?: string;
  notEqualTo?: string;
  distinctFrom?: string;
  notDistinctFrom?: string;
  in?: string[];
  notIn?: string[];
  lessThan?: string;
  lessThanOrEqualTo?: string;
  greaterThan?: string;
  greaterThanOrEqualTo?: string;
}
export interface BigFloatFilter {
  isNull?: boolean;
  equalTo?: string;
  notEqualTo?: string;
  distinctFrom?: string;
  notDistinctFrom?: string;
  in?: string[];
  notIn?: string[];
  lessThan?: string;
  lessThanOrEqualTo?: string;
  greaterThan?: string;
  greaterThanOrEqualTo?: string;
}
export interface BitStringFilter {
  isNull?: boolean;
  equalTo?: string;
  notEqualTo?: string;
}
export interface InternetAddressFilter {
  isNull?: boolean;
  equalTo?: string;
  notEqualTo?: string;
  distinctFrom?: string;
  notDistinctFrom?: string;
  in?: string[];
  notIn?: string[];
  lessThan?: string;
  lessThanOrEqualTo?: string;
  greaterThan?: string;
  greaterThanOrEqualTo?: string;
  contains?: string;
  containsOrEqualTo?: string;
  containedBy?: string;
  containedByOrEqualTo?: string;
  containsOrContainedBy?: string;
}
export interface FullTextFilter {
  matches?: string;
}
export interface VectorFilter {
  isNull?: boolean;
  equalTo?: number[];
  notEqualTo?: number[];
  distinctFrom?: number[];
  notDistinctFrom?: number[];
}
export interface StringListFilter {
  isNull?: boolean;
  equalTo?: string[];
  notEqualTo?: string[];
  distinctFrom?: string[];
  notDistinctFrom?: string[];
  lessThan?: string[];
  lessThanOrEqualTo?: string[];
  greaterThan?: string[];
  greaterThanOrEqualTo?: string[];
  contains?: string[];
  containedBy?: string[];
  overlaps?: string[];
  anyEqualTo?: string;
  anyNotEqualTo?: string;
  anyLessThan?: string;
  anyLessThanOrEqualTo?: string;
  anyGreaterThan?: string;
  anyGreaterThanOrEqualTo?: string;
}
export interface IntListFilter {
  isNull?: boolean;
  equalTo?: number[];
  notEqualTo?: number[];
  distinctFrom?: number[];
  notDistinctFrom?: number[];
  lessThan?: number[];
  lessThanOrEqualTo?: number[];
  greaterThan?: number[];
  greaterThanOrEqualTo?: number[];
  contains?: number[];
  containedBy?: number[];
  overlaps?: number[];
  anyEqualTo?: number;
  anyNotEqualTo?: number;
  anyLessThan?: number;
  anyLessThanOrEqualTo?: number;
  anyGreaterThan?: number;
  anyGreaterThanOrEqualTo?: number;
}
export interface UUIDListFilter {
  isNull?: boolean;
  equalTo?: string[];
  notEqualTo?: string[];
  distinctFrom?: string[];
  notDistinctFrom?: string[];
  lessThan?: string[];
  lessThanOrEqualTo?: string[];
  greaterThan?: string[];
  greaterThanOrEqualTo?: string[];
  contains?: string[];
  containedBy?: string[];
  overlaps?: string[];
  anyEqualTo?: string;
  anyNotEqualTo?: string;
  anyLessThan?: string;
  anyLessThanOrEqualTo?: string;
  anyGreaterThan?: string;
  anyGreaterThanOrEqualTo?: string;
}
// ============ Custom Scalar Types ============
export type FunctionRequirement = unknown;
// ============ Entity Types ============
export interface GetAllRecord {
  path?: string[] | null;
  data?: Record<string, unknown> | null;
}
/** Branch heads — mutable pointers into the commit chain */
export interface PlatformFunctionGraphRef {
  /** Commit this ref points to */
  commitId?: string | null;
  /** Database scope for multi-tenant isolation */
  databaseId?: string | null;
  /** Unique ref identifier */
  id: string;
  /** Ref name (e.g. HEAD, main) */
  name?: string | null;
  /** Store this ref belongs to */
  storeId?: string | null;
}
/** Named stores — one per version-controlled tree (e.g. one graph, one definition set) */
export interface PlatformFunctionGraphStore {
  /** Timestamp of store creation */
  createdAt?: string | null;
  /** Database scope for multi-tenant isolation */
  databaseId?: string | null;
  /** Current root object hash of this store */
  hash?: string | null;
  /** Unique store identifier */
  id: string;
  /** Human-readable store name */
  name?: string | null;
}
/** Content-addressed Merkle tree objects keyed by UUID v5 hash of data + children */
export interface PlatformFunctionGraphObject {
  /** Timestamp of object creation */
  createdAt?: string | null;
  /** Payload data for this object node */
  data?: Record<string, unknown> | null;
  /** Database scope for multi-tenant isolation */
  databaseId?: string | null;
  /** Content-addressed UUID v5 — deterministic hash of (data, kids, ktree) */
  id: string;
  /** Ordered array of child object IDs */
  kids?: string[] | null;
  /** Ordered array of child path names (parallel to kids) */
  ktree?: string[] | null;
}
/** Function execution logs — structured console output per invocation */
export interface OrgFunctionExecutionLog {
  /** Log entry timestamp (partition key) */
  createdAt?: string | null;
  /** User who triggered the execution (NULL for system/cron) */
  actorId?: string | null;
  /** Unique log entry identifier */
  id: string;
  /** Invocation this log entry belongs to (NULL for standalone job logs) */
  invocationId?: string | null;
  /** Log severity: debug, info, warn, error */
  logLevel?: string | null;
  /** Log message text */
  message?: string | null;
  /** Structured context (labels, trace data, extra fields) */
  metadata?: Record<string, unknown> | null;
  /** Function routing key (NULL for generic job logs) */
  taskIdentifier?: string | null;
}
/** Commit history — each commit snapshots a tree root for a store */
export interface PlatformFunctionGraphCommit {
  /** User who authored the changes */
  authorId?: string | null;
  /** User who committed (may differ from author) */
  committerId?: string | null;
  /** Database scope for multi-tenant isolation */
  databaseId?: string | null;
  /** Commit timestamp */
  date?: string | null;
  /** Unique commit identifier */
  id: string;
  /** Optional commit message */
  message?: string | null;
  /** Parent commit IDs (supports merge commits) */
  parentIds?: string[] | null;
  /** Store this commit belongs to */
  storeId?: string | null;
  /** Root object ID of the tree snapshot at this commit */
  treeId?: string | null;
}
/** Global secret name registry — declares which secrets the platform recognizes. Actual values live in app_secrets. */
export interface PlatformSecretDefinition {
  /** Freeform metadata annotations for secret definitions */
  annotations?: Record<string, unknown> | null;
  createdAt?: string | null;
  /** Database that owns this resource (database-scoped isolation) */
  databaseId?: string | null;
  /** Human-readable description of what this secret is used for */
  description?: string | null;
  id: string;
  /** Whether this row was seeded as a built-in secret definition. Built-in rows are immutable. */
  isBuiltIn?: boolean | null;
  /** Key-value metadata for filtering and grouping secret definitions */
  labels?: Record<string, unknown> | null;
  /** Secret name (must match app_secrets.name for resolution) */
  name?: string | null;
  updatedAt?: string | null;
}
/** Function execution logs — structured console output per invocation */
export interface PlatformFunctionExecutionLog {
  /** Log entry timestamp (partition key) */
  createdAt?: string | null;
  /** User who triggered the execution (NULL for system/cron) */
  actorId?: string | null;
  /** Database that owns this resource (database-scoped isolation) */
  databaseId?: string | null;
  /** Unique log entry identifier */
  id: string;
  /** Invocation this log entry belongs to (NULL for standalone job logs) */
  invocationId?: string | null;
  /** Log severity: debug, info, warn, error */
  logLevel?: string | null;
  /** Log message text */
  message?: string | null;
  /** Structured context (labels, trace data, extra fields) */
  metadata?: Record<string, unknown> | null;
  /** Function routing key (NULL for generic job logs) */
  taskIdentifier?: string | null;
}
/** Flow graph definitions — FBP graphs stored in the dedicated graph Merkle store */
export interface PlatformFunctionGraph {
  /** Evaluator/runtime context (function, js, sql, system) */
  context?: string | null;
  /** Timestamp of graph creation */
  createdAt?: string | null;
  /** Actor who created this graph */
  createdBy?: string | null;
  /** Database scope for multi-tenant isolation */
  databaseId?: string | null;
  /** Pinned definitions store commit for deterministic evaluation */
  definitionsCommitId?: string | null;
  /** Human-readable description of the graph */
  description?: string | null;
  /** Entity context (org/team) for scoped billing */
  entityId?: string | null;
  /** Unique graph identifier */
  id: string;
  /** Whether graph passes structural validation */
  isValid?: boolean | null;
  /** Graph name (unique per database) */
  name?: string | null;
  /** Graph store (Merkle store) holding the graph definition */
  storeId?: string | null;
  /** Timestamp of last modification */
  updatedAt?: string | null;
  /** Array of validation error objects when is_valid = false */
  validationErrors?: Record<string, unknown> | null;
}
/** Function invocation log — INSERT to call a function (business-layer, metered). Linked to definitions by task_identifier string. */
export interface OrgFunctionInvocation {
  /** Invocation creation timestamp (partition key) */
  createdAt?: string | null;
  /** Who triggered the invocation (NULL for system/cron) */
  actorId?: string | null;
  /** When execution completed */
  completedAt?: string | null;
  /** Wall-clock execution time in milliseconds */
  durationMs?: number | null;
  /** Error message when status is failed */
  error?: string | null;
  /** Groups all node invocations from a single flow graph execution */
  graphExecutionId?: string | null;
  /** Unique invocation identifier */
  id: string;
  /** FK to app_jobs.jobs — the underlying transport */
  jobId?: string | null;
  /** Parent invocation when this is a child node of a flow graph execution */
  parentInvocationId?: string | null;
  /** Function input payload */
  payload?: Record<string, unknown> | null;
  /** Function return value (success) or structured error (failure) */
  result?: Record<string, unknown> | null;
  /** When execution started */
  startedAt?: string | null;
  /** Lifecycle: pending → running → completed/failed/cancelled */
  status?: string | null;
  /** Function routing slug (scope:name). Links to function_definitions.task_identifier by convention — no FK. */
  taskIdentifier?: string | null;
}
/** Function invocation log — INSERT to call a function (business-layer, metered). Linked to definitions by task_identifier string. */
export interface PlatformFunctionInvocation {
  /** Invocation creation timestamp (partition key) */
  createdAt?: string | null;
  /** Who triggered the invocation (NULL for system/cron) */
  actorId?: string | null;
  /** When execution completed */
  completedAt?: string | null;
  /** Database that owns this resource (database-scoped isolation) */
  databaseId?: string | null;
  /** Wall-clock execution time in milliseconds */
  durationMs?: number | null;
  /** Error message when status is failed */
  error?: string | null;
  /** Groups all node invocations from a single flow graph execution */
  graphExecutionId?: string | null;
  /** Unique invocation identifier */
  id: string;
  /** FK to app_jobs.jobs — the underlying transport */
  jobId?: string | null;
  /** Parent invocation when this is a child node of a flow graph execution */
  parentInvocationId?: string | null;
  /** Function input payload */
  payload?: Record<string, unknown> | null;
  /** Function return value (success) or structured error (failure) */
  result?: Record<string, unknown> | null;
  /** When execution started */
  startedAt?: string | null;
  /** Lifecycle: pending → running → completed/failed/cancelled */
  status?: string | null;
  /** Function routing slug (scope:name). Links to function_definitions.task_identifier by convention — no FK. */
  taskIdentifier?: string | null;
}
/** Function definitions — registered cloud functions with routing, queue, and retry configuration */
export interface PlatformFunctionDefinition {
  createdAt?: string | null;
  /** Human-readable description of what this function does */
  description?: string | null;
  id: string;
  /** Whether this function is a built-in platform function (synced from platform) vs user-created */
  isBuiltIn?: boolean | null;
  /** Whether this function can be called via function_invocations (public API). Default false = internal-only via add_job() */
  isInvocable?: boolean | null;
  /** Maximum retry attempts for the underlying job */
  maxAttempts?: number | null;
  /** Function name within scope (e.g. send_verification_link, process_file_embedding) */
  name?: string | null;
  /** Namespace this function belongs to (FK to namespaces table) */
  namespaceId?: string | null;
  /** Job priority (lower = higher priority) */
  priority?: number | null;
  /** Job queue name for serialization (e.g. email, ai, default) */
  queueName?: string | null;
  /** Function grouping scope (e.g. email, embed, chunk, custom) */
  scope?: string | null;
  /** Optional service URL override for function dispatch. NULL = use gateway convention (gatewayUrl/task_identifier). Set for customer-deployed functions or external endpoints. */
  serviceUrl?: string | null;
  /** Computed routing slug: scope:name (used by Knative job worker for dispatch) */
  taskIdentifier?: string | null;
  updatedAt?: string | null;
  /** Embedded config requirements: array of (name, required) tuples */
  requiredConfigs?: FunctionRequirement[] | null;
  /** Embedded secret requirements: array of (name, required) tuples */
  requiredSecrets?: FunctionRequirement[] | null;
}
// ============ Relation Helper Types ============
export interface ConnectionResult<T> {
  nodes: T[];
  totalCount: number;
  pageInfo: PageInfo;
}
export interface PageInfo {
  hasNextPage: boolean;
  hasPreviousPage: boolean;
  startCursor?: string | null;
  endCursor?: string | null;
}
// ============ Entity Relation Types ============
export interface GetAllRecordRelations {}
export interface PlatformFunctionGraphRefRelations {}
export interface PlatformFunctionGraphStoreRelations {}
export interface PlatformFunctionGraphObjectRelations {}
export interface OrgFunctionExecutionLogRelations {}
export interface PlatformFunctionGraphCommitRelations {}
export interface PlatformSecretDefinitionRelations {}
export interface PlatformFunctionExecutionLogRelations {}
export interface PlatformFunctionGraphRelations {}
export interface OrgFunctionInvocationRelations {}
export interface PlatformFunctionInvocationRelations {}
export interface PlatformFunctionDefinitionRelations {}
// ============ Entity Types With Relations ============
export type GetAllRecordWithRelations = GetAllRecord & GetAllRecordRelations;
export type PlatformFunctionGraphRefWithRelations = PlatformFunctionGraphRef &
  PlatformFunctionGraphRefRelations;
export type PlatformFunctionGraphStoreWithRelations = PlatformFunctionGraphStore &
  PlatformFunctionGraphStoreRelations;
export type PlatformFunctionGraphObjectWithRelations = PlatformFunctionGraphObject &
  PlatformFunctionGraphObjectRelations;
export type OrgFunctionExecutionLogWithRelations = OrgFunctionExecutionLog &
  OrgFunctionExecutionLogRelations;
export type PlatformFunctionGraphCommitWithRelations = PlatformFunctionGraphCommit &
  PlatformFunctionGraphCommitRelations;
export type PlatformSecretDefinitionWithRelations = PlatformSecretDefinition &
  PlatformSecretDefinitionRelations;
export type PlatformFunctionExecutionLogWithRelations = PlatformFunctionExecutionLog &
  PlatformFunctionExecutionLogRelations;
export type PlatformFunctionGraphWithRelations = PlatformFunctionGraph &
  PlatformFunctionGraphRelations;
export type OrgFunctionInvocationWithRelations = OrgFunctionInvocation &
  OrgFunctionInvocationRelations;
export type PlatformFunctionInvocationWithRelations = PlatformFunctionInvocation &
  PlatformFunctionInvocationRelations;
export type PlatformFunctionDefinitionWithRelations = PlatformFunctionDefinition &
  PlatformFunctionDefinitionRelations;
// ============ Entity Select Types ============
export type GetAllRecordSelect = {
  path?: boolean;
  data?: boolean;
};
export type PlatformFunctionGraphRefSelect = {
  commitId?: boolean;
  databaseId?: boolean;
  id?: boolean;
  name?: boolean;
  storeId?: boolean;
};
export type PlatformFunctionGraphStoreSelect = {
  createdAt?: boolean;
  databaseId?: boolean;
  hash?: boolean;
  id?: boolean;
  name?: boolean;
};
export type PlatformFunctionGraphObjectSelect = {
  createdAt?: boolean;
  data?: boolean;
  databaseId?: boolean;
  id?: boolean;
  kids?: boolean;
  ktree?: boolean;
};
export type OrgFunctionExecutionLogSelect = {
  createdAt?: boolean;
  actorId?: boolean;
  id?: boolean;
  invocationId?: boolean;
  logLevel?: boolean;
  message?: boolean;
  metadata?: boolean;
  taskIdentifier?: boolean;
};
export type PlatformFunctionGraphCommitSelect = {
  authorId?: boolean;
  committerId?: boolean;
  databaseId?: boolean;
  date?: boolean;
  id?: boolean;
  message?: boolean;
  parentIds?: boolean;
  storeId?: boolean;
  treeId?: boolean;
};
export type PlatformSecretDefinitionSelect = {
  annotations?: boolean;
  createdAt?: boolean;
  databaseId?: boolean;
  description?: boolean;
  id?: boolean;
  isBuiltIn?: boolean;
  labels?: boolean;
  name?: boolean;
  updatedAt?: boolean;
};
export type PlatformFunctionExecutionLogSelect = {
  createdAt?: boolean;
  actorId?: boolean;
  databaseId?: boolean;
  id?: boolean;
  invocationId?: boolean;
  logLevel?: boolean;
  message?: boolean;
  metadata?: boolean;
  taskIdentifier?: boolean;
};
export type PlatformFunctionGraphSelect = {
  context?: boolean;
  createdAt?: boolean;
  createdBy?: boolean;
  databaseId?: boolean;
  definitionsCommitId?: boolean;
  description?: boolean;
  entityId?: boolean;
  id?: boolean;
  isValid?: boolean;
  name?: boolean;
  storeId?: boolean;
  updatedAt?: boolean;
  validationErrors?: boolean;
};
export type OrgFunctionInvocationSelect = {
  createdAt?: boolean;
  actorId?: boolean;
  completedAt?: boolean;
  durationMs?: boolean;
  error?: boolean;
  graphExecutionId?: boolean;
  id?: boolean;
  jobId?: boolean;
  parentInvocationId?: boolean;
  payload?: boolean;
  result?: boolean;
  startedAt?: boolean;
  status?: boolean;
  taskIdentifier?: boolean;
};
export type PlatformFunctionInvocationSelect = {
  createdAt?: boolean;
  actorId?: boolean;
  completedAt?: boolean;
  databaseId?: boolean;
  durationMs?: boolean;
  error?: boolean;
  graphExecutionId?: boolean;
  id?: boolean;
  jobId?: boolean;
  parentInvocationId?: boolean;
  payload?: boolean;
  result?: boolean;
  startedAt?: boolean;
  status?: boolean;
  taskIdentifier?: boolean;
};
export type PlatformFunctionDefinitionSelect = {
  createdAt?: boolean;
  description?: boolean;
  id?: boolean;
  isBuiltIn?: boolean;
  isInvocable?: boolean;
  maxAttempts?: boolean;
  name?: boolean;
  namespaceId?: boolean;
  priority?: boolean;
  queueName?: boolean;
  scope?: boolean;
  serviceUrl?: boolean;
  taskIdentifier?: boolean;
  updatedAt?: boolean;
  requiredConfigs?: boolean;
  requiredSecrets?: boolean;
};
// ============ Table Filter Types ============
export interface GetAllRecordFilter {
  path?: StringListFilter;
  data?: JSONFilter;
  and?: GetAllRecordFilter[];
  or?: GetAllRecordFilter[];
  not?: GetAllRecordFilter;
}
export interface PlatformFunctionGraphRefFilter {
  /** Filter by the object’s `commitId` field. */
  commitId?: UUIDFilter;
  /** Filter by the object’s `databaseId` field. */
  databaseId?: UUIDFilter;
  /** Filter by the object’s `id` field. */
  id?: UUIDFilter;
  /** Filter by the object’s `name` field. */
  name?: StringFilter;
  /** Filter by the object’s `storeId` field. */
  storeId?: UUIDFilter;
  /** Checks for all expressions in this list. */
  and?: PlatformFunctionGraphRefFilter[];
  /** Checks for any expressions in this list. */
  or?: PlatformFunctionGraphRefFilter[];
  /** Negates the expression. */
  not?: PlatformFunctionGraphRefFilter;
}
export interface PlatformFunctionGraphStoreFilter {
  /** Filter by the object’s `createdAt` field. */
  createdAt?: DatetimeFilter;
  /** Filter by the object’s `databaseId` field. */
  databaseId?: UUIDFilter;
  /** Filter by the object’s `hash` field. */
  hash?: UUIDFilter;
  /** Filter by the object’s `id` field. */
  id?: UUIDFilter;
  /** Filter by the object’s `name` field. */
  name?: StringFilter;
  /** Checks for all expressions in this list. */
  and?: PlatformFunctionGraphStoreFilter[];
  /** Checks for any expressions in this list. */
  or?: PlatformFunctionGraphStoreFilter[];
  /** Negates the expression. */
  not?: PlatformFunctionGraphStoreFilter;
}
export interface PlatformFunctionGraphObjectFilter {
  /** Filter by the object’s `createdAt` field. */
  createdAt?: DatetimeFilter;
  /** Filter by the object’s `data` field. */
  data?: JSONFilter;
  /** Filter by the object’s `databaseId` field. */
  databaseId?: UUIDFilter;
  /** Filter by the object’s `id` field. */
  id?: UUIDFilter;
  /** Filter by the object’s `kids` field. */
  kids?: UUIDListFilter;
  /** Filter by the object’s `ktree` field. */
  ktree?: StringListFilter;
  /** Checks for all expressions in this list. */
  and?: PlatformFunctionGraphObjectFilter[];
  /** Checks for any expressions in this list. */
  or?: PlatformFunctionGraphObjectFilter[];
  /** Negates the expression. */
  not?: PlatformFunctionGraphObjectFilter;
}
export interface OrgFunctionExecutionLogFilter {
  /** Filter by the object’s `createdAt` field. */
  createdAt?: DatetimeFilter;
  /** Filter by the object’s `actorId` field. */
  actorId?: UUIDFilter;
  /** Filter by the object’s `id` field. */
  id?: UUIDFilter;
  /** Filter by the object’s `invocationId` field. */
  invocationId?: UUIDFilter;
  /** Filter by the object’s `logLevel` field. */
  logLevel?: StringFilter;
  /** Filter by the object’s `message` field. */
  message?: StringFilter;
  /** Filter by the object’s `metadata` field. */
  metadata?: JSONFilter;
  /** Filter by the object’s `taskIdentifier` field. */
  taskIdentifier?: StringFilter;
  /** Checks for all expressions in this list. */
  and?: OrgFunctionExecutionLogFilter[];
  /** Checks for any expressions in this list. */
  or?: OrgFunctionExecutionLogFilter[];
  /** Negates the expression. */
  not?: OrgFunctionExecutionLogFilter;
}
export interface PlatformFunctionGraphCommitFilter {
  /** Filter by the object’s `authorId` field. */
  authorId?: UUIDFilter;
  /** Filter by the object’s `committerId` field. */
  committerId?: UUIDFilter;
  /** Filter by the object’s `databaseId` field. */
  databaseId?: UUIDFilter;
  /** Filter by the object’s `date` field. */
  date?: DatetimeFilter;
  /** Filter by the object’s `id` field. */
  id?: UUIDFilter;
  /** Filter by the object’s `message` field. */
  message?: StringFilter;
  /** Filter by the object’s `parentIds` field. */
  parentIds?: UUIDListFilter;
  /** Filter by the object’s `storeId` field. */
  storeId?: UUIDFilter;
  /** Filter by the object’s `treeId` field. */
  treeId?: UUIDFilter;
  /** Checks for all expressions in this list. */
  and?: PlatformFunctionGraphCommitFilter[];
  /** Checks for any expressions in this list. */
  or?: PlatformFunctionGraphCommitFilter[];
  /** Negates the expression. */
  not?: PlatformFunctionGraphCommitFilter;
}
export interface PlatformSecretDefinitionFilter {
  /** Filter by the object’s `annotations` field. */
  annotations?: JSONFilter;
  /** Filter by the object’s `createdAt` field. */
  createdAt?: DatetimeFilter;
  /** Filter by the object’s `databaseId` field. */
  databaseId?: UUIDFilter;
  /** Filter by the object’s `description` field. */
  description?: StringFilter;
  /** Filter by the object’s `id` field. */
  id?: UUIDFilter;
  /** Filter by the object’s `isBuiltIn` field. */
  isBuiltIn?: BooleanFilter;
  /** Filter by the object’s `labels` field. */
  labels?: JSONFilter;
  /** Filter by the object’s `name` field. */
  name?: StringFilter;
  /** Filter by the object’s `updatedAt` field. */
  updatedAt?: DatetimeFilter;
  /** Checks for all expressions in this list. */
  and?: PlatformSecretDefinitionFilter[];
  /** Checks for any expressions in this list. */
  or?: PlatformSecretDefinitionFilter[];
  /** Negates the expression. */
  not?: PlatformSecretDefinitionFilter;
}
export interface PlatformFunctionExecutionLogFilter {
  /** Filter by the object’s `createdAt` field. */
  createdAt?: DatetimeFilter;
  /** Filter by the object’s `actorId` field. */
  actorId?: UUIDFilter;
  /** Filter by the object’s `databaseId` field. */
  databaseId?: UUIDFilter;
  /** Filter by the object’s `id` field. */
  id?: UUIDFilter;
  /** Filter by the object’s `invocationId` field. */
  invocationId?: UUIDFilter;
  /** Filter by the object’s `logLevel` field. */
  logLevel?: StringFilter;
  /** Filter by the object’s `message` field. */
  message?: StringFilter;
  /** Filter by the object’s `metadata` field. */
  metadata?: JSONFilter;
  /** Filter by the object’s `taskIdentifier` field. */
  taskIdentifier?: StringFilter;
  /** Checks for all expressions in this list. */
  and?: PlatformFunctionExecutionLogFilter[];
  /** Checks for any expressions in this list. */
  or?: PlatformFunctionExecutionLogFilter[];
  /** Negates the expression. */
  not?: PlatformFunctionExecutionLogFilter;
}
export interface PlatformFunctionGraphFilter {
  /** Filter by the object’s `context` field. */
  context?: StringFilter;
  /** Filter by the object’s `createdAt` field. */
  createdAt?: DatetimeFilter;
  /** Filter by the object’s `createdBy` field. */
  createdBy?: UUIDFilter;
  /** Filter by the object’s `databaseId` field. */
  databaseId?: UUIDFilter;
  /** Filter by the object’s `definitionsCommitId` field. */
  definitionsCommitId?: UUIDFilter;
  /** Filter by the object’s `description` field. */
  description?: StringFilter;
  /** Filter by the object’s `entityId` field. */
  entityId?: UUIDFilter;
  /** Filter by the object’s `id` field. */
  id?: UUIDFilter;
  /** Filter by the object’s `isValid` field. */
  isValid?: BooleanFilter;
  /** Filter by the object’s `name` field. */
  name?: StringFilter;
  /** Filter by the object’s `storeId` field. */
  storeId?: UUIDFilter;
  /** Filter by the object’s `updatedAt` field. */
  updatedAt?: DatetimeFilter;
  /** Filter by the object’s `validationErrors` field. */
  validationErrors?: JSONFilter;
  /** Checks for all expressions in this list. */
  and?: PlatformFunctionGraphFilter[];
  /** Checks for any expressions in this list. */
  or?: PlatformFunctionGraphFilter[];
  /** Negates the expression. */
  not?: PlatformFunctionGraphFilter;
}
export interface OrgFunctionInvocationFilter {
  /** Filter by the object’s `createdAt` field. */
  createdAt?: DatetimeFilter;
  /** Filter by the object’s `actorId` field. */
  actorId?: UUIDFilter;
  /** Filter by the object’s `completedAt` field. */
  completedAt?: DatetimeFilter;
  /** Filter by the object’s `durationMs` field. */
  durationMs?: IntFilter;
  /** Filter by the object’s `error` field. */
  error?: StringFilter;
  /** Filter by the object’s `graphExecutionId` field. */
  graphExecutionId?: UUIDFilter;
  /** Filter by the object’s `id` field. */
  id?: UUIDFilter;
  /** Filter by the object’s `jobId` field. */
  jobId?: BigIntFilter;
  /** Filter by the object’s `parentInvocationId` field. */
  parentInvocationId?: UUIDFilter;
  /** Filter by the object’s `payload` field. */
  payload?: JSONFilter;
  /** Filter by the object’s `result` field. */
  result?: JSONFilter;
  /** Filter by the object’s `startedAt` field. */
  startedAt?: DatetimeFilter;
  /** Filter by the object’s `status` field. */
  status?: StringFilter;
  /** Filter by the object’s `taskIdentifier` field. */
  taskIdentifier?: StringFilter;
  /** Checks for all expressions in this list. */
  and?: OrgFunctionInvocationFilter[];
  /** Checks for any expressions in this list. */
  or?: OrgFunctionInvocationFilter[];
  /** Negates the expression. */
  not?: OrgFunctionInvocationFilter;
}
export interface PlatformFunctionInvocationFilter {
  /** Filter by the object’s `createdAt` field. */
  createdAt?: DatetimeFilter;
  /** Filter by the object’s `actorId` field. */
  actorId?: UUIDFilter;
  /** Filter by the object’s `completedAt` field. */
  completedAt?: DatetimeFilter;
  /** Filter by the object’s `databaseId` field. */
  databaseId?: UUIDFilter;
  /** Filter by the object’s `durationMs` field. */
  durationMs?: IntFilter;
  /** Filter by the object’s `error` field. */
  error?: StringFilter;
  /** Filter by the object’s `graphExecutionId` field. */
  graphExecutionId?: UUIDFilter;
  /** Filter by the object’s `id` field. */
  id?: UUIDFilter;
  /** Filter by the object’s `jobId` field. */
  jobId?: BigIntFilter;
  /** Filter by the object’s `parentInvocationId` field. */
  parentInvocationId?: UUIDFilter;
  /** Filter by the object’s `payload` field. */
  payload?: JSONFilter;
  /** Filter by the object’s `result` field. */
  result?: JSONFilter;
  /** Filter by the object’s `startedAt` field. */
  startedAt?: DatetimeFilter;
  /** Filter by the object’s `status` field. */
  status?: StringFilter;
  /** Filter by the object’s `taskIdentifier` field. */
  taskIdentifier?: StringFilter;
  /** Checks for all expressions in this list. */
  and?: PlatformFunctionInvocationFilter[];
  /** Checks for any expressions in this list. */
  or?: PlatformFunctionInvocationFilter[];
  /** Negates the expression. */
  not?: PlatformFunctionInvocationFilter;
}
export interface PlatformFunctionDefinitionFilter {
  /** Filter by the object’s `createdAt` field. */
  createdAt?: DatetimeFilter;
  /** Filter by the object’s `description` field. */
  description?: StringFilter;
  /** Filter by the object’s `id` field. */
  id?: UUIDFilter;
  /** Filter by the object’s `isBuiltIn` field. */
  isBuiltIn?: BooleanFilter;
  /** Filter by the object’s `isInvocable` field. */
  isInvocable?: BooleanFilter;
  /** Filter by the object’s `maxAttempts` field. */
  maxAttempts?: IntFilter;
  /** Filter by the object’s `name` field. */
  name?: StringFilter;
  /** Filter by the object’s `namespaceId` field. */
  namespaceId?: UUIDFilter;
  /** Filter by the object’s `priority` field. */
  priority?: IntFilter;
  /** Filter by the object’s `queueName` field. */
  queueName?: StringFilter;
  /** Filter by the object’s `scope` field. */
  scope?: StringFilter;
  /** Filter by the object’s `serviceUrl` field. */
  serviceUrl?: StringFilter;
  /** Filter by the object’s `taskIdentifier` field. */
  taskIdentifier?: StringFilter;
  /** Filter by the object’s `updatedAt` field. */
  updatedAt?: DatetimeFilter;
  /** Checks for all expressions in this list. */
  and?: PlatformFunctionDefinitionFilter[];
  /** Checks for any expressions in this list. */
  or?: PlatformFunctionDefinitionFilter[];
  /** Negates the expression. */
  not?: PlatformFunctionDefinitionFilter;
}
// ============ OrderBy Types ============
export type GetAllRecordsOrderBy =
  | 'PRIMARY_KEY_ASC'
  | 'PRIMARY_KEY_DESC'
  | 'NATURAL'
  | 'PATH_ASC'
  | 'PATH_DESC'
  | 'DATA_ASC'
  | 'DATA_DESC';
export type PlatformFunctionGraphRefOrderBy =
  | 'NATURAL'
  | 'PRIMARY_KEY_ASC'
  | 'PRIMARY_KEY_DESC'
  | 'COMMIT_ID_ASC'
  | 'COMMIT_ID_DESC'
  | 'DATABASE_ID_ASC'
  | 'DATABASE_ID_DESC'
  | 'ID_ASC'
  | 'ID_DESC'
  | 'NAME_ASC'
  | 'NAME_DESC'
  | 'STORE_ID_ASC'
  | 'STORE_ID_DESC';
export type PlatformFunctionGraphStoreOrderBy =
  | 'NATURAL'
  | 'PRIMARY_KEY_ASC'
  | 'PRIMARY_KEY_DESC'
  | 'CREATED_AT_ASC'
  | 'CREATED_AT_DESC'
  | 'DATABASE_ID_ASC'
  | 'DATABASE_ID_DESC'
  | 'HASH_ASC'
  | 'HASH_DESC'
  | 'ID_ASC'
  | 'ID_DESC'
  | 'NAME_ASC'
  | 'NAME_DESC';
export type PlatformFunctionGraphObjectOrderBy =
  | 'NATURAL'
  | 'PRIMARY_KEY_ASC'
  | 'PRIMARY_KEY_DESC'
  | 'CREATED_AT_ASC'
  | 'CREATED_AT_DESC'
  | 'DATA_ASC'
  | 'DATA_DESC'
  | 'DATABASE_ID_ASC'
  | 'DATABASE_ID_DESC'
  | 'ID_ASC'
  | 'ID_DESC'
  | 'KIDS_ASC'
  | 'KIDS_DESC'
  | 'KTREE_ASC'
  | 'KTREE_DESC';
export type OrgFunctionExecutionLogOrderBy =
  | 'NATURAL'
  | 'PRIMARY_KEY_ASC'
  | 'PRIMARY_KEY_DESC'
  | 'CREATED_AT_ASC'
  | 'CREATED_AT_DESC'
  | 'ACTOR_ID_ASC'
  | 'ACTOR_ID_DESC'
  | 'ID_ASC'
  | 'ID_DESC'
  | 'INVOCATION_ID_ASC'
  | 'INVOCATION_ID_DESC'
  | 'LOG_LEVEL_ASC'
  | 'LOG_LEVEL_DESC'
  | 'MESSAGE_ASC'
  | 'MESSAGE_DESC'
  | 'METADATA_ASC'
  | 'METADATA_DESC'
  | 'TASK_IDENTIFIER_ASC'
  | 'TASK_IDENTIFIER_DESC';
export type PlatformFunctionGraphCommitOrderBy =
  | 'NATURAL'
  | 'PRIMARY_KEY_ASC'
  | 'PRIMARY_KEY_DESC'
  | 'AUTHOR_ID_ASC'
  | 'AUTHOR_ID_DESC'
  | 'COMMITTER_ID_ASC'
  | 'COMMITTER_ID_DESC'
  | 'DATABASE_ID_ASC'
  | 'DATABASE_ID_DESC'
  | 'DATE_ASC'
  | 'DATE_DESC'
  | 'ID_ASC'
  | 'ID_DESC'
  | 'MESSAGE_ASC'
  | 'MESSAGE_DESC'
  | 'PARENT_IDS_ASC'
  | 'PARENT_IDS_DESC'
  | 'STORE_ID_ASC'
  | 'STORE_ID_DESC'
  | 'TREE_ID_ASC'
  | 'TREE_ID_DESC';
export type PlatformSecretDefinitionOrderBy =
  | 'NATURAL'
  | 'PRIMARY_KEY_ASC'
  | 'PRIMARY_KEY_DESC'
  | 'ANNOTATIONS_ASC'
  | 'ANNOTATIONS_DESC'
  | 'CREATED_AT_ASC'
  | 'CREATED_AT_DESC'
  | 'DATABASE_ID_ASC'
  | 'DATABASE_ID_DESC'
  | 'DESCRIPTION_ASC'
  | 'DESCRIPTION_DESC'
  | 'ID_ASC'
  | 'ID_DESC'
  | 'IS_BUILT_IN_ASC'
  | 'IS_BUILT_IN_DESC'
  | 'LABELS_ASC'
  | 'LABELS_DESC'
  | 'NAME_ASC'
  | 'NAME_DESC'
  | 'UPDATED_AT_ASC'
  | 'UPDATED_AT_DESC';
export type PlatformFunctionExecutionLogOrderBy =
  | 'NATURAL'
  | 'PRIMARY_KEY_ASC'
  | 'PRIMARY_KEY_DESC'
  | 'CREATED_AT_ASC'
  | 'CREATED_AT_DESC'
  | 'ACTOR_ID_ASC'
  | 'ACTOR_ID_DESC'
  | 'DATABASE_ID_ASC'
  | 'DATABASE_ID_DESC'
  | 'ID_ASC'
  | 'ID_DESC'
  | 'INVOCATION_ID_ASC'
  | 'INVOCATION_ID_DESC'
  | 'LOG_LEVEL_ASC'
  | 'LOG_LEVEL_DESC'
  | 'MESSAGE_ASC'
  | 'MESSAGE_DESC'
  | 'METADATA_ASC'
  | 'METADATA_DESC'
  | 'TASK_IDENTIFIER_ASC'
  | 'TASK_IDENTIFIER_DESC';
export type PlatformFunctionGraphOrderBy =
  | 'NATURAL'
  | 'PRIMARY_KEY_ASC'
  | 'PRIMARY_KEY_DESC'
  | 'CONTEXT_ASC'
  | 'CONTEXT_DESC'
  | 'CREATED_AT_ASC'
  | 'CREATED_AT_DESC'
  | 'CREATED_BY_ASC'
  | 'CREATED_BY_DESC'
  | 'DATABASE_ID_ASC'
  | 'DATABASE_ID_DESC'
  | 'DEFINITIONS_COMMIT_ID_ASC'
  | 'DEFINITIONS_COMMIT_ID_DESC'
  | 'DESCRIPTION_ASC'
  | 'DESCRIPTION_DESC'
  | 'ENTITY_ID_ASC'
  | 'ENTITY_ID_DESC'
  | 'ID_ASC'
  | 'ID_DESC'
  | 'IS_VALID_ASC'
  | 'IS_VALID_DESC'
  | 'NAME_ASC'
  | 'NAME_DESC'
  | 'STORE_ID_ASC'
  | 'STORE_ID_DESC'
  | 'UPDATED_AT_ASC'
  | 'UPDATED_AT_DESC'
  | 'VALIDATION_ERRORS_ASC'
  | 'VALIDATION_ERRORS_DESC';
export type OrgFunctionInvocationOrderBy =
  | 'NATURAL'
  | 'PRIMARY_KEY_ASC'
  | 'PRIMARY_KEY_DESC'
  | 'CREATED_AT_ASC'
  | 'CREATED_AT_DESC'
  | 'ACTOR_ID_ASC'
  | 'ACTOR_ID_DESC'
  | 'COMPLETED_AT_ASC'
  | 'COMPLETED_AT_DESC'
  | 'DURATION_MS_ASC'
  | 'DURATION_MS_DESC'
  | 'ERROR_ASC'
  | 'ERROR_DESC'
  | 'GRAPH_EXECUTION_ID_ASC'
  | 'GRAPH_EXECUTION_ID_DESC'
  | 'ID_ASC'
  | 'ID_DESC'
  | 'JOB_ID_ASC'
  | 'JOB_ID_DESC'
  | 'PARENT_INVOCATION_ID_ASC'
  | 'PARENT_INVOCATION_ID_DESC'
  | 'PAYLOAD_ASC'
  | 'PAYLOAD_DESC'
  | 'RESULT_ASC'
  | 'RESULT_DESC'
  | 'STARTED_AT_ASC'
  | 'STARTED_AT_DESC'
  | 'STATUS_ASC'
  | 'STATUS_DESC'
  | 'TASK_IDENTIFIER_ASC'
  | 'TASK_IDENTIFIER_DESC';
export type PlatformFunctionInvocationOrderBy =
  | 'NATURAL'
  | 'PRIMARY_KEY_ASC'
  | 'PRIMARY_KEY_DESC'
  | 'CREATED_AT_ASC'
  | 'CREATED_AT_DESC'
  | 'ACTOR_ID_ASC'
  | 'ACTOR_ID_DESC'
  | 'COMPLETED_AT_ASC'
  | 'COMPLETED_AT_DESC'
  | 'DATABASE_ID_ASC'
  | 'DATABASE_ID_DESC'
  | 'DURATION_MS_ASC'
  | 'DURATION_MS_DESC'
  | 'ERROR_ASC'
  | 'ERROR_DESC'
  | 'GRAPH_EXECUTION_ID_ASC'
  | 'GRAPH_EXECUTION_ID_DESC'
  | 'ID_ASC'
  | 'ID_DESC'
  | 'JOB_ID_ASC'
  | 'JOB_ID_DESC'
  | 'PARENT_INVOCATION_ID_ASC'
  | 'PARENT_INVOCATION_ID_DESC'
  | 'PAYLOAD_ASC'
  | 'PAYLOAD_DESC'
  | 'RESULT_ASC'
  | 'RESULT_DESC'
  | 'STARTED_AT_ASC'
  | 'STARTED_AT_DESC'
  | 'STATUS_ASC'
  | 'STATUS_DESC'
  | 'TASK_IDENTIFIER_ASC'
  | 'TASK_IDENTIFIER_DESC';
export type PlatformFunctionDefinitionOrderBy =
  | 'NATURAL'
  | 'PRIMARY_KEY_ASC'
  | 'PRIMARY_KEY_DESC'
  | 'CREATED_AT_ASC'
  | 'CREATED_AT_DESC'
  | 'DESCRIPTION_ASC'
  | 'DESCRIPTION_DESC'
  | 'ID_ASC'
  | 'ID_DESC'
  | 'IS_BUILT_IN_ASC'
  | 'IS_BUILT_IN_DESC'
  | 'IS_INVOCABLE_ASC'
  | 'IS_INVOCABLE_DESC'
  | 'MAX_ATTEMPTS_ASC'
  | 'MAX_ATTEMPTS_DESC'
  | 'NAME_ASC'
  | 'NAME_DESC'
  | 'NAMESPACE_ID_ASC'
  | 'NAMESPACE_ID_DESC'
  | 'PRIORITY_ASC'
  | 'PRIORITY_DESC'
  | 'QUEUE_NAME_ASC'
  | 'QUEUE_NAME_DESC'
  | 'SCOPE_ASC'
  | 'SCOPE_DESC'
  | 'SERVICE_URL_ASC'
  | 'SERVICE_URL_DESC'
  | 'TASK_IDENTIFIER_ASC'
  | 'TASK_IDENTIFIER_DESC'
  | 'UPDATED_AT_ASC'
  | 'UPDATED_AT_DESC'
  | 'REQUIRED_CONFIGS_ASC'
  | 'REQUIRED_CONFIGS_DESC'
  | 'REQUIRED_SECRETS_ASC'
  | 'REQUIRED_SECRETS_DESC';
// ============ CRUD Input Types ============
export interface CreateGetAllRecordInput {
  clientMutationId?: string;
  getAllRecord: {
    path?: string[];
    data?: Record<string, unknown>;
  };
}
export interface GetAllRecordPatch {
  path?: string[] | null;
  data?: Record<string, unknown> | null;
}
export interface UpdateGetAllRecordInput {
  clientMutationId?: string;
  id: string;
  getAllRecordPatch: GetAllRecordPatch;
}
export interface DeleteGetAllRecordInput {
  clientMutationId?: string;
  id: string;
}
export interface CreatePlatformFunctionGraphRefInput {
  clientMutationId?: string;
  platformFunctionGraphRef: {
    commitId?: string;
    databaseId: string;
    name: string;
    storeId: string;
  };
}
export interface PlatformFunctionGraphRefPatch {
  commitId?: string | null;
  databaseId?: string | null;
  name?: string | null;
  storeId?: string | null;
}
export interface UpdatePlatformFunctionGraphRefInput {
  clientMutationId?: string;
  id: string;
  platformFunctionGraphRefPatch: PlatformFunctionGraphRefPatch;
}
export interface DeletePlatformFunctionGraphRefInput {
  clientMutationId?: string;
  id: string;
}
export interface CreatePlatformFunctionGraphStoreInput {
  clientMutationId?: string;
  platformFunctionGraphStore: {
    databaseId: string;
    hash?: string;
    name: string;
  };
}
export interface PlatformFunctionGraphStorePatch {
  databaseId?: string | null;
  hash?: string | null;
  name?: string | null;
}
export interface UpdatePlatformFunctionGraphStoreInput {
  clientMutationId?: string;
  id: string;
  platformFunctionGraphStorePatch: PlatformFunctionGraphStorePatch;
}
export interface DeletePlatformFunctionGraphStoreInput {
  clientMutationId?: string;
  id: string;
}
export interface CreatePlatformFunctionGraphObjectInput {
  clientMutationId?: string;
  platformFunctionGraphObject: {
    data?: Record<string, unknown>;
    databaseId: string;
    kids?: string[];
    ktree?: string[];
  };
}
export interface PlatformFunctionGraphObjectPatch {
  data?: Record<string, unknown> | null;
  databaseId?: string | null;
  kids?: string[] | null;
  ktree?: string[] | null;
}
export interface UpdatePlatformFunctionGraphObjectInput {
  clientMutationId?: string;
  id: string;
  platformFunctionGraphObjectPatch: PlatformFunctionGraphObjectPatch;
}
export interface DeletePlatformFunctionGraphObjectInput {
  clientMutationId?: string;
  id: string;
}
export interface CreateOrgFunctionExecutionLogInput {
  clientMutationId?: string;
  orgFunctionExecutionLog: {
    actorId?: string;
    invocationId?: string;
    logLevel?: string;
    message: string;
    metadata?: Record<string, unknown>;
    taskIdentifier?: string;
  };
}
export interface OrgFunctionExecutionLogPatch {
  actorId?: string | null;
  invocationId?: string | null;
  logLevel?: string | null;
  message?: string | null;
  metadata?: Record<string, unknown> | null;
  taskIdentifier?: string | null;
}
export interface UpdateOrgFunctionExecutionLogInput {
  clientMutationId?: string;
  id: string;
  orgFunctionExecutionLogPatch: OrgFunctionExecutionLogPatch;
}
export interface DeleteOrgFunctionExecutionLogInput {
  clientMutationId?: string;
  id: string;
}
export interface CreatePlatformFunctionGraphCommitInput {
  clientMutationId?: string;
  platformFunctionGraphCommit: {
    authorId?: string;
    committerId?: string;
    databaseId: string;
    date?: string;
    message?: string;
    parentIds?: string[];
    storeId: string;
    treeId?: string;
  };
}
export interface PlatformFunctionGraphCommitPatch {
  authorId?: string | null;
  committerId?: string | null;
  databaseId?: string | null;
  date?: string | null;
  message?: string | null;
  parentIds?: string[] | null;
  storeId?: string | null;
  treeId?: string | null;
}
export interface UpdatePlatformFunctionGraphCommitInput {
  clientMutationId?: string;
  id: string;
  platformFunctionGraphCommitPatch: PlatformFunctionGraphCommitPatch;
}
export interface DeletePlatformFunctionGraphCommitInput {
  clientMutationId?: string;
  id: string;
}
export interface CreatePlatformSecretDefinitionInput {
  clientMutationId?: string;
  platformSecretDefinition: {
    annotations?: Record<string, unknown>;
    databaseId: string;
    description?: string;
    isBuiltIn?: boolean;
    labels?: Record<string, unknown>;
    name: string;
  };
}
export interface PlatformSecretDefinitionPatch {
  annotations?: Record<string, unknown> | null;
  databaseId?: string | null;
  description?: string | null;
  isBuiltIn?: boolean | null;
  labels?: Record<string, unknown> | null;
  name?: string | null;
}
export interface UpdatePlatformSecretDefinitionInput {
  clientMutationId?: string;
  id: string;
  platformSecretDefinitionPatch: PlatformSecretDefinitionPatch;
}
export interface DeletePlatformSecretDefinitionInput {
  clientMutationId?: string;
  id: string;
}
export interface CreatePlatformFunctionExecutionLogInput {
  clientMutationId?: string;
  platformFunctionExecutionLog: {
    actorId?: string;
    databaseId: string;
    invocationId?: string;
    logLevel?: string;
    message: string;
    metadata?: Record<string, unknown>;
    taskIdentifier?: string;
  };
}
export interface PlatformFunctionExecutionLogPatch {
  actorId?: string | null;
  databaseId?: string | null;
  invocationId?: string | null;
  logLevel?: string | null;
  message?: string | null;
  metadata?: Record<string, unknown> | null;
  taskIdentifier?: string | null;
}
export interface UpdatePlatformFunctionExecutionLogInput {
  clientMutationId?: string;
  id: string;
  platformFunctionExecutionLogPatch: PlatformFunctionExecutionLogPatch;
}
export interface DeletePlatformFunctionExecutionLogInput {
  clientMutationId?: string;
  id: string;
}
export interface CreatePlatformFunctionGraphInput {
  clientMutationId?: string;
  platformFunctionGraph: {
    context?: string;
    createdBy?: string;
    databaseId: string;
    definitionsCommitId?: string;
    description?: string;
    entityId?: string;
    isValid?: boolean;
    name: string;
    storeId: string;
    validationErrors?: Record<string, unknown>;
  };
}
export interface PlatformFunctionGraphPatch {
  context?: string | null;
  createdBy?: string | null;
  databaseId?: string | null;
  definitionsCommitId?: string | null;
  description?: string | null;
  entityId?: string | null;
  isValid?: boolean | null;
  name?: string | null;
  storeId?: string | null;
  validationErrors?: Record<string, unknown> | null;
}
export interface UpdatePlatformFunctionGraphInput {
  clientMutationId?: string;
  id: string;
  platformFunctionGraphPatch: PlatformFunctionGraphPatch;
}
export interface DeletePlatformFunctionGraphInput {
  clientMutationId?: string;
  id: string;
}
export interface CreateOrgFunctionInvocationInput {
  clientMutationId?: string;
  orgFunctionInvocation: {
    actorId?: string;
    completedAt?: string;
    durationMs?: number;
    error?: string;
    graphExecutionId?: string;
    jobId?: string;
    parentInvocationId?: string;
    payload?: Record<string, unknown>;
    result?: Record<string, unknown>;
    startedAt?: string;
    status?: string;
    taskIdentifier: string;
  };
}
export interface OrgFunctionInvocationPatch {
  actorId?: string | null;
  completedAt?: string | null;
  durationMs?: number | null;
  error?: string | null;
  graphExecutionId?: string | null;
  jobId?: string | null;
  parentInvocationId?: string | null;
  payload?: Record<string, unknown> | null;
  result?: Record<string, unknown> | null;
  startedAt?: string | null;
  status?: string | null;
  taskIdentifier?: string | null;
}
export interface UpdateOrgFunctionInvocationInput {
  clientMutationId?: string;
  id: string;
  orgFunctionInvocationPatch: OrgFunctionInvocationPatch;
}
export interface DeleteOrgFunctionInvocationInput {
  clientMutationId?: string;
  id: string;
}
export interface CreatePlatformFunctionInvocationInput {
  clientMutationId?: string;
  platformFunctionInvocation: {
    actorId?: string;
    completedAt?: string;
    databaseId: string;
    durationMs?: number;
    error?: string;
    graphExecutionId?: string;
    jobId?: string;
    parentInvocationId?: string;
    payload?: Record<string, unknown>;
    result?: Record<string, unknown>;
    startedAt?: string;
    status?: string;
    taskIdentifier: string;
  };
}
export interface PlatformFunctionInvocationPatch {
  actorId?: string | null;
  completedAt?: string | null;
  databaseId?: string | null;
  durationMs?: number | null;
  error?: string | null;
  graphExecutionId?: string | null;
  jobId?: string | null;
  parentInvocationId?: string | null;
  payload?: Record<string, unknown> | null;
  result?: Record<string, unknown> | null;
  startedAt?: string | null;
  status?: string | null;
  taskIdentifier?: string | null;
}
export interface UpdatePlatformFunctionInvocationInput {
  clientMutationId?: string;
  id: string;
  platformFunctionInvocationPatch: PlatformFunctionInvocationPatch;
}
export interface DeletePlatformFunctionInvocationInput {
  clientMutationId?: string;
  id: string;
}
export interface CreatePlatformFunctionDefinitionInput {
  clientMutationId?: string;
  platformFunctionDefinition: {
    description?: string;
    isBuiltIn?: boolean;
    isInvocable?: boolean;
    maxAttempts?: number;
    name: string;
    namespaceId?: string;
    priority?: number;
    queueName?: string;
    scope: string;
    serviceUrl?: string;
    taskIdentifier: string;
    requiredConfigs?: FunctionRequirementInput[];
    requiredSecrets?: FunctionRequirementInput[];
  };
}
export interface PlatformFunctionDefinitionPatch {
  description?: string | null;
  isBuiltIn?: boolean | null;
  isInvocable?: boolean | null;
  maxAttempts?: number | null;
  name?: string | null;
  namespaceId?: string | null;
  priority?: number | null;
  queueName?: string | null;
  scope?: string | null;
  serviceUrl?: string | null;
  taskIdentifier?: string | null;
  requiredConfigs?: FunctionRequirementInput[] | null;
  requiredSecrets?: FunctionRequirementInput[] | null;
}
export interface UpdatePlatformFunctionDefinitionInput {
  clientMutationId?: string;
  id: string;
  platformFunctionDefinitionPatch: PlatformFunctionDefinitionPatch;
}
export interface DeletePlatformFunctionDefinitionInput {
  clientMutationId?: string;
  id: string;
}
// ============ Connection Fields Map ============
export const connectionFieldsMap = {} as Record<string, Record<string, string>>;
// ============ Custom Input Types (from schema) ============
export interface PlatformValidateFunctionGraphInput {
  clientMutationId?: string;
  graphId?: string;
}
export interface InitEmptyRepoInput {
  clientMutationId?: string;
  sId?: string;
  storeId?: string;
}
export interface PlatformImportDefinitionsInput {
  clientMutationId?: string;
  graphId?: string;
  sourceScopeId?: string;
  sourceCommitId?: string;
  contexts?: string[];
}
export interface SetDataAtPathInput {
  clientMutationId?: string;
  sId?: string;
  root?: string;
  path?: string[];
  data?: Record<string, unknown>;
}
export interface PlatformCopyGraphInput {
  clientMutationId?: string;
  databaseId?: string;
  graphId?: string;
  name?: string;
}
export interface PlatformSaveGraphInput {
  clientMutationId?: string;
  graphId?: string;
  rootHash?: string;
  message?: string;
}
export interface PlatformAddEdgeAndSaveInput {
  clientMutationId?: string;
  graphId?: string;
  srcNode?: string;
  srcPort?: string;
  dstNode?: string;
  dstPort?: string;
  message?: string;
}
export interface PlatformAddNodeAndSaveInput {
  clientMutationId?: string;
  graphId?: string;
  nodeName?: string;
  nodeType?: string;
  props?: Record<string, unknown>;
  meta?: Record<string, unknown>;
  message?: string;
}
export interface PlatformCreateFunctionGraphInput {
  clientMutationId?: string;
  databaseId?: string;
  name?: string;
  context?: string;
  description?: string;
  entityId?: string;
  createdBy?: string;
  definitionsCommitId?: string;
}
export interface PlatformAddEdgeInput {
  clientMutationId?: string;
  databaseId?: string;
  rootHash?: string;
  srcNode?: string;
  srcPort?: string;
  dstNode?: string;
  dstPort?: string;
  context?: string;
  graphName?: string;
}
export interface PlatformAddNodeInput {
  clientMutationId?: string;
  databaseId?: string;
  rootHash?: string;
  nodeName?: string;
  nodeType?: string;
  context?: string;
  graphName?: string;
  props?: Record<string, unknown>;
  meta?: Record<string, unknown>;
}
export interface PlatformImportGraphJsonInput {
  clientMutationId?: string;
  databaseId?: string;
  name?: string;
  graphJson?: Record<string, unknown>;
  context?: string;
  description?: string;
  entityId?: string;
  createdBy?: string;
  definitionsCommitId?: string;
}
export interface InsertNodeAtPathInput {
  clientMutationId?: string;
  sId?: string;
  root?: string;
  path?: string[];
  data?: Record<string, unknown>;
  kids?: string[];
  ktree?: string[];
}
export interface PlatformStartExecutionInput {
  clientMutationId?: string;
  graphId?: string;
  inputPayload?: Record<string, unknown>;
  outputNode?: string;
  outputPort?: string;
  maxTicks?: number;
  maxPendingJobs?: number;
  timeoutInterval?: IntervalInput;
  parentExecutionId?: string;
  parentNodeName?: string;
}
export interface ProvisionBucketInput {
  /** The logical bucket key (e.g., "public", "private") */
  bucketKey: string;
  /**
   * Owner entity ID for entity-scoped bucket provisioning.
   * Omit for app-level (database-wide) storage.
   */
  ownerId?: string;
}
/** An interval of time that has passed where the smallest distinct unit is a second. */
export interface IntervalInput {
  /**
   * A quantity of seconds. This is the only non-integer field, as all the other
   * fields will dump their overflow into a smaller unit of time. Intervals don’t
   * have a smaller unit than seconds.
   */
  seconds?: number;
  /** A quantity of minutes. */
  minutes?: number;
  /** A quantity of hours. */
  hours?: number;
  /** A quantity of days. */
  days?: number;
  /** A quantity of months. */
  months?: number;
  /** A quantity of years. */
  years?: number;
}
// ============ Payload/Return Types (for custom operations) ============
export interface PlatformValidateFunctionGraphPayload {
  clientMutationId?: string | null;
  result?: boolean | null;
}
export type PlatformValidateFunctionGraphPayloadSelect = {
  clientMutationId?: boolean;
  result?: boolean;
};
export interface InitEmptyRepoPayload {
  clientMutationId?: string | null;
}
export type InitEmptyRepoPayloadSelect = {
  clientMutationId?: boolean;
};
export interface PlatformImportDefinitionsPayload {
  clientMutationId?: string | null;
}
export type PlatformImportDefinitionsPayloadSelect = {
  clientMutationId?: boolean;
};
export interface SetDataAtPathPayload {
  clientMutationId?: string | null;
  result?: string | null;
}
export type SetDataAtPathPayloadSelect = {
  clientMutationId?: boolean;
  result?: boolean;
};
export interface PlatformCopyGraphPayload {
  clientMutationId?: string | null;
  result?: string | null;
}
export type PlatformCopyGraphPayloadSelect = {
  clientMutationId?: boolean;
  result?: boolean;
};
export interface PlatformSaveGraphPayload {
  clientMutationId?: string | null;
  result?: string | null;
}
export type PlatformSaveGraphPayloadSelect = {
  clientMutationId?: boolean;
  result?: boolean;
};
export interface PlatformAddEdgeAndSavePayload {
  clientMutationId?: string | null;
  result?: string | null;
}
export type PlatformAddEdgeAndSavePayloadSelect = {
  clientMutationId?: boolean;
  result?: boolean;
};
export interface PlatformAddNodeAndSavePayload {
  clientMutationId?: string | null;
  result?: string | null;
}
export type PlatformAddNodeAndSavePayloadSelect = {
  clientMutationId?: boolean;
  result?: boolean;
};
export interface PlatformCreateFunctionGraphPayload {
  clientMutationId?: string | null;
  result?: string | null;
}
export type PlatformCreateFunctionGraphPayloadSelect = {
  clientMutationId?: boolean;
  result?: boolean;
};
export interface PlatformAddEdgePayload {
  clientMutationId?: string | null;
  result?: string | null;
}
export type PlatformAddEdgePayloadSelect = {
  clientMutationId?: boolean;
  result?: boolean;
};
export interface PlatformAddNodePayload {
  clientMutationId?: string | null;
  result?: string | null;
}
export type PlatformAddNodePayloadSelect = {
  clientMutationId?: boolean;
  result?: boolean;
};
export interface PlatformImportGraphJsonPayload {
  clientMutationId?: string | null;
  result?: string | null;
}
export type PlatformImportGraphJsonPayloadSelect = {
  clientMutationId?: boolean;
  result?: boolean;
};
export interface InsertNodeAtPathPayload {
  clientMutationId?: string | null;
  result?: string | null;
}
export type InsertNodeAtPathPayloadSelect = {
  clientMutationId?: boolean;
  result?: boolean;
};
export interface PlatformStartExecutionPayload {
  clientMutationId?: string | null;
  result?: string | null;
}
export type PlatformStartExecutionPayloadSelect = {
  clientMutationId?: boolean;
  result?: boolean;
};
export interface ProvisionBucketPayload {
  /** Whether provisioning succeeded */
  success: boolean;
  /** The S3 bucket name that was provisioned */
  bucketName: string;
  /** The access type applied */
  accessType: string;
  /** The storage provider used */
  provider: string;
  /** The S3 endpoint (null for AWS S3 default) */
  endpoint?: string | null;
  /** Error message if provisioning failed */
  error?: string | null;
}
export type ProvisionBucketPayloadSelect = {
  success?: boolean;
  bucketName?: boolean;
  accessType?: boolean;
  provider?: boolean;
  endpoint?: boolean;
  error?: boolean;
};
export interface CreatePlatformFunctionGraphRefPayload {
  clientMutationId?: string | null;
  /** The `PlatformFunctionGraphRef` that was created by this mutation. */
  platformFunctionGraphRef?: PlatformFunctionGraphRef | null;
  platformFunctionGraphRefEdge?: PlatformFunctionGraphRefEdge | null;
}
export type CreatePlatformFunctionGraphRefPayloadSelect = {
  clientMutationId?: boolean;
  platformFunctionGraphRef?: {
    select: PlatformFunctionGraphRefSelect;
  };
  platformFunctionGraphRefEdge?: {
    select: PlatformFunctionGraphRefEdgeSelect;
  };
};
export interface UpdatePlatformFunctionGraphRefPayload {
  clientMutationId?: string | null;
  /** The `PlatformFunctionGraphRef` that was updated by this mutation. */
  platformFunctionGraphRef?: PlatformFunctionGraphRef | null;
  platformFunctionGraphRefEdge?: PlatformFunctionGraphRefEdge | null;
}
export type UpdatePlatformFunctionGraphRefPayloadSelect = {
  clientMutationId?: boolean;
  platformFunctionGraphRef?: {
    select: PlatformFunctionGraphRefSelect;
  };
  platformFunctionGraphRefEdge?: {
    select: PlatformFunctionGraphRefEdgeSelect;
  };
};
export interface DeletePlatformFunctionGraphRefPayload {
  clientMutationId?: string | null;
  /** The `PlatformFunctionGraphRef` that was deleted by this mutation. */
  platformFunctionGraphRef?: PlatformFunctionGraphRef | null;
  platformFunctionGraphRefEdge?: PlatformFunctionGraphRefEdge | null;
}
export type DeletePlatformFunctionGraphRefPayloadSelect = {
  clientMutationId?: boolean;
  platformFunctionGraphRef?: {
    select: PlatformFunctionGraphRefSelect;
  };
  platformFunctionGraphRefEdge?: {
    select: PlatformFunctionGraphRefEdgeSelect;
  };
};
export interface CreatePlatformFunctionGraphStorePayload {
  clientMutationId?: string | null;
  /** The `PlatformFunctionGraphStore` that was created by this mutation. */
  platformFunctionGraphStore?: PlatformFunctionGraphStore | null;
  platformFunctionGraphStoreEdge?: PlatformFunctionGraphStoreEdge | null;
}
export type CreatePlatformFunctionGraphStorePayloadSelect = {
  clientMutationId?: boolean;
  platformFunctionGraphStore?: {
    select: PlatformFunctionGraphStoreSelect;
  };
  platformFunctionGraphStoreEdge?: {
    select: PlatformFunctionGraphStoreEdgeSelect;
  };
};
export interface UpdatePlatformFunctionGraphStorePayload {
  clientMutationId?: string | null;
  /** The `PlatformFunctionGraphStore` that was updated by this mutation. */
  platformFunctionGraphStore?: PlatformFunctionGraphStore | null;
  platformFunctionGraphStoreEdge?: PlatformFunctionGraphStoreEdge | null;
}
export type UpdatePlatformFunctionGraphStorePayloadSelect = {
  clientMutationId?: boolean;
  platformFunctionGraphStore?: {
    select: PlatformFunctionGraphStoreSelect;
  };
  platformFunctionGraphStoreEdge?: {
    select: PlatformFunctionGraphStoreEdgeSelect;
  };
};
export interface DeletePlatformFunctionGraphStorePayload {
  clientMutationId?: string | null;
  /** The `PlatformFunctionGraphStore` that was deleted by this mutation. */
  platformFunctionGraphStore?: PlatformFunctionGraphStore | null;
  platformFunctionGraphStoreEdge?: PlatformFunctionGraphStoreEdge | null;
}
export type DeletePlatformFunctionGraphStorePayloadSelect = {
  clientMutationId?: boolean;
  platformFunctionGraphStore?: {
    select: PlatformFunctionGraphStoreSelect;
  };
  platformFunctionGraphStoreEdge?: {
    select: PlatformFunctionGraphStoreEdgeSelect;
  };
};
export interface CreatePlatformFunctionGraphObjectPayload {
  clientMutationId?: string | null;
  /** The `PlatformFunctionGraphObject` that was created by this mutation. */
  platformFunctionGraphObject?: PlatformFunctionGraphObject | null;
  platformFunctionGraphObjectEdge?: PlatformFunctionGraphObjectEdge | null;
}
export type CreatePlatformFunctionGraphObjectPayloadSelect = {
  clientMutationId?: boolean;
  platformFunctionGraphObject?: {
    select: PlatformFunctionGraphObjectSelect;
  };
  platformFunctionGraphObjectEdge?: {
    select: PlatformFunctionGraphObjectEdgeSelect;
  };
};
export interface UpdatePlatformFunctionGraphObjectPayload {
  clientMutationId?: string | null;
  /** The `PlatformFunctionGraphObject` that was updated by this mutation. */
  platformFunctionGraphObject?: PlatformFunctionGraphObject | null;
  platformFunctionGraphObjectEdge?: PlatformFunctionGraphObjectEdge | null;
}
export type UpdatePlatformFunctionGraphObjectPayloadSelect = {
  clientMutationId?: boolean;
  platformFunctionGraphObject?: {
    select: PlatformFunctionGraphObjectSelect;
  };
  platformFunctionGraphObjectEdge?: {
    select: PlatformFunctionGraphObjectEdgeSelect;
  };
};
export interface DeletePlatformFunctionGraphObjectPayload {
  clientMutationId?: string | null;
  /** The `PlatformFunctionGraphObject` that was deleted by this mutation. */
  platformFunctionGraphObject?: PlatformFunctionGraphObject | null;
  platformFunctionGraphObjectEdge?: PlatformFunctionGraphObjectEdge | null;
}
export type DeletePlatformFunctionGraphObjectPayloadSelect = {
  clientMutationId?: boolean;
  platformFunctionGraphObject?: {
    select: PlatformFunctionGraphObjectSelect;
  };
  platformFunctionGraphObjectEdge?: {
    select: PlatformFunctionGraphObjectEdgeSelect;
  };
};
export interface CreateOrgFunctionExecutionLogPayload {
  clientMutationId?: string | null;
  /** The `OrgFunctionExecutionLog` that was created by this mutation. */
  orgFunctionExecutionLog?: OrgFunctionExecutionLog | null;
  orgFunctionExecutionLogEdge?: OrgFunctionExecutionLogEdge | null;
}
export type CreateOrgFunctionExecutionLogPayloadSelect = {
  clientMutationId?: boolean;
  orgFunctionExecutionLog?: {
    select: OrgFunctionExecutionLogSelect;
  };
  orgFunctionExecutionLogEdge?: {
    select: OrgFunctionExecutionLogEdgeSelect;
  };
};
export interface UpdateOrgFunctionExecutionLogPayload {
  clientMutationId?: string | null;
  /** The `OrgFunctionExecutionLog` that was updated by this mutation. */
  orgFunctionExecutionLog?: OrgFunctionExecutionLog | null;
  orgFunctionExecutionLogEdge?: OrgFunctionExecutionLogEdge | null;
}
export type UpdateOrgFunctionExecutionLogPayloadSelect = {
  clientMutationId?: boolean;
  orgFunctionExecutionLog?: {
    select: OrgFunctionExecutionLogSelect;
  };
  orgFunctionExecutionLogEdge?: {
    select: OrgFunctionExecutionLogEdgeSelect;
  };
};
export interface DeleteOrgFunctionExecutionLogPayload {
  clientMutationId?: string | null;
  /** The `OrgFunctionExecutionLog` that was deleted by this mutation. */
  orgFunctionExecutionLog?: OrgFunctionExecutionLog | null;
  orgFunctionExecutionLogEdge?: OrgFunctionExecutionLogEdge | null;
}
export type DeleteOrgFunctionExecutionLogPayloadSelect = {
  clientMutationId?: boolean;
  orgFunctionExecutionLog?: {
    select: OrgFunctionExecutionLogSelect;
  };
  orgFunctionExecutionLogEdge?: {
    select: OrgFunctionExecutionLogEdgeSelect;
  };
};
export interface CreatePlatformFunctionGraphCommitPayload {
  clientMutationId?: string | null;
  /** The `PlatformFunctionGraphCommit` that was created by this mutation. */
  platformFunctionGraphCommit?: PlatformFunctionGraphCommit | null;
  platformFunctionGraphCommitEdge?: PlatformFunctionGraphCommitEdge | null;
}
export type CreatePlatformFunctionGraphCommitPayloadSelect = {
  clientMutationId?: boolean;
  platformFunctionGraphCommit?: {
    select: PlatformFunctionGraphCommitSelect;
  };
  platformFunctionGraphCommitEdge?: {
    select: PlatformFunctionGraphCommitEdgeSelect;
  };
};
export interface UpdatePlatformFunctionGraphCommitPayload {
  clientMutationId?: string | null;
  /** The `PlatformFunctionGraphCommit` that was updated by this mutation. */
  platformFunctionGraphCommit?: PlatformFunctionGraphCommit | null;
  platformFunctionGraphCommitEdge?: PlatformFunctionGraphCommitEdge | null;
}
export type UpdatePlatformFunctionGraphCommitPayloadSelect = {
  clientMutationId?: boolean;
  platformFunctionGraphCommit?: {
    select: PlatformFunctionGraphCommitSelect;
  };
  platformFunctionGraphCommitEdge?: {
    select: PlatformFunctionGraphCommitEdgeSelect;
  };
};
export interface DeletePlatformFunctionGraphCommitPayload {
  clientMutationId?: string | null;
  /** The `PlatformFunctionGraphCommit` that was deleted by this mutation. */
  platformFunctionGraphCommit?: PlatformFunctionGraphCommit | null;
  platformFunctionGraphCommitEdge?: PlatformFunctionGraphCommitEdge | null;
}
export type DeletePlatformFunctionGraphCommitPayloadSelect = {
  clientMutationId?: boolean;
  platformFunctionGraphCommit?: {
    select: PlatformFunctionGraphCommitSelect;
  };
  platformFunctionGraphCommitEdge?: {
    select: PlatformFunctionGraphCommitEdgeSelect;
  };
};
export interface CreatePlatformSecretDefinitionPayload {
  clientMutationId?: string | null;
  /** The `PlatformSecretDefinition` that was created by this mutation. */
  platformSecretDefinition?: PlatformSecretDefinition | null;
  platformSecretDefinitionEdge?: PlatformSecretDefinitionEdge | null;
}
export type CreatePlatformSecretDefinitionPayloadSelect = {
  clientMutationId?: boolean;
  platformSecretDefinition?: {
    select: PlatformSecretDefinitionSelect;
  };
  platformSecretDefinitionEdge?: {
    select: PlatformSecretDefinitionEdgeSelect;
  };
};
export interface UpdatePlatformSecretDefinitionPayload {
  clientMutationId?: string | null;
  /** The `PlatformSecretDefinition` that was updated by this mutation. */
  platformSecretDefinition?: PlatformSecretDefinition | null;
  platformSecretDefinitionEdge?: PlatformSecretDefinitionEdge | null;
}
export type UpdatePlatformSecretDefinitionPayloadSelect = {
  clientMutationId?: boolean;
  platformSecretDefinition?: {
    select: PlatformSecretDefinitionSelect;
  };
  platformSecretDefinitionEdge?: {
    select: PlatformSecretDefinitionEdgeSelect;
  };
};
export interface DeletePlatformSecretDefinitionPayload {
  clientMutationId?: string | null;
  /** The `PlatformSecretDefinition` that was deleted by this mutation. */
  platformSecretDefinition?: PlatformSecretDefinition | null;
  platformSecretDefinitionEdge?: PlatformSecretDefinitionEdge | null;
}
export type DeletePlatformSecretDefinitionPayloadSelect = {
  clientMutationId?: boolean;
  platformSecretDefinition?: {
    select: PlatformSecretDefinitionSelect;
  };
  platformSecretDefinitionEdge?: {
    select: PlatformSecretDefinitionEdgeSelect;
  };
};
export interface CreatePlatformFunctionExecutionLogPayload {
  clientMutationId?: string | null;
  /** The `PlatformFunctionExecutionLog` that was created by this mutation. */
  platformFunctionExecutionLog?: PlatformFunctionExecutionLog | null;
  platformFunctionExecutionLogEdge?: PlatformFunctionExecutionLogEdge | null;
}
export type CreatePlatformFunctionExecutionLogPayloadSelect = {
  clientMutationId?: boolean;
  platformFunctionExecutionLog?: {
    select: PlatformFunctionExecutionLogSelect;
  };
  platformFunctionExecutionLogEdge?: {
    select: PlatformFunctionExecutionLogEdgeSelect;
  };
};
export interface UpdatePlatformFunctionExecutionLogPayload {
  clientMutationId?: string | null;
  /** The `PlatformFunctionExecutionLog` that was updated by this mutation. */
  platformFunctionExecutionLog?: PlatformFunctionExecutionLog | null;
  platformFunctionExecutionLogEdge?: PlatformFunctionExecutionLogEdge | null;
}
export type UpdatePlatformFunctionExecutionLogPayloadSelect = {
  clientMutationId?: boolean;
  platformFunctionExecutionLog?: {
    select: PlatformFunctionExecutionLogSelect;
  };
  platformFunctionExecutionLogEdge?: {
    select: PlatformFunctionExecutionLogEdgeSelect;
  };
};
export interface DeletePlatformFunctionExecutionLogPayload {
  clientMutationId?: string | null;
  /** The `PlatformFunctionExecutionLog` that was deleted by this mutation. */
  platformFunctionExecutionLog?: PlatformFunctionExecutionLog | null;
  platformFunctionExecutionLogEdge?: PlatformFunctionExecutionLogEdge | null;
}
export type DeletePlatformFunctionExecutionLogPayloadSelect = {
  clientMutationId?: boolean;
  platformFunctionExecutionLog?: {
    select: PlatformFunctionExecutionLogSelect;
  };
  platformFunctionExecutionLogEdge?: {
    select: PlatformFunctionExecutionLogEdgeSelect;
  };
};
export interface CreatePlatformFunctionGraphPayload {
  clientMutationId?: string | null;
  /** The `PlatformFunctionGraph` that was created by this mutation. */
  platformFunctionGraph?: PlatformFunctionGraph | null;
  platformFunctionGraphEdge?: PlatformFunctionGraphEdge | null;
}
export type CreatePlatformFunctionGraphPayloadSelect = {
  clientMutationId?: boolean;
  platformFunctionGraph?: {
    select: PlatformFunctionGraphSelect;
  };
  platformFunctionGraphEdge?: {
    select: PlatformFunctionGraphEdgeSelect;
  };
};
export interface UpdatePlatformFunctionGraphPayload {
  clientMutationId?: string | null;
  /** The `PlatformFunctionGraph` that was updated by this mutation. */
  platformFunctionGraph?: PlatformFunctionGraph | null;
  platformFunctionGraphEdge?: PlatformFunctionGraphEdge | null;
}
export type UpdatePlatformFunctionGraphPayloadSelect = {
  clientMutationId?: boolean;
  platformFunctionGraph?: {
    select: PlatformFunctionGraphSelect;
  };
  platformFunctionGraphEdge?: {
    select: PlatformFunctionGraphEdgeSelect;
  };
};
export interface DeletePlatformFunctionGraphPayload {
  clientMutationId?: string | null;
  /** The `PlatformFunctionGraph` that was deleted by this mutation. */
  platformFunctionGraph?: PlatformFunctionGraph | null;
  platformFunctionGraphEdge?: PlatformFunctionGraphEdge | null;
}
export type DeletePlatformFunctionGraphPayloadSelect = {
  clientMutationId?: boolean;
  platformFunctionGraph?: {
    select: PlatformFunctionGraphSelect;
  };
  platformFunctionGraphEdge?: {
    select: PlatformFunctionGraphEdgeSelect;
  };
};
export interface CreateOrgFunctionInvocationPayload {
  clientMutationId?: string | null;
  /** The `OrgFunctionInvocation` that was created by this mutation. */
  orgFunctionInvocation?: OrgFunctionInvocation | null;
  orgFunctionInvocationEdge?: OrgFunctionInvocationEdge | null;
}
export type CreateOrgFunctionInvocationPayloadSelect = {
  clientMutationId?: boolean;
  orgFunctionInvocation?: {
    select: OrgFunctionInvocationSelect;
  };
  orgFunctionInvocationEdge?: {
    select: OrgFunctionInvocationEdgeSelect;
  };
};
export interface UpdateOrgFunctionInvocationPayload {
  clientMutationId?: string | null;
  /** The `OrgFunctionInvocation` that was updated by this mutation. */
  orgFunctionInvocation?: OrgFunctionInvocation | null;
  orgFunctionInvocationEdge?: OrgFunctionInvocationEdge | null;
}
export type UpdateOrgFunctionInvocationPayloadSelect = {
  clientMutationId?: boolean;
  orgFunctionInvocation?: {
    select: OrgFunctionInvocationSelect;
  };
  orgFunctionInvocationEdge?: {
    select: OrgFunctionInvocationEdgeSelect;
  };
};
export interface DeleteOrgFunctionInvocationPayload {
  clientMutationId?: string | null;
  /** The `OrgFunctionInvocation` that was deleted by this mutation. */
  orgFunctionInvocation?: OrgFunctionInvocation | null;
  orgFunctionInvocationEdge?: OrgFunctionInvocationEdge | null;
}
export type DeleteOrgFunctionInvocationPayloadSelect = {
  clientMutationId?: boolean;
  orgFunctionInvocation?: {
    select: OrgFunctionInvocationSelect;
  };
  orgFunctionInvocationEdge?: {
    select: OrgFunctionInvocationEdgeSelect;
  };
};
export interface CreatePlatformFunctionInvocationPayload {
  clientMutationId?: string | null;
  /** The `PlatformFunctionInvocation` that was created by this mutation. */
  platformFunctionInvocation?: PlatformFunctionInvocation | null;
  platformFunctionInvocationEdge?: PlatformFunctionInvocationEdge | null;
}
export type CreatePlatformFunctionInvocationPayloadSelect = {
  clientMutationId?: boolean;
  platformFunctionInvocation?: {
    select: PlatformFunctionInvocationSelect;
  };
  platformFunctionInvocationEdge?: {
    select: PlatformFunctionInvocationEdgeSelect;
  };
};
export interface UpdatePlatformFunctionInvocationPayload {
  clientMutationId?: string | null;
  /** The `PlatformFunctionInvocation` that was updated by this mutation. */
  platformFunctionInvocation?: PlatformFunctionInvocation | null;
  platformFunctionInvocationEdge?: PlatformFunctionInvocationEdge | null;
}
export type UpdatePlatformFunctionInvocationPayloadSelect = {
  clientMutationId?: boolean;
  platformFunctionInvocation?: {
    select: PlatformFunctionInvocationSelect;
  };
  platformFunctionInvocationEdge?: {
    select: PlatformFunctionInvocationEdgeSelect;
  };
};
export interface DeletePlatformFunctionInvocationPayload {
  clientMutationId?: string | null;
  /** The `PlatformFunctionInvocation` that was deleted by this mutation. */
  platformFunctionInvocation?: PlatformFunctionInvocation | null;
  platformFunctionInvocationEdge?: PlatformFunctionInvocationEdge | null;
}
export type DeletePlatformFunctionInvocationPayloadSelect = {
  clientMutationId?: boolean;
  platformFunctionInvocation?: {
    select: PlatformFunctionInvocationSelect;
  };
  platformFunctionInvocationEdge?: {
    select: PlatformFunctionInvocationEdgeSelect;
  };
};
export interface CreatePlatformFunctionDefinitionPayload {
  clientMutationId?: string | null;
  /** The `PlatformFunctionDefinition` that was created by this mutation. */
  platformFunctionDefinition?: PlatformFunctionDefinition | null;
  platformFunctionDefinitionEdge?: PlatformFunctionDefinitionEdge | null;
}
export type CreatePlatformFunctionDefinitionPayloadSelect = {
  clientMutationId?: boolean;
  platformFunctionDefinition?: {
    select: PlatformFunctionDefinitionSelect;
  };
  platformFunctionDefinitionEdge?: {
    select: PlatformFunctionDefinitionEdgeSelect;
  };
};
export interface UpdatePlatformFunctionDefinitionPayload {
  clientMutationId?: string | null;
  /** The `PlatformFunctionDefinition` that was updated by this mutation. */
  platformFunctionDefinition?: PlatformFunctionDefinition | null;
  platformFunctionDefinitionEdge?: PlatformFunctionDefinitionEdge | null;
}
export type UpdatePlatformFunctionDefinitionPayloadSelect = {
  clientMutationId?: boolean;
  platformFunctionDefinition?: {
    select: PlatformFunctionDefinitionSelect;
  };
  platformFunctionDefinitionEdge?: {
    select: PlatformFunctionDefinitionEdgeSelect;
  };
};
export interface DeletePlatformFunctionDefinitionPayload {
  clientMutationId?: string | null;
  /** The `PlatformFunctionDefinition` that was deleted by this mutation. */
  platformFunctionDefinition?: PlatformFunctionDefinition | null;
  platformFunctionDefinitionEdge?: PlatformFunctionDefinitionEdge | null;
}
export type DeletePlatformFunctionDefinitionPayloadSelect = {
  clientMutationId?: boolean;
  platformFunctionDefinition?: {
    select: PlatformFunctionDefinitionSelect;
  };
  platformFunctionDefinitionEdge?: {
    select: PlatformFunctionDefinitionEdgeSelect;
  };
};
/** A `PlatformFunctionGraphRef` edge in the connection. */
export interface PlatformFunctionGraphRefEdge {
  cursor?: string | null;
  /** The `PlatformFunctionGraphRef` at the end of the edge. */
  node?: PlatformFunctionGraphRef | null;
}
export type PlatformFunctionGraphRefEdgeSelect = {
  cursor?: boolean;
  node?: {
    select: PlatformFunctionGraphRefSelect;
  };
};
/** A `PlatformFunctionGraphStore` edge in the connection. */
export interface PlatformFunctionGraphStoreEdge {
  cursor?: string | null;
  /** The `PlatformFunctionGraphStore` at the end of the edge. */
  node?: PlatformFunctionGraphStore | null;
}
export type PlatformFunctionGraphStoreEdgeSelect = {
  cursor?: boolean;
  node?: {
    select: PlatformFunctionGraphStoreSelect;
  };
};
/** A `PlatformFunctionGraphObject` edge in the connection. */
export interface PlatformFunctionGraphObjectEdge {
  cursor?: string | null;
  /** The `PlatformFunctionGraphObject` at the end of the edge. */
  node?: PlatformFunctionGraphObject | null;
}
export type PlatformFunctionGraphObjectEdgeSelect = {
  cursor?: boolean;
  node?: {
    select: PlatformFunctionGraphObjectSelect;
  };
};
/** A `OrgFunctionExecutionLog` edge in the connection. */
export interface OrgFunctionExecutionLogEdge {
  cursor?: string | null;
  /** The `OrgFunctionExecutionLog` at the end of the edge. */
  node?: OrgFunctionExecutionLog | null;
}
export type OrgFunctionExecutionLogEdgeSelect = {
  cursor?: boolean;
  node?: {
    select: OrgFunctionExecutionLogSelect;
  };
};
/** A `PlatformFunctionGraphCommit` edge in the connection. */
export interface PlatformFunctionGraphCommitEdge {
  cursor?: string | null;
  /** The `PlatformFunctionGraphCommit` at the end of the edge. */
  node?: PlatformFunctionGraphCommit | null;
}
export type PlatformFunctionGraphCommitEdgeSelect = {
  cursor?: boolean;
  node?: {
    select: PlatformFunctionGraphCommitSelect;
  };
};
/** A `PlatformSecretDefinition` edge in the connection. */
export interface PlatformSecretDefinitionEdge {
  cursor?: string | null;
  /** The `PlatformSecretDefinition` at the end of the edge. */
  node?: PlatformSecretDefinition | null;
}
export type PlatformSecretDefinitionEdgeSelect = {
  cursor?: boolean;
  node?: {
    select: PlatformSecretDefinitionSelect;
  };
};
/** A `PlatformFunctionExecutionLog` edge in the connection. */
export interface PlatformFunctionExecutionLogEdge {
  cursor?: string | null;
  /** The `PlatformFunctionExecutionLog` at the end of the edge. */
  node?: PlatformFunctionExecutionLog | null;
}
export type PlatformFunctionExecutionLogEdgeSelect = {
  cursor?: boolean;
  node?: {
    select: PlatformFunctionExecutionLogSelect;
  };
};
/** A `PlatformFunctionGraph` edge in the connection. */
export interface PlatformFunctionGraphEdge {
  cursor?: string | null;
  /** The `PlatformFunctionGraph` at the end of the edge. */
  node?: PlatformFunctionGraph | null;
}
export type PlatformFunctionGraphEdgeSelect = {
  cursor?: boolean;
  node?: {
    select: PlatformFunctionGraphSelect;
  };
};
/** A `OrgFunctionInvocation` edge in the connection. */
export interface OrgFunctionInvocationEdge {
  cursor?: string | null;
  /** The `OrgFunctionInvocation` at the end of the edge. */
  node?: OrgFunctionInvocation | null;
}
export type OrgFunctionInvocationEdgeSelect = {
  cursor?: boolean;
  node?: {
    select: OrgFunctionInvocationSelect;
  };
};
/** A `PlatformFunctionInvocation` edge in the connection. */
export interface PlatformFunctionInvocationEdge {
  cursor?: string | null;
  /** The `PlatformFunctionInvocation` at the end of the edge. */
  node?: PlatformFunctionInvocation | null;
}
export type PlatformFunctionInvocationEdgeSelect = {
  cursor?: boolean;
  node?: {
    select: PlatformFunctionInvocationSelect;
  };
};
/** A `PlatformFunctionDefinition` edge in the connection. */
export interface PlatformFunctionDefinitionEdge {
  cursor?: string | null;
  /** The `PlatformFunctionDefinition` at the end of the edge. */
  node?: PlatformFunctionDefinition | null;
}
export type PlatformFunctionDefinitionEdgeSelect = {
  cursor?: boolean;
  node?: {
    select: PlatformFunctionDefinitionSelect;
  };
};
