-- Revert: schemas/constructive_memberships_public/tables/org_permission_default_grants/indexes/org_permission_default_grants_created_at_idx


DROP INDEX "constructive_memberships_public".org_permission_default_grants_created_at_idx;


