-- Revert: schemas/constructive_platform_function_graph_public/tables/platform_function_graph_object/columns/kids/alterations/alt0000002608


ALTER TABLE "constructive_platform_function_graph_public".platform_function_graph_object 
  DROP CONSTRAINT platform_function_graph_objects_kids_ktree_chk;


