-- Revert: schemas/constructive_compute_private/tables/platform_function_graph_execution_node_states/columns/started_at/alterations/alt0000002710


COMMENT ON COLUMN "constructive_compute_private".platform_function_graph_execution_node_states.started_at IS NULL;
