-- Verify: schemas/constructive_storage_public/tables/platform_buckets/triggers/platform_buckets_force_current_user_actor_id_tg


SELECT verify_trigger('constructive_storage_public.platform_buckets_force_current_user_actor_id_tg');


