/**
 * Multi-target context management commands
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { CLIOptions, extractFirst,Inquirerer } from 'inquirerer';

import { getStore } from '../executor';
const usage =
  '\nconstructive-functions context <command>\n\nCommands:\n  create <name>         Create a new context\n  list                  List all contexts\n  use <name>            Set the active context\n  current               Show current context\n  delete <name>         Delete a context\n\nCreate Options:\n  --api-endpoint <url>  api endpoint (default: )\n  --compute-endpoint <url>  compute endpoint (default: )\n  --objects-endpoint <url>  objects endpoint (default: )\n\n  --help, -h            Show this help message\n';
export default async (
  argv: Partial<Record<string, unknown>>,
  prompter: Inquirerer,
  _options: CLIOptions
) => {
  if (argv.help || argv.h) {
    console.log(usage);
    process.exit(0);
  }
  const store = getStore();
  const { first: subcommand, newArgv } = extractFirst(argv);
  if (!subcommand) {
    const answer = await prompter.prompt(argv, [
      {
        type: 'autocomplete',
        name: 'subcommand',
        message: 'What do you want to do?',
        options: ['create', 'list', 'use', 'current', 'delete'],
      },
    ]);
    return handleSubcommand(answer.subcommand as string, newArgv, prompter, store);
  }
  return handleSubcommand(subcommand, newArgv, prompter, store);
};
async function handleSubcommand(
  subcommand: string,
  argv: Partial<Record<string, unknown>>,
  prompter: Inquirerer,
  store: ReturnType<typeof getStore>
) {
  switch (subcommand) {
    case 'create':
      return handleCreate(argv, prompter, store);
    case 'list':
      return handleList(store);
    case 'use':
      return handleUse(argv, prompter, store);
    case 'current':
      return handleCurrent(store);
    case 'delete':
      return handleDelete(argv, prompter, store);
    default:
      console.log(usage);
      process.exit(1);
  }
}
async function handleCreate(
  argv: Partial<Record<string, unknown>>,
  prompter: Inquirerer,
  store: ReturnType<typeof getStore>
) {
  const { first: name, newArgv: restArgv } = extractFirst(argv);
  const answers = await prompter.prompt(
    {
      name,
      ...restArgv,
    },
    [
      {
        type: 'text',
        name: 'name',
        message: 'Context name',
        required: true,
      },
      {
        type: 'text',
        name: 'apiEndpoint',
        message: 'api endpoint',
        default: '',
      },
      {
        type: 'text',
        name: 'computeEndpoint',
        message: 'compute endpoint',
        default: '',
      },
      {
        type: 'text',
        name: 'objectsEndpoint',
        message: 'objects endpoint',
        default: '',
      },
    ]
  );
  const contextName = answers.name as string;
  const targets = {
    api: {
      endpoint: answers.apiEndpoint as string,
    },
    compute: {
      endpoint: answers.computeEndpoint as string,
    },
    objects: {
      endpoint: answers.objectsEndpoint as string,
    },
  };
  store.createContext(contextName, {
    endpoint: answers.apiEndpoint as string,
    targets: targets,
  });
  const settings = store.loadSettings();
  if (!settings.currentContext) {
    store.setCurrentContext(contextName);
  }
  console.log(`Created context: ${contextName}`);
  console.log(`  api: ${answers.apiEndpoint as string}`);
  console.log(`  compute: ${answers.computeEndpoint as string}`);
  console.log(`  objects: ${answers.objectsEndpoint as string}`);
}
function handleList(store: ReturnType<typeof getStore>) {
  const contexts = store.listContexts();
  const settings = store.loadSettings();
  if (contexts.length === 0) {
    console.log('No contexts configured.');
    return;
  }
  console.log('Contexts:');
  for (const ctx of contexts) {
    const marker = ctx.name === settings.currentContext ? '* ' : '  ';
    const authStatus = store.hasValidCredentials(ctx.name) ? '[authenticated]' : '[no token]';
    console.log(`${marker}${ctx.name} ${authStatus}`);
    console.log(`    Endpoint: ${ctx.endpoint}`);
  }
}
async function handleUse(
  argv: Partial<Record<string, unknown>>,
  prompter: Inquirerer,
  store: ReturnType<typeof getStore>
) {
  const { first: name } = extractFirst(argv);
  const contexts = store.listContexts();
  if (contexts.length === 0) {
    console.log('No contexts configured.');
    return;
  }
  let contextName = name;
  if (!contextName) {
    const answer = await prompter.prompt(argv, [
      {
        type: 'autocomplete',
        name: 'name',
        message: 'Select context',
        options: contexts.map((c) => c.name),
      },
    ]);
    contextName = answer.name as string;
  }
  if (store.setCurrentContext(contextName)) {
    console.log(`Switched to context: ${contextName}`);
  } else {
    console.error(`Context "${contextName}" not found.`);
    process.exit(1);
  }
}
function handleCurrent(store: ReturnType<typeof getStore>) {
  const current = store.getCurrentContext();
  if (!current) {
    console.log('No current context set.');
    return;
  }
  console.log(`Current context: ${current.name}`);
  console.log(`  Endpoint: ${current.endpoint}`);
  const hasAuth = store.hasValidCredentials(current.name);
  console.log(`  Auth: ${hasAuth ? 'authenticated' : 'not authenticated'}`);
}
async function handleDelete(
  argv: Partial<Record<string, unknown>>,
  prompter: Inquirerer,
  store: ReturnType<typeof getStore>
) {
  const { first: name } = extractFirst(argv);
  const contexts = store.listContexts();
  if (contexts.length === 0) {
    console.log('No contexts configured.');
    return;
  }
  let contextName = name;
  if (!contextName) {
    const answer = await prompter.prompt(argv, [
      {
        type: 'autocomplete',
        name: 'name',
        message: 'Select context to delete',
        options: contexts.map((c) => c.name),
      },
    ]);
    contextName = answer.name as string;
  }
  if (store.deleteContext(contextName)) {
    console.log(`Deleted context: ${contextName}`);
  } else {
    console.error(`Context "${contextName}" not found.`);
    process.exit(1);
  }
}
