/**
 * Object model for ORM client
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { OrmClient } from '../client';
import {
  QueryBuilder,
  buildFindManyDocument,
  buildFindFirstDocument,
  buildFindOneDocument,
  buildCreateDocument,
  buildUpdateByPkDocument,
  buildDeleteByPkDocument,
} from '../query-builder';
import type {
  ConnectionResult,
  FindManyArgs,
  FindFirstArgs,
  CreateArgs,
  UpdateArgs,
  DeleteArgs,
  InferSelectResult,
  StrictSelect,
} from '../select-types';
import type {
  Object,
  ObjectWithRelations,
  ObjectSelect,
  ObjectFilter,
  ObjectOrderBy,
  CreateObjectInput,
  UpdateObjectInput,
  ObjectPatch,
} from '../input-types';
import { connectionFieldsMap } from '../input-types';
export class ObjectModel {
  constructor(private client: OrmClient) {}
  findMany<S extends ObjectSelect>(
    args: FindManyArgs<S, ObjectFilter, ObjectOrderBy> & {
      select: S;
    } & StrictSelect<S, ObjectSelect>
  ): QueryBuilder<{
    objects: ConnectionResult<InferSelectResult<ObjectWithRelations, S>>;
  }> {
    const { document, variables } = buildFindManyDocument(
      'Object',
      'objects',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
        first: args?.first,
        last: args?.last,
        after: args?.after,
        before: args?.before,
        offset: args?.offset,
      },
      'ObjectFilter',
      'ObjectOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'Object',
      fieldName: 'objects',
      document,
      variables,
    });
  }
  findFirst<S extends ObjectSelect>(
    args: FindFirstArgs<S, ObjectFilter, ObjectOrderBy> & {
      select: S;
    } & StrictSelect<S, ObjectSelect>
  ): QueryBuilder<{
    object: InferSelectResult<ObjectWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindFirstDocument(
      'Object',
      'objects',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
      },
      'ObjectFilter',
      'ObjectOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'Object',
      fieldName: 'object',
      document,
      variables,
      transform: (data: {
        objects?: {
          nodes?: InferSelectResult<ObjectWithRelations, S>[];
        };
      }) => ({
        object: data.objects?.nodes?.[0] ?? null,
      }),
    });
  }
  findOne<S extends ObjectSelect>(
    args: {
      id: string;
      select: S;
    } & StrictSelect<S, ObjectSelect>
  ): QueryBuilder<{
    object: InferSelectResult<ObjectWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindOneDocument(
      'Object',
      'getNodeAtPath',
      args.id,
      args.select,
      'id',
      'UUID!',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'Object',
      fieldName: 'object',
      document,
      variables,
    });
  }
  create<S extends ObjectSelect>(
    args: CreateArgs<S, CreateObjectInput['object']> & {
      select: S;
    } & StrictSelect<S, ObjectSelect>
  ): QueryBuilder<{
    createObject: {
      object: InferSelectResult<ObjectWithRelations, S>;
    };
  }> {
    const { document, variables } = buildCreateDocument(
      'Object',
      'createObject',
      'object',
      args.select,
      args.data,
      'CreateObjectInput',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'Object',
      fieldName: 'createObject',
      document,
      variables,
    });
  }
  update<S extends ObjectSelect>(
    args: UpdateArgs<
      S,
      {
        id: string;
      },
      ObjectPatch
    > & {
      select: S;
    } & StrictSelect<S, ObjectSelect>
  ): QueryBuilder<{
    updateObject: {
      object: InferSelectResult<ObjectWithRelations, S>;
    };
  }> {
    const { document, variables } = buildUpdateByPkDocument(
      'Object',
      'updateObject',
      'object',
      args.select,
      args.where.id,
      args.data,
      'UpdateObjectInput',
      'id',
      'objectPatch',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'Object',
      fieldName: 'updateObject',
      document,
      variables,
    });
  }
  delete<S extends ObjectSelect>(
    args: DeleteArgs<
      {
        id: string;
      },
      S
    > & {
      select: S;
    } & StrictSelect<S, ObjectSelect>
  ): QueryBuilder<{
    deleteObject: {
      object: InferSelectResult<ObjectWithRelations, S>;
    };
  }> {
    const { document, variables } = buildDeleteByPkDocument(
      'Object',
      'deleteObject',
      'object',
      {
        id: args.where.id,
      },
      'DeleteObjectInput',
      args.select,
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'Object',
      fieldName: 'deleteObject',
      document,
      variables,
    });
  }
}
